In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/raw/IPL.csv")

/var/folders/9x/3x7xy3b937b7s21dnh9vzpp00000gn/T/ipykernel_9792/1363405620.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/raw/IPL.csv")

In [3]:
data.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  object
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), object(35)
memory usage: 130.3+ MB

In [5]:
data.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='object')

In [7]:
data[['runs_batter','batter_runs','bowler_wicket','wicket_kind']].head(50)

    runs_batter  batter_runs  bowler_wicket wicket_kind
0             0            0              0         NaN
1             0            0              0         NaN
2             0            0              0         NaN
3             0            0              0         NaN
4             0            0              0         NaN
5             0            0              0         NaN
6             0            0              0         NaN
7             0            0              0         NaN
8             4            4              0         NaN
9             4            8              0         NaN
10            6           14              0         NaN
11            4           18              0         NaN
12            0           18              0         NaN
13            0            0              0         NaN
14            0            0              0         NaN
15            0            0              0         NaN
16            4           22              0         NaN
17            1           23              0         NaN
18            0            0              0         NaN
19            0           23              0         NaN
20            6           29              0         NaN
21            0           29              0         NaN
22            4            4              0         NaN
23            0            4              0         NaN
24            1            5              0         NaN
25            6           35              0         NaN
26            4            9              0         NaN
27            1           10              0         NaN
28            4           39              0         NaN
29            0           39              0         NaN
30            1           40              0         NaN
31            0           10              0         NaN
32            1           41              0         NaN
33            0           10              1      caught
34            0            0              0         NaN
35            0            0              0         NaN
36            0            0              0         NaN
37            0            0              0         NaN
38            1           42              0         NaN
39            1            1              0         NaN
40            1           43              0         NaN
41            2            3              0         NaN
42            1            4              0         NaN
43            1           44              0         NaN
44            0           44              0         NaN
45            1           45              0         NaN
46            1            5              0         NaN
47            1           46              0         NaN
48            1            6              0         NaN
49            1           47              0         NaN

In [8]:
batter_df = data.groupby(['match_id','batter']).agg(
    runs=('runs_batter', 'sum'),
    balls=('valid_ball', 'sum'),
    fours=('runs_batter', lambda x: (x == 4).sum()),
    sixes=('runs_batter', lambda x: (x == 6).sum())
).reset_index()

In [10]:
batter_df['strike_rate'] = (batter_df['runs'] / batter_df['balls']) * 100

In [11]:
batter_df

       match_id           batter  runs  balls  fours  sixes  strike_rate
0        335982        AA Noffke     9     10      1      0    90.000000
1        335982          B Akhil     0      2      0      0     0.000000
2        335982      BB McCullum   158     73     10     13   216.438356
3        335982         CL White     6     10      0      0    60.000000
4        335982        DJ Hussey    12     12      1      0   100.000000
...         ...              ...   ...    ...    ...    ...          ...
17633   1485779          SS Iyer    53     33      5      2   160.606061
17634   1485779     Sameer Rizvi    58     25      3      5   232.000000
17635   1485779  Sediqullah Atal    22     16      0      2   137.500000
17636   1485779   Shashank Singh    11     10      0      0   110.000000
17637   1485779         T Stubbs    18     14      2      0   128.571429

[17638 rows x 7 columns]

In [12]:
bowler_df = data.groupby(['match_id', 'bowler']).agg(
    runs_conceded=('runs_bowler', 'sum'),
    balls_bowled=('valid_ball', 'sum'),
    wickets=('bowler_wicket', 'sum')
).reset_index()

bowler_df['overs'] = bowler_df['balls_bowled'] / 6
bowler_df['economy'] = bowler_df['runs_conceded'] / bowler_df['overs']

In [17]:
bowler_df

,match_id,bowler,runs_conceded,balls_bowled,wickets,overs,economy
0,335982,AA Noffke,40,24,1,4.0,10.000000
1,335982,AB Agarkar,25,24,3,4.0,6.250000
2,335982,AB Dinda,9,18,2,3.0,3.000000
3,335982,CL White,24,6,0,1.0,24.000000
4,335982,I Sharma,7,18,1,3.0,2.333333
...,...,...,...,...,...,...,...
13841,1485779,MP Stoinis,21,9,0,1.5,14.000000
13842,1485779,Mukesh Kumar,49,24,1,4.0,12.250000
13843,1485779,Mustafizur Rahman,33,24,3,4.0,8.250000
13844,1485779,P Dubey,20,12,1,2.0,10.000000
13845,1485779,V Nigam,38,24,2,4.0,9.500000