In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/raw/IPL.csv")

/var/folders/9x/3x7xy3b937b7s21dnh9vzpp00000gn/T/ipykernel_7705/1363405620.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/raw/IPL.csv")

In [3]:
data.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  object
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), object(35)
memory usage: 130.3+ MB

In [5]:
data.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='object')

In [6]:
data[['runs_batter','batter_runs','bowler_wicket','wicket_kind']].head(50)

    runs_batter  batter_runs  bowler_wicket wicket_kind
0             0            0              0         NaN
1             0            0              0         NaN
2             0            0              0         NaN
3             0            0              0         NaN
4             0            0              0         NaN
5             0            0              0         NaN
6             0            0              0         NaN
7             0            0              0         NaN
8             4            4              0         NaN
9             4            8              0         NaN
10            6           14              0         NaN
11            4           18              0         NaN
12            0           18              0         NaN
13            0            0              0         NaN
14            0            0              0         NaN
15            0            0              0         NaN
16            4           22              0         NaN
17            1           23              0         NaN
18            0            0              0         NaN
19            0           23              0         NaN
20            6           29              0         NaN
21            0           29              0         NaN
22            4            4              0         NaN
23            0            4              0         NaN
24            1            5              0         NaN
25            6           35              0         NaN
26            4            9              0         NaN
27            1           10              0         NaN
28            4           39              0         NaN
29            0           39              0         NaN
30            1           40              0         NaN
31            0           10              0         NaN
32            1           41              0         NaN
33            0           10              1      caught
34            0            0              0         NaN
35            0            0              0         NaN
36            0            0              0         NaN
37            0            0              0         NaN
38            1           42              0         NaN
39            1            1              0         NaN
40            1           43              0         NaN
41            2            3              0         NaN
42            1            4              0         NaN
43            1           44              0         NaN
44            0           44              0         NaN
45            1           45              0         NaN
46            1            5              0         NaN
47            1           46              0         NaN
48            1            6              0         NaN
49            1           47              0         NaN

In [7]:
batter_df = data.groupby(['match_id','batter']).agg(
    runs=('runs_batter', 'sum'),
    balls=('valid_ball', 'sum'),
    fours=('runs_batter', lambda x: (x == 4).sum()),
    sixes=('runs_batter', lambda x: (x == 6).sum())
).reset_index()

In [8]:
batter_df['strike_rate'] = (batter_df['runs'] / batter_df['balls']) * 100

In [9]:
batter_df

       match_id           batter  runs  balls  fours  sixes  strike_rate
0        335982        AA Noffke     9     10      1      0    90.000000
1        335982          B Akhil     0      2      0      0     0.000000
2        335982      BB McCullum   158     73     10     13   216.438356
3        335982         CL White     6     10      0      0    60.000000
4        335982        DJ Hussey    12     12      1      0   100.000000
...         ...              ...   ...    ...    ...    ...          ...
17633   1485779          SS Iyer    53     33      5      2   160.606061
17634   1485779     Sameer Rizvi    58     25      3      5   232.000000
17635   1485779  Sediqullah Atal    22     16      0      2   137.500000
17636   1485779   Shashank Singh    11     10      0      0   110.000000
17637   1485779         T Stubbs    18     14      2      0   128.571429

[17638 rows x 7 columns]

In [10]:
bowler_df = data.groupby(['match_id', 'bowler']).agg(
    runs_conceded=('runs_bowler', 'sum'),
    balls_bowled=('valid_ball', 'sum'),
    wickets=('bowler_wicket', 'sum')
).reset_index()

bowler_df['overs'] = bowler_df['balls_bowled'] / 6
bowler_df['economy'] = bowler_df['runs_conceded'] / bowler_df['overs']

In [11]:
bowler_df

,match_id,bowler,runs_conceded,balls_bowled,wickets,overs,economy
0,335982,AA Noffke,40,24,1,4.0,10.000000
1,335982,AB Agarkar,25,24,3,4.0,6.250000
2,335982,AB Dinda,9,18,2,3.0,3.000000
3,335982,CL White,24,6,0,1.0,24.000000
4,335982,I Sharma,7,18,1,3.0,2.333333
...,...,...,...,...,...,...,...
13841,1485779,MP Stoinis,21,9,0,1.5,14.000000
13842,1485779,Mukesh Kumar,49,24,1,4.0,12.250000
13843,1485779,Mustafizur Rahman,33,24,3,4.0,8.250000
13844,1485779,P Dubey,20,12,1,2.0,10.000000
13845,1485779,V Nigam,38,24,2,4.0,9.500000

In [12]:
batter_df.columns

Index(['match_id', 'batter', 'runs', 'balls', 'fours', 'sixes', 'strike_rate'], dtype='object')

In [13]:
bowler_df.columns

Index(['match_id', 'bowler', 'runs_conceded', 'balls_bowled', 'wickets',
       'overs', 'economy'],
      dtype='object')

In [14]:
batter_df = batter_df.rename(columns={"batter": "player"})
bowler_df = bowler_df.rename(columns={"bowler": "player"})

In [15]:
player_match_df = batter_df.merge(
    bowler_df,
    on=["match_id", "player"],
    how="outer"
)

In [16]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00
1,335982,AB Agarkar,NaN,NaN,NaN,NaN,NaN,25.0,24.0,3.0,4.0,6.25
2,335982,AB Dinda,NaN,NaN,NaN,NaN,NaN,9.0,18.0,2.0,3.0,3.00
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,NaN,NaN,NaN,NaN,NaN
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,NaN,NaN,NaN,NaN,NaN
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,NaN,NaN,NaN,NaN,NaN
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,NaN,NaN,NaN,NaN,NaN
25017,1485779,V Nigam,NaN,NaN,NaN,NaN,NaN,38.0,24.0,2.0,4.0,9.50

In [17]:
player_match_df = player_match_df.fillna(0)

In [18]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50

In [19]:
catches = (
    data[data["wicket_kind"] == "caught"]
    .groupby(["match_id", "fielders"])
    .size()
    .reset_index(name="catches")
)

In [20]:
catches

      match_id        fielders  catches
0       335982     BB McCullum        1
1       335982        CL White        1
2       335982       JH Kallis        1
3       335982        M Kartik        2
4       335982         P Kumar        1
...        ...             ...      ...
7121   1485779       MM Sharma        1
7122   1485779   Priyansh Arya        1
7123   1485779    Sameer Rizvi        1
7124   1485779  Shashank Singh        1
7125   1485779        T Stubbs        3

[7126 rows x 3 columns]

In [21]:
stumpings = (
    data[data["wicket_kind"] == "stumped"]
    .groupby(["match_id", "fielders"])
    .size()
    .reset_index(name="stumpings")
)

In [22]:
stumpings

     match_id      fielders  stumpings
0      335985    MV Boucher          1
1      335987  Kamran Akmal          1
2      335990  Kamran Akmal          1
3      336002    SP Goswami          1
4      336003       WP Saha          2
..        ...           ...        ...
323   1473475  RD Rickelton          1
324   1473476    JC Buttler          2
325   1473494      MS Dhoni          1
326   1473501  RD Rickelton          2
327   1485779      T Stubbs          1

[328 rows x 3 columns]

In [23]:
runout_raw = data[data["wicket_kind"] == "run out"][["match_id", "fielders"]].copy()
runout_raw = runout_raw.dropna(subset=["fielders"])
runout_raw["num_fielders"] = runout_raw["fielders"].str.count(",") + 1
runout_raw["fielders"] = runout_raw["fielders"].str.split(",")
runout_raw = runout_raw.explode("fielders")
runout_raw["fielders"] = runout_raw["fielders"].str.strip()
runout_raw["runout_points"] = 0

In [24]:
runout_raw

        match_id             fielders  num_fielders  runout_points
197       335982           AB Agarkar             2              0
197       335982              WP Saha             2              0
727       335985               Z Khan             1              0
1055      335986      Mohammad Hafeez             2              0
1055      335986              WP Saha             2              0
...          ...                  ...           ...            ...
274996   1473499         Ishan Kishan             2              0
274996   1473499  Nithish Kumar Reddy             2              0
276061   1473503            E Malinga             1              0
276817   1473505           JD Unadkat             1              0
277936   1473510            HH Pandya             1              0

[1499 rows x 4 columns]

In [25]:
runout_raw.loc[runout_raw["num_fielders"] == 1, "runout_points"] = 12
runout_raw.loc[runout_raw["num_fielders"] > 1, "runout_points"] = 6

In [26]:
runout_raw

        match_id             fielders  num_fielders  runout_points
197       335982           AB Agarkar             2              6
197       335982              WP Saha             2              6
727       335985               Z Khan             1             12
1055      335986      Mohammad Hafeez             2              6
1055      335986              WP Saha             2              6
...          ...                  ...           ...            ...
274996   1473499         Ishan Kishan             2              6
274996   1473499  Nithish Kumar Reddy             2              6
276061   1473503            E Malinga             1             12
276817   1473505           JD Unadkat             1             12
277936   1473510            HH Pandya             1             12

[1499 rows x 4 columns]

In [27]:
runout_points = (
    runout_raw.groupby(["match_id", "fielders"])["runout_points"]
    .sum()
    .reset_index()
)
runout_points = runout_points.rename(columns={"fielders": "player"})

In [28]:
runout_points

      match_id               player  runout_points
0       335982           AB Agarkar              6
1       335982              WP Saha              6
2       335985               Z Khan             12
3       335986      Mohammad Hafeez              6
4       335986              WP Saha              6
...        ...                  ...            ...
1403   1473499         Ishan Kishan             18
1404   1473499  Nithish Kumar Reddy              6
1405   1473503            E Malinga             12
1406   1473505           JD Unadkat             12
1407   1473510            HH Pandya             12

[1408 rows x 3 columns]

In [29]:
stumpings

     match_id      fielders  stumpings
0      335985    MV Boucher          1
1      335987  Kamran Akmal          1
2      335990  Kamran Akmal          1
3      336002    SP Goswami          1
4      336003       WP Saha          2
..        ...           ...        ...
323   1473475  RD Rickelton          1
324   1473476    JC Buttler          2
325   1473494      MS Dhoni          1
326   1473501  RD Rickelton          2
327   1485779      T Stubbs          1

[328 rows x 3 columns]

In [30]:
catches

      match_id        fielders  catches
0       335982     BB McCullum        1
1       335982        CL White        1
2       335982       JH Kallis        1
3       335982        M Kartik        2
4       335982         P Kumar        1
...        ...             ...      ...
7121   1485779       MM Sharma        1
7122   1485779   Priyansh Arya        1
7123   1485779    Sameer Rizvi        1
7124   1485779  Shashank Singh        1
7125   1485779        T Stubbs        3

[7126 rows x 3 columns]

In [31]:
runout_points

      match_id               player  runout_points
0       335982           AB Agarkar              6
1       335982              WP Saha              6
2       335985               Z Khan             12
3       335986      Mohammad Hafeez              6
4       335986              WP Saha              6
...        ...                  ...            ...
1403   1473499         Ishan Kishan             18
1404   1473499  Nithish Kumar Reddy              6
1405   1473503            E Malinga             12
1406   1473505           JD Unadkat             12
1407   1473510            HH Pandya             12

[1408 rows x 3 columns]

In [32]:
print(catches.columns)
print(runout_points.columns)
print(stumpings.columns)

Index(['match_id', 'fielders', 'catches'], dtype='object')
Index(['match_id', 'player', 'runout_points'], dtype='object')
Index(['match_id', 'fielders', 'stumpings'], dtype='object')

In [33]:
catches = catches.rename(columns={"fielders": "player"})
stumpings = stumpings.rename(columns={"fielders": "player"})

In [34]:
catches

      match_id          player  catches
0       335982     BB McCullum        1
1       335982        CL White        1
2       335982       JH Kallis        1
3       335982        M Kartik        2
4       335982         P Kumar        1
...        ...             ...      ...
7121   1485779       MM Sharma        1
7122   1485779   Priyansh Arya        1
7123   1485779    Sameer Rizvi        1
7124   1485779  Shashank Singh        1
7125   1485779        T Stubbs        3

[7126 rows x 3 columns]

In [35]:
stumpings

     match_id        player  stumpings
0      335985    MV Boucher          1
1      335987  Kamran Akmal          1
2      335990  Kamran Akmal          1
3      336002    SP Goswami          1
4      336003       WP Saha          2
..        ...           ...        ...
323   1473475  RD Rickelton          1
324   1473476    JC Buttler          2
325   1473494      MS Dhoni          1
326   1473501  RD Rickelton          2
327   1485779      T Stubbs          1

[328 rows x 3 columns]

In [36]:
fielding_df = catches.merge(stumpings,on = ['match_id','player'],how = 'outer')
fielding_df = fielding_df.merge(runout_points,on=["match_id", "player"],how="outer")

In [37]:
fielding_df

      match_id          player  catches  stumpings  runout_points
0       335982      AB Agarkar      NaN        NaN            6.0
1       335982     BB McCullum      1.0        NaN            NaN
2       335982        CL White      1.0        NaN            NaN
3       335982       JH Kallis      1.0        NaN            NaN
4       335982        M Kartik      2.0        NaN            NaN
...        ...             ...      ...        ...            ...
8201   1485779       MM Sharma      1.0        NaN            NaN
8202   1485779   Priyansh Arya      1.0        NaN            NaN
8203   1485779    Sameer Rizvi      1.0        NaN            NaN
8204   1485779  Shashank Singh      1.0        NaN            NaN
8205   1485779        T Stubbs      3.0        1.0            NaN

[8206 rows x 5 columns]

In [38]:
fielding_df = fielding_df.fillna(0)

In [39]:
fielding_df

      match_id          player  catches  stumpings  runout_points
0       335982      AB Agarkar      0.0        0.0            6.0
1       335982     BB McCullum      1.0        0.0            0.0
2       335982        CL White      1.0        0.0            0.0
3       335982       JH Kallis      1.0        0.0            0.0
4       335982        M Kartik      2.0        0.0            0.0
...        ...             ...      ...        ...            ...
8201   1485779       MM Sharma      1.0        0.0            0.0
8202   1485779   Priyansh Arya      1.0        0.0            0.0
8203   1485779    Sameer Rizvi      1.0        0.0            0.0
8204   1485779  Shashank Singh      1.0        0.0            0.0
8205   1485779        T Stubbs      3.0        1.0            0.0

[8206 rows x 5 columns]

In [40]:
fielding_df['fielding_points'] = fielding_df['catches']*8 + fielding_df['stumpings']*12 + fielding_df["runout_points"]
fielding_df

,match_id,player,catches,stumpings,runout_points,fielding_points
0,335982,AB Agarkar,0.0,0.0,6.0,6.0
1,335982,BB McCullum,1.0,0.0,0.0,8.0
2,335982,CL White,1.0,0.0,0.0,8.0
3,335982,JH Kallis,1.0,0.0,0.0,8.0
4,335982,M Kartik,2.0,0.0,0.0,16.0
...,...,...,...,...,...,...
8201,1485779,MM Sharma,1.0,0.0,0.0,8.0
8202,1485779,Priyansh Arya,1.0,0.0,0.0,8.0
8203,1485779,Sameer Rizvi,1.0,0.0,0.0,8.0
8204,1485779,Shashank Singh,1.0,0.0,0.0,8.0
8205,1485779,T Stubbs,3.0,1.0,0.0,36.0

In [41]:
fielding_df.loc[fielding_df['catches']>=3,'fielding_points'] += 4

In [42]:
fielding_df

,match_id,player,catches,stumpings,runout_points,fielding_points
0,335982,AB Agarkar,0.0,0.0,6.0,6.0
1,335982,BB McCullum,1.0,0.0,0.0,8.0
2,335982,CL White,1.0,0.0,0.0,8.0
3,335982,JH Kallis,1.0,0.0,0.0,8.0
4,335982,M Kartik,2.0,0.0,0.0,16.0
...,...,...,...,...,...,...
8201,1485779,MM Sharma,1.0,0.0,0.0,8.0
8202,1485779,Priyansh Arya,1.0,0.0,0.0,8.0
8203,1485779,Sameer Rizvi,1.0,0.0,0.0,8.0
8204,1485779,Shashank Singh,1.0,0.0,0.0,8.0
8205,1485779,T Stubbs,3.0,1.0,0.0,40.0

In [43]:
player_match_df = player_match_df.merge(
    fielding_df[["match_id", "player", "fielding_points"]],
    on=["match_id", "player"],
    how="left"
)
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,NaN
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,NaN
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,NaN
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,NaN
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,NaN

In [44]:
player_match_df['fielding_points'] = player_match_df['fielding_points'].fillna(0)
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,0.0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,0.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,0.0
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,0.0

In [45]:
player_match_df.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points'],
      dtype='object')

In [46]:
player_match_df["batting_points"] = (
    player_match_df["runs"]
    + player_match_df["fours"] * 1
    + player_match_df["sixes"] * 2
)
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,0.0,10.0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0,0.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,0.0,0.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0,194.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0,71.0
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,0.0,26.0
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0,11.0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0,20.0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,0.0,0.0

In [47]:
duck_mask = (player_match_df["runs"] == 0) & (player_match_df["balls"] > 0)

player_match_df.loc[duck_mask, "batting_points"] -= 2

In [48]:
player_match_df["batting_bonus"] = 0

player_match_df.loc[player_match_df["runs"] >= 30, "batting_bonus"] = 4
player_match_df.loc[player_match_df["runs"] >= 50, "batting_bonus"] = 8
player_match_df.loc[player_match_df["runs"] >= 100, "batting_bonus"] = 16

In [49]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,0.0,10.0,0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0,0.0,0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,0.0,0.0,0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,-2.0,0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0,194.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0,71.0,8
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,0.0,26.0,0
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0,11.0,0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0,20.0,0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,0.0,0.0,0

In [50]:
player_match_df["sr_bonus"] = 0

mask = player_match_df["balls"] >= 10

player_match_df.loc[mask & (player_match_df["strike_rate"] < 50), "sr_bonus"] = -6
player_match_df.loc[mask & (player_match_df["strike_rate"].between(50,59.99)), "sr_bonus"] = -4
player_match_df.loc[mask & (player_match_df["strike_rate"].between(60,69.99)), "sr_bonus"] = -2
player_match_df.loc[mask & (player_match_df["strike_rate"].between(130,149.99)), "sr_bonus"] = 2
player_match_df.loc[mask & (player_match_df["strike_rate"].between(150,169.99)), "sr_bonus"] = 4
player_match_df.loc[mask & (player_match_df["strike_rate"] >= 170), "sr_bonus"] = 6

In [51]:
player_match_df["wicket_bonus"] = 0

player_match_df.loc[player_match_df["wickets"] >= 3, "wicket_bonus"] = 4
player_match_df.loc[player_match_df["wickets"] >= 4, "wicket_bonus"] = 8
player_match_df.loc[player_match_df["wickets"] >= 5, "wicket_bonus"] = 16

In [52]:
player_match_df["eco_bonus"] = 0

mask = player_match_df["balls_bowled"] >= 12

player_match_df.loc[mask & (player_match_df["economy"] < 5), "eco_bonus"] = 6
player_match_df.loc[mask & (player_match_df["economy"].between(5,5.99)), "eco_bonus"] = 4
player_match_df.loc[mask & (player_match_df["economy"].between(6,6.99)), "eco_bonus"] = 2
player_match_df.loc[mask & (player_match_df["economy"].between(10,11)), "eco_bonus"] = -2
player_match_df.loc[mask & (player_match_df["economy"].between(11.01,12)), "eco_bonus"] = -4
player_match_df.loc[mask & (player_match_df["economy"] > 12), "eco_bonus"] = -6

In [53]:
lbw_bowled = data[
    data["wicket_kind"].isin(["bowled", "lbw"])
]

In [54]:
lbw_bowled

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
131,132101,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,1,...,4,7,1,NaN,2,3,1,"('R Dravid', 'W Jaffer')",V Kohli,True
138,132108,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,2,...,9,14,2,NaN,1,5,1,"('V Kohli', 'W Jaffer')",JH Kallis,True
210,132180,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,13,1,...,70,79,9,NaN,3,8,1,"('P Kumar', 'Z Khan')",SB Joshi,True
264,132234,335983,2008-04-19,T20,Indian Premier League,1,Chennai Super Kings,Kings XI Punjab,6,2,...,57,38,2,NaN,25,17,1,"('MEK Hussey', 'ML Hayden')",MS Dhoni,True
269,132239,335983,2008-04-19,T20,Indian Premier League,1,Chennai Super Kings,Kings XI Punjab,7,1,...,62,43,3,NaN,2,3,1,"('MEK Hussey', 'MS Dhoni')",SK Raina,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277681,277432,1473509,2025-05-30,T20,Indian Premier League,2,Gujarat Titans,Mumbai Indians,15,4,...,170,94,4,NaN,80,49,1,"('B Sai Sudharsan', 'SE Rutherford')",R Tewatia,True
278019,277770,1473511,2025-06-03,T20,Indian Premier League,1,Royal Challengers Bengaluru,Punjab Kings,10,5,...,96,65,3,NaN,26,16,1,"('RM Patidar', 'V Kohli')",LS Livingstone,True
278062,277813,1473511,2025-06-03,T20,Indian Premier League,1,Royal Challengers Bengaluru,Punjab Kings,16,5,...,167,101,5,NaN,25,15,1,"('JM Sharma', 'LS Livingstone')",R Shepherd,True
278067,277818,1473511,2025-06-03,T20,Indian Premier League,1,Royal Challengers Bengaluru,Punjab Kings,17,4,...,171,106,6,NaN,24,10,1,"('JM Sharma', 'R Shepherd')",KH Pandya,True
278077,277828,1473511,2025-06-03,T20,Indian Premier League,1,Royal Challengers Bengaluru,Punjab Kings,19,2,...,188,116,7,NaN,17,9,1,"('KH Pandya', 'R Shepherd')",B Kumar,True

In [55]:
lbw_bowled = (
    lbw_bowled
    .groupby(["match_id", "bowler"])
    .size()
    .reset_index(name="lbw_bowled_wickets")
)

In [56]:
lbw_bowled["lbw_bowled_bonus"] = lbw_bowled["lbw_bowled_wickets"] * 8

In [57]:
lbw_bowled

      match_id             bowler  lbw_bowled_wickets  lbw_bowled_bonus
0       335982           AB Dinda                   1                 8
1       335982           I Sharma                   1                 8
2       335982         SC Ganguly                   1                 8
3       335983          IK Pathan                   2                16
4       335983           JR Hopes                   1                 8
...        ...                ...                 ...               ...
2723   1473511     Arshdeep Singh                   1                 8
2724   1473511        KA Jamieson                   2                16
2725   1473511  Vijaykumar Vyshak                   1                 8
2726   1485779      Harpreet Brar                   1                 8
2727   1485779            V Nigam                   1                 8

[2728 rows x 4 columns]

In [58]:
lbw_bowled = lbw_bowled.rename(columns={"bowler": "player"})

In [59]:
player_match_df = player_match_df.merge(
    lbw_bowled[["match_id", "player", "lbw_bowled_bonus"]],
    on=["match_id", "player"],
    how="left"
)

In [60]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,0.0,10.0,0,0,0,-2,NaN
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0,0.0,0,0,4,2,NaN
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,0.0,0.0,0,0,0,6,8.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,-2.0,0,0,0,0,NaN
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0,194.0,16,6,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0,71.0,8,6,0,0,NaN
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,0.0,26.0,0,2,0,0,NaN
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0,11.0,0,0,0,0,NaN
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0,20.0,0,0,0,0,NaN
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,0.0,0.0,0,0,0,0,8.0

In [61]:
player_match_df["lbw_bowled_bonus"] = player_match_df["lbw_bowled_bonus"].fillna(0)

In [62]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,0.0,10.0,0,0,0,-2,0.0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0,0.0,0,0,4,2,0.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,0.0,0.0,0,0,0,6,8.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,-2.0,0,0,0,0,0.0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0,194.0,16,6,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0,71.0,8,6,0,0,0.0
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,0.0,26.0,0,2,0,0,0.0
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0,11.0,0,0,0,0,0.0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0,20.0,0,0,0,0,0.0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,0.0,0.0,0,0,0,0,8.0

In [63]:
player_match_df["bowling_points"] = player_match_df["wickets"] * 25

In [64]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,4.0,10.00,0.0,10.0,0,0,0,-2,0.0,25.0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,4.0,6.25,6.0,0.0,0,0,4,2,0.0,75.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,3.0,3.00,0.0,0.0,0,0,0,6,8.0,50.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,-2.0,0,0,0,0,0.0,0.0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,0.0,0.00,8.0,194.0,16,6,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,0.0,0.00,8.0,71.0,8,6,0,0,0.0,0.0
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,0.0,0.00,0.0,26.0,0,2,0,0,0.0,0.0
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,0.0,0.00,8.0,11.0,0,0,0,0,0.0,0.0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,0.0,0.00,40.0,20.0,0,0,0,0,0.0,0.0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,4.0,9.50,0.0,0.0,0,0,0,0,8.0,50.0

In [65]:
player_match_df["fantasy_points"] = (
    player_match_df["batting_points"]
    + player_match_df["batting_bonus"]
    + player_match_df["sr_bonus"]
    + player_match_df["bowling_points"]
    + player_match_df["wicket_bonus"]
    + player_match_df["eco_bonus"]
    + player_match_df["lbw_bowled_bonus"]
    + player_match_df["fielding_points"]
)

In [66]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,...,10.00,0.0,10.0,0,0,0,-2,0.0,25.0,33.0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,...,6.25,6.0,0.0,0,0,4,2,0.0,75.0,87.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,...,3.00,0.0,0.0,0,0,0,6,8.0,50.0,64.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.00,0.0,-2.0,0,0,0,0,0.0,0.0,-2.0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,...,0.00,8.0,194.0,16,6,0,0,0.0,0.0,224.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25013,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,...,0.00,8.0,71.0,8,6,0,0,0.0,0.0,93.0
25014,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,...,0.00,0.0,26.0,0,2,0,0,0.0,0.0,28.0
25015,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,...,0.00,8.0,11.0,0,0,0,0,0.0,0.0,19.0
25016,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,...,0.00,40.0,20.0,0,0,0,0,0.0,0.0,60.0
25017,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,...,9.50,0.0,0.0,0,0,0,0,8.0,50.0,58.0

In [67]:
valid_balls = data[data["valid_ball"] == 1]

In [68]:
valid_balls

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,131975,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,...,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,...,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,...,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,...,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,...,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

In [69]:
over_runs = (
    valid_balls
    .groupby(["match_id", "bowler", "over"])
    .agg(
        balls=("valid_ball", "count"),
        runs=("runs_bowler", "sum")
    )
    .reset_index()
)

In [70]:
over_runs

       match_id      bowler  over  balls  runs
0        335982   AA Noffke     3      6    17
1        335982   AA Noffke     6      6     7
2        335982   AA Noffke    15      6     4
3        335982   AA Noffke    17      6     7
4        335982  AB Agarkar     4      6     8
...         ...         ...   ...    ...   ...
45016   1485779     P Dubey    10      6    16
45017   1485779     V Nigam     5      6    15
45018   1485779     V Nigam     7      6     6
45019   1485779     V Nigam     9      6     6
45020   1485779     V Nigam    13      6    10

[45021 rows x 5 columns]

In [71]:
maiden_overs = over_runs[
    (over_runs["balls"] == 6) &
    (over_runs["runs"] == 0)
]

In [72]:
maiden_overs = (
    maiden_overs
    .groupby(["match_id", "bowler"])
    .size()
    .reset_index(name="maidens")
)

In [73]:
maiden_overs["maiden_points"] = maiden_overs["maidens"] * 12

In [74]:
maiden_overs = maiden_overs.rename(columns={"bowler": "player"})

In [75]:
player_match_df = player_match_df.merge(
    maiden_overs[["match_id", "player", "maiden_points"]],
    on=["match_id", "player"],
    how="left"
)

In [76]:
player_match_df["maiden_points"] = player_match_df["maiden_points"].fillna(0)

In [77]:
player_match_df["fantasy_points"] = (
    player_match_df["batting_points"]
    + player_match_df["batting_bonus"]
    + player_match_df["sr_bonus"]
    + player_match_df["bowling_points"]
    + player_match_df["wicket_bonus"]
    + player_match_df["eco_bonus"]
    + player_match_df["lbw_bowled_bonus"]
    + player_match_df["maiden_points"]
    + player_match_df["fielding_points"]
)

In [78]:
player_match_df.head(50)

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,...,0.0,10.0,0,0,0,-2,0.0,25.0,33.0,0.0
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,...,6.0,0.0,0,0,4,2,0.0,75.0,87.0,0.0
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,...,0.0,0.0,0,0,0,6,8.0,50.0,64.0,0.0
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,-2.0,0,0,0,0,0.0,0.0,-2.0,0.0
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,...,8.0,194.0,16,6,0,0,0.0,0.0,224.0,0.0
5,335982,CL White,6.0,10.0,0.0,0.0,60.000000,24.0,6.0,0.0,...,8.0,6.0,0,-2,0,0,0.0,0.0,12.0,0.0
6,335982,DJ Hussey,12.0,12.0,1.0,0.0,100.000000,0.0,0.0,0.0,...,0.0,13.0,0,0,0,0,0.0,0.0,13.0,0.0
7,335982,I Sharma,0.0,0.0,0.0,0.0,0.000000,7.0,18.0,1.0,...,0.0,0.0,0,0,0,6,8.0,25.0,39.0,0.0
8,335982,JH Kallis,8.0,7.0,0.0,1.0,114.285714,48.0,24.0,1.0,...,8.0,10.0,0,0,0,-4,0.0,25.0,39.0,0.0
9,335982,LR Shukla,0.0,0.0,0.0,0.0,0.000000,12.0,7.0,1.0,...,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0
10,335982,MV Boucher,7.0,9.0,1.0,0.0,77.777778,0.0,0.0,0.0,...,0.0,8.0,0,0,0,0,0.0,0.0,8.0,0.0
11,335982,Mohammad Hafeez,5.0,3.0,1.0,0.0,166.666667,0.0,0.0,0.0,...,0.0,6.0,0,0,0,0,0.0,0.0,6.0,0.0
12,335982,P Kumar,18.0,15.0,1.0,2.0,120.000000,38.0,24.0,0.0,...,8.0,23.0,0,0,0,0,0.0,0.0,43.0,12.0
13,335982,R Dravid,2.0,3.0,0.0,0.0,66.666667,0.0,0.0,0.0,...,0.0,2.0,0,0,0,0,0.0,0.0,2.0,0.0
14,335982,RT Ponting,20.0,20.0,1.0,1.0,100.000000,0.0,0.0,0.0,...,16.0,23.0,0,0,0,0,0.0,0.0,39.0,0.0
15,335982,SB Joshi,3.0,6.0,0.0,0.0,50.000000,26.0,18.0,0.0,...,0.0,3.0,0,0,0,0,0.0,0.0,3.0,0.0
16,335982,SC Ganguly,10.0,12.0,2.0,0.0,83.333333,21.0,24.0,2.0,...,0.0,12.0,0,0,0,4,8.0,50.0,74.0,0.0
17,335982,V Kohli,1.0,5.0,0.0,0.0,20.000000,0.0,0.0,0.0,...,0.0,1.0,0,0,0,0,0.0,0.0,1.0,0.0
18,335982,W Jaffer,6.0,16.0,0.0,0.0,37.500000,0.0,0.0,0.0,...,0.0,6.0,0,-6,0,0,0.0,0.0,0.0,0.0
19,335982,Z Khan,3.0,8.0,0.0,0.0,37.500000,38.0,24.0,1.0,...,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0
20,335983,B Lee,0.0,0.0,0.0,0.0,0.000000,35.0,24.0,1.0,...,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0
21,335983,IK Pathan,3.0,5.0,0.0,0.0,60.000000,47.0,24.0,2.0,...,8.0,3.0,0,0,0,-4,16.0,50.0,73.0,0.0
22,335983,JDP Oram,13.0,10.0,0.0,1.0,130.000000,37.0,24.0,0.0,...,0.0,15.0,0,2,0,0,0.0,0.0,17.0,0.0
23,335983,JR Hopes,71.0,33.0,10.0,3.0,215.151515,53.0,24.0,1.0,...,0.0,87.0,8,6,0,-6,8.0,25.0,128.0,0.0
24,335983,Joginder Sharma,0.0,0.0,0.0,0.0,0.000000,47.0,24.0,1.0,...,16.0,0.0,0,0,0,-4,0.0,25.0,37.0,0.0
25,335983,K Goel,24.0,19.0,2.0,1.0,126.315789,25.0,12.0,0.0,...,0.0,28.0,0,0,0,-6,0.0,0.0,22.0,0.0
26,335983,KC Sangakkara,54.0,33.0,5.0,2.0,163.636364,0.0,0.0,0.0,...,8.0,63.0,8,4,0,0,0.0,0.0,83.0,0.0
27,335983,M Muralitharan,0.0,0.0,0.0,0.0,0.000000,33.0,24.0,1.0,...,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0
28,335983,MEK Hussey,116.0,54.0,8.0,9.0,214.814815,0.0,0.0,0.0,...,0.0,142.0,16,6,0,0,0.0,0.0,164.0,0.0
29,335983,ML Hayden,25.0,16.0,4.0,1.0,156.250000,0.0,0.0,0.0,...,0.0,31.0,0,4,0,0,0.0,0.0,35.0,0.0
30,335983,MS Dhoni,2.0,3.0,0.0,0.0,66.666667,0.0,0.0,0.0,...,0.0,2.0,0,0,0,0,0.0,0.0,2.0,0.0
31,335983,MS Gony,0.0,0.0,0.0,0.0,0.000000,42.0,24.0,1.0,...,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0
32,335983,P Amarnath,0.0,0.0,0.0,0.0,0.000000,42.0,24.0,1.0,...,8.0,0.0,0,0,0,-2,0.0,25.0,31.0,0.0
33,335983,PA Patel,15.0,10.0,3.0,0.0,150.000000,0.0,0.0,0.0,...,8.0,18.0,0,4,0,0,0.0,0.0,30.0,0.0
34,335983,PP Chawla,0.0,0.0,0.0,0.0,0.000000,19.0,6.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0
35,335983,S Badrinath,31.0,14.0,3.0,2.0,221.428571,0.0,0.0,0.0,...,0.0,38.0,4,6,0,0,0.0,0.0,48.0,0.0
36,335983,S Sreesanth,0.0,0.0,0.0,0.0,0.000000,35.0,18.0,0.0,...,0.0,0.0,0,0,0,-4,0.0,0.0,-4.0,0.0
37,335983,SK Raina,32.0,13.0,2.0,3.0,246.153846,0.0,0.0,0.0,...,0.0,40.0,4,6,0,0,0.0,0.0,50.0,0.0
38,335983,SM Katich,21.0,17.0,0.0,1.0,123.529412,0.0,0.0,0.0,...,0.0,23.0,0,0,0,0,0.0,0.0,23.0,0.0
39,335983,WA Mota,0.0,0.0,0.0,0.0,0.000000,24.0,12.0,1.0,...,0.0,0.0,0,0,0,-4,0.0,25.0,21.0,0.0
40,335983,Yuvraj Singh,23.0,13.0,1.0,2.0,176.923077,0.0,0.0,0.0,...,0.0,28.0,0,6,0,0,0.0,0.0,34.0,0.0
41,335984,B Geeves,0.0,0.0,0.0,0.0,0.000000,41.0,24.0,0.0,...,8.0,0.0,0,0,0,-2,0.0,0.0,6.0,0.0
42,335984,D Salunkhe,26.0,20.0,4.0,0.0,130.000000,11.0,6.0,0.0,...,0.0,30.0,0,2,0,0,0.0,0.0,32.0,0.0
43,335984,DL Vettori,0.0,0.0,0.0,0.0,0.000000,35.0,24.0,1.0,...,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0
44,335984,DS Lehmann,1.0,2.0,0.0,0.0,50.000000,0.0,0.0,0.0,...,0.0,1.0,0,0,0,0,0.0,0.0,1.0,0.0
45,335984,G Gambhir,58.0,46.0,7.0,1.0,126.086957,0.0,0.0,0.0,...,0.0,67.0,8,0,0,0,0.0,0.0,75.0,0.0
46,335984,GD McGrath,0.0,0.0,0.0,0.0,0.000000,21.0,24.0,1.0,...,0.0,0.0,0,0,0,4,0.0,25.0,41.0,12.0
47,335984,M Kaif,9.0,19.0,0.0,0.0,47.368421,0.0,0.0,0.0,...,0.0,9.0,0,-6,0,0,0.0,0.0,3.0,0.0
48,335984,M Rawat,2.0,4.0,0.0,0.0,50.000000,0.0,0.0,0.0,...,0.0,2.0,0,0,0,0,0.0,0.0,2.0,0.0
49,335984,MF Maharoof,0.0,0.0,0.0,0.0,0.000000,11.0,24.0,2.0,...,0.0,0.0,0,0,0,6,16.0,50.0,72.0,0.0

In [79]:
match_meta = data[[
    "match_id",
    "venue",
    "city",
    "toss_winner",
    "toss_decision",
    "stage",
    "season"
]].drop_duplicates()

In [80]:
match_meta

,match_id,venue,city,toss_winner,toss_decision,stage,season
0,335982,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08
225,335983,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Unknown,2007/08
473,335984,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Unknown,2007/08
692,335985,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Unknown,2007/08
938,335986,Eden Gardens,Kolkata,Deccan Chargers,bat,Unknown,2007/08
...,...,...,...,...,...,...,...
277070,1473507,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Royal Challengers Bengaluru,field,Unknown,2025
277314,1473508,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Royal Challengers Bengaluru,field,Qualifier 1,2025
277461,1473509,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Mumbai Indians,bat,Eliminator,2025
277709,1473510,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Punjab Kings,field,Qualifier 2,2025
277953,1473511,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Punjab Kings,field,Final,2025

In [81]:
player_team = data[[
    "match_id",
    "batter",
    "bowler",
    "batting_team",
    "bowling_team"
]]

In [82]:
batter_team = player_team[["match_id","batter","batting_team","bowling_team"]]

batter_team = batter_team.rename(columns={
    "batter":"player",
    "batting_team":"team",
    "bowling_team":"opponent"
})

In [83]:
bowler_team = player_team[["match_id","bowler","batting_team","bowling_team"]]

bowler_team = bowler_team.rename(columns={
    "bowler":"player",
    "bowling_team":"team",
    "batting_team":"opponent"
})

In [84]:
player_teams = pd.concat([batter_team, bowler_team])

player_teams = player_teams.drop_duplicates()

In [85]:
player_match_df = player_match_df.merge(
    player_teams,
    on=["match_id","player"],
    how="left"
)

In [86]:
player_match_df = player_match_df.merge(
    match_meta,
    on="match_id",
    how="left"
)

In [87]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,...,33.0,0.0,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,...,87.0,0.0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,...,64.0,0.0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,-2.0,0.0,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,...,224.0,0.0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,...,93.0,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025
25121,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,...,28.0,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025
25122,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,...,19.0,0.0,Punjab Kings,Delhi Capitals,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025
25123,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,...,60.0,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025
25124,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,...,58.0,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025

In [88]:
player_match_df.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points', 'batting_points', 'batting_bonus', 'sr_bonus',
       'wicket_bonus', 'eco_bonus', 'lbw_bowled_bonus', 'bowling_points',
       'fantasy_points', 'maiden_points', 'team', 'opponent', 'venue', 'city',
       'toss_winner', 'toss_decision', 'stage', 'season'],
      dtype='object')

In [89]:
match_date = data[["match_id", "date"]].drop_duplicates()

In [90]:
player_match_df = player_match_df.merge(match_date, on="match_id", how="left")

In [91]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date
0,335982,AA Noffke,9.0,10.0,1.0,0.0,90.000000,40.0,24.0,1.0,...,0.0,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08,2008-04-18
1,335982,AB Agarkar,0.0,0.0,0.0,0.0,0.000000,25.0,24.0,3.0,...,0.0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08,2008-04-18
2,335982,AB Dinda,0.0,0.0,0.0,0.0,0.000000,9.0,18.0,2.0,...,0.0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08,2008-04-18
3,335982,B Akhil,0.0,2.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08,2008-04-18
4,335982,BB McCullum,158.0,73.0,10.0,13.0,216.438356,0.0,0.0,0.0,...,0.0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2007/08,2008-04-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1485779,Sameer Rizvi,58.0,25.0,3.0,5.0,232.000000,0.0,0.0,0.0,...,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025,2025-05-24
25121,1485779,Sediqullah Atal,22.0,16.0,0.0,2.0,137.500000,0.0,0.0,0.0,...,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025,2025-05-24
25122,1485779,Shashank Singh,11.0,10.0,0.0,0.0,110.000000,0.0,0.0,0.0,...,0.0,Punjab Kings,Delhi Capitals,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025,2025-05-24
25123,1485779,T Stubbs,18.0,14.0,2.0,0.0,128.571429,0.0,0.0,0.0,...,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025,2025-05-24
25124,1485779,V Nigam,0.0,0.0,0.0,0.0,0.000000,38.0,24.0,2.0,...,0.0,Delhi Capitals,Punjab Kings,"Sawai Mansingh Stadium, Jaipur",Jaipur,Delhi Capitals,field,Unknown,2025,2025-05-24

In [92]:
player_match_df = player_match_df.sort_values(["player", "date"])
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date
5895,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,...,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26
6001,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,...,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29
6044,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,...,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01
6132,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,...,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04
6219,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,...,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24396,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,...,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23
24444,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,...,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25
24617,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,...,0.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02
24701,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,...,0.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05
24824,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,...,0.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19

In [93]:
player_match_df["player_match_number"] = (
    player_match_df.groupby("player").cumcount() + 1
)

In [94]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number
5895,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,...,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1
6001,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,...,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2
6044,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,...,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3
6132,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,...,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4
6219,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,...,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24396,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,...,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6
24444,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,...,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7
24617,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,...,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8
24701,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,...,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9
24824,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,...,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10

In [95]:
player_match_df["last3_avg_points"] = (
    player_match_df
    .groupby("player")["fantasy_points"]
    .rolling(3)
    .mean()
    .shift(1)
    .reset_index(level=0, drop=True)
)

In [96]:
player_match_df["last5_avg_points"] = (
    player_match_df
    .groupby("player")["fantasy_points"]
    .rolling(5)
    .mean()
    .shift(1)
    .reset_index(level=0, drop=True)
)

In [97]:
player_match_df["last10_avg_points"] = (
    player_match_df
    .groupby("player")["fantasy_points"]
    .rolling(10)
    .mean()
    .shift(1)
    .reset_index(level=0, drop=True)
)

In [98]:
player_match_df["rolling_strike_rate"] = (
    player_match_df
    .groupby("player")["strike_rate"]
    .rolling(5)
    .mean()
    .shift(1)
    .reset_index(level=0, drop=True)
)

In [99]:
player_match_df["rolling_wickets"] = (
    player_match_df
    .groupby("player")["wickets"]
    .rolling(5)
    .mean()
    .shift(1)
    .reset_index(level=0, drop=True)
)

In [100]:
venue_avg = (
    player_match_df
    .groupby(["player", "venue"])["fantasy_points"]
    .mean()
    .reset_index(name="venue_avg_points")
)

In [101]:
player_match_df = player_match_df.merge(
    venue_avg,
    on=["player", "venue"],
    how="left"
)

In [102]:
opp_avg = (
    player_match_df
    .groupby(["player", "opponent"])["fantasy_points"]
    .mean()
    .reset_index(name="opponent_avg_points")
)

In [103]:
player_match_df = player_match_df.merge(
    opp_avg,
    on=["player", "opponent"],
    how="left"
)

In [104]:
player_match_df.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points', 'batting_points', 'batting_bonus', 'sr_bonus',
       'wicket_bonus', 'eco_bonus', 'lbw_bowled_bonus', 'bowling_points',
       'fantasy_points', 'maiden_points', 'team', 'opponent', 'venue', 'city',
       'toss_winner', 'toss_decision', 'stage', 'season', 'date',
       'player_match_number', 'last3_avg_points', 'last5_avg_points',
       'last10_avg_points', 'rolling_strike_rate', 'rolling_wickets',
       'venue_avg_points', 'opponent_avg_points'],
      dtype='object')

In [105]:
pitch_map = {

# Chennai
"MA Chidambaram Stadium": "spin_friendly",
"MA Chidambaram Stadium, Chepauk": "spin_friendly",

# Delhi
"Arun Jaitley Stadium": "batting_friendly",
"Feroz Shah Kotla": "batting_friendly",

# Mumbai
"Wankhede Stadium": "batting_friendly",
"Dr DY Patil Sports Academy": "batting_friendly",
"Brabourne Stadium": "batting_friendly",

# Bangalore
"M Chinnaswamy Stadium": "batting_friendly",
"M.Chinnaswamy Stadium": "batting_friendly",

# Kolkata
"Eden Gardens": "balanced",

# Ahmedabad
"Narendra Modi Stadium": "balanced",
"Sardar Patel Stadium, Motera": "balanced",

# Hyderabad
"Rajiv Gandhi International Stadium": "balanced",
"Rajiv Gandhi Intl. Cricket Stadium": "balanced",

# Jaipur
"Sawai Mansingh Stadium": "balanced",

# Punjab
"Punjab Cricket Association Stadium": "pace_friendly",
"Punjab Cricket Association IS Bindra Stadium": "pace_friendly",
"IS Bindra Stadium": "pace_friendly",

# Lucknow
"BRSABV Ekana Cricket Stadium": "spin_friendly",
"Ekana Cricket Stadium": "spin_friendly",

# Dharamshala
"Himachal Pradesh Cricket Association Stadium": "pace_friendly",

# Nagpur
"Vidarbha Cricket Association Stadium": "balanced",

# Raipur
"Shaheed Veer Narayan Singh International Stadium": "balanced",

# Indore
"Holkar Cricket Stadium": "batting_friendly",

# Cuttack
"Barabati Stadium": "balanced",

# Ranchi
"JSCA International Stadium Complex": "balanced",

# Guwahati
"Barsapara Cricket Stadium": "batting_friendly",

# Pune
"Maharashtra Cricket Association Stadium": "balanced",

# Cape Town (IPL 2009)
"Newlands": "balanced",

# Johannesburg (IPL 2009)
"New Wanderers Stadium": "batting_friendly",

# Durban (IPL 2009)
"Kingsmead": "pace_friendly",

# Port Elizabeth (IPL 2009)
"St George's Park": "pace_friendly",

# Centurion (IPL 2009)
"SuperSport Park": "batting_friendly",

# East London (IPL 2009)
"Buffalo Park": "balanced",

# Kimberley (IPL 2009)
"De Beers Diamond Oval": "balanced",

# Bloemfontein (IPL 2009)
"Mangaung Oval": "balanced",

# UAE 2014 / 2020 / 2021

# Dubai
"Dubai International Cricket Stadium": "balanced",

# Abu Dhabi
"Sheikh Zayed Stadium": "balanced",

# Sharjah
"Sharjah Cricket Stadium": "batting_friendly",

# Mohali alternate
"Inderjit Singh Bindra Stadium": "pace_friendly",

# Visakhapatnam
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "balanced",

# Kanpur
"Green Park": "spin_friendly",

# Thiruvananthapuram
"Greenfield International Stadium": "balanced"

}

In [106]:
player_match_df["pitch_type"] = player_match_df["venue"].map(pitch_map)

In [107]:
player_match_df["pitch_type"].head(50)

0                  NaN
1     batting_friendly
2             balanced
3        spin_friendly
4     batting_friendly
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11    batting_friendly
12    batting_friendly
13            balanced
14            balanced
15                 NaN
16       spin_friendly
17            balanced
18                 NaN
19    batting_friendly
20            balanced
21            balanced
22                 NaN
23                 NaN
24                 NaN
25    batting_friendly
26                 NaN
27                 NaN
28                 NaN
29                 NaN
30                 NaN
31                 NaN
32                 NaN
33                 NaN
34                 NaN
35                 NaN
36                 NaN
37                 NaN
38                 NaN
39                 NaN
40                 NaN
41                 NaN
42                 NaN
43                 NaN
44                 NaN
45                 NaN
46                 NaN
47                 NaN
48                 NaN
49                 NaN
Name: pitch_type, dtype: object

In [108]:
player_match_df['venue'].unique()

array(['Subrata Roy Sahara Stadium', 'Wankhede Stadium',
       'Barabati Stadium', 'MA Chidambaram Stadium, Chepauk',
       'M Chinnaswamy Stadium',
       'Rajiv Gandhi International Stadium, Uppal', 'Feroz Shah Kotla',
       'Eden Gardens', 'Maharashtra Cricket Association Stadium',
       'Sawai Mansingh Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Punjab Cricket Association Stadium, Mohali',
       'Wankhede Stadium, Mumbai', 'Brabourne Stadium, Mumbai',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'MA Chidambaram Stadium, Chepauk, Chennai',
       'M Chinnaswamy Stadium, Bengaluru',
       'Sawai Mansingh Stadium, Jaipur',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'Narendra Modi Stadium, Ahmedabad', 'Eden Gardens, Kolkata',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'Arun Jaitley Stadium, Delhi',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Newlands', "St George's Park", 'Kingsmead',
       'New Wanderers Stadium', 'SuperSport Park', 'Brabourne Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Dr DY Patil Sports Academy', 'Buffalo Park', 'OUTsurance Oval',
       'Sardar Patel Stadium, Motera', 'Nehru Stadium',
       'Himachal Pradesh Cricket Association Stadium',
       'Sheikh Zayed Stadium', 'Sharjah Cricket Stadium',
       'Dubai International Cricket Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'Saurashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'M.Chinnaswamy Stadium', 'Green Park',
       'Punjab Cricket Association IS Bindra Stadium',
       'Arun Jaitley Stadium', 'Rajiv Gandhi International Stadium',
       'MA Chidambaram Stadium', 'JSCA International Stadium Complex',
       'Zayed Cricket Stadium, Abu Dhabi',
       'Barsapara Cricket Stadium, Guwahati',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'De Beers Diamond Oval', 'Holkar Cricket Stadium',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'],
      dtype=object)

In [109]:
player_match_df["venue"] = player_match_df["venue"].str.strip()

In [110]:
player_match_df['venue'].unique()

array(['Subrata Roy Sahara Stadium', 'Wankhede Stadium',
       'Barabati Stadium', 'MA Chidambaram Stadium, Chepauk',
       'M Chinnaswamy Stadium',
       'Rajiv Gandhi International Stadium, Uppal', 'Feroz Shah Kotla',
       'Eden Gardens', 'Maharashtra Cricket Association Stadium',
       'Sawai Mansingh Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Punjab Cricket Association Stadium, Mohali',
       'Wankhede Stadium, Mumbai', 'Brabourne Stadium, Mumbai',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'MA Chidambaram Stadium, Chepauk, Chennai',
       'M Chinnaswamy Stadium, Bengaluru',
       'Sawai Mansingh Stadium, Jaipur',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'Narendra Modi Stadium, Ahmedabad', 'Eden Gardens, Kolkata',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'Arun Jaitley Stadium, Delhi',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Newlands', "St George's Park", 'Kingsmead',
       'New Wanderers Stadium', 'SuperSport Park', 'Brabourne Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Dr DY Patil Sports Academy', 'Buffalo Park', 'OUTsurance Oval',
       'Sardar Patel Stadium, Motera', 'Nehru Stadium',
       'Himachal Pradesh Cricket Association Stadium',
       'Sheikh Zayed Stadium', 'Sharjah Cricket Stadium',
       'Dubai International Cricket Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'Saurashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'M.Chinnaswamy Stadium', 'Green Park',
       'Punjab Cricket Association IS Bindra Stadium',
       'Arun Jaitley Stadium', 'Rajiv Gandhi International Stadium',
       'MA Chidambaram Stadium', 'JSCA International Stadium Complex',
       'Zayed Cricket Stadium, Abu Dhabi',
       'Barsapara Cricket Stadium, Guwahati',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'De Beers Diamond Oval', 'Holkar Cricket Stadium',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'],
      dtype=object)

In [111]:
pitch_map = {

# Pune
"Subrata Roy Sahara Stadium": "balanced",
"Maharashtra Cricket Association Stadium": "balanced",
"Maharashtra Cricket Association Stadium, Pune": "balanced",

# Mumbai
"Wankhede Stadium": "batting_friendly",
"Wankhede Stadium, Mumbai": "batting_friendly",
"Brabourne Stadium": "batting_friendly",
"Brabourne Stadium, Mumbai": "batting_friendly",
"Dr DY Patil Sports Academy": "batting_friendly",
"Dr DY Patil Sports Academy, Mumbai": "batting_friendly",

# Chennai
"MA Chidambaram Stadium": "spin_friendly",
"MA Chidambaram Stadium, Chepauk": "spin_friendly",
"MA Chidambaram Stadium, Chepauk, Chennai": "spin_friendly",

# Bangalore
"M Chinnaswamy Stadium": "batting_friendly",
"M Chinnaswamy Stadium, Bengaluru": "batting_friendly",
"M.Chinnaswamy Stadium": "batting_friendly",

# Hyderabad
"Rajiv Gandhi International Stadium": "balanced",
"Rajiv Gandhi International Stadium, Uppal": "balanced",
"Rajiv Gandhi International Stadium, Uppal, Hyderabad": "balanced",

# Delhi
"Feroz Shah Kotla": "batting_friendly",
"Arun Jaitley Stadium": "batting_friendly",
"Arun Jaitley Stadium, Delhi": "batting_friendly",

# Kolkata
"Eden Gardens": "balanced",
"Eden Gardens, Kolkata": "balanced",

# Jaipur
"Sawai Mansingh Stadium": "balanced",
"Sawai Mansingh Stadium, Jaipur": "balanced",

# Vizag
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "balanced",
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam": "balanced",

# Mohali / Punjab
"Punjab Cricket Association Stadium, Mohali": "pace_friendly",
"Punjab Cricket Association IS Bindra Stadium": "pace_friendly",
"Punjab Cricket Association IS Bindra Stadium, Mohali": "pace_friendly",
"Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "pace_friendly",

# Lucknow
"Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow": "spin_friendly",

# Ahmedabad
"Narendra Modi Stadium, Ahmedabad": "balanced",
"Sardar Patel Stadium, Motera": "balanced",

# Dharamshala
"Himachal Pradesh Cricket Association Stadium": "pace_friendly",
"Himachal Pradesh Cricket Association Stadium, Dharamsala": "pace_friendly",

# Cuttack
"Barabati Stadium": "balanced",

# Ranchi
"JSCA International Stadium Complex": "balanced",

# Guwahati
"Barsapara Cricket Stadium, Guwahati": "batting_friendly",

# Raipur
"Shaheed Veer Narayan Singh International Stadium": "balanced",

# Rajkot
"Saurashtra Cricket Association Stadium": "batting_friendly",

# Kanpur
"Green Park": "spin_friendly",

# Indore
"Holkar Cricket Stadium": "batting_friendly",

# Nagpur
"Vidarbha Cricket Association Stadium, Jamtha": "balanced",

# Kochi
"Nehru Stadium": "batting_friendly",

# Chandigarh new stadium
"Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur": "balanced",
"Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh": "balanced",

# UAE
"Dubai International Cricket Stadium": "balanced",
"Sharjah Cricket Stadium": "batting_friendly",
"Sheikh Zayed Stadium": "balanced",
"Zayed Cricket Stadium, Abu Dhabi": "balanced",

# South Africa IPL 2009
"Newlands": "balanced",
"St George's Park": "pace_friendly",
"Kingsmead": "pace_friendly",
"New Wanderers Stadium": "batting_friendly",
"SuperSport Park": "batting_friendly",
"Buffalo Park": "balanced",
"OUTsurance Oval": "balanced",
"De Beers Diamond Oval": "balanced"

}

In [112]:
player_match_df["pitch_type"] = player_match_df["venue"].map(pitch_map)

In [113]:
player_match_df['pitch_type'].head(50)

0             balanced
1     batting_friendly
2             balanced
3        spin_friendly
4     batting_friendly
5             balanced
6             balanced
7             balanced
8             balanced
9             balanced
10            balanced
11    batting_friendly
12    batting_friendly
13            balanced
14            balanced
15            balanced
16       spin_friendly
17            balanced
18            balanced
19    batting_friendly
20            balanced
21            balanced
22       pace_friendly
23            balanced
24            balanced
25    batting_friendly
26            balanced
27            balanced
28    batting_friendly
29    batting_friendly
30    batting_friendly
31    batting_friendly
32    batting_friendly
33    batting_friendly
34    batting_friendly
35            balanced
36            balanced
37            balanced
38    batting_friendly
39       spin_friendly
40       spin_friendly
41    batting_friendly
42       spin_friendly
43            balanced
44       spin_friendly
45       pace_friendly
46       spin_friendly
47       spin_friendly
48            balanced
49            balanced
Name: pitch_type, dtype: object

In [114]:
player_match_df['pitch_type'].tail(50)

25075    batting_friendly
25076            balanced
25077    batting_friendly
25078    batting_friendly
25079            balanced
25080            balanced
25081            balanced
25082    batting_friendly
25083            balanced
25084    batting_friendly
25085    batting_friendly
25086    batting_friendly
25087    batting_friendly
25088            balanced
25089            balanced
25090            balanced
25091    batting_friendly
25092            balanced
25093    batting_friendly
25094    batting_friendly
25095    batting_friendly
25096    batting_friendly
25097    batting_friendly
25098    batting_friendly
25099       pace_friendly
25100            balanced
25101            balanced
25102            balanced
25103            balanced
25104    batting_friendly
25105            balanced
25106    batting_friendly
25107    batting_friendly
25108            balanced
25109    batting_friendly
25110            balanced
25111    batting_friendly
25112       spin_friendly
25113    batting_friendly
25114    batting_friendly
25115            balanced
25116            balanced
25117            balanced
25118            balanced
25119    batting_friendly
25120            balanced
25121       spin_friendly
25122            balanced
25123            balanced
25124       spin_friendly
Name: pitch_type, dtype: object

In [115]:
match_runs = player_match_df.groupby("match_id")["runs"].sum().reset_index()
match_runs.rename(columns={"runs": "total_match_runs"}, inplace=True)

In [116]:
match_runs = match_runs.merge(
    player_match_df[["match_id", "venue"]].drop_duplicates(),
    on="match_id"
)

In [117]:
match_runs

,match_id,total_match_runs,venue
0,335982,268.0,M Chinnaswamy Stadium
1,335983,430.0,"Punjab Cricket Association Stadium, Mohali"
2,335984,244.0,Feroz Shah Kotla
3,335985,315.0,Wankhede Stadium
4,335986,184.0,Eden Gardens
...,...,...,...
1164,1473508,192.0,Maharaja Yadavindra Singh International Cricke...
1165,1473509,419.0,Maharaja Yadavindra Singh International Cricke...
1166,1473510,397.0,"Narendra Modi Stadium, Ahmedabad"
1167,1473511,354.0,"Narendra Modi Stadium, Ahmedabad"
1168,1485779,398.0,"Sawai Mansingh Stadium, Jaipur"

In [118]:
venue_avg_runs = match_runs.groupby("venue")["total_match_runs"].mean()

In [119]:
venue_avg_runs

venue
Arun Jaitley Stadium                                                       310.785714
Arun Jaitley Stadium, Delhi                                                366.086957
Barabati Stadium                                                           313.571429
Barsapara Cricket Stadium, Guwahati                                        322.600000
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow      317.409091
Brabourne Stadium                                                          326.300000
Brabourne Stadium, Mumbai                                                  323.352941
Buffalo Park                                                               247.333333
De Beers Diamond Oval                                                      286.000000
Dr DY Patil Sports Academy                                                 264.117647
Dr DY Patil Sports Academy, Mumbai                                         309.950000
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                        275.769231
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam         363.250000
Dubai International Cricket Stadium                                        298.978261
Eden Gardens                                                               291.467532
Eden Gardens, Kolkata                                                      352.652174
Feroz Shah Kotla                                                           296.050000
Green Park                                                                 309.000000
Himachal Pradesh Cricket Association Stadium                               302.222222
Himachal Pradesh Cricket Association Stadium, Dharamsala                   332.333333
Holkar Cricket Stadium                                                     303.888889
JSCA International Stadium Complex                                         279.428571
Kingsmead                                                                  271.733333
M Chinnaswamy Stadium                                                      294.446154
M Chinnaswamy Stadium, Bengaluru                                           350.473684
M.Chinnaswamy Stadium                                                      326.400000
MA Chidambaram Stadium                                                     273.666667
MA Chidambaram Stadium, Chepauk                                            301.500000
MA Chidambaram Stadium, Chepauk, Chennai                                   306.235294
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur         302.200000
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh    419.000000
Maharashtra Cricket Association Stadium                                    303.954545
Maharashtra Cricket Association Stadium, Pune                              301.000000
Narendra Modi Stadium, Ahmedabad                                           340.606061
Nehru Stadium                                                              257.200000
New Wanderers Stadium                                                      304.875000
Newlands                                                                   273.142857
OUTsurance Oval                                                            244.000000
Punjab Cricket Association IS Bindra Stadium                               333.400000
Punjab Cricket Association IS Bindra Stadium, Mohali                       310.545455
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh           351.600000
Punjab Cricket Association Stadium, Mohali                                 297.742857
Rajiv Gandhi International Stadium                                         295.933333
Rajiv Gandhi International Stadium, Uppal                                  289.367347
Rajiv Gandhi International Stadium, Uppal, Hyderabad                       346.157895
Sardar Patel Stadium, Motera                                               299.083333
Saurashtra Cricket Association Stadium                                     319.800000
Sawai Mansingh Stadium                                                     286.659574
Sawai Mansingh Stadium, Jaipur                                             343.117647
Shaheed Veer Narayan Singh International Stadium                           277.333333
Sharjah Cricket Stadium                                                    291.392857
Sheikh Zayed Stadium                                                       291.965517
St George's Park                                                           272.000000
Subrata Roy Sahara Stadium                                                 268.500000
SuperSport Park                                                            286.666667
Vidarbha Cricket Association Stadium, Jamtha                               274.000000
Wankhede Stadium                                                           308.273973
Wankhede Stadium, Mumbai                                                   326.557692
Zayed Cricket Stadium, Abu Dhabi                                           296.500000
Name: total_match_runs, dtype: float64

In [120]:
overall_avg_runs = match_runs["total_match_runs"].mean()

In [121]:
venue_run_factor = venue_avg_runs / overall_avg_runs

In [122]:
venue_run_factor

venue
Arun Jaitley Stadium                                                       1.018501
Arun Jaitley Stadium, Delhi                                                1.199733
Barabati Stadium                                                           1.027630
Barsapara Cricket Stadium, Guwahati                                        1.057219
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow      1.040207
Brabourne Stadium                                                          1.069344
Brabourne Stadium, Mumbai                                                  1.059686
Buffalo Park                                                               0.810556
De Beers Diamond Oval                                                      0.937274
Dr DY Patil Sports Academy                                                 0.865561
Dr DY Patil Sports Academy, Mumbai                                         1.015762
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                        0.903746
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam         1.190436
Dubai International Cricket Stadium                                        0.979806
Eden Gardens                                                               0.955192
Eden Gardens, Kolkata                                                      1.155705
Feroz Shah Kotla                                                           0.970209
Green Park                                                                 1.012649
Himachal Pradesh Cricket Association Stadium                               0.990437
Himachal Pradesh Cricket Association Stadium, Dharamsala                   1.089117
Holkar Cricket Stadium                                                     0.995899
JSCA International Stadium Complex                                         0.915738
Kingsmead                                                                  0.890519
M Chinnaswamy Stadium                                                      0.964953
M Chinnaswamy Stadium, Bengaluru                                           1.148566
M.Chinnaswamy Stadium                                                      1.069672
MA Chidambaram Stadium                                                     0.896855
MA Chidambaram Stadium, Chepauk                                            0.988070
MA Chidambaram Stadium, Chepauk, Chennai                                   1.003589
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur         0.990364
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh    1.373139
Maharashtra Cricket Association Stadium                                    0.996114
Maharashtra Cricket Association Stadium, Pune                              0.986432
Narendra Modi Stadium, Ahmedabad                                           1.116228
Nehru Stadium                                                              0.842891
New Wanderers Stadium                                                      0.999131
Newlands                                                                   0.895139
OUTsurance Oval                                                            0.799632
Punjab Cricket Association IS Bindra Stadium                               1.092612
Punjab Cricket Association IS Bindra Stadium, Mohali                       1.017714
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh           1.152257
Punjab Cricket Association Stadium, Mohali                                 0.975757
Rajiv Gandhi International Stadium                                         0.969827
Rajiv Gandhi International Stadium, Uppal                                  0.948309
Rajiv Gandhi International Stadium, Uppal, Hyderabad                       1.134422
Sardar Patel Stadium, Motera                                               0.980150
Saurashtra Cricket Association Stadium                                     1.048043
Sawai Mansingh Stadium                                                     0.939435
Sawai Mansingh Stadium, Jaipur                                             1.124459
Shaheed Veer Narayan Singh International Stadium                           0.908872
Sharjah Cricket Stadium                                                    0.954947
Sheikh Zayed Stadium                                                       0.956824
St George's Park                                                           0.891393
Subrata Roy Sahara Stadium                                                 0.879923
SuperSport Park                                                            0.939459
Vidarbha Cricket Association Stadium, Jamtha                               0.897948
Wankhede Stadium                                                           1.010270
Wankhede Stadium, Mumbai                                                   1.070189
Zayed Cricket Stadium, Abu Dhabi                                           0.971684
Name: total_match_runs, dtype: float64

In [123]:
player_match_df["venue_run_factor"] = player_match_df["venue"].map(venue_run_factor)

In [124]:
player_match_df.head(50)

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,...,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,32.0,24.0,2.0,...,1,NaN,NaN,NaN,NaN,NaN,58.000000,39.250000,balanced,0.879923
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.000000,11.0,13.0,1.0,...,2,NaN,NaN,NaN,NaN,NaN,41.000000,30.000000,batting_friendly,1.010270
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,32.0,18.0,1.0,...,3,NaN,NaN,NaN,NaN,NaN,23.000000,39.250000,balanced,1.027630
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.000000,16.0,12.0,1.0,...,4,40.666667,NaN,NaN,NaN,NaN,45.000000,47.333333,spin_friendly,0.988070
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,36.0,24.0,1.0,...,5,30.666667,NaN,NaN,NaN,NaN,31.750000,38.714286,batting_friendly,0.964953
5,548359,A Ashish Reddy,8.0,8.0,1.0,0.0,100.000000,39.0,24.0,2.0,...,6,28.000000,36.6,NaN,40.000000,1.2,34.250000,41.333333,balanced,0.948309
6,548329,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,29.0,12.0,0.0,...,7,47.333333,41.2,NaN,60.000000,1.2,34.250000,17.250000,balanced,0.948309
7,548373,A Ashish Reddy,10.0,4.0,2.0,0.0,250.000000,17.0,12.0,0.0,...,8,36.000000,31.8,NaN,40.000000,1.0,34.250000,14.000000,balanced,0.948309
8,548376,A Ashish Reddy,4.0,4.0,0.0,0.0,100.000000,25.0,24.0,3.0,...,9,29.000000,29.6,NaN,90.000000,0.8,34.250000,38.714286,balanced,0.948309
9,598000,A Ashish Reddy,7.0,4.0,1.0,0.0,175.000000,21.0,12.0,1.0,...,10,30.333333,41.0,NaN,90.000000,1.2,34.250000,39.250000,balanced,0.948309
10,598004,A Ashish Reddy,14.0,12.0,0.0,1.0,116.666667,7.0,6.0,1.0,...,11,45.333333,42.2,39.4,125.000000,1.2,34.250000,38.714286,balanced,0.948309
11,598048,A Ashish Reddy,3.0,4.0,0.0,0.0,75.000000,12.0,6.0,0.0,...,12,57.666667,35.8,38.5,128.333333,1.0,31.750000,38.714286,batting_friendly,0.964953
12,598010,A Ashish Reddy,16.0,9.0,2.0,0.0,177.777778,0.0,0.0,0.0,...,13,30.333333,37.6,34.7,143.333333,1.0,26.000000,17.250000,batting_friendly,0.970209
13,598013,A Ashish Reddy,4.0,5.0,0.0,0.0,80.000000,15.0,12.0,1.0,...,14,26.000000,40.4,35.0,128.888889,1.0,37.000000,42.500000,balanced,0.955192
14,598018,A Ashish Reddy,19.0,15.0,0.0,1.0,126.666667,0.0,0.0,0.0,...,15,22.000000,30.8,35.9,124.888889,0.6,37.000000,39.250000,balanced,0.996114
15,598021,A Ashish Reddy,7.0,7.0,1.0,0.0,100.000000,0.0,0.0,0.0,...,16,33.333333,30.4,36.3,115.222222,0.4,34.250000,41.333333,balanced,0.948309
16,598030,A Ashish Reddy,36.0,16.0,2.0,3.0,225.000000,15.0,4.0,0.0,...,17,30.000000,23.8,29.8,111.888889,0.2,45.000000,47.333333,spin_friendly,0.988070
17,598032,A Ashish Reddy,14.0,11.0,1.0,0.0,127.272727,0.0,0.0,0.0,...,18,38.333333,35.6,36.6,141.888889,0.2,15.000000,14.000000,balanced,0.939435
18,598044,A Ashish Reddy,5.0,6.0,1.0,0.0,83.333333,0.0,0.0,0.0,...,19,31.000000,33.4,36.9,131.787879,0.2,34.250000,17.250000,balanced,0.948309
19,829719,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,11.0,6.0,1.0,...,20,27.666667,27.2,29.0,132.454545,0.0,31.750000,38.714286,batting_friendly,0.964953
20,829727,A Ashish Reddy,13.0,9.0,0.0,1.0,144.444444,5.0,6.0,0.0,...,21,20.666667,28.0,29.2,107.121212,0.2,29.000000,14.000000,balanced,0.903746
21,829731,A Ashish Reddy,15.0,8.0,1.0,1.0,187.500000,15.0,12.0,1.0,...,22,20.666667,27.8,25.8,116.010101,0.2,29.000000,17.250000,balanced,0.903746
22,829759,A Ashish Reddy,22.0,8.0,1.0,2.0,275.000000,0.0,0.0,0.0,...,23,33.000000,24.0,29.8,108.510101,0.4,27.000000,41.333333,pace_friendly,0.975757
23,829773,A Ashish Reddy,6.0,6.0,1.0,0.0,100.000000,19.0,12.0,1.0,...,24,28.333333,26.4,29.9,138.055556,0.4,34.250000,47.333333,balanced,0.948309
24,829815,A Ashish Reddy,17.0,15.0,0.0,1.0,113.333333,0.0,0.0,0.0,...,25,40.666667,35.6,31.4,141.388889,0.6,34.250000,30.000000,balanced,0.948309
25,980907,A Ashish Reddy,32.0,18.0,2.0,3.0,177.777778,25.0,11.0,0.0,...,26,32.666667,31.2,29.6,164.055556,0.4,31.750000,38.714286,batting_friendly,0.964953
26,980915,A Ashish Reddy,13.0,8.0,0.0,1.0,162.500000,14.0,12.0,1.0,...,27,40.333333,38.2,33.0,170.722222,0.4,34.250000,42.500000,balanced,0.948309
27,980953,A Ashish Reddy,2.0,3.0,0.0,0.0,66.666667,0.0,0.0,0.0,...,28,39.000000,39.2,31.6,165.722222,0.4,34.250000,38.714286,balanced,0.948309
28,1304050,A Badoni,54.0,41.0,4.0,3.0,131.707317,0.0,0.0,0.0,...,1,36.000000,35.8,31.1,124.055556,0.4,42.000000,38.285714,batting_friendly,1.070189
29,1304053,A Badoni,19.0,9.0,0.0,2.0,211.111111,0.0,0.0,0.0,...,2,NaN,NaN,NaN,NaN,NaN,23.000000,39.500000,batting_friendly,1.059686
30,1304058,A Badoni,19.0,12.0,3.0,0.0,158.333333,0.0,0.0,0.0,...,3,NaN,NaN,NaN,NaN,NaN,23.333333,32.500000,batting_friendly,1.015762
31,1304061,A Badoni,10.0,3.0,1.0,1.0,333.333333,0.0,0.0,0.0,...,4,43.666667,NaN,NaN,NaN,NaN,23.333333,31.333333,batting_friendly,1.015762
32,1304066,A Badoni,5.0,7.0,0.0,0.0,71.428571,0.0,0.0,0.0,...,5,26.000000,NaN,NaN,NaN,NaN,42.000000,21.000000,batting_friendly,1.070189
33,1304077,A Badoni,13.0,13.0,2.0,0.0,100.000000,0.0,0.0,0.0,...,6,20.000000,31.4,NaN,181.182733,0.0,23.333333,17.000000,batting_friendly,1.015762
34,1304083,A Badoni,14.0,11.0,0.0,1.0,127.272727,6.0,6.0,1.0,...,7,13.666667,19.6,NaN,174.841270,0.0,42.000000,31.500000,batting_friendly,1.070189
35,1304088,A Badoni,4.0,4.0,0.0,0.0,100.000000,0.0,0.0,0.0,...,8,20.333333,23.2,NaN,158.073593,0.2,24.666667,43.000000,balanced,0.986432
36,1304099,A Badoni,15.0,18.0,0.0,0.0,83.333333,0.0,0.0,0.0,...,9,25.333333,20.4,NaN,146.406926,0.2,24.666667,29.000000,balanced,0.986432
37,1304103,A Badoni,8.0,11.0,1.0,0.0,72.727273,0.0,0.0,0.0,...,10,32.666667,23.6,NaN,96.406926,0.2,24.666667,38.285714,balanced,0.986432
38,1304109,A Badoni,0.0,1.0,0.0,0.0,0.000000,5.0,6.0,1.0,...,11,24.666667,26.0,28.7,96.666667,0.2,23.000000,21.000000,batting_friendly,1.059686
39,1359477,A Badoni,18.0,7.0,1.0,2.0,257.142857,0.0,0.0,0.0,...,12,25.666667,27.6,23.6,76.666667,0.4,28.277778,31.333333,spin_friendly,1.040207
40,1359480,A Badoni,23.0,18.0,0.0,0.0,127.777778,0.0,0.0,0.0,...,13,21.000000,24.0,23.6,102.640693,0.2,16.000000,39.500000,spin_friendly,1.003589
41,1359489,A Badoni,30.0,24.0,4.0,0.0,125.000000,0.0,0.0,0.0,...,14,23.000000,24.6,22.5,108.196248,0.2,18.000000,17.000000,batting_friendly,1.148566
42,1359495,A Badoni,5.0,6.0,0.0,0.0,83.333333,0.0,0.0,0.0,...,15,28.000000,24.8,24.2,116.529582,0.2,28.277778,43.000000,spin_friendly,1.040207
43,1359500,A Badoni,1.0,4.0,0.0,0.0,25.000000,0.0,0.0,0.0,...,16,22.000000,22.4,24.2,118.650794,0.2,23.000000,21.000000,balanced,1.124459
44,1359504,A Badoni,8.0,6.0,0.0,0.0,133.333333,0.0,0.0,0.0,...,17,14.666667,18.0,22.8,123.650794,0.0,28.277778,38.285714,spin_friendly,1.040207
45,1359512,A Badoni,43.0,23.0,3.0,3.0,186.956522,0.0,1.0,0.0,...,18,4.666667,15.0,19.5,98.888889,0.0,70.000000,43.000000,pace_friendly,1.152257
46,1359517,A Badoni,4.0,11.0,0.0,0.0,36.363636,0.0,0.0,0.0,...,19,26.333333,24.4,24.5,110.724638,0.0,28.277778,17.000000,spin_friendly,1.040207
47,1359519,A Badoni,59.0,33.0,2.0,4.0,178.787879,0.0,0.0,0.0,...,20,25.333333,16.4,20.6,92.997365,0.0,28.277778,39.500000,spin_friendly,1.040207
48,1359525,A Badoni,21.0,11.0,1.0,2.0,190.909091,0.0,0.0,0.0,...,21,50.333333,32.0,27.2,112.088274,0.0,49.000000,38.285714,balanced,1.116228
49,1359542,A Badoni,25.0,21.0,2.0,1.0,119.047619,0.0,0.0,0.0,...,22,37.666667,38.2,28.1,145.270092,0.0,31.000000,29.000000,balanced,1.155705

In [125]:
pd.set_option('display.max_columns', None)

In [126]:
player_match_df.head(50)

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,58.0,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,58.000000,39.250000,balanced,0.879923
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.000000,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,41.0,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,41.000000,30.000000,batting_friendly,1.010270
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,23.000000,39.250000,balanced,1.027630
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.000000,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,45.000000,47.333333,spin_friendly,0.988070
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,31.750000,38.714286,batting_friendly,0.964953
5,548359,A Ashish Reddy,8.0,8.0,1.0,0.0,100.000000,39.0,24.0,2.0,4.000000,9.750000,6.0,9.0,0,0,0,0,16.0,50.0,81.0,0.0,Deccan Chargers,Kings XI Punjab,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Deccan Chargers,field,Unknown,2012,2012-05-08,6,28.000000,36.6,NaN,40.000000,1.2,34.250000,41.333333,balanced,0.948309
6,548329,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,29.0,12.0,0.0,2.000000,14.500000,0.0,0.0,0,0,0,-6,0.0,0.0,-6.0,0.0,Deccan Chargers,Delhi Daredevils,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Deccan Chargers,bat,Unknown,2012,2012-05-10,7,47.333333,41.2,NaN,60.000000,1.2,34.250000,17.250000,balanced,0.948309
7,548373,A Ashish Reddy,10.0,4.0,2.0,0.0,250.000000,17.0,12.0,0.0,2.000000,8.500000,0.0,12.0,0,0,0,0,0.0,0.0,12.0,0.0,Deccan Chargers,Rajasthan Royals,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Rajasthan Royals,bat,Unknown,2012,2012-05-18,8,36.000000,31.8,NaN,40.000000,1.0,34.250000,14.000000,balanced,0.948309
8,548376,A Ashish Reddy,4.0,4.0,0.0,0.0,100.000000,25.0,24.0,3.0,4.000000,6.250000,0.0,4.0,0,0,4,2,0.0,75.0,85.0,0.0,Deccan Chargers,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Royal Challengers Bangalore,field,Unknown,2012,2012-05-20,9,29.000000,29.6,NaN,90.000000,0.8,34.250000,38.714286,balanced,0.948309
9,598000,A Ashish Reddy,7.0,4.0,1.0,0.0,175.000000,21.0,12.0,1.0,2.000000,10.500000,0.0,8.0,0,0,0,-2,8.0,25.0,39.0,0.0,Sunrisers Hyderabad,Pune Warriors,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Pune Warriors,field,Unknown,2013,2013-04-05,10,30.333333,41.0,NaN,90.000000,1.2,34.250000,39.250000,balanced,0.948309
10,598004,A Ashish Reddy,14.0,12.0,0.0,1.0,116.666667,7.0,6.0,1.0,1.000000,7.000000,8.0,16.0,0,0,0,0,0.0,25.0,49.0,0.0,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Royal Challengers Bangalore,bat,Unknown,2013,2013-04-07,11,45.333333,42.2,39.4,125.000000,1.2,34.250000,38.714286,balanced,0.948309
11,598048,A Ashish Reddy,3.0,4.0,0.0,0.0,75.000000,12.0,6.0,0.0,1.000000,12.000000,0.0,3.0,0,0,0,0,0.0,0.0,3.0,0.0,Sunrisers Hyderabad,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Sunrisers Hyderabad,bat,Unknown,2013,2013-04-09,12,57.666667,35.8,38.5,128.333333,1.0,31.750000,38.714286,batting_friendly,0.964953
12,598010,A Ashish Reddy,16.0,9.0,2.0,0.0,177.777778,0.0,0.0,0.0,0.000000,0.000000,8.0,18.0,0,0,0,0,0.0,0.0,26.0,0.0,Sunrisers Hyderabad,Delhi Daredevils,Feroz Shah Kotla,Delhi,Delhi Daredevils,bat,Unknown,2013,2013-04-12,13,30.333333,37.6,34.7,143.333333,1.0,26.000000,17.250000,batting_friendly,0.970209
13,598013,A Ashish Reddy,4.0,5.0,0.0,0.0,80.000000,15.0,12.0,1.0,2.000000,7.500000,0.0,4.0,0,0,0,0,8.0,25.0,37.0,0.0,Sunrisers Hyderabad,Kolkata Knight Riders,Eden Gardens,Kolkata,Kolkata Knight Riders,bat,Unknown,2013,2013-04-14,14,26.000000,40.4,35.0,128.888889,1.0,37.000000,42.500000,balanced,0.955192
14,598018,A Ashish Reddy,19.0,15.0,0.0,1.0,126.666667,0.0,0.0,0.0,0.000000,0.000000,16.0,21.0,0,0,0,0,0.0,0.0,37.0,0.0,Sunrisers Hyderabad,Pune Warriors,Maharashtra Cricket Association Stadium,Pune,Pune Warriors,field,Unknown,2013,2013-04-17,15,22.000000,30.8,35.9,124.888889,0.6,37.000000,39.250000,balanced,0.996114
15,598021,A Ashish Reddy,7.0,7.0,1.0,0.0,100.000000,0.0,0.0,0.0,0.000000,0.000000,8.0,8.0,0,0,0,0,0.0,0.0,16.0,0.0,Sunrisers Hyderabad,Kings XI Punjab,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Kings XI Punjab,bat,Unknown,2013,2013-04-19,16,33.333333,30.4,36.3,115.222222,0.4,34.250000,41.333333,balanced,0.948309
16,598030,A Ashish Reddy,36.0,16.0,2.0,3.0,225.000000,15.0,4.0,0.0,0.666667,22.500000,8.0,44.0,4,6,0,0,0.0,0.0,62.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Sunrisers Hyderabad,bat,Unknown,2013,2013-04-25,17,30.000000,23.8,29.8,111.888889,0.2,45.000000,47.333333,spin_friendly,0.988070
17,598032,A Ashish Reddy,14.0,11.0,1.0,0.0,127.272727,0.0,0.0,0.0,0.000000,0.000000,0.0,15.0,0,0,0,0,0.0,0.0,15.0,0.0,Sunrisers Hyderabad,Rajasthan Royals,Sawai Mansingh Stadium,Jaipur,Sunrisers Hyderabad,bat,Unknown,2013,2013-04-27,18,38.333333,35.6,36.6,141.888889,0.2,15.000000,14.000000,balanced,0.939435
18,598044,A Ashish Reddy,5.0,6.0,1.0,0.0,83.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,6.0,0,0,0,0,0.0,0.0,6.0,0.0,Sunrisers Hyderabad,Delhi Daredevils,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Delhi Daredevils,bat,Unknown,2013,2013-05-04,19,31.000000,33.4,36.9,131.787879,0.2,34.250000,17.250000,balanced,0.948309
19,829719,A Ashish Reddy,0.0,0.0,0.0,0.0,0.000000,11.0,6.0,1.0,1.000000,11.000000,8.0,0.0,0,0,0,0,8.0,25.0,41.0,0.0,Sunrisers Hyderabad,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Sunrisers Hyderabad,field,Unknown,2015,2015-04-13,20,27.666667,27.2,29.0,132.454545,0.0,31.750000,38.714286,batting_friendly,0.964953
20,829727,A Ashish Reddy,13.0,9.0,0.0,1.0,144.444444,5.0,6.0,0.0,1.000000,5.000000,0.0,15.0,0,0,0,0,0.0,0.0,15.0,0.0,Sunrisers Hyderabad,Rajasthan Royals,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Visakhapatnam,Rajasthan Royals,field,Unknown,2015,2015-04-16,21,20.666667,28.0,29.2,107.121212,0.2,29.000000,14.000000,balanced,0.903746
21,829731,A Ashish Reddy,15.0,8.0,1.0,1.0,187.500000,15.0,12.0,1.0,2.000000,7.500000,0.0,18.0,0,0,0,0,0.0,25.0,43.0,0.0,Sunrisers Hyderabad,Delhi Daredevils,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Visakhapatnam,Delhi Daredevils,bat,Unknown,2015,2015-04-18,22,20.666667,27.8,25.8,116.010101,0.2,29.000000,17.250000,balanced,0.903746
22,829759,A Ashish Reddy,22.0,8.0,1.0,2.0,275.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,27.0,0,0,0,0,0.0,0.0,27.0,0.0,Sunrisers Hyderabad,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Kings XI Punjab,field,Unknown,2015,2015-04-27,23,33.000000,24.0,29.8,108.510101,0.4,27.000000,41.333333,pace_friendly,0.975757
23,829773,A Ashish Reddy,6.0,6.0,1.0,0.0,100.000000,19.0,12.0,1.0,2.000000,9.500000,12.0,7.0,0,0,0,0,8.0,25.0,52.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Chennai Super Kings,field,Unknown,2015,2015-05-02,24,28.333333,26.4,29.9,138.055556,0.4,34.250000,47.333333,balanced,0.948309
24,829815,A Ashish Reddy,17.0,15.0,0.0,1.0,113.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,19.0,0,0,0,0,0.0,0.0,19.0,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,bat,Unknown,2015,2015-05-17,25,40.666667,35.6,31.4,141.388889,0.6,34.250000,30.000000,balanced,0.948309
25,980907,A Ashish Reddy,32.0,18.0,2.0,3.0,177.777778,25.0,11.0,0.0,1.833333,13.636364,0.0,40.0,4,6,0,0,0.0,0.0,50.0,0.0,Sunrisers Hyderabad,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Sunrisers Hyderabad,field,Unknown,2016,2016-04-12,26,32.666667,31.2,29.6,164.055556,0.4,31.750000,38.714286,batting_friendly,0.964953
26,980915,A Ashish Reddy,13.0,8.0,0.0,1.0,162.500000,14.0,12.0,1.0,2.000000,7.000000,0.0,15.0,0,0,0,0,8.0,25.0,48.0,0.0,Sunrisers Hyderabad,Kolkata Knight Riders,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,bat,Unknown,2016,2016-04-16,27,40.333333,38.2,33.0,170.722222,0.4,34.250000,42.500000,balanced,0.948309
27,980953,A Ashish Reddy,2.0,3.0,0.0,0.0,66.666667,0.0,0.0,0.0,0.000000,0.000000,8.0,2.0,0,0,0,0,0.0,0.0,10.0,0.0,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Royal Challengers Bangalore,field,Unknown,2016,2016-04-30,28,39.000000,39.2,31.6,165.722222,0.4,34.250000,38.714286,balanced,0.948309
28,1304050,A Badoni,54.0,41.0,4.0,3.0,131.707317,0.0,0.0,0.0,0.000000,0.000000,0.0,64.0,8,2,0,0,0.0,0.0,74.0,0.0,Lucknow Super Giants,Gujarat Titans,"Wankhede Stadium, Mumbai",Mumbai,Gujarat Titans,field,Unknown,2022,2022-03-28,1,36.000000,35.8,31.1,124.055556,0.4,42.000000,38.285714,batting_friendly,1.070189
29,1304053,A Badoni,19.0,9.0,0.0,2.0,211.111111,0.0,0.0,0.0,0.000000,0.000000,0.0,23.0,0,0,0,0,0.0,0.0,23.0,0.0,Lucknow Super Giants,Chennai Super Kings,"Brabourne Stadium, Mumbai",Mumbai,Lucknow Super Giants,field,Unknown,2022,2022-03-31,2,NaN,NaN,NaN,NaN,NaN,23.000000,39.500000,batting_friendly,1.059686
30,1304058,A Badoni,19.0,12.0,3.0,0.0,158.333333,0.0,0.0,0.0,0.000000,0.000000,8.0,22.0,0,4,0,0,0.0,0.0,34.0,0.0,Lucknow Super Giants,Sunrisers Hyderabad,"Dr DY Patil Sports Academy, Mumbai",Mumbai,Sunrisers Hyderabad,field,Unknown,2022,2022-04-04,3,NaN,NaN,NaN,NaN,NaN,23.333333,32.500000,batting_friendly,1.015762
31,1304061,A Badoni,10.0,3.0,1.0,1.0,333.333333,0.0,0.0,0.0,0.000000,0.000000,8.0,13.0,0,0,0,0,0.0,0.0,21.0,0.0,Lucknow Super Giants,Delhi Capitals,"Dr DY Patil Sports Academy, Mumbai",Mumbai,Lucknow Super Giants,field,Unknown,2022,2022-04-07,4,43.666667,NaN,NaN,NaN,NaN,23.333333,31.333333,batting_friendly,1.015762
32,1304066,A Badoni,5.0,7.0,0.0,0.0,71.428571,0.0,0.0,0.0,0.000000,0.000000,0.0,5.0,0,0,0,0,0.0,0.0,5.0,0.0,Lucknow Super Giants,Rajasthan Royals,"Wankhede Stadium, Mumbai",Mumbai,Lucknow Super Giants,field,Unknown,2022,2022-04-10,5,26.000000,NaN,NaN,NaN,NaN,42.000000,21.000000,batting_friendly,1.070189
33,1304077,A Badoni,13.0,13.0,2.0,0.0,100.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,15.0,0,0,0,0,0.0,0.0,15.0,0.0,Lucknow Super Giants,Royal Challengers Bangalore,"Dr DY Patil Sports Academy, Mumbai",Mumbai,Lucknow Super Giants,field,Unknown,2022,2022-04-19,6,20.000000,31.4,NaN,181.182733,0.0,23.333333,17.000000,batting_friendly,1.015762
34,1304083,A Badoni,14.0,11.0,0.0,1.0,127.272727,6.0,6.0,1.0,1.000000,6.000000,0.0,16.0,0,0,0,0,0.0,25.0,41.0,0.0,Lucknow Super Giants,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai,Mumbai Indians,field,Unknown,2022,2022-04-24,7,13.666667,19.6,NaN,174.841270,0.0,42.000000,31.500000,batting_friendly,1.070189
35,1304088,A Badoni,4.0,4.0,0.0,0.0,100.000000,0.0,0.0,0.0,0.000000,0.000000,16.0,4.0,0,0,0,0,0.0,0.0,20.0,0.0,Lucknow Super Giants,Punjab Kings,"Maharashtra Cricket Association Stadium, Pune",Pune,Punjab Kings,field,Unknown,2022,2022-04-29,8,20.333333,23.2,NaN,158.073593,0.2,24.666667,43.000000,balanced,0.986432
36,1304099,A Badoni,15.0,18.0,0.0,0.0,83.333333,0.0,0.0,0.0,0.000000,0.000000,22.0,15.0,0,0,0,0,0.0,0.0,37.0,0.0,Lucknow Super Giants,Kolkata Knight Riders,"Maharashtra Cricket Association Stadium, Pune",Pune,Kolkata Knight Riders,field,Unknown,2022,2022-05-07,9,25.333333,20.4,NaN,146.406926,0.2,24.666667,29.000000,balanced,0.986432
37,1304103,A Badoni,8.0,11.0,1.0,0.0,72.727273,0.0,0.0,0.0,0.000000,0.000000,8.0,9.0,0,0,0,0,0.0,0.0,17.0,0.0,Lucknow Super Giants,Gujarat Titans,"Maharashtra Cricket Association Stadium, Pune",Pune,Gujarat Titans,bat,Unknown,2022,2022-05-10,10,32.666667,23.6,NaN,96.406926,0.2,24.666667,38.285714,balanced,0.986432
38,1304109,A Badoni,0.0,1.0,0.0,0.0,0.000000,5.0,6.0,1.0,1.000000,5.000000,0.0,-2.0,0,0,0,0,0.0,25.0,23.0,0.0,Lucknow Super Giants,Rajasthan Royals,"Brabourne Stadium, Mumbai",Mumbai,Rajasthan Royals,bat,Unknown,2022,2022-05-15,11,24.666667,26.0,28.7,96.666667,0.2,23.000000,21.000000,batting_friendly,1.059686
39,1359477,A Badoni,18.0,7.0,1.0,2.0,257.142857,0.0,0.0,0.0,0.000000,0.000000,0.0,23.0,0,0,0,0,0.0,0.0,23.0,0.0,Lucknow Super Giants,Delhi Capitals,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Delhi Capitals,field,Unknown,2023,2023-04-01,12,25.666667,27.6,23.6,76.666667,0.4,28.277778,31.333333,spin_friendly,1.040207
40,1359480,A Badoni,23.0,18.0,0.0,0.0,127.777778,0.0,0.0,0.0,0.000000,0.000000,0.0,23.0,0,0,0,0,0.0,0.0,23.0,0.0,Lucknow Super Giants,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Lucknow Super Giants,field,Unknown,2023,2023-04-03,13,21.000000,24.0,23.6,102.640693,0.2,16.000000,39.500000,spin_friendly,1.003589
41,1359489,A Badoni,30.0,24.0,4.0,0.0,125.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,34.0,4,0,0,0,0.0,0.0,38.0,0.0,Lucknow Super Giants,Royal Challengers Bangalore,"M Chinnaswamy Stadium, Bengaluru",Bengaluru,Lucknow Super Giants,field,Unknown,2023,2023-04-10,14,23.000000,24.6,22.5,108.196248,0.2,18.000000,17.000000,batting_friendly,1.148566
42,1359495,A Badoni,5.0,6.0,0.0,0.0,83.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,5.0,0,0,0,0,0.0,0.0,5.0,0.0,Lucknow Super Giants,Punjab Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Punjab Kings,field,Unknown,2023,2023-04-15,15,28.000000,24.8,24.2,116.529582,0.2,28.277778,43.000000,spin_friendly,1.040207
43,1359500,A Badoni,1.0,4.0,0.0,0.0,25.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0,0,0,0,0.0,0.0,1.0,0.0,Lucknow Super Giants,Rajasthan Royals,"Sawai Mansingh Stadium, Jaipur",Jaipur,Rajasthan Royals,field,Unknown,2023,2023-04-19,16,22.000000,22.4,24.2,118.650794,0.2,23.000000,21.000000,balanced,1.124459
44,1359504,A Badoni,8.0,6.0,0.0,0.0,133.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,8.0,0,0,0,0,0.0,0.0,8.0,0.0,Lucknow Super Giants,Gujarat Titans,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Gujarat Titans,bat,Unknown,2023,2023-04-22,17,14.666667,18.0,22.8,123.650794,0.0,28.277778,38.285714,spin_friendly,1.040207
45,1359512,A Badoni,43.0,23.0,3.0,3.0,186.956522,0.0,1.0,0.0,0.166667,0.000000,8.0,52.0,4,6,0,0,0.0,0.0,70.0,0.0,Lucknow Super Giants,Punjab Kings,"Punjab Cricket Association IS Bindra Stadium, ...",Chandigarh,Punjab Kings,field,Unknown,2023,2023-04-28,18,4.666667,15.0,19.5,98.888889,0.0,70.000000,43.000000,pace_friendly,1.152257
46,1359517,A Badoni,4.0,11.0,0.0,0.0,36.363636,0.0,0.0,0.0,0.000000,0.000000,0.0,4.0,0,-6,0,0,0.0,0.0,-2.0,0.0,Lucknow Super Giants,Royal Challengers Bangalore,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Royal Challengers Bangalore,bat,Unknown,2023,2023-05-01,19,26.333333,24.4,24.5,110.724638,0.0,28.277778,17.000000,spin_friendly,1.040207
47,1359519,A Badoni,59.0,33.0,2.0,4.0,178.787879,0.0,0.0,0.0,0.000000,0.000000,0.0,69.0,8,6,0,0,0.0,0.0,83.0,0.0,Lucknow Super Giants,Chennai Super Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Chennai Super Kings,field,Unknown,2023,2023-05-03,20,25.333333,16.4,20.6,92.997365,0.0,28.277778,39.500000,spin_friendly,1.040207
48,1359525,A Badoni,21.0,11.0,1.0,2.0,190.909091,0.0,0.0,0.0,0.000000,0.000000,0.0,26.0,0,6,0,0,0.0,0.0,32.0,0.0,Lucknow Super Giants,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Lucknow Super Giants,field,Unknown,2023,2023-05-07,21,50.333333,32.0,27.2,112.088274,0.0,49.000000,38.285714,balanced,1.116228
49,1359542,A Badoni,25.0,21.0,2.0,1.0,119.047619,0.0,0.0,0.0,0.000000,0.000000,0.0,29.0,0,0,0,0,0.0,0.0,29.0,0.0,Lucknow Super Giants,Kolkata Knight Riders,"Eden Gardens, Kolkata",Kolkata,Kolkata Knight Riders,field,Unknown,2023,2023-05-20,22,37.666667,38.2,28.1,145.270092,0.0,31.000000,29.000000,balanced,1.155705

In [127]:
denominator = player_match_df["fantasy_points"] - player_match_df["fielding_points"]

player_match_df["batting_contribution_ratio"] = (
    player_match_df["batting_points"]
    + player_match_df["batting_bonus"]
    + player_match_df["sr_bonus"]
) / denominator.replace(0, 1)

In [128]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,58.0,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,58.00,39.250000,balanced,0.879923,0.000000
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,41.0,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,41.00,30.000000,batting_friendly,1.010270,0.292683
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,23.00,39.250000,balanced,1.027630,0.000000
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,45.00,47.333333,spin_friendly,0.988070,0.107143
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,31.75,38.714286,batting_friendly,0.964953,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,6.75,18.500000,balanced,1.134422,0.000000
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,23.00,11.500000,balanced,1.116228,0.000000
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,4.0,0.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,6.75,44.500000,balanced,1.134422,-0.000000
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,-2.0,0.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000

In [129]:
player_match_df["bowling_contribution_ratio"] = (
    player_match_df["bowling_points"]
    + player_match_df["eco_bonus"]
    + player_match_df["wicket_bonus"]
    + player_match_df["lbw_bowled_bonus"]
    + player_match_df["maiden_points"]
) / denominator.replace(0, 1)

In [130]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,58.0,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,58.00,39.250000,balanced,0.879923,0.000000,1.000000
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,41.0,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,23.00,39.250000,balanced,1.027630,0.000000,1.000000
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,6.75,18.500000,balanced,1.134422,0.000000,1.000000
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000,0.000000
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,23.00,11.500000,balanced,1.116228,0.000000,1.000000
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,4.0,0.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,6.75,44.500000,balanced,1.134422,-0.000000,1.000000
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,-2.0,0.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000,1.000000

In [131]:
def detect_role(row):
    if row["batting_contribution_ratio"] > 0.75:
        return "batsman"
    elif row["bowling_contribution_ratio"] > 0.75:
        return "bowler"
    else:
        return "allrounder"

player_match_df["player_role"] = player_match_df.apply(detect_role, axis=1)

In [132]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,58.0,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,41.0,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,6.75,18.500000,balanced,1.134422,0.000000,1.000000,bowler
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000,0.000000,allrounder
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,23.00,11.500000,balanced,1.116228,0.000000,1.000000,bowler
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,4.0,0.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,6.75,44.500000,balanced,1.134422,-0.000000,1.000000,bowler
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,-2.0,0.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000,1.000000,bowler

In [133]:
player_match_df.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points', 'batting_points', 'batting_bonus', 'sr_bonus',
       'wicket_bonus', 'eco_bonus', 'lbw_bowled_bonus', 'bowling_points',
       'fantasy_points', 'maiden_points', 'team', 'opponent', 'venue', 'city',
       'toss_winner', 'toss_decision', 'stage', 'season', 'date',
       'player_match_number', 'last3_avg_points', 'last5_avg_points',
       'last10_avg_points', 'rolling_strike_rate', 'rolling_wickets',
       'venue_avg_points', 'opponent_avg_points', 'pitch_type',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'player_role'],
      dtype='object')

In [134]:
player_match_df['last10_std_points'] = (
    player_match_df
    .groupby('player')['fantasy_points']
    .rolling(10, min_periods=3)
    .std()
    .reset_index(level=0, drop=True)
)

In [135]:
player_match_df['last10_std_points']

0              NaN
1              NaN
2        17.502381
3        15.631165
4        13.685759
           ...
25120    32.204037
25121    30.937725
25122    28.645618
25123    27.459060
25124    26.807130
Name: last10_std_points, Length: 25125, dtype: float64

In [136]:
player_match_df['player_consistency_index'] = (
    player_match_df['last10_avg_points'] /
    player_match_df['last10_std_points']
)

In [137]:
player_match_df['player_consistency_index'] = (
    player_match_df['player_consistency_index']
    .replace([float('inf'), -float('inf')], 0)
    .fillna(0)
)

In [138]:
player_match_df['player_consistency_index'].tail(50)

25075    0.890330
25076    1.055577
25077    1.319740
25078    0.939655
25079    1.191739
25080    1.380927
25081    1.641053
25082    1.578081
25083    1.611349
25084    1.379126
25085    1.341396
25086    1.197844
25087    1.037367
25088    1.500123
25089    1.177577
25090    1.049772
25091    1.045440
25092    1.006626
25093    1.019716
25094    1.064649
25095    1.235670
25096    1.123413
25097    0.828388
25098    1.013439
25099    1.049401
25100    1.171929
25101    1.046984
25102    1.058546
25103    1.098300
25104    0.975170
25105    0.939584
25106    1.127811
25107    1.389766
25108    1.179339
25109    0.999288
25110    0.861592
25111    0.745213
25112    0.734760
25113    0.702189
25114    0.829952
25115    0.000000
25116    0.000000
25117    0.000000
25118    0.000000
25119    0.000000
25120    0.000000
25121    0.000000
25122    0.000000
25123    0.000000
25124    0.000000
Name: player_consistency_index, dtype: float64

In [139]:
player_match_df['form_momentum'] = (
    player_match_df['last3_avg_points'] - player_match_df['last10_avg_points']
)

In [140]:
player_match_df[['player','last3_avg_points','last10_avg_points','form_momentum']].head(50)

            player  last3_avg_points  last10_avg_points  form_momentum
0   A Ashish Reddy               NaN                NaN            NaN
1   A Ashish Reddy               NaN                NaN            NaN
2   A Ashish Reddy               NaN                NaN            NaN
3   A Ashish Reddy         40.666667                NaN            NaN
4   A Ashish Reddy         30.666667                NaN            NaN
5   A Ashish Reddy         28.000000                NaN            NaN
6   A Ashish Reddy         47.333333                NaN            NaN
7   A Ashish Reddy         36.000000                NaN            NaN
8   A Ashish Reddy         29.000000                NaN            NaN
9   A Ashish Reddy         30.333333                NaN            NaN
10  A Ashish Reddy         45.333333               39.4       5.933333
11  A Ashish Reddy         57.666667               38.5      19.166667
12  A Ashish Reddy         30.333333               34.7      -4.366667
13  A Ashish Reddy         26.000000               35.0      -9.000000
14  A Ashish Reddy         22.000000               35.9     -13.900000
15  A Ashish Reddy         33.333333               36.3      -2.966667
16  A Ashish Reddy         30.000000               29.8       0.200000
17  A Ashish Reddy         38.333333               36.6       1.733333
18  A Ashish Reddy         31.000000               36.9      -5.900000
19  A Ashish Reddy         27.666667               29.0      -1.333333
20  A Ashish Reddy         20.666667               29.2      -8.533333
21  A Ashish Reddy         20.666667               25.8      -5.133333
22  A Ashish Reddy         33.000000               29.8       3.200000
23  A Ashish Reddy         28.333333               29.9      -1.566667
24  A Ashish Reddy         40.666667               31.4       9.266667
25  A Ashish Reddy         32.666667               29.6       3.066667
26  A Ashish Reddy         40.333333               33.0       7.333333
27  A Ashish Reddy         39.000000               31.6       7.400000
28        A Badoni         36.000000               31.1       4.900000
29        A Badoni               NaN                NaN            NaN
30        A Badoni               NaN                NaN            NaN
31        A Badoni         43.666667                NaN            NaN
32        A Badoni         26.000000                NaN            NaN
33        A Badoni         20.000000                NaN            NaN
34        A Badoni         13.666667                NaN            NaN
35        A Badoni         20.333333                NaN            NaN
36        A Badoni         25.333333                NaN            NaN
37        A Badoni         32.666667                NaN            NaN
38        A Badoni         24.666667               28.7      -4.033333
39        A Badoni         25.666667               23.6       2.066667
40        A Badoni         21.000000               23.6      -2.600000
41        A Badoni         23.000000               22.5       0.500000
42        A Badoni         28.000000               24.2       3.800000
43        A Badoni         22.000000               24.2      -2.200000
44        A Badoni         14.666667               22.8      -8.133333
45        A Badoni          4.666667               19.5     -14.833333
46        A Badoni         26.333333               24.5       1.833333
47        A Badoni         25.333333               20.6       4.733333
48        A Badoni         50.333333               27.2      23.133333
49        A Badoni         37.666667               28.1       9.566667

In [141]:
player_match_df.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
fantasy_points                   0
maiden_points                    0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points              1461
last5_avg_points              2701
last10_avg_points             5300
rolling_strike_rate           2711
rolling_wickets               2701
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1460
player_consistency_index         0
form_momentum                 5300
dtype: int64

In [142]:
bat_pos_data = data[['match_id','batter','bat_pos']]

In [143]:
bat_pos_data

        match_id          batter  bat_pos
0         335982      SC Ganguly        1
1         335982     BB McCullum        2
2         335982     BB McCullum        2
3         335982     BB McCullum        2
4         335982     BB McCullum        2
...          ...             ...      ...
278200   1473511  Shashank Singh        6
278201   1473511  Shashank Singh        6
278202   1473511  Shashank Singh        6
278203   1473511  Shashank Singh        6
278204   1473511  Shashank Singh        6

[278205 rows x 3 columns]

In [144]:
bat_pos_data = bat_pos_data.groupby(['batter'])['bat_pos'].agg(lambda x: x.mode()[0]).reset_index()

In [145]:
bat_pos_data = bat_pos_data.rename(columns = {'batter':'player'})

In [146]:
bat_pos_data

             player  bat_pos
0    A Ashish Reddy        7
1          A Badoni        6
2        A Chandila        8
3          A Chopra        2
4       A Choudhary       10
..              ...      ...
698   Yashpal Singh        5
699     Younis Khan        3
700   Yudhvir Singh        9
701    Yuvraj Singh        4
702          Z Khan        9

[703 rows x 2 columns]

In [147]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,58.0,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,NaN,0.0,NaN
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,41.0,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,NaN,0.0,NaN
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,17.502381,0.0,NaN
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,15.631165,0.0,NaN
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,13.685759,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,6.75,18.500000,balanced,1.134422,0.000000,1.000000,bowler,32.204037,0.0,NaN
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000,0.000000,allrounder,30.937725,0.0,NaN
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,23.00,11.500000,balanced,1.116228,0.000000,1.000000,bowler,28.645618,0.0,NaN
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,4.0,0.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,6.75,44.500000,balanced,1.134422,-0.000000,1.000000,bowler,27.459060,0.0,NaN
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,-2.0,0.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000,1.000000,bowler,26.807130,0.0,NaN

In [148]:
player_match_df = pd.merge(player_match_df,bat_pos_data,on = ['player'],how = 'left')

In [149]:
player_match_df.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
fantasy_points                   0
maiden_points                    0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points              1461
last5_avg_points              2701
last10_avg_points             5300
rolling_strike_rate           2711
rolling_wickets               2701
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1460
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
dtype: int64

In [150]:
#boundary_percentage = (4* fours + 6* sixes) / runs
player_match_df['boundary_percentage'] = (player_match_df['fours']*4 + player_match_df['sixes']*6)/player_match_df['runs']

In [151]:
player_match_df

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,fantasy_points,maiden_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,58.0,0.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,NaN
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,41.0,0.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,NaN,0.0,NaN,7.0,0.6
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,17.502381,0.0,NaN,7.0,NaN
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,28.0,0.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,15.631165,0.0,NaN,7.0,0.0
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,33.0,0.0,Deccan Chargers,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,13.685759,0.0,NaN,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,25.0,0.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,6.75,18.500000,balanced,1.134422,0.000000,1.000000,bowler,32.204037,0.0,NaN,NaN,NaN
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000,0.000000,allrounder,30.937725,0.0,NaN,NaN,NaN
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,23.0,0.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,23.00,11.500000,balanced,1.116228,0.000000,1.000000,bowler,28.645618,0.0,NaN,NaN,NaN
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,4.0,0.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,6.75,44.500000,balanced,1.134422,-0.000000,1.000000,bowler,27.459060,0.0,NaN,NaN,NaN
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,-2.0,0.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000,1.000000,bowler,26.807130,0.0,NaN,NaN,NaN

In [152]:
player_match_df['boundary_percentage'] = player_match_df['boundary_percentage'].fillna(0)

In [153]:
player_match_df.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points', 'batting_points', 'batting_bonus', 'sr_bonus',
       'wicket_bonus', 'eco_bonus', 'lbw_bowled_bonus', 'bowling_points',
       'fantasy_points', 'maiden_points', 'team', 'opponent', 'venue', 'city',
       'toss_winner', 'toss_decision', 'stage', 'season', 'date',
       'player_match_number', 'last3_avg_points', 'last5_avg_points',
       'last10_avg_points', 'rolling_strike_rate', 'rolling_wickets',
       'venue_avg_points', 'opponent_avg_points', 'pitch_type',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'player_role', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage'],
      dtype='object')

In [154]:
match_batting_pos = data[['match_id','batter','bat_pos']]
match_batting_pos = match_batting_pos.groupby(['match_id','batter'])['bat_pos'].first().reset_index()
match_batting_pos = match_batting_pos.rename(columns = {'batter':'player','bat_pos':'bat_pos_per_match'})

In [155]:
player_match_df = pd.merge(player_match_df,match_batting_pos,on = ['match_id','player'],how = 'left')

In [156]:
player_match_df.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
fantasy_points                   0
maiden_points                    0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points              1461
last5_avg_points              2701
last10_avg_points             5300
rolling_strike_rate           2711
rolling_wickets               2701
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1460
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
boundary_percentage              0
bat_pos_per_match             7403
dtype: int64

In [157]:
player_match_df['bat_pos_per_match'] = player_match_df['bat_pos_per_match'].fillna(player_match_df['bat_pos'])