In [39]:
import numpy as np
import pandas as pd
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv")

In [40]:
data.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'last10_std_points', 'player_consistency_index', 'form_momentum',
       'bat_pos', 'boundary_percentage', 'venue_avg_points',
       'player_role_wicketkeeper', 'team_won_toss', 'recent_form',
       'venue_form', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler'],
      dtype='object')

In [41]:
import pandas as pd
import joblib

model = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/models/point_predicter.pkl")

In [42]:
team1 = "Chennai Super Kings"
team2 = "Mumbai Indians"

venue = "Wankhede Stadium"

squad = [
'MS Dhoni','Ravindra Jadeja','Ruturaj Gaikwad','Deepak Chahar','Moeen Ali',
'Shivam Dube','Matheesha Pathirana','Ajinkya Rahane','Daryl Mitchell',
'Mitchell Santner','Tushar Deshpande',

'Rohit Sharma','Ishan Kishan','Suryakumar Yadav','Hardik Pandya',
'Tim David','Jasprit Bumrah','Piyush Chawla','Tilak Varma',
'Gerald Coetzee','Romario Shepherd','Nehal Wadhera'
]

In [43]:
historical_data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv")

In [44]:
historical_data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
0,548341,A Ashish Reddy,58.0,Subrata Roy Sahara Stadium,2012,1,35.672040,80.762144,0.0,39.250000,...,False,False,False,False,False,False,False,False,False,True
1,548346,A Ashish Reddy,41.0,Wankhede Stadium,2012,2,35.672040,80.762144,0.0,30.000000,...,False,False,False,False,True,True,False,False,False,False
2,548348,A Ashish Reddy,23.0,Barabati Stadium,2012,3,35.672040,80.762144,0.0,39.250000,...,False,False,False,False,False,False,False,False,False,True
3,548352,A Ashish Reddy,28.0,MA Chidambaram Stadium,2012,4,40.666667,80.762144,0.0,47.333333,...,False,False,False,False,False,False,False,True,False,True
4,548356,A Ashish Reddy,33.0,M Chinnaswamy Stadium,2012,5,30.666667,80.762144,0.0,38.714286,...,False,False,True,False,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Rajiv Gandhi International Stadium,2025,6,3.333333,0.000000,0.8,18.500000,...,False,False,False,False,True,False,False,False,False,True
25121,1473480,Zeeshan Ansari,0.0,MA Chidambaram Stadium,2025,7,11.666667,0.000000,0.4,0.000000,...,False,False,False,False,True,False,False,True,False,False
25122,1473488,Zeeshan Ansari,23.0,"Narendra Modi Stadium, Ahmedabad",2025,8,12.333333,0.000000,0.2,11.500000,...,False,False,False,False,True,False,False,False,False,True
25123,1473492,Zeeshan Ansari,4.0,Rajiv Gandhi International Stadium,2025,9,16.000000,0.000000,0.4,44.500000,...,False,False,False,False,True,False,False,False,False,True
25124,1473499,Zeeshan Ansari,-2.0,Ekana Cricket Stadium,2025,10,9.000000,0.000000,0.4,-2.000000,...,False,False,False,False,True,False,False,True,False,True

In [45]:
from difflib import get_close_matches
unique_player_list_from_df = historical_data['player'].unique()
unique_players = list(unique_player_list_from_df)
print(unique_player_list_from_df)

def map_player_name(name):
    
    match = get_close_matches(name, unique_players, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None

['A Ashish Reddy' 'A Badoni' 'A Chandila' 'A Chopra' 'A Choudhary'
 'A Dananjaya' 'A Flintoff' 'A Kamboj' 'A Kumble' 'A Manohar' 'A Mhatre'
 'A Mishra' 'A Mithun' 'A Mukund' 'A Nehra' 'A Nel' 'A Nortje'
 'A Raghuvanshi' 'A Singh' 'A Symonds' 'A Tomar' 'A Uniyal' 'A Zampa'
 'AA Bilakhia' 'AA Chavan' 'AA Jhunjhunwala' 'AA Kazi' 'AA Kulkarni'
 'AA Noffke' 'AB Agarkar' 'AB Barath' 'AB Dinda' 'AB McDonald'
 'AB de Villiers' 'AC Blizzard' 'AC Gilchrist' 'AC Thomas' 'AC Voges'
 'AD Hales' 'AD Mascarenhas' 'AD Mathews' 'AD Nath' 'AD Russell'
 'AF Milne' 'AG Murtaza' 'AG Paunikar' 'AJ Finch' 'AJ Hosein' 'AJ Turner'
 'AJ Tye' 'AK Markram' 'AL Menaria' 'AM Nayar' 'AM Rahane' 'AM Salvi'
 'AN Ahmed' 'AN Ghosh' 'AP Dole' 'AP Majumdar' 'AP Tare' 'AR Bawne'
 'AR Patel' 'AS Joseph' 'AS Rajpoot' 'AS Raut' 'AS Roy' 'AS Yadav'
 'AT Carey' 'AT Rayudu' 'AU Rashid' 'AUK Pathan' 'Abdul Basith'
 'Abdul Samad' 'Abdur Razzak' 'Abhishek Sharma' 'Abishek Porel'
 'Akash Deep' 'Akash Madhwal' 'Akash Singh' 'Aman Hakim Khan'
 'Anand Rajan' 'Aniket Verma' 'Anirudh Singh' 'Ankit Sharma' 'Ankit Soni'
 'Anmolpreet Singh' 'Anuj Rawat' 'Anureet Singh' 'Arjun Tendulkar'
 'Arshad Khan' 'Arshad Khan (2)' 'Arshdeep Singh' 'Ashutosh Sharma'
 'Ashwani Kumar' 'Atharva Taide' 'Avesh Khan' 'Azhar Mahmood'
 'Azmatullah Omarzai' 'B Akhil' 'B Chipli' 'B Geeves' 'B Indrajith'
 'B Kumar' 'B Laughlin' 'B Lee' 'B Sai Sudharsan' 'B Stanlake' 'B Sumanth'
 'BA Bhatt' 'BA Stokes' 'BAW Mendis' 'BB McCullum' 'BB Samantray'
 'BB Sran' 'BCJ Cutting' 'BE Hendricks' 'BJ Haddin' 'BJ Hodge' 'BJ Rohrer'
 'BKG Mendis' 'BMAJ Mendis' 'BR Dunk' 'BR Sharath' 'BW Hilfenhaus'
 'Basil Thampi' 'Bipul Sharma' 'C Bosch' 'C Ganapathy' 'C Green' 'C Madan'
 'C Munro' 'C Nanda' 'C Sakariya' 'C de Grandhomme' 'CA Ingram' 'CA Lynn'
 'CA Pujara' 'CH Gayle' 'CH Morris' 'CJ Anderson' 'CJ Dala' 'CJ Ferguson'
 'CJ Green' 'CJ Jordan' 'CJ McKay' 'CK Kapugedera' 'CK Langeveldt'
 'CL White' 'CM Gautam' 'CR Brathwaite' 'CR Woakes' 'CRD Fernando'
 'CV Varun' 'D Brevis' 'D Ferreira' 'D Jansen' 'D Kalyankrishna'
 'D Padikkal' 'D Pretorius' 'D Salunkhe' 'D Wiese' 'D du Preez'
 'DA Miller' 'DA Warner' 'DAJ Bracewell' 'DB Das' 'DB Ravi Teja'
 'DE Bollinger' 'DG Nalkande' 'DH Yagnik' 'DJ Bravo' 'DJ Harris'
 'DJ Hooda' 'DJ Hussey' 'DJ Jacobs' 'DJ Malan' 'DJ Mitchell'
 'DJ Muthuswami' 'DJ Thornely' 'DJ Willey' 'DJG Sammy' 'DJM Short'
 'DL Chahar' 'DL Vettori' 'DM Bravo' 'DNT Zoysa' 'DP Conway' 'DP Nannes'
 'DP Vijaykumar' 'DPMD Jayawardene' 'DR Martyn' 'DR Sams' 'DR Shorey'
 'DR Smith' 'DS Kulkarni' 'DS Lehmann' 'DS Rathi' 'DT Christian'
 'DT Patil' 'DW Steyn' 'Dhruv Jurel' 'E Lewis' 'E Malinga' 'EJG Morgan'
 'ER Dwivedi' 'F Behardien' 'F du Plessis' 'FA Allen' 'FH Edwards'
 'FY Fazal' 'Fazalhaq Farooqi' 'G Coetzee' 'G Gambhir' 'GB Hogg'
 'GC Smith' 'GC Viljoen' 'GD McGrath' 'GD Phillips' 'GH Vihari'
 'GHS Garton' 'GJ Bailey' 'GJ Maxwell' 'GR Napier' 'GS Sandhu'
 'Gagandeep Singh' 'Gulbadin Naib' 'Gurkeerat Singh' 'Gurnoor Brar'
 'H Das' 'H Klaasen' 'H Sharma' 'HC Brook' 'HE van der Dussen' 'HF Gurney'
 'HH Gibbs' 'HH Pandya' 'HM Amla' 'HR Shokeen' 'HV Patel'
 'Harbhajan Singh' 'Harmeet Singh' 'Harpreet Brar' 'Harpreet Singh'
 'Harsh Dubey' 'Harshit Rana' 'I Malhotra' 'I Sharma' 'I Udana'
 'IC Pandey' 'IC Porel' 'IK Pathan' 'IR Jaggi' 'IS Sodhi' 'Imran Tahir'
 'Iqbal Abdulla' 'Ishan Kishan' 'J Arunkumar' 'J Botha' 'J Fraser-McGurk'
 'J Little' 'J Overton' 'J Suchith' 'J Syed Mohammad' 'J Theron' 'J Yadav'
 'JA Morkel' 'JA Richardson' 'JC Archer' 'JC Buttler' 'JD Ryder'
 'JD Unadkat' 'JDP Oram' 'JDS Neesham' 'JE Root' 'JE Taylor'
 'JEC Franklin' 'JG Bethell' 'JH Kallis' 'JJ Bumrah' 'JJ Roy'
 'JJ van der Wath' 'JL Denly' 'JL Pattinson' 'JM Bairstow' 'JM Kemp'
 'JM Sharma' 'JO Holder' 'JP Behrendorff' 'JP Duminy' 'JP Faulkner'
 'JP Inglis' 'JPR Scantlebury-Searles' 'JR Hazlewood' 'JR Hopes'
 'JR Philippe' 'JW Hastings' 'Jalaj S Saxena' 'Jaskaran Singh'
 'Joginder Sharma' 'K Goel' 'K Gowtham' 'K Kartikeya' 'K Khejroliya'
 'K Rabada' 'K Santokie' 'K Upadhyay' 'K Yadav' 'KA Jamieson' 'KA Maharaj'
 'KA Pollard' 'KAJ Roach' 'KB Arun Karthik' 'KC Cariappa' 'KC Sangakkara'
 'KD Karthik' 'KH Pandya' 'KJ Abbott' 'KK Ahmed' 'KK Cooper' 'KK Nair'
 'KL Nagarkoti' 'KL Rahul' 'KM Asif' 'KM Jadhav' 'KMA Paul'
 'KMDN Kulasekara' 'KP Appanna' 'KP Pietersen' 'KR Mayers' 'KR Sen'
 'KS Bharat' 'KS Rathore' 'KS Sharma' 'KS Williamson' 'KT Maphaka'
 'KV Sharma' 'KW Richardson' 'Kamran Akmal' 'Kamran Khan'
 'Karanveer Singh' 'Karim Janat' 'Kartik Tyagi' 'Kuldeep Yadav'
 'Kumar Kushagra' 'L Ablish' 'L Balaji' 'L Ngidi' 'L Ronchi' 'L Wood'
 'LA Carseldine' 'LA Pomersbach' 'LB Williams' 'LE Plunkett' 'LH Ferguson'
 'LI Meriwala' 'LJ Wright' 'LMP Simmons' 'LPC Silva' 'LR Shukla'
 'LRPL Taylor' 'LS Livingstone' 'Lalit Yadav' 'Liton Das' 'M Ashwin'
 'M Jansen' 'M Kaif' 'M Kartik' 'M Klinger' 'M Manhas' 'M Markande'
 'M Morkel' 'M Muralitharan' 'M Ntini' 'M Pathirana' 'M Prasidh Krishna'
 'M Rawat' 'M Shahrukh Khan' 'M Siddharth' 'M Theekshana' 'M Tiwari'
 'M Vijay' 'M Vohra' 'M de Lange' 'MA Agarwal' 'MA Khote' 'MA Starc'
 'MA Wood' 'MB Parmar' 'MC Henriques' 'MC Juneja' 'MD Mishra' 'MD Shanaka'
 'MDKJ Perera' 'MEK Hussey' 'MF Maharoof' 'MG Bracewell' 'MG Johnson'
 'MG Neser' 'MJ Clarke' 'MJ Guptill' 'MJ Henry' 'MJ Lumb' 'MJ McClenaghan'
 'MJ Owen' 'MJ Santner' 'MJ Suthar' 'MK Lomror' 'MK Pandey' 'MK Tiwary'
 'ML Hayden' 'MM Ali' 'MM Patel' 'MM Sharma' 'MN Samuels' 'MN van Wyk'
 'MP Breetzke' 'MP Stoinis' 'MP Yadav' 'MR Marsh' 'MS Bhandage' 'MS Bisla'
 'MS Dhoni' 'MS Gony' 'MS Wade' 'MV Boucher' 'MW Short' 'Mandeep Singh'
 'Mashrafe Mortaza' 'Mayank Dagar' 'Misbah-ul-Haq' 'Mohammad Ashraful'
 'Mohammad Asif' 'Mohammad Hafeez' 'Mohammad Nabi' 'Mohammed Shami'
 'Mohammed Siraj' 'Mohit Rathee' 'Mohsin Khan' 'Monu Kumar'
 'Mujeeb Ur Rahman' 'Mukesh Choudhary' 'Mukesh Kumar' 'Musheer Khan'
 'Mustafizur Rahman' 'N Burger' 'N Jagadeesan' 'N Pooran' 'N Rana'
 'N Saini' 'N Thushara' 'N Wadhera' 'NA Saini' 'NB Singh' 'ND Doshi'
 'NJ Maddinson' 'NJ Rimmington' 'NK Patel' 'NL McCullum' 'NLTC Perera'
 'NM Coulter-Nile' 'NS Naik' 'NT Ellis' 'NV Ojha' 'Naman Dhir'
 'Navdeep Saini' 'Naveen-ul-Haq' 'Nithish Kumar Reddy' 'Noor Ahmad'
 'O Thomas' 'OA Shah' 'OC McCoy' 'OF Smith' 'P Amarnath' 'P Awana'
 'P Chopra' 'P Dogra' 'P Dubey' 'P Kumar' 'P Negi' 'P Parameswaran'
 'P Prasanth' 'P Ray Barman' 'P Sahu' 'P Simran Singh' 'P Suyal'
 'PA Patel' 'PA Reddy' 'PBB Rajapaksa' 'PC Valthaty' 'PD Collingwood'
 'PD Salt' 'PH Solanki' 'PHKD Mendis' 'PJ Cummins' 'PJ Sangwan' 'PK Garg'
 'PM Sarvesh Kumar' 'PN Mankad' 'PP Chawla' 'PP Ojha' 'PP Shaw' 'PR Shah'
 'PSP Handscomb' 'PV Tambe' 'PVD Chameera' 'PVSN Raju' 'PWA Mulder'
 'PWH de Silva' 'Pankaj Singh' 'Parvez Rasool' 'Prince Yadav'
 'Priyansh Arya' 'Q de Kock' 'R Ashwin' 'R Bhatia' 'R Bishnoi' 'R Dhawan'
 'R Dravid' 'R Goyal' 'R McLaren' 'R Minz' 'R Ninan' 'R Parag' 'R Powell'
 'R Rampaul' 'R Ravindra' 'R Sai Kishore' 'R Sanjay Yadav' 'R Sathish'
 'R Sharma' 'R Shepherd' 'R Shukla' 'R Tewatia' 'R Vinay Kumar' 'RA Bawa'
 'RA Jadeja' 'RA Shaikh' 'RA Tripathi' 'RD Chahar' 'RD Gaikwad'
 'RD Rickelton' 'RE Levi' 'RE van der Merwe' 'RG More' 'RG Sharma'
 'RJ Gleeson' 'RJ Harris' 'RJ Peterson' 'RJ Quiney' 'RJW Topley' 'RK Bhui'
 'RK Singh' 'RM Patidar' 'RN ten Doeschate' 'RP Meredith' 'RP Singh'
 'RR Bhatkal' 'RR Bose' 'RR Pant' 'RR Powar' 'RR Raje' 'RR Rossouw'
 'RR Sarwan' 'RS Bopara' 'RS Gavaskar' 'RS Hangargekar' 'RS Sodhi'
 'RT Ponting' 'RV Gomez' 'RV Patel' 'RV Uthappa' 'RW Price'
 'Rahmanullah Gurbaz' 'Ramandeep Singh' 'Rashid Khan' 'Rasikh Salam'
 'Ravi Bishnoi' 'S Anirudha' 'S Aravind' 'S Badree' 'S Badrinath'
 'S Chanderpaul' 'S Dhawan' 'S Dube' 'S Gopal' 'S Joseph' 'S Kaul'
 'S Kaushik' 'S Ladda' 'S Lamichhane' 'S Midhun' 'S Nadeem' 'S Narwal'
 'S Rana' 'S Randiv' 'S Sandeep Warrier' 'S Sohal' 'S Sreesanth'
 'S Sriram' 'S Tyagi' 'S Vidyut' 'SA Abbott' 'SA Asnodkar' 'SA Yadav'
 'SB Bangar' 'SB Dubey' 'SB Jakati' 'SB Joshi' 'SB Styris' 'SB Wagh'
 'SC Ganguly' 'SC Kuggeleijn' 'SD Chitnis' 'SD Hope' 'SD Lad' 'SE Bond'
 'SE Marsh' 'SE Rutherford' 'SH Johnson' 'SJ Srivastava' 'SK Raina'
 'SK Rasheed' 'SK Trivedi' 'SK Warne' 'SL Malinga' 'SM Boland' 'SM Curran'
 'SM Harwood' 'SM Katich' 'SM Pollock' 'SMSM Senanayake' 'SN Khan'
 'SN Thakur' 'SO Hetmyer' 'SP Fleming' 'SP Goswami' 'SP Jackson'
 'SP Narine' 'SPD Smith' 'SR Tendulkar' 'SR Watson' 'SS Agarwal'
 'SS Cottrell' 'SS Iyer' 'SS Mundhe' 'SS Prabhudessai' 'SS Sarkar'
 'SS Shaikh' 'SS Tiwary' 'SSB Magala' 'ST Jayasuriya' 'STR Binny'
 'SV Samson' 'SW Billings' 'SW Tait' 'SZ Mulani' 'Sachin Baby'
 'Salman Butt' 'Sameer Rizvi' 'Sandeep Sharma' 'Sanvir Singh'
 'Saurav Chauhan' 'Sediqullah Atal' 'Shahbaz Ahmed' 'Shahid Afridi'
 'Shakib Al Hasan' 'Shashank Singh' 'Shivam Mavi' 'Shivam Sharma'
 'Shivam Singh' 'Shoaib Ahmed' 'Shoaib Akhtar' 'Shoaib Malik'
 'Shubman Gill' 'Sikandar Raza' 'Simarjeet Singh' 'Sohail Tanvir'
 'Sumit Kumar' 'Sunny Gupta' 'Sunny Singh' 'Suryansh Shedge'
 'Suyash Sharma' 'Swapnil Singh' 'T Banton' 'T Henderson'
 'T Kohler-Cadmore' 'T Kohli' 'T Natarajan' 'T Shamsi' 'T Stubbs'
 'T Taibu' 'T Thushara' 'TA Boult' 'TD Paine' 'TG Southee' 'TH David'
 'TK Curran' 'TL Seifert' 'TL Suman' 'TM Dilshan' 'TM Head'
 'TM Srivastava' 'TP Sudhindra' 'TR Birt' 'TS Mills' 'TU Deshpande'
 'Tanush Kotian' 'Tejas Baroka' 'Tilak Varma' 'U Kaul' 'UA Birla'
 'UBT Chand' 'UT Khawaja' 'UT Yadav' 'Umar Gul' 'Umran Malik'
 'Urvil Patel' 'V Kaverappa' 'V Kohli' 'V Nigam' 'V Pratap Singh'
 'V Puthur' 'V Sehwag' 'V Shankar' 'V Suryavanshi' 'V Viyaskanth'
 'VG Arora' 'VH Zol' 'VR Aaron' 'VR Iyer' 'VRV Singh' 'VS Malik'
 'VS Yeligati' 'VVS Laxman' 'VY Mahesh' 'Vijaykumar Vyshak' 'Virat Singh'
 'Vishnu Vinod' 'Vivrant Sharma' 'W Jaffer' "W O'Rourke" 'WA Mota'
 'WD Parnell' 'WG Jacks' 'WP Saha' 'WPUJC Vaas' 'Washington Sundar'
 'X Thalaivan Sargunam' 'XC Bartlett' 'Y Gnaneswara Rao' 'Y Nagar'
 'Y Prithvi Raj' 'Y Venugopal Rao' 'YA Abdulla' 'YBK Jaiswal' 'YK Pathan'
 'YS Chahal' 'YV Dhull' 'YV Takawale' 'Yash Dayal' 'Yash Thakur'
 'Yashpal Singh' 'Younis Khan' 'Yudhvir Singh' 'Yuvraj Singh' 'Z Khan'
 'Zeeshan Ansari']

In [46]:
mapped_players = [map_player_name(p) for p in squad]
mapped_players = [p for p in mapped_players if p is not None]
print(mapped_players)

['MS Dhoni', 'RA Jadeja', 'RD Gaikwad', 'RD Chahar', 'MM Ali', 'S Dube', 'M Pathirana', 'AM Rahane', 'DJ Mitchell', 'MJ Santner', 'TU Deshpande', 'R Sharma', 'Ishan Kishan', 'R Sanjay Yadav', 'KH Pandya', 'TH David', 'JJ Bumrah', 'PP Chawla', 'Tilak Varma', 'G Coetzee', 'R Shepherd', 'N Wadhera']

In [47]:
unique_venue_list_from_df = historical_data['venue'].unique()
unique_venues = list(unique_venue_list_from_df)
print(unique_venues)
def map_venue_name(name):
    
    match = get_close_matches(name, unique_venues, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None
print(historical_data['venue'].value_counts())

['Subrata Roy Sahara Stadium', 'Wankhede Stadium', 'Barabati Stadium', 'MA Chidambaram Stadium', 'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium', 'Arun Jaitley Stadium', 'Eden Gardens', 'Maharashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Punjab Cricket Association IS Bindra Stadium', 'Brabourne Stadium', 'Dr DY Patil Sports Academy', 'Ekana Cricket Stadium', 'Narendra Modi Stadium, Ahmedabad', 'Himachal Pradesh Cricket Association Stadium', 'Newlands', "St George's Park", 'Kingsmead', 'New Wanderers Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Buffalo Park', 'OUTsurance Oval', 'Nehru Stadium', 'Sheikh Zayed Stadium', 'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium', 'Shaheed Veer Narayan Singh International Stadium', 'Saurashtra Cricket Association Stadium', 'Green Park', 'JSCA International Stadium Complex', 'Barsapara Cricket Stadium, Guwahati', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'De Beers Diamond Oval', 'Holkar Cricket Stadium']
venue
Wankhede Stadium                                                      2719
Eden Gardens                                                          2125
M Chinnaswamy Stadium                                                 2116
Arun Jaitley Stadium                                                  2099
MA Chidambaram Stadium                                                1991
Rajiv Gandhi International Stadium                                    1772
Sawai Mansingh Stadium                                                1347
Punjab Cricket Association IS Bindra Stadium                          1297
Narendra Modi Stadium, Ahmedabad                                      1002
Dubai International Cricket Stadium                                    988
Sheikh Zayed Stadium                                                   788
Dr DY Patil Sports Academy                                             786
Maharashtra Cricket Association Stadium                                746
Sharjah Cricket Stadium                                                594
Brabourne Stadium                                                      567
Ekana Cricket Stadium                                                  501
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    374
Subrata Roy Sahara Stadium                                             336
Kingsmead                                                              317
Himachal Pradesh Cricket Association Stadium                           309
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     260
SuperSport Park                                                        249
Saurashtra Cricket Association Stadium                                 203
Holkar Cricket Stadium                                                 188
New Wanderers Stadium                                                  184
Newlands                                                               164
Barabati Stadium                                                       149
JSCA International Stadium Complex                                     148
St George's Park                                                       144
Shaheed Veer Narayan Singh International Stadium                       126
Barsapara Cricket Stadium, Guwahati                                    115
Nehru Stadium                                                          107
Green Park                                                              83
Vidarbha Cricket Association Stadium, Jamtha                            65
De Beers Diamond Oval                                                   62
Buffalo Park                                                            61
OUTsurance Oval                                                         43
Name: count, dtype: int64

In [48]:
mapped_venues = map_venue_name(venue)
mapped_venues

'Wankhede Stadium'

In [49]:
players_df = historical_data[
    historical_data['player'].isin(mapped_players)
].copy()

In [50]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
1557,335994,AM Rahane,-2.0,Dr DY Patil Sports Academy,2007/08,1,17.000000,93.818369,0.0,20.666667,...,False,False,False,False,True,True,False,False,True,False
1558,335997,AM Rahane,5.0,Eden Gardens,2007/08,2,35.672040,80.762144,0.0,36.318182,...,False,False,False,False,False,False,False,False,True,False
1559,392203,AM Rahane,11.0,Buffalo Park,2009,3,35.672040,80.762144,0.0,36.318182,...,False,False,False,False,False,False,False,False,True,False
1560,392208,AM Rahane,-2.0,New Wanderers Stadium,2009,4,4.666667,80.762144,0.0,47.583333,...,False,False,True,False,False,True,False,False,True,False
1561,392215,AM Rahane,14.0,Buffalo Park,2009,5,4.666667,80.762144,0.0,53.954545,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23066,1473493,Tilak Varma,7.0,Wankhede Stadium,2025,47,18.666667,143.084148,0.0,35.857143,...,False,False,False,False,True,True,False,False,True,False
23067,1473501,Tilak Varma,30.0,Wankhede Stadium,2025,48,10.666667,124.463458,0.0,48.857143,...,False,False,False,False,True,True,False,False,True,False
23068,1473506,Tilak Varma,1.0,Sawai Mansingh Stadium,2025,49,17.333333,108.705882,0.0,36.333333,...,False,False,False,False,True,False,False,False,True,False
23069,1473509,Tilak Varma,45.0,Maharaja Yadavindra Singh International Cricke...,2025,50,12.666667,89.000000,0.0,35.857143,...,False,False,False,False,False,False,False,False,True,False
23070,1473510,Tilak Varma,58.0,"Narendra Modi Stadium, Ahmedabad",2025,51,25.333333,114.454545,0.0,36.333333,...,False,False,False,False,True,False,False,False,True,False

In [51]:
players_df = (
    players_df
    .sort_values('player_match_number')
    .groupby('player')
    .tail(1)
)

In [52]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
16657,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,...,False,False,False,True,True,True,False,False,False,False
6141,1473509,G Coetzee,2.0,Maharaja Yadavindra Singh International Cricke...,2025,14,26.333333,100.857143,0.6,23.000000,...,False,False,False,False,False,False,False,False,False,True
5105,1426306,DJ Mitchell,20.0,M Chinnaswamy Stadium,2024,15,52.000000,154.983925,0.0,20.000000,...,False,False,True,False,True,True,False,False,True,False
16745,1473511,R Shepherd,43.0,"Narendra Modi Stadium, Ahmedabad",2025,17,38.666667,81.538462,0.8,27.600000,...,False,False,False,False,True,False,False,False,False,False
12432,1473510,MJ Santner,6.0,"Narendra Modi Stadium, Ahmedabad",2025,31,60.333333,20.000000,1.4,33.500000,...,False,False,False,False,True,False,False,False,True,False
14364,1473511,N Wadhera,17.0,"Narendra Modi Stadium, Ahmedabad",2025,31,30.333333,128.719064,0.0,36.500000,...,False,False,True,False,True,False,False,False,True,False
11561,1473504,M Pathirana,41.0,"Narendra Modi Stadium, Ahmedabad",2025,32,25.666667,0.000000,1.0,47.600000,...,False,False,False,False,False,False,False,False,False,True
22805,1473503,TH David,1.0,Ekana Cricket Stadium,2025,44,21.000000,216.000000,0.0,53.000000,...,False,False,False,True,True,False,False,True,True,False
16728,733975,R Sharma,-2.0,Arun Jaitley Stadium,2014,44,15.000000,0.000000,0.6,28.833333,...,True,False,False,False,True,True,False,False,False,True
23017,1473500,TU Deshpande,33.0,Arun Jaitley Stadium,2025,46,24.000000,10.000000,0.6,18.333333,...,False,False,False,False,True,True,False,False,False,True
23070,1473510,Tilak Varma,58.0,"Narendra Modi Stadium, Ahmedabad",2025,51,25.333333,114.454545,0.0,36.333333,...,False,False,False,False,True,False,False,False,True,False
12819,1473494,MM Ali,29.0,Eden Gardens,2025,70,33.000000,23.717949,1.0,32.800000,...,False,False,False,False,False,False,False,False,False,True
17445,1473459,RD Gaikwad,1.0,Maharaja Yadavindra Singh International Cricke...,2025,70,34.000000,94.405594,0.0,36.444444,...,False,False,False,False,False,False,False,False,True,False
19174,1473504,S Dube,31.0,"Narendra Modi Stadium, Ahmedabad",2025,76,38.666667,173.541667,0.0,31.750000,...,False,False,False,False,False,False,False,False,True,False
17375,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,...,False,False,False,False,True,True,False,False,False,False
7797,1473505,Ishan Kishan,37.0,Arun Jaitley Stadium,2025,114,70.000000,110.343137,0.0,38.181818,...,False,False,False,False,False,True,False,False,True,False
9915,1473511,KH Pandya,68.0,"Narendra Modi Stadium, Ahmedabad",2025,144,17.000000,58.405797,0.6,36.736842,...,False,False,False,False,True,False,False,False,False,True
8635,1473510,JJ Bumrah,-2.0,"Narendra Modi Stadium, Ahmedabad",2025,147,57.666667,0.000000,1.8,45.666667,...,False,False,False,False,True,False,False,False,False,True
1739,1473505,AM Rahane,18.0,Arun Jaitley Stadium,2025,183,49.000000,139.011544,0.0,33.772727,...,False,False,False,True,False,True,False,False,True,False
15604,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,...,False,False,False,False,True,True,False,False,False,True
13476,1473500,MS Dhoni,18.0,Arun Jaitley Stadium,2025,241,25.000000,129.222222,0.0,34.807692,...,True,False,False,False,True,True,False,False,True,False
17196,1473504,RA Jadeja,78.0,"Narendra Modi Stadium, Ahmedabad",2025,247,56.000000,129.261438,0.6,50.857143,...,False,False,False,False,False,False,False,False,False,False

In [53]:
players_df['venue'] = venue
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
16657,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,...,False,False,False,True,True,True,False,False,False,False
6141,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,...,False,False,False,False,False,False,False,False,False,True
5105,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,...,False,False,True,False,True,True,False,False,True,False
16745,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,...,False,False,False,False,True,False,False,False,False,False
12432,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,...,False,False,False,False,True,False,False,False,True,False
14364,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,...,False,False,True,False,True,False,False,False,True,False
11561,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,...,False,False,False,False,False,False,False,False,False,True
22805,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,...,False,False,False,True,True,False,False,True,True,False
16728,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,...,True,False,False,False,True,True,False,False,False,True
23017,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,...,False,False,False,False,True,True,False,False,False,True
23070,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,...,False,False,False,False,True,False,False,False,True,False
12819,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,...,False,False,False,False,False,False,False,False,False,True
17445,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,...,False,False,False,False,False,False,False,False,True,False
19174,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,...,False,False,False,False,False,False,False,False,True,False
17375,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,...,False,False,False,False,True,True,False,False,False,False
7797,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,...,False,False,False,False,False,True,False,False,True,False
9915,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,...,False,False,False,False,True,False,False,False,False,True
8635,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,...,False,False,False,False,True,False,False,False,False,True
1739,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,...,False,False,False,True,False,True,False,False,True,False
15604,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,...,False,False,False,False,True,True,False,False,False,True
13476,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,...,True,False,False,False,True,True,False,False,True,False
17196,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,...,False,False,False,False,False,False,False,False,False,False

In [54]:
players_df = players_df.drop(columns = ['venue_avg_points'])
venue_data = historical_data[historical_data['venue'] == venue][['player','venue_avg_points']].drop_duplicates()
venue_data

               player  venue_avg_points
1      A Ashish Reddy         41.000000
28           A Badoni         42.000000
91           A Chopra          1.000000
96        A Choudhary         25.000000
99        A Dananjaya          0.000000
...               ...               ...
24628       YS Chahal         43.333333
24810      Yash Dayal         24.250000
24895    Yuvraj Singh         32.300000
25017          Z Khan         33.500000
25119  Zeeshan Ansari         12.000000

[477 rows x 2 columns]

In [55]:
players_df = players_df.merge(venue_data,on = ['player'],how = 'left')
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points
0,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,...,False,False,True,True,True,False,False,False,False,-6.000000
1,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,...,False,False,False,False,False,False,False,False,True,35.333333
2,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,...,False,True,False,True,True,False,False,True,False,18.000000
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,...,False,False,False,True,False,False,False,False,False,21.000000
4,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,...,False,False,False,True,False,False,False,True,False,32.111111
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,...,False,True,False,True,False,False,False,True,False,23.833333
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,...,False,False,False,False,False,False,False,False,True,58.000000
7,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,...,False,False,True,True,False,False,True,True,False,36.857143
8,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,...,False,False,False,True,True,False,False,False,True,35.666667
9,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,...,False,False,False,True,True,False,False,False,True,29.666667
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,...,False,False,False,True,False,False,False,True,False,33.947368
11,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,...,False,False,False,False,False,False,False,False,True,86.750000
12,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,...,False,False,False,False,False,False,False,True,False,39.272727
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,...,False,False,False,False,False,False,False,True,False,33.083333
14,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,...,False,False,False,True,True,False,False,False,False,9.333333
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,...,False,False,False,False,True,False,False,True,False,38.333333
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,...,False,False,False,True,False,False,False,False,True,46.466667
17,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,...,False,False,False,True,False,False,False,False,True,43.306122
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,...,False,False,True,False,True,False,False,True,False,44.071429
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,...,False,False,False,True,True,False,False,False,True,32.736842
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,...,False,False,False,True,True,False,False,True,False,26.791667
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,...,False,False,False,False,False,False,False,False,False,50.043478

In [60]:
players_df.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'last10_std_points', 'player_consistency_index', 'form_momentum',
       'bat_pos', 'boundary_percentage', 'player_role_wicketkeeper',
       'team_won_toss', 'recent_form', 'venue_form', 'team_Deccan Chargers',
       'team_Delhi Capitals', 'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler', 'venue_avg_points',
       'predicted_points'],
      dtype='object')

In [61]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'last10_std_points', 'player_consistency_index', 'form_momentum',
       'bat_pos', 'boundary_percentage', 'venue_avg_points',
       'player_role_wicketkeeper', 'team_won_toss', 'recent_form',
       'venue_form', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler'],
      dtype='object')

In [ ]:
team1_team = "team_" + team1
team1_opp = "opponent_" + team1
team2_team = "team_" + team2
team2_opp = "opponent_" + team2
venue_data = historical_data[historical_data['venue'] == venue][['player','venue_avg_points']].drop_duplicates()
venue_data

In [56]:

X_pred = players_df.drop(columns=['fantasy_points','player','venue','player_match_number','match_id','season','player_role_batsman','player_role_bowler'])

players_df['predicted_points'] = model.predict(X_pred)

In [57]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,predicted_points
0,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,...,False,True,True,True,False,False,False,False,-6.000000,-0.492052
1,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,...,False,False,False,False,False,False,False,True,35.333333,-4.797108
2,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,...,True,False,True,True,False,False,True,False,18.000000,2.672321
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,...,False,False,True,False,False,False,False,False,21.000000,20.377450
4,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,...,False,False,True,False,False,False,True,False,32.111111,-1.372118
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,...,True,False,True,False,False,False,True,False,23.833333,8.962113
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,...,False,False,False,False,False,False,False,True,58.000000,9.267481
7,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,...,False,True,True,False,False,True,True,False,36.857143,-3.300153
8,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,...,False,False,True,True,False,False,False,True,35.666667,2.254959
9,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,...,False,False,True,True,False,False,False,True,29.666667,-0.472841
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,...,False,False,True,False,False,False,True,False,33.947368,15.265597
11,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,...,False,False,False,False,False,False,False,True,86.750000,2.121328
12,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,...,False,False,False,False,False,False,True,False,39.272727,0.050483
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,...,False,False,False,False,False,False,True,False,33.083333,7.300417
14,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,...,False,False,True,True,False,False,False,False,9.333333,-1.339733
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,...,False,False,False,True,False,False,True,False,38.333333,22.639511
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,...,False,False,True,False,False,False,False,True,46.466667,13.102722
17,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,...,False,False,True,False,False,False,False,True,43.306122,-0.562207
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,...,False,True,False,True,False,False,True,False,44.071429,2.851325
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,...,False,False,True,True,False,False,False,True,32.736842,8.005026
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,...,False,False,True,True,False,False,True,False,26.791667,13.283223
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,...,False,False,False,False,False,False,False,False,50.043478,30.571514

In [58]:
top11 = players_df.sort_values(
    'predicted_points',
    ascending=False
).head(11)

In [59]:
top11

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,predicted_points
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,...,False,False,False,False,False,False,False,False,50.043478,30.571514
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,...,False,False,False,True,False,False,True,False,38.333333,22.639511
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,...,False,False,True,False,False,False,False,False,21.000000,20.377450
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,...,False,False,True,False,False,False,True,False,33.947368,15.265597
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,...,False,False,True,True,False,False,True,False,26.791667,13.283223
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,...,False,False,True,False,False,False,False,True,46.466667,13.102722
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,...,False,False,False,False,False,False,False,True,58.000000,9.267481
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,...,True,False,True,False,False,False,True,False,23.833333,8.962113
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,...,False,False,True,True,False,False,False,True,32.736842,8.005026
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,...,False,False,False,False,False,False,True,False,33.083333,7.300417
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,...,False,True,False,True,False,False,True,False,44.071429,2.851325