In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv")

In [2]:
data.columns
pd.set_option("display.max_columns",None)

In [3]:
import joblib

model = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/models/point_predicter.pkl")

In [4]:
team1 = "Chennai Super Kings"
team2 = "Mumbai Indians"

venue = "Wankhede Stadium"

squad = [
'MS Dhoni','Ravindra Jadeja','Ruturaj Gaikwad','Deepak Chahar','Moeen Ali',
'Shivam Dube','Matheesha Pathirana','Ajinkya Rahane','Daryl Mitchell',
'Mitchell Santner','Tushar Deshpande',

'Rohit Sharma','Ishan Kishan','Suryakumar Yadav','Hardik Pandya',
'Tim David','Jasprit Bumrah','Piyush Chawla','Tilak Varma',
'Gerald Coetzee','Romario Shepherd','Nehal Wadhera'
]

In [5]:
historical_data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/historical_data.csv")

In [6]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'toss_decision', 'stage', 'season', 'player_match_number',
       'last3_avg_points', 'last5_avg_points', 'last10_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'opponent_avg_points',
       'pitch_type', 'venue_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'player_role', 'last10_std_points', 'player_consistency_index',
       'form_momentum', 'bat_pos', 'boundary_percentage', 'bat_pos_per_match',
       'player_role_wicketkeeper', 'match_month', 'team_won_toss',
       'recent_form', 'venue_form'],
      dtype='object')

In [7]:
colsToDrop =  ['last5_avg_points',
              'last10_avg_points',
              'bat_pos_per_match',
              'match_month',
              'stage'
              ]
historical_data = historical_data.drop(columns = colsToDrop)

In [8]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'toss_decision', 'season', 'player_match_number', 'last3_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'opponent_avg_points',
       'pitch_type', 'venue_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'player_role', 'last10_std_points', 'player_consistency_index',
       'form_momentum', 'bat_pos', 'boundary_percentage',
       'player_role_wicketkeeper', 'team_won_toss', 'recent_form',
       'venue_form'],
      dtype='object')

In [9]:
from difflib import get_close_matches
unique_player_list_from_df = historical_data['player'].unique()
unique_players = list(unique_player_list_from_df)
print(unique_player_list_from_df)

def map_player_name(name):
    
    match = get_close_matches(name, unique_players, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None

['A Ashish Reddy' 'A Badoni' 'A Chandila' 'A Chopra' 'A Choudhary'
 'A Dananjaya' 'A Flintoff' 'A Kamboj' 'A Kumble' 'A Manohar' 'A Mhatre'
 'A Mishra' 'A Mithun' 'A Mukund' 'A Nehra' 'A Nel' 'A Nortje'
 'A Raghuvanshi' 'A Singh' 'A Symonds' 'A Tomar' 'A Uniyal' 'A Zampa'
 'AA Bilakhia' 'AA Chavan' 'AA Jhunjhunwala' 'AA Kazi' 'AA Kulkarni'
 'AA Noffke' 'AB Agarkar' 'AB Barath' 'AB Dinda' 'AB McDonald'
 'AB de Villiers' 'AC Blizzard' 'AC Gilchrist' 'AC Thomas' 'AC Voges'
 'AD Hales' 'AD Mascarenhas' 'AD Mathews' 'AD Nath' 'AD Russell'
 'AF Milne' 'AG Murtaza' 'AG Paunikar' 'AJ Finch' 'AJ Hosein' 'AJ Turner'
 'AJ Tye' 'AK Markram' 'AL Menaria' 'AM Nayar' 'AM Rahane' 'AM Salvi'
 'AN Ahmed' 'AN Ghosh' 'AP Dole' 'AP Majumdar' 'AP Tare' 'AR Bawne'
 'AR Patel' 'AS Joseph' 'AS Rajpoot' 'AS Raut' 'AS Roy' 'AS Yadav'
 'AT Carey' 'AT Rayudu' 'AU Rashid' 'AUK Pathan' 'Abdul Basith'
 'Abdul Samad' 'Abdur Razzak' 'Abhishek Sharma' 'Abishek Porel'
 'Akash Deep' 'Akash Madhwal' 'Akash Singh' 'Aman Hakim Khan'
 'Anand Rajan' 'Aniket Verma' 'Anirudh Singh' 'Ankit Sharma' 'Ankit Soni'
 'Anmolpreet Singh' 'Anuj Rawat' 'Anureet Singh' 'Arjun Tendulkar'
 'Arshad Khan' 'Arshad Khan (2)' 'Arshdeep Singh' 'Ashutosh Sharma'
 'Ashwani Kumar' 'Atharva Taide' 'Avesh Khan' 'Azhar Mahmood'
 'Azmatullah Omarzai' 'B Akhil' 'B Chipli' 'B Geeves' 'B Indrajith'
 'B Kumar' 'B Laughlin' 'B Lee' 'B Sai Sudharsan' 'B Stanlake' 'B Sumanth'
 'BA Bhatt' 'BA Stokes' 'BAW Mendis' 'BB McCullum' 'BB Samantray'
 'BB Sran' 'BCJ Cutting' 'BE Hendricks' 'BJ Haddin' 'BJ Hodge' 'BJ Rohrer'
 'BKG Mendis' 'BMAJ Mendis' 'BR Dunk' 'BR Sharath' 'BW Hilfenhaus'
 'Basil Thampi' 'Bipul Sharma' 'C Bosch' 'C Ganapathy' 'C Green' 'C Madan'
 'C Munro' 'C Nanda' 'C Sakariya' 'C de Grandhomme' 'CA Ingram' 'CA Lynn'
 'CA Pujara' 'CH Gayle' 'CH Morris' 'CJ Anderson' 'CJ Dala' 'CJ Ferguson'
 'CJ Green' 'CJ Jordan' 'CJ McKay' 'CK Kapugedera' 'CK Langeveldt'
 'CL White' 'CM Gautam' 'CR Brathwaite' 'CR Woakes' 'CRD Fernando'
 'CV Varun' 'D Brevis' 'D Ferreira' 'D Jansen' 'D Kalyankrishna'
 'D Padikkal' 'D Pretorius' 'D Salunkhe' 'D Wiese' 'D du Preez'
 'DA Miller' 'DA Warner' 'DAJ Bracewell' 'DB Das' 'DB Ravi Teja'
 'DE Bollinger' 'DG Nalkande' 'DH Yagnik' 'DJ Bravo' 'DJ Harris'
 'DJ Hooda' 'DJ Hussey' 'DJ Jacobs' 'DJ Malan' 'DJ Mitchell'
 'DJ Muthuswami' 'DJ Thornely' 'DJ Willey' 'DJG Sammy' 'DJM Short'
 'DL Chahar' 'DL Vettori' 'DM Bravo' 'DNT Zoysa' 'DP Conway' 'DP Nannes'
 'DP Vijaykumar' 'DPMD Jayawardene' 'DR Martyn' 'DR Sams' 'DR Shorey'
 'DR Smith' 'DS Kulkarni' 'DS Lehmann' 'DS Rathi' 'DT Christian'
 'DT Patil' 'DW Steyn' 'Dhruv Jurel' 'E Lewis' 'E Malinga' 'EJG Morgan'
 'ER Dwivedi' 'F Behardien' 'F du Plessis' 'FA Allen' 'FH Edwards'
 'FY Fazal' 'Fazalhaq Farooqi' 'G Coetzee' 'G Gambhir' 'GB Hogg'
 'GC Smith' 'GC Viljoen' 'GD McGrath' 'GD Phillips' 'GH Vihari'
 'GHS Garton' 'GJ Bailey' 'GJ Maxwell' 'GR Napier' 'GS Sandhu'
 'Gagandeep Singh' 'Gulbadin Naib' 'Gurkeerat Singh' 'Gurnoor Brar'
 'H Das' 'H Klaasen' 'H Sharma' 'HC Brook' 'HE van der Dussen' 'HF Gurney'
 'HH Gibbs' 'HH Pandya' 'HM Amla' 'HR Shokeen' 'HV Patel'
 'Harbhajan Singh' 'Harmeet Singh' 'Harpreet Brar' 'Harpreet Singh'
 'Harsh Dubey' 'Harshit Rana' 'I Malhotra' 'I Sharma' 'I Udana'
 'IC Pandey' 'IC Porel' 'IK Pathan' 'IR Jaggi' 'IS Sodhi' 'Imran Tahir'
 'Iqbal Abdulla' 'Ishan Kishan' 'J Arunkumar' 'J Botha' 'J Fraser-McGurk'
 'J Little' 'J Overton' 'J Suchith' 'J Syed Mohammad' 'J Theron' 'J Yadav'
 'JA Morkel' 'JA Richardson' 'JC Archer' 'JC Buttler' 'JD Ryder'
 'JD Unadkat' 'JDP Oram' 'JDS Neesham' 'JE Root' 'JE Taylor'
 'JEC Franklin' 'JG Bethell' 'JH Kallis' 'JJ Bumrah' 'JJ Roy'
 'JJ van der Wath' 'JL Denly' 'JL Pattinson' 'JM Bairstow' 'JM Kemp'
 'JM Sharma' 'JO Holder' 'JP Behrendorff' 'JP Duminy' 'JP Faulkner'
 'JP Inglis' 'JPR Scantlebury-Searles' 'JR Hazlewood' 'JR Hopes'
 'JR Philippe' 'JW Hastings' 'Jalaj S Saxena' 'Jaskaran Singh'
 'Joginder Sharma' 'K Goel' 'K Gowtham' 'K Kartikeya' 'K Khejroliya'
 'K Rabada' 'K Santokie' 'K Upadhyay' 'K Yadav' 'KA Jamieson' 'KA Maharaj'
 'KA Pollard' 'KAJ Roach' 'KB Arun Karthik' 'KC Cariappa' 'KC Sangakkara'
 'KD Karthik' 'KH Pandya' 'KJ Abbott' 'KK Ahmed' 'KK Cooper' 'KK Nair'
 'KL Nagarkoti' 'KL Rahul' 'KM Asif' 'KM Jadhav' 'KMA Paul'
 'KMDN Kulasekara' 'KP Appanna' 'KP Pietersen' 'KR Mayers' 'KR Sen'
 'KS Bharat' 'KS Rathore' 'KS Sharma' 'KS Williamson' 'KT Maphaka'
 'KV Sharma' 'KW Richardson' 'Kamran Akmal' 'Kamran Khan'
 'Karanveer Singh' 'Karim Janat' 'Kartik Tyagi' 'Kuldeep Yadav'
 'Kumar Kushagra' 'L Ablish' 'L Balaji' 'L Ngidi' 'L Ronchi' 'L Wood'
 'LA Carseldine' 'LA Pomersbach' 'LB Williams' 'LE Plunkett' 'LH Ferguson'
 'LI Meriwala' 'LJ Wright' 'LMP Simmons' 'LPC Silva' 'LR Shukla'
 'LRPL Taylor' 'LS Livingstone' 'Lalit Yadav' 'Liton Das' 'M Ashwin'
 'M Jansen' 'M Kaif' 'M Kartik' 'M Klinger' 'M Manhas' 'M Markande'
 'M Morkel' 'M Muralitharan' 'M Ntini' 'M Pathirana' 'M Prasidh Krishna'
 'M Rawat' 'M Shahrukh Khan' 'M Siddharth' 'M Theekshana' 'M Tiwari'
 'M Vijay' 'M Vohra' 'M de Lange' 'MA Agarwal' 'MA Khote' 'MA Starc'
 'MA Wood' 'MB Parmar' 'MC Henriques' 'MC Juneja' 'MD Mishra' 'MD Shanaka'
 'MDKJ Perera' 'MEK Hussey' 'MF Maharoof' 'MG Bracewell' 'MG Johnson'
 'MG Neser' 'MJ Clarke' 'MJ Guptill' 'MJ Henry' 'MJ Lumb' 'MJ McClenaghan'
 'MJ Owen' 'MJ Santner' 'MJ Suthar' 'MK Lomror' 'MK Pandey' 'MK Tiwary'
 'ML Hayden' 'MM Ali' 'MM Patel' 'MM Sharma' 'MN Samuels' 'MN van Wyk'
 'MP Breetzke' 'MP Stoinis' 'MP Yadav' 'MR Marsh' 'MS Bhandage' 'MS Bisla'
 'MS Dhoni' 'MS Gony' 'MS Wade' 'MV Boucher' 'MW Short' 'Mandeep Singh'
 'Mashrafe Mortaza' 'Mayank Dagar' 'Misbah-ul-Haq' 'Mohammad Ashraful'
 'Mohammad Asif' 'Mohammad Hafeez' 'Mohammad Nabi' 'Mohammed Shami'
 'Mohammed Siraj' 'Mohit Rathee' 'Mohsin Khan' 'Monu Kumar'
 'Mujeeb Ur Rahman' 'Mukesh Choudhary' 'Mukesh Kumar' 'Musheer Khan'
 'Mustafizur Rahman' 'N Burger' 'N Jagadeesan' 'N Pooran' 'N Rana'
 'N Saini' 'N Thushara' 'N Wadhera' 'NA Saini' 'NB Singh' 'ND Doshi'
 'NJ Maddinson' 'NJ Rimmington' 'NK Patel' 'NL McCullum' 'NLTC Perera'
 'NM Coulter-Nile' 'NS Naik' 'NT Ellis' 'NV Ojha' 'Naman Dhir'
 'Navdeep Saini' 'Naveen-ul-Haq' 'Nithish Kumar Reddy' 'Noor Ahmad'
 'O Thomas' 'OA Shah' 'OC McCoy' 'OF Smith' 'P Amarnath' 'P Awana'
 'P Chopra' 'P Dogra' 'P Dubey' 'P Kumar' 'P Negi' 'P Parameswaran'
 'P Prasanth' 'P Ray Barman' 'P Sahu' 'P Simran Singh' 'P Suyal'
 'PA Patel' 'PA Reddy' 'PBB Rajapaksa' 'PC Valthaty' 'PD Collingwood'
 'PD Salt' 'PH Solanki' 'PHKD Mendis' 'PJ Cummins' 'PJ Sangwan' 'PK Garg'
 'PM Sarvesh Kumar' 'PN Mankad' 'PP Chawla' 'PP Ojha' 'PP Shaw' 'PR Shah'
 'PSP Handscomb' 'PV Tambe' 'PVD Chameera' 'PVSN Raju' 'PWA Mulder'
 'PWH de Silva' 'Pankaj Singh' 'Parvez Rasool' 'Prince Yadav'
 'Priyansh Arya' 'Q de Kock' 'R Ashwin' 'R Bhatia' 'R Bishnoi' 'R Dhawan'
 'R Dravid' 'R Goyal' 'R McLaren' 'R Minz' 'R Ninan' 'R Parag' 'R Powell'
 'R Rampaul' 'R Ravindra' 'R Sai Kishore' 'R Sanjay Yadav' 'R Sathish'
 'R Sharma' 'R Shepherd' 'R Shukla' 'R Tewatia' 'R Vinay Kumar' 'RA Bawa'
 'RA Jadeja' 'RA Shaikh' 'RA Tripathi' 'RD Chahar' 'RD Gaikwad'
 'RD Rickelton' 'RE Levi' 'RE van der Merwe' 'RG More' 'RG Sharma'
 'RJ Gleeson' 'RJ Harris' 'RJ Peterson' 'RJ Quiney' 'RJW Topley' 'RK Bhui'
 'RK Singh' 'RM Patidar' 'RN ten Doeschate' 'RP Meredith' 'RP Singh'
 'RR Bhatkal' 'RR Bose' 'RR Pant' 'RR Powar' 'RR Raje' 'RR Rossouw'
 'RR Sarwan' 'RS Bopara' 'RS Gavaskar' 'RS Hangargekar' 'RS Sodhi'
 'RT Ponting' 'RV Gomez' 'RV Patel' 'RV Uthappa' 'RW Price'
 'Rahmanullah Gurbaz' 'Ramandeep Singh' 'Rashid Khan' 'Rasikh Salam'
 'Ravi Bishnoi' 'S Anirudha' 'S Aravind' 'S Badree' 'S Badrinath'
 'S Chanderpaul' 'S Dhawan' 'S Dube' 'S Gopal' 'S Joseph' 'S Kaul'
 'S Kaushik' 'S Ladda' 'S Lamichhane' 'S Midhun' 'S Nadeem' 'S Narwal'
 'S Rana' 'S Randiv' 'S Sandeep Warrier' 'S Sohal' 'S Sreesanth'
 'S Sriram' 'S Tyagi' 'S Vidyut' 'SA Abbott' 'SA Asnodkar' 'SA Yadav'
 'SB Bangar' 'SB Dubey' 'SB Jakati' 'SB Joshi' 'SB Styris' 'SB Wagh'
 'SC Ganguly' 'SC Kuggeleijn' 'SD Chitnis' 'SD Hope' 'SD Lad' 'SE Bond'
 'SE Marsh' 'SE Rutherford' 'SH Johnson' 'SJ Srivastava' 'SK Raina'
 'SK Rasheed' 'SK Trivedi' 'SK Warne' 'SL Malinga' 'SM Boland' 'SM Curran'
 'SM Harwood' 'SM Katich' 'SM Pollock' 'SMSM Senanayake' 'SN Khan'
 'SN Thakur' 'SO Hetmyer' 'SP Fleming' 'SP Goswami' 'SP Jackson'
 'SP Narine' 'SPD Smith' 'SR Tendulkar' 'SR Watson' 'SS Agarwal'
 'SS Cottrell' 'SS Iyer' 'SS Mundhe' 'SS Prabhudessai' 'SS Sarkar'
 'SS Shaikh' 'SS Tiwary' 'SSB Magala' 'ST Jayasuriya' 'STR Binny'
 'SV Samson' 'SW Billings' 'SW Tait' 'SZ Mulani' 'Sachin Baby'
 'Salman Butt' 'Sameer Rizvi' 'Sandeep Sharma' 'Sanvir Singh'
 'Saurav Chauhan' 'Sediqullah Atal' 'Shahbaz Ahmed' 'Shahid Afridi'
 'Shakib Al Hasan' 'Shashank Singh' 'Shivam Mavi' 'Shivam Sharma'
 'Shivam Singh' 'Shoaib Ahmed' 'Shoaib Akhtar' 'Shoaib Malik'
 'Shubman Gill' 'Sikandar Raza' 'Simarjeet Singh' 'Sohail Tanvir'
 'Sumit Kumar' 'Sunny Gupta' 'Sunny Singh' 'Suryansh Shedge'
 'Suyash Sharma' 'Swapnil Singh' 'T Banton' 'T Henderson'
 'T Kohler-Cadmore' 'T Kohli' 'T Natarajan' 'T Shamsi' 'T Stubbs'
 'T Taibu' 'T Thushara' 'TA Boult' 'TD Paine' 'TG Southee' 'TH David'
 'TK Curran' 'TL Seifert' 'TL Suman' 'TM Dilshan' 'TM Head'
 'TM Srivastava' 'TP Sudhindra' 'TR Birt' 'TS Mills' 'TU Deshpande'
 'Tanush Kotian' 'Tejas Baroka' 'Tilak Varma' 'U Kaul' 'UA Birla'
 'UBT Chand' 'UT Khawaja' 'UT Yadav' 'Umar Gul' 'Umran Malik'
 'Urvil Patel' 'V Kaverappa' 'V Kohli' 'V Nigam' 'V Pratap Singh'
 'V Puthur' 'V Sehwag' 'V Shankar' 'V Suryavanshi' 'V Viyaskanth'
 'VG Arora' 'VH Zol' 'VR Aaron' 'VR Iyer' 'VRV Singh' 'VS Malik'
 'VS Yeligati' 'VVS Laxman' 'VY Mahesh' 'Vijaykumar Vyshak' 'Virat Singh'
 'Vishnu Vinod' 'Vivrant Sharma' 'W Jaffer' "W O'Rourke" 'WA Mota'
 'WD Parnell' 'WG Jacks' 'WP Saha' 'WPUJC Vaas' 'Washington Sundar'
 'X Thalaivan Sargunam' 'XC Bartlett' 'Y Gnaneswara Rao' 'Y Nagar'
 'Y Prithvi Raj' 'Y Venugopal Rao' 'YA Abdulla' 'YBK Jaiswal' 'YK Pathan'
 'YS Chahal' 'YV Dhull' 'YV Takawale' 'Yash Dayal' 'Yash Thakur'
 'Yashpal Singh' 'Younis Khan' 'Yudhvir Singh' 'Yuvraj Singh' 'Z Khan'
 'Zeeshan Ansari']

In [10]:
mapped_players = [map_player_name(p) for p in squad]
mapped_players = [p for p in mapped_players if p is not None]
print(mapped_players)

['MS Dhoni', 'RA Jadeja', 'RD Gaikwad', 'RD Chahar', 'MM Ali', 'S Dube', 'M Pathirana', 'AM Rahane', 'DJ Mitchell', 'MJ Santner', 'TU Deshpande', 'R Sharma', 'Ishan Kishan', 'R Sanjay Yadav', 'KH Pandya', 'TH David', 'JJ Bumrah', 'PP Chawla', 'Tilak Varma', 'G Coetzee', 'R Shepherd', 'N Wadhera']

In [11]:
unique_venue_list_from_df = historical_data['venue'].unique()
unique_venues = list(unique_venue_list_from_df)
print(unique_venues)
def map_venue_name(name):
    
    match = get_close_matches(name, unique_venues, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None
print(historical_data['venue'].value_counts())

['Subrata Roy Sahara Stadium', 'Wankhede Stadium', 'Barabati Stadium', 'MA Chidambaram Stadium', 'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium', 'Arun Jaitley Stadium', 'Eden Gardens', 'Maharashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Punjab Cricket Association IS Bindra Stadium', 'Brabourne Stadium', 'Dr DY Patil Sports Academy', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'Narendra Modi Stadium', 'Himachal Pradesh Cricket Association Stadium', 'Newlands', "St George's Park", 'Kingsmead', 'New Wanderers Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Buffalo Park', 'OUTsurance Oval', 'Nehru Stadium', 'Sheikh Zayed Stadium', 'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium', 'Shaheed Veer Narayan Singh International Stadium', 'Saurashtra Cricket Association Stadium', 'Green Park', 'JSCA International Stadium Complex', 'Barsapara Cricket Stadium', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'De Beers Diamond Oval', 'Holkar Cricket Stadium']
venue
Wankhede Stadium                                                      2719
Eden Gardens                                                          2125
M Chinnaswamy Stadium                                                 2116
Arun Jaitley Stadium                                                  2099
MA Chidambaram Stadium                                                1991
Rajiv Gandhi International Stadium                                    1772
Sawai Mansingh Stadium                                                1347
Punjab Cricket Association IS Bindra Stadium                          1297
Narendra Modi Stadium                                                 1002
Dubai International Cricket Stadium                                    988
Sheikh Zayed Stadium                                                   788
Dr DY Patil Sports Academy                                             786
Maharashtra Cricket Association Stadium                                746
Sharjah Cricket Stadium                                                594
Brabourne Stadium                                                      567
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           501
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    374
Subrata Roy Sahara Stadium                                             336
Kingsmead                                                              317
Himachal Pradesh Cricket Association Stadium                           309
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     260
SuperSport Park                                                        249
Saurashtra Cricket Association Stadium                                 203
Holkar Cricket Stadium                                                 188
New Wanderers Stadium                                                  184
Newlands                                                               164
Barabati Stadium                                                       149
JSCA International Stadium Complex                                     148
St George's Park                                                       144
Shaheed Veer Narayan Singh International Stadium                       126
Barsapara Cricket Stadium                                              115
Nehru Stadium                                                          107
Green Park                                                              83
Vidarbha Cricket Association Stadium, Jamtha                            65
De Beers Diamond Oval                                                   62
Buffalo Park                                                            61
OUTsurance Oval                                                         43
Name: count, dtype: int64

In [12]:
mapped_venues = map_venue_name(venue)
mapped_venues

'Wankhede Stadium'

In [13]:
players_df = data[
    data['player'].isin(mapped_players)
].copy()
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
1557,335994,AM Rahane,-2.0,Dr DY Patil Sports Academy,2007/08,1,17.000000,93.818369,0.0,20.666667,19.333333,0.946751,1.0,-0.0,9.433392,1.070665,6.900000,1.0,0.000000,0,0,15.230000,294.446667,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False
1558,335997,AM Rahane,5.0,Eden Gardens,2007/08,2,35.672040,80.762144,0.0,36.318182,44.647059,1.001310,1.0,-0.0,0.000000,0.000000,0.000000,1.0,1.000000,0,0,35.672040,1592.651659,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1559,392203,AM Rahane,11.0,Buffalo Park,2009,3,35.672040,80.762144,0.0,36.318182,12.500000,0.810556,1.0,0.0,0.000000,0.000000,0.000000,1.0,0.400000,0,1,35.672040,445.900498,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1560,392208,AM Rahane,-2.0,New Wanderers Stadium,2009,4,4.666667,80.762144,0.0,47.583333,-2.000000,0.999131,1.0,-0.0,6.506407,0.000000,0.000000,1.0,0.000000,0,1,17.068816,-34.137632,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False
1561,392215,AM Rahane,14.0,Buffalo Park,2009,5,4.666667,80.762144,0.0,53.954545,12.500000,0.810556,1.0,0.0,6.271629,0.000000,0.000000,1.0,0.666667,0,1,17.068816,213.360199,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23066,1473493,Tilak Varma,7.0,Wankhede Stadium,2025,47,18.666667,143.084148,0.0,35.857143,33.947368,1.035196,1.0,0.0,25.954875,1.814688,-28.433333,5.0,0.000000,0,0,29.290000,994.318421,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False
23067,1473501,Tilak Varma,30.0,Wankhede Stadium,2025,48,10.666667,124.463458,0.0,48.857143,33.947368,1.035196,1.0,0.0,28.631956,1.477370,-31.633333,5.0,0.370370,0,0,19.510000,662.313158,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False
23068,1473506,Tilak Varma,1.0,Sawai Mansingh Stadium,2025,49,17.333333,108.705882,0.0,36.333333,43.500000,0.988582,1.0,0.0,28.054708,1.397270,-21.866667,5.0,0.000000,0,0,19.900000,865.650000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
23069,1473509,Tilak Varma,45.0,Maharaja Yadavindra Singh International Cricke...,2025,50,12.666667,89.000000,0.0,35.857143,51.500000,1.025162,1.0,0.0,30.214787,1.138515,-21.733333,5.0,0.720000,0,1,14.820000,763.230000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
23070,1473510,Tilak Varma,58.0,Narendra Modi Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.0,0.0,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.410000,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False

In [14]:
players_df = (
    players_df
    .sort_values('player_match_number')
    .groupby('player')
    .tail(1)
)
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
16657,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,-6.000000,1.035196,0.333333,0.666667,18.541545,1.256637,8.033333,8.0,0.000000,0,1,31.51,-189.060000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
6141,1473509,G Coetzee,2.0,Maharaja Yadavindra Singh International Cricke...,2025,14,26.333333,100.857143,0.6,23.000000,40.500000,1.025162,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
5105,1426306,DJ Mitchell,20.0,M Chinnaswamy Stadium,2024,15,52.000000,154.983925,0.0,20.000000,20.000000,1.016059,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False
16745,1473511,R Shepherd,43.0,Narendra Modi Stadium,2025,17,38.666667,81.538462,0.8,27.600000,43.000000,1.079940,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
12432,1473510,MJ Santner,6.0,Narendra Modi Stadium,2025,31,60.333333,20.000000,1.4,33.500000,9.500000,1.079940,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
14364,1473511,N Wadhera,17.0,Narendra Modi Stadium,2025,31,30.333333,128.719064,0.0,36.500000,38.250000,1.079940,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
11561,1473504,M Pathirana,41.0,Narendra Modi Stadium,2025,32,25.666667,0.000000,1.0,47.600000,48.500000,1.079940,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
22805,1473503,TH David,1.0,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025,44,21.000000,216.000000,0.0,53.000000,36.000000,1.040207,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False
16728,733975,R Sharma,-2.0,Arun Jaitley Stadium,2014,44,15.000000,0.000000,0.6,28.833333,6.500000,1.031603,-0.000000,1.000000,20.278341,1.277225,-10.900000,9.0,0.000000,0,0,17.77,115.505000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,True
23017,1473500,TU Deshpande,33.0,Arun Jaitley Stadium,2025,46,24.000000,10.000000,0.6,18.333333,20.666667,1.031603,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True
23070,1473510,Tilak Varma,58.0,Narendra Modi Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
12819,1473494,MM Ali,29.0,Eden Gardens,2025,70,33.000000,23.717949,1.0,32.800000,40.200000,1.001310,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
17445,1473459,RD Gaikwad,1.0,Maharaja Yadavindra Singh International Cricke...,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,1.025162,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
19174,1473504,S Dube,31.0,Narendra Modi Stadium,2025,76,38.666667,173.541667,0.0,31.750000,35.250000,1.079940,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
17375,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,9.333333,1.035196,0.000000,0.000000,35.377488,0.980850,-15.366667,9.0,0.000000,0,0,29.29,273.373333,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False
7797,1473505,Ishan Kishan,37.0,Arun Jaitley Stadium,2025,114,70.000000,110.343137,0.0,38.181818,19.500000,1.031603,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False
9915,1473511,KH Pandya,68.0,Narendra Modi Stadium,2025,144,17.000000,58.405797,0.6,36.736842,37.000000,1.079940,0.066667,0.933333,36.687267,0.986718,-19.200000,5.0,0.000000,0,0,26.24,970.880000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
8635,1473510,JJ Bumrah,-2.0,Narendra Modi Stadium,2025,147,57.666667,0.000000,1.8,45.666667,30.666667,1.079940,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
1739,1473505,AM Rahane,18.0,Arun Jaitley Stadium,2025,183,49.000000,139.011544,0.0,33.772727,40.100000,1.031603,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False
15604,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,32.736842,1.035196,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True
13476,1473500,MS Dhoni,18.0,Arun Jaitley Stadium,2025,241,25.000000,129.222222,0.0,34.807692,27.900000,1.031603,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False
17196,1473504,RA Jadeja,78.0,Narendra Modi Stadium,2025,247,56.000000,129.261438,0.6,50.857143,43.600000,1.079940,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
players_df['venue'] = venue
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
16657,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,-6.000000,1.035196,0.333333,0.666667,18.541545,1.256637,8.033333,8.0,0.000000,0,1,31.51,-189.060000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
6141,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,40.500000,1.025162,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
5105,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,20.000000,1.016059,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False
16745,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,43.000000,1.079940,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
12432,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,9.500000,1.079940,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
14364,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,38.250000,1.079940,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
11561,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,48.500000,1.079940,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
22805,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,36.000000,1.040207,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False
16728,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,6.500000,1.031603,-0.000000,1.000000,20.278341,1.277225,-10.900000,9.0,0.000000,0,0,17.77,115.505000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,True
23017,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,20.666667,1.031603,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True
23070,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
12819,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,40.200000,1.001310,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
17445,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,1.025162,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
19174,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,35.250000,1.079940,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
17375,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,9.333333,1.035196,0.000000,0.000000,35.377488,0.980850,-15.366667,9.0,0.000000,0,0,29.29,273.373333,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False
7797,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,19.500000,1.031603,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False
9915,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,37.000000,1.079940,0.066667,0.933333,36.687267,0.986718,-19.200000,5.0,0.000000,0,0,26.24,970.880000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
8635,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,30.666667,1.079940,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
1739,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,40.100000,1.031603,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False
15604,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,32.736842,1.035196,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True
13476,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,27.900000,1.031603,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False
17196,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,43.600000,1.079940,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
players_df = players_df.drop(columns = ['venue_avg_points'])
venue_data = data[data['venue'] == venue][['player','venue_avg_points']].drop_duplicates()
venue_data

               player  venue_avg_points
1      A Ashish Reddy         41.000000
28           A Badoni         42.000000
91           A Chopra          1.000000
96        A Choudhary         25.000000
99        A Dananjaya          0.000000
...               ...               ...
24628       YS Chahal         43.333333
24810      Yash Dayal         24.250000
24895    Yuvraj Singh         32.300000
25017          Z Khan         33.500000
25119  Zeeshan Ansari         12.000000

[477 rows x 2 columns]

In [17]:
players_df = players_df.merge(venue_data,on = ['player'],how = 'left')
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points
0,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,1.035196,0.333333,0.666667,18.541545,1.256637,8.033333,8.0,0.000000,0,1,31.51,-189.060000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,-6.000000
1,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,1.025162,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333
2,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.016059,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,1.079940,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000
4,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.079940,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.079940,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,1.079940,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000
7,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.040207,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143
8,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,1.031603,-0.000000,1.000000,20.278341,1.277225,-10.900000,9.0,0.000000,0,0,17.77,115.505000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,True,35.666667
9,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,1.031603,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.079940,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368
11,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,1.001310,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000
12,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.025162,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.079940,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333
14,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,1.035196,0.000000,0.000000,35.377488,0.980850,-15.366667,9.0,0.000000,0,0,29.29,273.373333,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,9.333333
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.031603,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,1.079940,0.066667,0.933333,36.687267,0.986718,-19.200000,5.0,0.000000,0,0,26.24,970.880000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,46.466667
17,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,1.079940,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.031603,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,1.035196,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.031603,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,1.079940,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478

In [18]:
pd.set_option("display.max_columns",None)

In [19]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points
0,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,1.035196,0.333333,0.666667,18.541545,1.256637,8.033333,8.0,0.000000,0,1,31.51,-189.060000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,-6.000000
1,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,1.025162,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333
2,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.016059,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,1.079940,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000
4,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.079940,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.079940,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,1.079940,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000
7,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.040207,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143
8,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,1.031603,-0.000000,1.000000,20.278341,1.277225,-10.900000,9.0,0.000000,0,0,17.77,115.505000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,True,35.666667
9,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,1.031603,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.079940,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368
11,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,1.001310,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000
12,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.025162,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.079940,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333
14,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,1.035196,0.000000,0.000000,35.377488,0.980850,-15.366667,9.0,0.000000,0,0,29.29,273.373333,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,9.333333
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.031603,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,1.079940,0.066667,0.933333,36.687267,0.986718,-19.200000,5.0,0.000000,0,0,26.24,970.880000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,46.466667
17,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,1.079940,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.031603,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,1.035196,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.031603,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,1.079940,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478

In [22]:
venue_run_data = historical_data[historical_data['venue'] == venue][['player','venue_run_factor']].drop_duplicates()
venue_run_data

               player  venue_run_factor
1      A Ashish Reddy          1.035196
28           A Badoni          1.035196
91           A Chopra          1.035196
96        A Choudhary          1.035196
99        A Dananjaya          1.035196
...               ...               ...
24628       YS Chahal          1.035196
24810      Yash Dayal          1.035196
24895    Yuvraj Singh          1.035196
25017          Z Khan          1.035196
25119  Zeeshan Ansari          1.035196

[477 rows x 2 columns]

In [23]:
players_df = players_df.drop(columns = ['venue_run_factor'])
players_df = players_df.merge(venue_run_data,on = ['player'],how = 'left')
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor
0,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,0.333333,0.666667,18.541545,1.256637,8.033333,8.0,0.000000,0,1,31.51,-189.060000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,-6.000000,1.035196
1,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196
2,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196
4,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196
7,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196
8,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,-0.000000,1.000000,20.278341,1.277225,-10.900000,9.0,0.000000,0,0,17.77,115.505000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,True,35.666667,1.035196
9,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196
11,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196
12,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196
14,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,0.000000,0.000000,35.377488,0.980850,-15.366667,9.0,0.000000,0,0,29.29,273.373333,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,9.333333,1.035196
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,0.066667,0.933333,36.687267,0.986718,-19.200000,5.0,0.000000,0,0,26.24,970.880000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,46.466667,1.035196
17,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196

In [24]:
players_df = players_df.drop(columns = ['venue_form'])
players_df['venue_form'] = players_df['venue_avg_points'] * players_df['recent_form']
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form
0,1304111,R Sanjay Yadav,-6.0,Wankhede Stadium,2022,1,31.333333,18.571429,1.4,-6.000000,0.333333,0.666667,18.541545,1.256637,8.033333,8.0,0.000000,0,1,31.51,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,-6.000000,1.035196,-189.060000
1,1473509,G Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667
2,1426306,DJ Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196,931.140000
3,1473511,R Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000
4,1473510,MJ Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222
5,1473511,N Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196,809.380000
6,1473504,M Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000
7,1473503,TH David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196,1076.597143
8,733975,R Sharma,-2.0,Wankhede Stadium,2014,44,15.000000,0.000000,0.6,28.833333,-0.000000,1.000000,20.278341,1.277225,-10.900000,9.0,0.000000,0,0,17.77,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,True,35.666667,1.035196,633.796667
9,1473500,TU Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667
10,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263
11,1473494,MM Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500
12,1473459,RD Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182
13,1473504,S Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167
14,1473470,RD Chahar,0.0,Wankhede Stadium,2025,80,19.333333,52.000000,1.4,0.500000,0.000000,0.000000,35.377488,0.980850,-15.366667,9.0,0.000000,0,0,29.29,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,9.333333,1.035196,273.373333
15,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667
16,1473511,KH Pandya,68.0,Wankhede Stadium,2025,144,17.000000,58.405797,0.6,36.736842,0.066667,0.933333,36.687267,0.986718,-19.200000,5.0,0.000000,0,0,26.24,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,46.466667,1.035196,1219.285333
17,1473510,JJ Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490
18,1473505,AM Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196,2118.954286
19,1426305,PP Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737
20,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083
21,1473504,RA Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348

In [25]:
players_df.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'player_role_wicketkeeper', 'team_won_toss',
       'recent_form', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler', 'venue_avg_points',
       'venue_run_factor', 'venue_form'],
      dtype='object')