In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv")

In [2]:
data.columns
pd.set_option("display.max_columns",None)

In [3]:
import joblib

model = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/models/point_predicter.pkl")

In [4]:
team1 = "Chennai Super Kings"
team2 = "Mumbai Indians"

venue = "Wankhede Stadium"
team1_squad =  [
    'MS Dhoni','Ravindra Jadeja','Ruturaj Gaikwad','Deepak Chahar','Moeen Ali',
'Shivam Dube','Matheesha Pathirana','Ajinkya Rahane','Daryl Mitchell',
'Mitchell Santner','Tushar Deshpande'
]
team2_squad = ['Rohit Sharma','Ishan Kishan','Suryakumar Yadav','Hardik Pandya',
'Tim David','Jasprit Bumrah','Piyush Chawla','Tilak Varma',
'Gerald Coetzee','Romario Shepherd','Nehal Wadhera'
]
squad = team1_squad+team2_squad

In [5]:
historical_data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/historical_data.csv")
historical_data['pitch_type'] = historical_data['pitch_type'].fillna('balanced')

In [6]:
player_mapping = {
    'A Ashish Reddy': 'Ashish Reddy',
    'A Badoni': 'Ayush Badoni',
    'A Chandila': 'Ajit Chandila',
    'A Chopra': 'Aakash Chopra',
    'A Choudhary': 'Aniket Choudhary',
    'A Dananjaya': 'Akila Dananjaya',
    'A Flintoff': 'Andrew Flintoff',
    'A Kamboj': 'Anshul Kamboj',
    'A Kumble': 'Anil Kumble',
    'A Manohar': 'Abhinav Manohar',
    'A Mhatre': 'Ayush Mhatre',
    'A Mishra': 'Amit Mishra',
    'A Mithun': 'Abhimanyu Mithun',
    'A Mukund': 'Abhinav Mukund',
    'A Nehra': 'Ashish Nehra',
    'A Nel': 'André Nel',
    'A Nortje': 'Anrich Nortje',
    'A Raghuvanshi': 'Angkrish Raghuvanshi',
    'A Singh': 'Anureet Singh',
    'A Symonds': 'Andrew Symonds',
    'A Tomar': 'Anshuman Tomar',
    'A Uniyal': 'Amit Uniyal',
    'A Zampa': 'Adam Zampa',
    'AA Bilakhia': 'Akshath Bilakhia',
    'AA Chavan': 'Ankeet Chavan',
    'AA Jhunjhunwala': 'Abhishek Jhunjhunwala',
    'AA Kazi': 'Abrar Kazi',
    'AA Kulkarni': 'Arshin Kulkarni',
    'AA Noffke': 'Ashley Noffke',
    'AB Agarkar': 'Ajit Agarkar',
    'AB Barath': 'Adrian Barath',
    'AB Dinda': 'Ashoke Dinda',
    'AB McDonald': 'Andrew McDonald',
    'AB de Villiers': 'AB de Villiers',
    'AC Blizzard': 'Aiden Blizzard',
    'AC Gilchrist': 'Adam Gilchrist',
    'AC Thomas': 'Alfonso Thomas',
    'AC Voges': 'Adam Voges',
    'AD Hales': 'Alex Hales',
    'AD Mascarenhas': 'Dimitri Mascarenhas',
    'AD Mathews': 'Angelo Mathews',
    'AD Nath': 'Akshdeep Nath',
    'AD Russell': 'Andre Russell',
    'AF Milne': 'Adam Milne',
    'AG Murtaza': 'Ali Murtaza',
    'AG Paunikar': 'Amit Paunikar',
    'AJ Finch': 'Aaron Finch',
    'AJ Hosein': 'Akeal Hosein',
    'AJ Turner': 'Ashton Turner',
    'AJ Tye': 'Andrew Tye',
    'AK Markram': 'Aiden Markram',
    'AL Menaria': 'Ashok Menaria',
    'AM Nayar': 'Abhishek Nayar',
    'AM Rahane': 'Ajinkya Rahane',
    'AM Salvi': 'Aavishkar Salvi',
    'AN Ahmed': 'Abu Nechim',
    'AN Ghosh': 'Arindam Ghosh',
    'AP Dole': 'Aditya Dole',
    'AP Majumdar': 'Anustup Majumdar',
    'AP Tare': 'Aditya Tare',
    'AR Bawne': 'Ankit Bawne',
    'AR Patel': 'Axar Patel',
    'AS Joseph': 'Alzarri Joseph',
    'AS Rajpoot': 'Ankit Rajpoot',
    'AS Raut': 'Abhishek Raut',
    'AS Roy': 'Anukul Roy',
    'AS Yadav': 'Suryakumar Yadav',
    'AT Carey': 'Alex Carey',
    'AT Rayudu': 'Ambati Rayudu',
    'AU Rashid': 'Adil Rashid',
    'AUK Pathan': 'Asad Pathan',
    'B Akhil': 'Balachandra Akhil',
    'B Chipli': 'Bharat Chipli',
    'B Geeves': 'Brett Geeves',
    'B Indrajith': 'Baba Indrajith',
    'B Kumar': 'Bhuvaneshwar Kumar',
    'B Laughlin': 'Ben Laughlin',
    'B Lee': 'Brett Lee',
    'B Sai Sudharsan': 'Sai Sudharsan',
    'B Stanlake': 'Billy Stanlake',
    'B Sumanth': 'Bodanapu Sumanth',
    'BA Bhatt': 'Bhargav Bhatt',
    'BA Stokes': 'Ben Stokes',
    'BAW Mendis': 'Ajantha Mendis',
    'BB McCullum': 'Brendon McCullum',
    'BB Samantray': 'Biplab Samantray',
    'BB Sran': 'Barinder Sran',
    'BCJ Cutting': 'Ben Cutting',
    'BE Hendricks': 'Beuran Hendricks',
    'BJ Haddin': 'Brad Haddin',
    'BJ Hodge': 'Brad Hodge',
    'BJ Rohrer': 'Ben Rohrer',
    'BKG Mendis': 'Jeevan Mendis',
    'BMAJ Mendis': 'Jeevan Mendis',
    'BR Dunk': 'Ben Dunk',
    'BR Sharath': 'Barafe Sharath',
    'BW Hilfenhaus': 'Ben Hilfenhaus',
    'C Bosch': 'Corbin Bosch',
    'C Ganapathy': 'Chandrasekar Ganapathy',
    'C Green': 'Cameron Green',
    'C Madan': 'Chandan Madan',
    'C Munro': 'Colin Munro',
    'C Nanda': 'Chetan Nanda',
    'C Sakariya': 'Chetan Sakariya',
    'C de Grandhomme': 'Colin de Grandhomme',
    'CA Ingram': 'Colin Ingram',
    'CA Lynn': 'Chris Lynn',
    'CA Pujara': 'Cheteshwar Pujara',
    'CH Gayle': 'Chris Gayle',
    'CH Morris': 'Chris Morris',
    'CJ Anderson': 'Corey Anderson',
    'CJ Dala': 'Junior Dala',
    'CJ Ferguson': 'Callum Ferguson',
    'CJ Green': 'Chris Green',
    'CJ Jordan': 'Chris Jordan',
    'CJ McKay': 'Clint McKay',
    'CK Kapugedera': 'Chamara Kapugedera',
    'CK Langeveldt': 'Charl Langeveldt',
    'CL White': 'Cameron White',
    'CM Gautam': 'C. M. Gautam',
    'CR Brathwaite': 'Carlos Brathwaite',
    'CR Woakes': 'Chris Woakes',
    'CRD Fernando': 'Dilhara Fernando',
    'CV Varun': 'Varun Chakravarthy',
    'D Brevis': 'Dewald Brevis',
    'D Ferreira': 'Donovan Ferreira',
    'D Jansen': 'Duan Jansen',
    'D Kalyankrishna': 'Doddapaneni Kalyankrishna',
    'D Padikkal': 'Devdutt Padikkal',
    'D Pretorius': 'Dwaine Pretorius',
    'D Salunkhe': 'Dinesh Salunkhe',
    'D Wiese': 'David Wiese',
    'D du Preez': 'Dillon du Preez',
    'DA Miller': 'David Miller',
    'DA Warner': 'David Warner',
    'DAJ Bracewell': 'Doug Bracewell',
    'DB Das': 'Debabrata Das',
    'DB Ravi Teja': 'Dwaraka Ravi Teja',
    'DE Bollinger': 'Doug Bollinger',
    'DG Nalkande': 'Darshan Nalkande',
    'DH Yagnik': 'Dishant Yagnik',
    'DJ Bravo': 'Dwayne Bravo',
    'DJ Harris': 'Daniel Harris',
    'DJ Hooda': 'Deepak Hooda',
    'DJ Hussey': 'David Hussey',
    'DJ Jacobs': 'Davy Jacobs',
    'DJ Malan': 'Dawid Malan',
    'DJ Mitchell': 'Daryl Mitchell',
    'DJ Muthuswami': 'Domnic Muthuswami',
    'DJ Thornely': 'Dominic Thornely',
    'DJ Willey': 'David Willey',
    'DJG Sammy': 'Darren Sammy',
    'DJM Short': "D'Arcy Short",
    'DL Chahar': 'Deepak Chahar',
    'DL Vettori': 'Daniel Vettori',
    'DM Bravo': 'Darren Bravo',
    'DNT Zoysa': 'Nuwan Zoysa',
    'DP Conway': 'Devon Conway',
    'DP Nannes': 'Dirk Nannes',
    'DP Vijaykumar': 'Doddapaneni Vijaykumar',
    'DPMD Jayawardene': 'Mahela Jayawardene',
    'DR Martyn': 'Damien Martyn',
    'DR Sams': 'Daniel Sams',
    'DR Shorey': 'Dhruv Shorey',
    'DR Smith': 'Dwayne Smith',
    'DS Kulkarni': 'Dhawal Kulkarni',
    'DS Lehmann': 'Darren Lehmann',
    'DS Rathi': 'Dhruv Rathi',
    'DT Christian': 'Dan Christian',
    'DT Patil': 'Dinesh Patil',
    'DW Steyn': 'Dale Steyn',
    'E Lewis': 'Evin Lewis',
    'E Malinga': 'Lasith Malinga',
    'EJG Morgan': 'Eoin Morgan',
    'ER Dwivedi': 'Eklavya Dwivedi',
    'F Behardien': 'Farhaan Behardien',
    'F du Plessis': 'Faf du Plessis',
    'FA Allen': 'Fabian Allen',
    'FH Edwards': 'Fidel Edwards',
    'FY Fazal': 'Faiz Fazal',
    'G Coetzee': 'Gerald Coetzee',
    'G Gambhir': 'Gautam Gambhir',
    'GB Hogg': 'Brad Hogg',
    'GC Smith': 'Graeme Smith',
    'GC Viljoen': 'Hardus Viljoen',
    'GD McGrath': 'Glenn McGrath',
    'GD Phillips': 'Glenn Phillips',
    'GH Vihari': 'Hanuma Vihari',
    'GHS Garton': 'George Garton',
    'GJ Bailey': 'George Bailey',
    'GJ Maxwell': 'Glenn Maxwell',
    'GR Napier': 'Graham Napier',
    'GS Sandhu': 'Gurinder Sandhu',
    'H Das': 'Halhadar Das',
    'H Klaasen': 'Heinrich Klaasen',
    'H Sharma': 'Himanshu Sharma',
    'HC Brook': 'Harry Brook',
    'HE van der Dussen': 'Rassie van der Dussen',
    'HF Gurney': 'Harry Gurney',
    'HH Gibbs': 'Herschelle Gibbs',
    'HH Pandya': 'Hardik Pandya',
    'HM Amla': 'Hashim Amla',
    'HR Shokeen': 'Hrithik Shokeen',
    'HV Patel': 'Harshal Patel',
    'I Malhotra': 'Ishan Malhotra',
    'I Sharma': 'Ishant Sharma',
    'I Udana': 'Isuru Udana',
    'IC Pandey': 'Ishwar Pandey',
    'IC Porel': 'Ishan Porel',
    'IK Pathan': 'Irfan Pathan',
    'IR Jaggi': 'Ishank Jaggi',
    'IS Sodhi': 'Ish Sodhi',
    'J Arunkumar': 'Jagadeesh Arunkumar',
    'J Botha': 'Johan Botha',
    'J Fraser-McGurk': 'Jake Fraser-McGurk',
    'J Little': 'Joshua Little',
    'J Overton': 'Jamie Overton',
    'J Suchith': 'Jagadeesha Suchith',
    'J Syed Mohammad': 'Jamaluddin Syed Mohammad',
    'J Theron': 'Juan Theron',
    'J Yadav': 'Jayant Yadav',
    'JA Morkel': 'Albie Morkel',
    'JA Richardson': 'Jhye Richardson',
    'JC Archer': 'Jofra Archer',
    'JC Buttler': 'Jos Buttler',
    'JD Ryder': 'Jesse Ryder',
    'JD Unadkat': 'Jaydev Unadkat',
    'JDP Oram': 'Jacob Oram',
    'JDS Neesham': 'Jimmy Neesham',
    'JE Root': 'Joe Root',
    'JE Taylor': 'Jerome Taylor',
    'JEC Franklin': 'James Franklin',
    'JG Bethell': 'Jacob Bethell',
    'JH Kallis': 'Jacques Kallis',
    'JJ Bumrah': 'Jasprit Bumrah',
    'JJ Roy': 'Jason Roy',
    'JJ van der Wath': 'Johan van der Wath',
    'JL Denly': 'Joe Denly',
    'JL Pattinson': 'James Pattinson',
    'JM Bairstow': 'Jonny Bairstow',
    'JM Kemp': 'Justin Kemp',
    'JM Sharma': 'Jitesh Sharma',
    'JO Holder': 'Jason Holder',
    'JP Behrendorff': 'Jason Behrendorff',
    'JP Duminy': 'JP Duminy',
    'JP Faulkner': 'James Faulkner',
    'JP Inglis': 'Josh Inglis',
    'JPR Scantlebury-Searles': 'Javon Searles',
    'JR Hazlewood': 'Josh Hazlewood',
    'JR Hopes': 'James Hopes',
    'JR Philippe': 'Josh Philippe',
    'JW Hastings': 'John Hastings',
    'K Goel': 'Karan Goel',
    'K Gowtham': 'Krishnappa Gowtham',
    'K Kartikeya': 'Kumar Kartikeya',
    'K Khejroliya': 'Kulwant Khejroliya',
    'K Rabada': 'Kagiso Rabada',
    'K Santokie': 'Krishmar Santokie',
    'K Upadhyay': 'Krishnakumar Upadhyay',
    'K Yadav': 'Kuldeep Yadav',
    'KA Jamieson': 'Kyle Jamieson',
    'KA Maharaj': 'Keshav Maharaj',
    'KA Pollard': 'Kieron Pollard',
    'KAJ Roach': 'Kemar Roach',
    'KB Arun Karthik': 'Arun Karthik',
    'KC Cariappa': 'K. C. Cariappa',
    'KC Sangakkara': 'Kumar Sangakkara',
    'KD Karthik': 'Dinesh Karthik',
    'KH Pandya': 'Krunal Pandya',
    'KJ Abbott': 'Kyle Abbott',
    'KK Ahmed': 'Khaleel Ahmed',
    'KK Cooper': 'Kevon Cooper',
    'KK Nair': 'Karun Nair',
    'KL Nagarkoti': 'Kamlesh Nagarkoti',
    'KL Rahul': 'KL Rahul',
    'KM Asif': 'KM Asif',
    'KM Jadhav': 'Kedar Jadhav',
    'KMA Paul': 'Keemo Paul',
    'KMDN Kulasekara': 'Nuwan Kulasekara',
    'KP Appanna': 'Kotarangada Appanna',
    'KP Pietersen': 'Kevin Pietersen',
    'KR Mayers': 'Kyle Mayers',
    'KR Sen': 'Kuldeep Sen',
    'KS Bharat': 'Srikar Bharat',
    'KS Rathore': 'Kunal Singh Rathore',
    'KS Sharma': 'Karn Sharma',
    'KS Williamson': 'Kane Williamson',
    'KT Maphaka': 'Kwena Maphaka',
    'KV Sharma': 'Karn Sharma',
    'KW Richardson': 'Kane Richardson',
    'L Ablish': 'Love Ablish',
    'L Balaji': 'Lakshmipathy Balaji',
    'L Ngidi': 'Lungi Ngidi',
    'L Ronchi': 'Luke Ronchi',
    'L Wood': 'Luke Wood',
    'LA Carseldine': 'Lee Carseldine',
    'LA Pomersbach': 'Luke Pomersbach',
    'LB Williams': 'Lizaad Williams',
    'LE Plunkett': 'Liam Plunkett',
    'LH Ferguson': 'Lockie Ferguson',
    'LI Meriwala': 'Lukman Meriwala',
    'LJ Wright': 'Luke Wright',
    'LMP Simmons': 'Lendl Simmons',
    'LPC Silva': 'Chamara Silva',
    'LR Shukla': 'Laxmi Ratan Shukla',
    'LRPL Taylor': 'Ross Taylor',
    'LS Livingstone': 'Liam Livingstone',
    'M Ashwin': 'Murugan Ashwin',
    'M Jansen': 'Marco Jansen',
    'M Kaif': 'Mohammad Kaif',
    'M Kartik': 'Murali Kartik',
    'M Klinger': 'Michael Klinger',
    'M Manhas': 'Mithun Manhas',
    'M Markande': 'Mayank Markande',
    'M Morkel': 'Morne Morkel',
    'M Muralitharan': 'Muttiah Muralitharan',
    'M Ntini': 'Makhaya Ntini',
    'M Pathirana': 'Matheesha Pathirana',
    'M Prasidh Krishna': 'Prasidh Krishna',
    'M Rawat': 'Mahesh Rawat',
    'M Shahrukh Khan': 'Shahrukh Khan',
    'M Siddharth': 'Manimaran Siddharth',
    'M Theekshana': 'Maheesh Theekshana',
    'M Tiwari': 'Manoj Tiwary',
    'M Vijay': 'Murali Vijay',
    'M Vohra': 'Manan Vohra',
    'M de Lange': 'Marchant de Lange',
    'MA Agarwal': 'Mayank Agarwal',
    'MA Khote': 'Musavir Khote',
    'MA Starc': 'Mitchell Starc',
    'MA Wood': 'Mark Wood',
    'MB Parmar': 'Mohnish Parmar',
    'MC Henriques': 'Moises Henriques',
    'MC Juneja': 'Manpreet Juneja',
    'MD Mishra': 'Mohnish Mishra',
    'MD Shanaka': 'Dasun Shanaka',
    'MDKJ Perera': 'Kusal Perera',
    'MEK Hussey': 'Michael Hussey',
    'MF Maharoof': 'Farveez Maharoof',
    'MG Bracewell': 'Michael Bracewell',
    'MG Johnson': 'Mitchell Johnson',
    'MG Neser': 'Michael Neser',
    'MJ Clarke': 'Michael Clarke',
    'MJ Guptill': 'Martin Guptill',
    'MJ Henry': 'Matt Henry',
    'MJ Lumb': 'Michael Lumb',
    'MJ McClenaghan': 'Mitchell McClenaghan',
    'MJ Owen': 'Mitchell Owen',
    'MJ Santner': 'Mitchell Santner',
    'MJ Suthar': 'Manav Suthar',
    'MK Lomror': 'Mahipal Lomror',
    'MK Pandey': 'Manish Pandey',
    'MK Tiwary': 'Manoj Tiwary',
    'ML Hayden': 'Matthew Hayden',
    'MM Ali': 'Moeen Ali',
    'MM Patel': 'Munaf Patel',
    'MM Sharma': 'Mohit Sharma',
    'MN Samuels': 'Marlon Samuels',
    'MN van Wyk': 'Morne van Wyk',
    'MP Breetzke': 'Matthew Breetzke',
    'MP Stoinis': 'Marcus Stoinis',
    'MP Yadav': 'Mayank Yadav',
    'MR Marsh': 'Mitchell Marsh',
    'MS Bhandage': 'Manoj Bhandage',
    'MS Bisla': 'Manvinder Bisla',
    'MS Dhoni': 'MS Dhoni',
    'MS Gony': 'Manpreet Gony',
    'MS Wade': 'Matthew Wade',
    'MV Boucher': 'Mark Boucher',
    'MW Short': 'Matthew Short',
    'N Burger': 'Nandre Burger',
    'N Jagadeesan': 'Narayan Jagadeesan',
    'N Pooran': 'Nicholas Pooran',
    'N Rana': 'Nitish Rana',
    'N Saini': 'Navdeep Saini',
    'N Thushara': 'Nuwan Thushara',
    'N Wadhera': 'Nehal Wadhera',
    'NA Saini': 'Navdeep Saini',
    'NB Singh': 'Nikhil Singh',
    'ND Doshi': 'Nayan Doshi',
    'NJ Maddinson': 'Nic Maddinson',
    'NJ Rimmington': 'Nathan Rimmington',
    'NK Patel': 'Niraj Patel',
    'NL McCullum': 'Nathan McCullum',
    'NLTC Perera': 'Thisara Perera',
    'NM Coulter-Nile': 'Nathan Coulter-Nile',
    'NS Naik': 'Nikhil Naik',
    'NT Ellis': 'Nathan Ellis',
    'NV Ojha': 'Naman Ojha',
    'O Thomas': 'Oshane Thomas',
    'OA Shah': 'Owais Shah',
    'OC McCoy': 'Obed McCoy',
    'OF Smith': 'Odean Smith',
    'P Amarnath': 'Palani Amarnath',
    'P Awana': 'Parvinder Awana',
    'P Chopra': 'Prashant Chopra',
    'P Dogra': 'Paras Dogra',
    'P Dubey': 'Praveen Dubey',
    'P Kumar': 'Praveen Kumar',
    'P Negi': 'Pawan Negi',
    'P Parameswaran': 'Prasanth Parameswaran',
    'P Prasanth': 'Padmanabhan Prasanth',
    'P Ray Barman': 'Prayas Ray Barman',
    'P Sahu': 'Pardeep Sahu',
    'P Simran Singh': 'Prabhsimran Singh',
    'P Suyal': 'Pawan Suyal',
    'PA Patel': 'Parthiv Patel',
    'PA Reddy': 'Akshath Reddy',
    'PBB Rajapaksa': 'Bhanuka Rajapaksa',
    'PC Valthaty': 'Paul Valthaty',
    'PD Collingwood': 'Paul Collingwood',
    'PD Salt': 'Phil Salt',
    'PH Solanki': 'Prashant Solanki',
    'PHKD Mendis': 'Kamindu Mendis',
    'PJ Cummins': 'Pat Cummins',
    'PJ Sangwan': 'Pradeep Sangwan',
    'PK Garg': 'Priyam Garg',
    'PM Sarvesh Kumar': 'Sarvesh Kumar',
    'PN Mankad': 'Prerak Mankad',
    'PP Chawla': 'Piyush Chawla',
    'PP Ojha': 'Pragyan Ojha',
    'PP Shaw': 'Prithvi Shaw',
    'PR Shah': 'Pinal Shah',
    'PSP Handscomb': 'Peter Handscomb',
    'PV Tambe': 'Pravin Tambe',
    'PVD Chameera': 'Dushmantha Chameera',
    'PVSN Raju': 'Venugopal Rao',
    'PWA Mulder': 'Wiaan Mulder',
    'PWH de Silva': 'Wanindu Hasaranga',
    'Q de Kock': 'Quinton de Kock',
    'R Ashwin': 'Ravichandran Ashwin',
    'R Bhatia': 'Rajat Bhatia',
    'R Bishnoi': 'Ravi Bishnoi',
    'R Dhawan': 'Rishi Dhawan',
    'R Dravid': 'Rahul Dravid',
    'R Goyal': 'Ravi Goyal',
    'R McLaren': 'Ryan McLaren',
    'R Minz': 'Robin Minz',
    'R Ninan': 'Ryan Ninan',
    'R Parag': 'Riyan Parag',
    'R Powell': 'Rovman Powell',
    'R Rampaul': 'Ravi Rampaul',
    'R Ravindra': 'Rachin Ravindra',
    'R Sai Kishore': 'Ravisrinivasan Sai Kishore',
    'R Sanjay Yadav': 'Sanjay Yadav',
    'R Sathish': 'Rajagopal Sathish',
    'R Sharma': 'Rahul Sharma',
    'R Shepherd': 'Romario Shepherd',
    'R Shukla': 'Rahul Shukla',
    'R Tewatia': 'Rahul Tewatia',
    'R Vinay Kumar': 'Vinay Kumar',
    'RA Bawa': 'Raj Bawa',
    'RA Jadeja': 'Ravindra Jadeja',
    'RA Shaikh': 'Rahil Shaikh',
    'RA Tripathi': 'Rahul Tripathi',
    'RD Chahar': 'Rahul Chahar',
    'RD Gaikwad': 'Ruturaj Gaikwad',
    'RD Rickelton': 'Ryan Rickelton',
    'RE Levi': 'Richard Levi',
    'RE van der Merwe': 'Roelof van der Merwe',
    'RG More': 'Ronit More',
    'RG Sharma': 'Rohit Sharma',
    'RJ Gleeson': 'Richard Gleeson',
    'RJ Harris': 'Ryan Harris',
    'RJ Peterson': 'Robin Peterson',
    'RJ Quiney': 'Rob Quiney',
    'RJW Topley': 'Reece Topley',
    'RK Bhui': 'Ricky Bhui',
    'RK Singh': 'Rinku Singh',
    'RM Patidar': 'Rajat Patidar',
    'RN ten Doeschate': 'Ryan ten Doeschate',
    'RP Meredith': 'Riley Meredith',
    'RP Singh': 'R. P. Singh',
    'RR Bhatkal': 'Raju Bhatkal',
    'RR Bose': 'Ranadeb Bose',
    'RR Pant': 'Rishabh Pant',
    'RR Powar': 'Ramesh Powar',
    'RR Raje': 'Rohan Raje',
    'RR Rossouw': 'Rilee Rossouw',
    'RR Sarwan': 'Ramnaresh Sarwan',
    'RS Bopara': 'Ravi Bopara',
    'RS Gavaskar': 'Rohan Gavaskar',
    'RS Hangargekar': 'Rajvardhan Hangargekar',
    'RS Sodhi': 'Reetinder Sodhi',
    'RT Ponting': 'Ricky Ponting',
    'RV Gomez': 'Raiphi Gomez',
    'RV Patel': 'Ripal Patel',
    'RV Uthappa': 'Robin Uthappa',
    'RW Price': 'Ray Price',
    'S Anirudha': 'Anirudha Srikkanth',
    'S Aravind': 'Sreenath Aravind',
    'S Badree': 'Samuel Badree',
    'S Badrinath': 'Subramaniam Badrinath',
    'S Chanderpaul': 'Shivnarine Chanderpaul',
    'S Dhawan': 'Shikhar Dhawan',
    'S Dube': 'Shivam Dube',
    'S Gopal': 'Shreyas Gopal',
    'S Joseph': 'Shamar Joseph',
    'S Kaul': 'Siddharth Kaul',
    'S Kaushik': 'Shivil Kaushik',
    'S Ladda': 'Sarabjit Ladda',
    'S Lamichhane': 'Sandeep Lamichhane',
    'S Midhun': 'Sudhesan Midhun',
    'S Nadeem': 'Shahbaz Nadeem',
    'S Narwal': 'Sumit Narwal',
    'S Rana': 'Sachin Rana',
    'S Randiv': 'Suraj Randiv',
    'S Sandeep Warrier': 'Sandeep Warrier',
    'S Sohal': 'Sunny Sohal',
    'S Sreesanth': 'Sreesanth',
    'S Sriram': 'Sridharan Sriram',
    'S Tyagi': 'Sudeep Tyagi',
    'S Vidyut': 'Vidyut Sivaramakrishnan',
    'SA Abbott': 'Sean Abbott',
    'SA Asnodkar': 'Swapnil Asnodkar',
    'SA Yadav': 'Suryakumar Yadav',
    'SB Bangar': 'Sanjay Bangar',
    'SB Dubey': 'Shivam Dubey',
    'SB Jakati': 'Shadab Jakati',
    'SB Joshi': 'Sunil Joshi',
    'SB Styris': 'Scott Styris',
    'SB Wagh': 'Shrikant Wagh',
    'SC Ganguly': 'Sourav Ganguly',
    'SC Kuggeleijn': 'Scott Kuggeleijn',
    'SD Chitnis': 'Siddharth Chitnis',
    'SD Hope': 'Shai Hope',
    'SD Lad': 'Siddhesh Lad',
    'SE Bond': 'Shane Bond',
    'SE Marsh': 'Shaun Marsh',
    'SE Rutherford': 'Sherfane Rutherford',
    'SH Johnson': 'Spencer Johnson',
    'SJ Srivastava': 'Shalabh Srivastava',
    'SK Raina': 'Suresh Raina',
    'SK Rasheed': 'Shaik Rasheed',
    'SK Trivedi': 'Siddharth Trivedi',
    'SK Warne': 'Shane Warne',
    'SL Malinga': 'Lasith Malinga',
    'SM Boland': 'Scott Boland',
    'SM Curran': 'Sam Curran',
    'SM Harwood': 'Shane Harwood',
    'SM Katich': 'Simon Katich',
    'SM Pollock': 'Shaun Pollock',
    'SMSM Senanayake': 'Sachithra Senanayake',
    'SN Khan': 'Sarfaraz Khan',
    'SN Thakur': 'Shardul Thakur',
    'SO Hetmyer': 'Shimron Hetmyer',
    'SP Fleming': 'Stephen Fleming',
    'SP Goswami': 'Shreevats Goswami',
    'SP Jackson': 'Sheldon Jackson',
    'SP Narine': 'Sunil Narine',
    'SPD Smith': 'Steve Smith',
    'SR Tendulkar': 'Sachin Tendulkar',
    'SR Watson': 'Shane Watson',
    'SS Agarwal': 'Shubham Agarwal',
    'SS Cottrell': 'Sheldon Cottrell',
    'SS Iyer': 'Shreyas Iyer',
    'SS Mundhe': 'Shrikant Mundhe',
    'SS Prabhudessai': 'Suyash Prabhudessai',
    'SS Sarkar': 'Soumya Sarkar',
    'SS Shaikh': 'Sufiyan Shaikh',
    'SS Tiwary': 'Saurabh Tiwary',
    'SSB Magala': 'Sisanda Magala',
    'ST Jayasuriya': 'Sanath Jayasuriya',
    'STR Binny': 'Stuart Binny',
    'SV Samson': 'Sanju Samson',
    'SW Billings': 'Sam Billings',
    'SW Tait': 'Shaun Tait',
    'SZ Mulani': 'Shams Mulani',
    'T Banton': 'Tom Banton',
    'T Henderson': 'Tyron Henderson',
    'T Kohler-Cadmore': 'Tom Kohler-Cadmore',
    'T Kohli': 'Taruwar Kohli',
    'T Natarajan': 'T. Natarajan',
    'T Shamsi': 'Tabraiz Shamsi',
    'T Stubbs': 'Tristan Stubbs',
    'T Taibu': 'Tatenda Taibu',
    'T Thushara': 'Thilan Thushara',
    'TA Boult': 'Trent Boult',
    'TD Paine': 'Tim Paine',
    'TG Southee': 'Tim Southee',
    'TH David': 'Tim David',
    'TK Curran': 'Tom Curran',
    'TL Seifert': 'Tim Seifert',
    'TL Suman': 'Tirumalasetti Suman',
    'TM Dilshan': 'Tillakaratne Dilshan',
    'TM Head': 'Travis Head',
    'TM Srivastava': 'Tanmay Srivastava',
    'TP Sudhindra': 'T. P. Sudhindra',
    'TR Birt': 'Travis Birt',
    'TS Mills': 'Tymal Mills',
    'TU Deshpande': 'Tushar Deshpande',
    'U Kaul': 'Uday Kaul',
    'UA Birla': 'Udit Birla',
    'UBT Chand': 'Unmukt Chand',
    'UT Khawaja': 'Usman Khawaja',
    'UT Yadav': 'Umesh Yadav',
    'V Kaverappa': 'Vidwath Kaverappa',
    'V Kohli': 'Virat Kohli',
    'V Nigam': 'Vikas Nigam',
    'V Pratap Singh': 'Vishwa Pratap Singh',
    'V Puthur': 'Vyshak Vijaykumar',
    'V Sehwag': 'Virender Sehwag',
    'V Shankar': 'Vijay Shankar',
    'V Suryavanshi': 'Vaibhav Suryavanshi',
    'V Viyaskanth': 'Vijayakanth Viyaskanth',
    'VG Arora': 'Vaibhav Arora',
    'VH Zol': 'Vijay Zol',
    'VR Aaron': 'Varun Aaron',
    'VR Iyer': 'Venkatesh Iyer',
    'VRV Singh': 'V. R. V. Singh',
    'VS Malik': 'Vikramjeet Malik',
    'VS Yeligati': 'Vinayak Yeligati',
    'VVS Laxman': 'V. V. S. Laxman',
    'VY Mahesh': 'V. Y. Mahesh',
    'W Jaffer': 'Wasim Jaffer',
    "W O'Rourke": "William O'Rourke",
    'WA Mota': 'Wilkin Mota',
    'WD Parnell': 'Wayne Parnell',
    'WG Jacks': 'Will Jacks',
    'WP Saha': 'Wriddhiman Saha',
    'WPUJC Vaas': 'Chaminda Vaas',
    'X Thalaivan Sargunam': 'Xavier Thalaivan Sargunam',
    'XC Bartlett': 'Xavier Bartlett',
    'Y Gnaneswara Rao': 'Yalaka Gnaneswara Rao',
    'Y Nagar': 'Yogesh Nagar',
    'Y Prithvi Raj': 'Yarra Prithvi Raj',
    'Y Venugopal Rao': 'Yalaka Venugopal Rao',
    'YA Abdulla': 'Yusuf Abdulla',
    'YBK Jaiswal': 'Yashasvi Jaiswal',
    'YK Pathan': 'Yusuf Pathan',
    'YS Chahal': 'Yuzvendra Chahal',
    'YV Dhull': 'Yash Dhull',
    'YV Takawale': 'Yogesh Takawale',
    'Z Khan': 'Zaheer Khan'
}

In [7]:
historical_data['player'] = historical_data['player'].replace(player_mapping)
data['player'] = data['player'].replace(player_mapping)

In [8]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'toss_decision', 'stage', 'season', 'player_match_number',
       'last3_avg_points', 'last5_avg_points', 'last10_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'opponent_avg_points',
       'pitch_type', 'venue_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'player_role', 'last10_std_points', 'player_consistency_index',
       'form_momentum', 'bat_pos', 'boundary_percentage', 'bat_pos_per_match',
       'player_role_wicketkeeper', 'match_month', 'team_won_toss',
       'recent_form', 'venue_form'],
      dtype='object')

In [9]:
historical_data

,match_id,player,fantasy_points,team,opponent,venue,toss_decision,stage,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper,match_month,team_won_toss,recent_form,venue_form
0,548341,Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,bat,Unknown,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0,4,1,35.672040,2068.978308
1,548346,Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,field,Unknown,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,0,4,0,35.672040,1462.553632
2,548348,Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,bat,Unknown,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0,5,1,35.672040,820.456915
3,548352,Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,bat,Unknown,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,0,5,0,38.668816,1740.096716
4,548356,Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,field,Unknown,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,0,5,0,32.668816,1037.234905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,field,Unknown,2025,6,3.333333,25.60000,35.67204,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,0,4,0,13.247204,89.418627
25121,1473480,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,field,Unknown,2025,7,11.666667,13.60000,35.67204,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,0,4,1,14.647204,0.000000
25122,1473488,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,field,Unknown,2025,8,12.333333,7.00000,35.67204,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,0,5,1,13.067204,300.545692
25123,1473492,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,field,Unknown,2025,9,16.000000,11.60000,35.67204,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,0,5,1,16.647204,112.368627
25124,1473499,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,field,Unknown,2025,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,0,5,1,12.807204,-25.614408

In [10]:
colsToDrop =  ['last5_avg_points',
              'last10_avg_points',
              'bat_pos_per_match',
              'match_month',
              'stage'
              ]
historical_data = historical_data.drop(columns = colsToDrop)

In [11]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'toss_decision', 'season', 'player_match_number', 'last3_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'opponent_avg_points',
       'pitch_type', 'venue_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'player_role', 'last10_std_points', 'player_consistency_index',
       'form_momentum', 'bat_pos', 'boundary_percentage',
       'player_role_wicketkeeper', 'team_won_toss', 'recent_form',
       'venue_form'],
      dtype='object')

In [12]:

from difflib import get_close_matches
unique_player_list_from_df = historical_data['player'].unique()
unique_players = list(unique_player_list_from_df)
print(unique_player_list_from_df)

def map_player_name(name):
    
    match = get_close_matches(name, unique_players, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None

['Ashish Reddy' 'Ayush Badoni' 'Ajit Chandila' 'Aakash Chopra'
 'Aniket Choudhary' 'Akila Dananjaya' 'Andrew Flintoff' 'Anshul Kamboj'
 'Anil Kumble' 'Abhinav Manohar' 'Ayush Mhatre' 'Amit Mishra'
 'Abhimanyu Mithun' 'Abhinav Mukund' 'Ashish Nehra' 'André Nel'
 'Anrich Nortje' 'Angkrish Raghuvanshi' 'Anureet Singh' 'Andrew Symonds'
 'Anshuman Tomar' 'Amit Uniyal' 'Adam Zampa' 'Akshath Bilakhia'
 'Ankeet Chavan' 'Abhishek Jhunjhunwala' 'Abrar Kazi' 'Arshin Kulkarni'
 'Ashley Noffke' 'Ajit Agarkar' 'Adrian Barath' 'Ashoke Dinda'
 'Andrew McDonald' 'AB de Villiers' 'Aiden Blizzard' 'Adam Gilchrist'
 'Alfonso Thomas' 'Adam Voges' 'Alex Hales' 'Dimitri Mascarenhas'
 'Angelo Mathews' 'Akshdeep Nath' 'Andre Russell' 'Adam Milne'
 'Ali Murtaza' 'Amit Paunikar' 'Aaron Finch' 'Akeal Hosein'
 'Ashton Turner' 'Andrew Tye' 'Aiden Markram' 'Ashok Menaria'
 'Abhishek Nayar' 'Ajinkya Rahane' 'Aavishkar Salvi' 'Abu Nechim'
 'Arindam Ghosh' 'Aditya Dole' 'Anustup Majumdar' 'Aditya Tare'
 'Ankit Bawne' 'Axar Patel' 'Alzarri Joseph' 'Ankit Rajpoot'
 'Abhishek Raut' 'Anukul Roy' 'Suryakumar Yadav' 'Alex Carey'
 'Ambati Rayudu' 'Adil Rashid' 'Asad Pathan' 'Abdul Basith' 'Abdul Samad'
 'Abdur Razzak' 'Abhishek Sharma' 'Abishek Porel' 'Akash Deep'
 'Akash Madhwal' 'Akash Singh' 'Aman Hakim Khan' 'Anand Rajan'
 'Aniket Verma' 'Anirudh Singh' 'Ankit Sharma' 'Ankit Soni'
 'Anmolpreet Singh' 'Anuj Rawat' 'Arjun Tendulkar' 'Arshad Khan'
 'Arshad Khan (2)' 'Arshdeep Singh' 'Ashutosh Sharma' 'Ashwani Kumar'
 'Atharva Taide' 'Avesh Khan' 'Azhar Mahmood' 'Azmatullah Omarzai'
 'Balachandra Akhil' 'Bharat Chipli' 'Brett Geeves' 'Baba Indrajith'
 'Bhuvaneshwar Kumar' 'Ben Laughlin' 'Brett Lee' 'Sai Sudharsan'
 'Billy Stanlake' 'Bodanapu Sumanth' 'Bhargav Bhatt' 'Ben Stokes'
 'Ajantha Mendis' 'Brendon McCullum' 'Biplab Samantray' 'Barinder Sran'
 'Ben Cutting' 'Beuran Hendricks' 'Brad Haddin' 'Brad Hodge' 'Ben Rohrer'
 'Jeevan Mendis' 'Ben Dunk' 'Barafe Sharath' 'Ben Hilfenhaus'
 'Basil Thampi' 'Bipul Sharma' 'Corbin Bosch' 'Chandrasekar Ganapathy'
 'Cameron Green' 'Chandan Madan' 'Colin Munro' 'Chetan Nanda'
 'Chetan Sakariya' 'Colin de Grandhomme' 'Colin Ingram' 'Chris Lynn'
 'Cheteshwar Pujara' 'Chris Gayle' 'Chris Morris' 'Corey Anderson'
 'Junior Dala' 'Callum Ferguson' 'Chris Green' 'Chris Jordan'
 'Clint McKay' 'Chamara Kapugedera' 'Charl Langeveldt' 'Cameron White'
 'C. M. Gautam' 'Carlos Brathwaite' 'Chris Woakes' 'Dilhara Fernando'
 'Varun Chakravarthy' 'Dewald Brevis' 'Donovan Ferreira' 'Duan Jansen'
 'Doddapaneni Kalyankrishna' 'Devdutt Padikkal' 'Dwaine Pretorius'
 'Dinesh Salunkhe' 'David Wiese' 'Dillon du Preez' 'David Miller'
 'David Warner' 'Doug Bracewell' 'Debabrata Das' 'Dwaraka Ravi Teja'
 'Doug Bollinger' 'Darshan Nalkande' 'Dishant Yagnik' 'Dwayne Bravo'
 'Daniel Harris' 'Deepak Hooda' 'David Hussey' 'Davy Jacobs' 'Dawid Malan'
 'Daryl Mitchell' 'Domnic Muthuswami' 'Dominic Thornely' 'David Willey'
 'Darren Sammy' "D'Arcy Short" 'Deepak Chahar' 'Daniel Vettori'
 'Darren Bravo' 'Nuwan Zoysa' 'Devon Conway' 'Dirk Nannes'
 'Doddapaneni Vijaykumar' 'Mahela Jayawardene' 'Damien Martyn'
 'Daniel Sams' 'Dhruv Shorey' 'Dwayne Smith' 'Dhawal Kulkarni'
 'Darren Lehmann' 'Dhruv Rathi' 'Dan Christian' 'Dinesh Patil'
 'Dale Steyn' 'Dhruv Jurel' 'Evin Lewis' 'Lasith Malinga' 'Eoin Morgan'
 'Eklavya Dwivedi' 'Farhaan Behardien' 'Faf du Plessis' 'Fabian Allen'
 'Fidel Edwards' 'Faiz Fazal' 'Fazalhaq Farooqi' 'Gerald Coetzee'
 'Gautam Gambhir' 'Brad Hogg' 'Graeme Smith' 'Hardus Viljoen'
 'Glenn McGrath' 'Glenn Phillips' 'Hanuma Vihari' 'George Garton'
 'George Bailey' 'Glenn Maxwell' 'Graham Napier' 'Gurinder Sandhu'
 'Gagandeep Singh' 'Gulbadin Naib' 'Gurkeerat Singh' 'Gurnoor Brar'
 'Halhadar Das' 'Heinrich Klaasen' 'Himanshu Sharma' 'Harry Brook'
 'Rassie van der Dussen' 'Harry Gurney' 'Herschelle Gibbs' 'Hardik Pandya'
 'Hashim Amla' 'Hrithik Shokeen' 'Harshal Patel' 'Harbhajan Singh'
 'Harmeet Singh' 'Harpreet Brar' 'Harpreet Singh' 'Harsh Dubey'
 'Harshit Rana' 'Ishan Malhotra' 'Ishant Sharma' 'Isuru Udana'
 'Ishwar Pandey' 'Ishan Porel' 'Irfan Pathan' 'Ishank Jaggi' 'Ish Sodhi'
 'Imran Tahir' 'Iqbal Abdulla' 'Ishan Kishan' 'Jagadeesh Arunkumar'
 'Johan Botha' 'Jake Fraser-McGurk' 'Joshua Little' 'Jamie Overton'
 'Jagadeesha Suchith' 'Jamaluddin Syed Mohammad' 'Juan Theron'
 'Jayant Yadav' 'Albie Morkel' 'Jhye Richardson' 'Jofra Archer'
 'Jos Buttler' 'Jesse Ryder' 'Jaydev Unadkat' 'Jacob Oram' 'Jimmy Neesham'
 'Joe Root' 'Jerome Taylor' 'James Franklin' 'Jacob Bethell'
 'Jacques Kallis' 'Jasprit Bumrah' 'Jason Roy' 'Johan van der Wath'
 'Joe Denly' 'James Pattinson' 'Jonny Bairstow' 'Justin Kemp'
 'Jitesh Sharma' 'Jason Holder' 'Jason Behrendorff' 'JP Duminy'
 'James Faulkner' 'Josh Inglis' 'Javon Searles' 'Josh Hazlewood'
 'James Hopes' 'Josh Philippe' 'John Hastings' 'Jalaj S Saxena'
 'Jaskaran Singh' 'Joginder Sharma' 'Karan Goel' 'Krishnappa Gowtham'
 'Kumar Kartikeya' 'Kulwant Khejroliya' 'Kagiso Rabada'
 'Krishmar Santokie' 'Krishnakumar Upadhyay' 'Kuldeep Yadav'
 'Kyle Jamieson' 'Keshav Maharaj' 'Kieron Pollard' 'Kemar Roach'
 'Arun Karthik' 'K. C. Cariappa' 'Kumar Sangakkara' 'Dinesh Karthik'
 'Krunal Pandya' 'Kyle Abbott' 'Khaleel Ahmed' 'Kevon Cooper' 'Karun Nair'
 'Kamlesh Nagarkoti' 'KL Rahul' 'KM Asif' 'Kedar Jadhav' 'Keemo Paul'
 'Nuwan Kulasekara' 'Kotarangada Appanna' 'Kevin Pietersen' 'Kyle Mayers'
 'Kuldeep Sen' 'Srikar Bharat' 'Kunal Singh Rathore' 'Karn Sharma'
 'Kane Williamson' 'Kwena Maphaka' 'Kane Richardson' 'Kamran Akmal'
 'Kamran Khan' 'Karanveer Singh' 'Karim Janat' 'Kartik Tyagi'
 'Kumar Kushagra' 'Love Ablish' 'Lakshmipathy Balaji' 'Lungi Ngidi'
 'Luke Ronchi' 'Luke Wood' 'Lee Carseldine' 'Luke Pomersbach'
 'Lizaad Williams' 'Liam Plunkett' 'Lockie Ferguson' 'Lukman Meriwala'
 'Luke Wright' 'Lendl Simmons' 'Chamara Silva' 'Laxmi Ratan Shukla'
 'Ross Taylor' 'Liam Livingstone' 'Lalit Yadav' 'Liton Das'
 'Murugan Ashwin' 'Marco Jansen' 'Mohammad Kaif' 'Murali Kartik'
 'Michael Klinger' 'Mithun Manhas' 'Mayank Markande' 'Morne Morkel'
 'Muttiah Muralitharan' 'Makhaya Ntini' 'Matheesha Pathirana'
 'Prasidh Krishna' 'Mahesh Rawat' 'Shahrukh Khan' 'Manimaran Siddharth'
 'Maheesh Theekshana' 'Manoj Tiwary' 'Murali Vijay' 'Manan Vohra'
 'Marchant de Lange' 'Mayank Agarwal' 'Musavir Khote' 'Mitchell Starc'
 'Mark Wood' 'Mohnish Parmar' 'Moises Henriques' 'Manpreet Juneja'
 'Mohnish Mishra' 'Dasun Shanaka' 'Kusal Perera' 'Michael Hussey'
 'Farveez Maharoof' 'Michael Bracewell' 'Mitchell Johnson' 'Michael Neser'
 'Michael Clarke' 'Martin Guptill' 'Matt Henry' 'Michael Lumb'
 'Mitchell McClenaghan' 'Mitchell Owen' 'Mitchell Santner' 'Manav Suthar'
 'Mahipal Lomror' 'Manish Pandey' 'Matthew Hayden' 'Moeen Ali'
 'Munaf Patel' 'Mohit Sharma' 'Marlon Samuels' 'Morne van Wyk'
 'Matthew Breetzke' 'Marcus Stoinis' 'Mayank Yadav' 'Mitchell Marsh'
 'Manoj Bhandage' 'Manvinder Bisla' 'MS Dhoni' 'Manpreet Gony'
 'Matthew Wade' 'Mark Boucher' 'Matthew Short' 'Mandeep Singh'
 'Mashrafe Mortaza' 'Mayank Dagar' 'Misbah-ul-Haq' 'Mohammad Ashraful'
 'Mohammad Asif' 'Mohammad Hafeez' 'Mohammad Nabi' 'Mohammed Shami'
 'Mohammed Siraj' 'Mohit Rathee' 'Mohsin Khan' 'Monu Kumar'
 'Mujeeb Ur Rahman' 'Mukesh Choudhary' 'Mukesh Kumar' 'Musheer Khan'
 'Mustafizur Rahman' 'Nandre Burger' 'Narayan Jagadeesan'
 'Nicholas Pooran' 'Nitish Rana' 'Navdeep Saini' 'Nuwan Thushara'
 'Nehal Wadhera' 'Nikhil Singh' 'Nayan Doshi' 'Nic Maddinson'
 'Nathan Rimmington' 'Niraj Patel' 'Nathan McCullum' 'Thisara Perera'
 'Nathan Coulter-Nile' 'Nikhil Naik' 'Nathan Ellis' 'Naman Ojha'
 'Naman Dhir' 'Naveen-ul-Haq' 'Nithish Kumar Reddy' 'Noor Ahmad'
 'Oshane Thomas' 'Owais Shah' 'Obed McCoy' 'Odean Smith' 'Palani Amarnath'
 'Parvinder Awana' 'Prashant Chopra' 'Paras Dogra' 'Praveen Dubey'
 'Praveen Kumar' 'Pawan Negi' 'Prasanth Parameswaran'
 'Padmanabhan Prasanth' 'Prayas Ray Barman' 'Pardeep Sahu'
 'Prabhsimran Singh' 'Pawan Suyal' 'Parthiv Patel' 'Akshath Reddy'
 'Bhanuka Rajapaksa' 'Paul Valthaty' 'Paul Collingwood' 'Phil Salt'
 'Prashant Solanki' 'Kamindu Mendis' 'Pat Cummins' 'Pradeep Sangwan'
 'Priyam Garg' 'Sarvesh Kumar' 'Prerak Mankad' 'Piyush Chawla'
 'Pragyan Ojha' 'Prithvi Shaw' 'Pinal Shah' 'Peter Handscomb'
 'Pravin Tambe' 'Dushmantha Chameera' 'Venugopal Rao' 'Wiaan Mulder'
 'Wanindu Hasaranga' 'Pankaj Singh' 'Parvez Rasool' 'Prince Yadav'
 'Priyansh Arya' 'Quinton de Kock' 'Ravichandran Ashwin' 'Rajat Bhatia'
 'Ravi Bishnoi' 'Rishi Dhawan' 'Rahul Dravid' 'Ravi Goyal' 'Ryan McLaren'
 'Robin Minz' 'Ryan Ninan' 'Riyan Parag' 'Rovman Powell' 'Ravi Rampaul'
 'Rachin Ravindra' 'Ravisrinivasan Sai Kishore' 'Sanjay Yadav'
 'Rajagopal Sathish' 'Rahul Sharma' 'Romario Shepherd' 'Rahul Shukla'
 'Rahul Tewatia' 'Vinay Kumar' 'Raj Bawa' 'Ravindra Jadeja' 'Rahil Shaikh'
 'Rahul Tripathi' 'Rahul Chahar' 'Ruturaj Gaikwad' 'Ryan Rickelton'
 'Richard Levi' 'Roelof van der Merwe' 'Ronit More' 'Rohit Sharma'
 'Richard Gleeson' 'Ryan Harris' 'Robin Peterson' 'Rob Quiney'
 'Reece Topley' 'Ricky Bhui' 'Rinku Singh' 'Rajat Patidar'
 'Ryan ten Doeschate' 'Riley Meredith' 'R. P. Singh' 'Raju Bhatkal'
 'Ranadeb Bose' 'Rishabh Pant' 'Ramesh Powar' 'Rohan Raje' 'Rilee Rossouw'
 'Ramnaresh Sarwan' 'Ravi Bopara' 'Rohan Gavaskar'
 'Rajvardhan Hangargekar' 'Reetinder Sodhi' 'Ricky Ponting' 'Raiphi Gomez'
 'Ripal Patel' 'Robin Uthappa' 'Ray Price' 'Rahmanullah Gurbaz'
 'Ramandeep Singh' 'Rashid Khan' 'Rasikh Salam' 'Anirudha Srikkanth'
 'Sreenath Aravind' 'Samuel Badree' 'Subramaniam Badrinath'
 'Shivnarine Chanderpaul' 'Shikhar Dhawan' 'Shivam Dube' 'Shreyas Gopal'
 'Shamar Joseph' 'Siddharth Kaul' 'Shivil Kaushik' 'Sarabjit Ladda'
 'Sandeep Lamichhane' 'Sudhesan Midhun' 'Shahbaz Nadeem' 'Sumit Narwal'
 'Sachin Rana' 'Suraj Randiv' 'Sandeep Warrier' 'Sunny Sohal' 'Sreesanth'
 'Sridharan Sriram' 'Sudeep Tyagi' 'Vidyut Sivaramakrishnan' 'Sean Abbott'
 'Swapnil Asnodkar' 'Sanjay Bangar' 'Shivam Dubey' 'Shadab Jakati'
 'Sunil Joshi' 'Scott Styris' 'Shrikant Wagh' 'Sourav Ganguly'
 'Scott Kuggeleijn' 'Siddharth Chitnis' 'Shai Hope' 'Siddhesh Lad'
 'Shane Bond' 'Shaun Marsh' 'Sherfane Rutherford' 'Spencer Johnson'
 'Shalabh Srivastava' 'Suresh Raina' 'Shaik Rasheed' 'Siddharth Trivedi'
 'Shane Warne' 'Scott Boland' 'Sam Curran' 'Shane Harwood' 'Simon Katich'
 'Shaun Pollock' 'Sachithra Senanayake' 'Sarfaraz Khan' 'Shardul Thakur'
 'Shimron Hetmyer' 'Stephen Fleming' 'Shreevats Goswami' 'Sheldon Jackson'
 'Sunil Narine' 'Steve Smith' 'Sachin Tendulkar' 'Shane Watson'
 'Shubham Agarwal' 'Sheldon Cottrell' 'Shreyas Iyer' 'Shrikant Mundhe'
 'Suyash Prabhudessai' 'Soumya Sarkar' 'Sufiyan Shaikh' 'Saurabh Tiwary'
 'Sisanda Magala' 'Sanath Jayasuriya' 'Stuart Binny' 'Sanju Samson'
 'Sam Billings' 'Shaun Tait' 'Shams Mulani' 'Sachin Baby' 'Salman Butt'
 'Sameer Rizvi' 'Sandeep Sharma' 'Sanvir Singh' 'Saurav Chauhan'
 'Sediqullah Atal' 'Shahbaz Ahmed' 'Shahid Afridi' 'Shakib Al Hasan'
 'Shashank Singh' 'Shivam Mavi' 'Shivam Sharma' 'Shivam Singh'
 'Shoaib Ahmed' 'Shoaib Akhtar' 'Shoaib Malik' 'Shubman Gill'
 'Sikandar Raza' 'Simarjeet Singh' 'Sohail Tanvir' 'Sumit Kumar'
 'Sunny Gupta' 'Sunny Singh' 'Suryansh Shedge' 'Suyash Sharma'
 'Swapnil Singh' 'Tom Banton' 'Tyron Henderson' 'Tom Kohler-Cadmore'
 'Taruwar Kohli' 'T. Natarajan' 'Tabraiz Shamsi' 'Tristan Stubbs'
 'Tatenda Taibu' 'Thilan Thushara' 'Trent Boult' 'Tim Paine' 'Tim Southee'
 'Tim David' 'Tom Curran' 'Tim Seifert' 'Tirumalasetti Suman'
 'Tillakaratne Dilshan' 'Travis Head' 'Tanmay Srivastava'
 'T. P. Sudhindra' 'Travis Birt' 'Tymal Mills' 'Tushar Deshpande'
 'Tanush Kotian' 'Tejas Baroka' 'Tilak Varma' 'Uday Kaul' 'Udit Birla'
 'Unmukt Chand' 'Usman Khawaja' 'Umesh Yadav' 'Umar Gul' 'Umran Malik'
 'Urvil Patel' 'Vidwath Kaverappa' 'Virat Kohli' 'Vikas Nigam'
 'Vishwa Pratap Singh' 'Vyshak Vijaykumar' 'Virender Sehwag'
 'Vijay Shankar' 'Vaibhav Suryavanshi' 'Vijayakanth Viyaskanth'
 'Vaibhav Arora' 'Vijay Zol' 'Varun Aaron' 'Venkatesh Iyer'
 'V. R. V. Singh' 'Vikramjeet Malik' 'Vinayak Yeligati' 'V. V. S. Laxman'
 'V. Y. Mahesh' 'Vijaykumar Vyshak' 'Virat Singh' 'Vishnu Vinod'
 'Vivrant Sharma' 'Wasim Jaffer' "William O'Rourke" 'Wilkin Mota'
 'Wayne Parnell' 'Will Jacks' 'Wriddhiman Saha' 'Chaminda Vaas'
 'Washington Sundar' 'Xavier Thalaivan Sargunam' 'Xavier Bartlett'
 'Yalaka Gnaneswara Rao' 'Yogesh Nagar' 'Yarra Prithvi Raj'
 'Yalaka Venugopal Rao' 'Yusuf Abdulla' 'Yashasvi Jaiswal' 'Yusuf Pathan'
 'Yuzvendra Chahal' 'Yash Dhull' 'Yogesh Takawale' 'Yash Dayal'
 'Yash Thakur' 'Yashpal Singh' 'Younis Khan' 'Yudhvir Singh'
 'Yuvraj Singh' 'Zaheer Khan' 'Zeeshan Ansari']

In [13]:
mapped_players_1 = [map_player_name(p) for p in team1_squad]
mapped_players_2 = [map_player_name(p) for p in team2_squad]

mapped_players_1+mapped_players_2
all_mapped = mapped_players_1 + mapped_players_2

In [14]:
all_mapped

['MS Dhoni',
 'Ravindra Jadeja',
 'Ruturaj Gaikwad',
 'Deepak Chahar',
 'Moeen Ali',
 'Shivam Dube',
 'Matheesha Pathirana',
 'Ajinkya Rahane',
 'Daryl Mitchell',
 'Mitchell Santner',
 'Tushar Deshpande',
 'Rohit Sharma',
 'Ishan Kishan',
 'Suryakumar Yadav',
 'Hardik Pandya',
 'Tim David',
 'Jasprit Bumrah',
 'Piyush Chawla',
 'Tilak Varma',
 'Gerald Coetzee',
 'Romario Shepherd',
 'Nehal Wadhera']

In [15]:
unique_venue_list_from_df = historical_data['venue'].unique()
unique_venues = list(unique_venue_list_from_df)
print(unique_venues)
def map_venue_name(name):
    
    match = get_close_matches(name, unique_venues, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None
print(historical_data['venue'].value_counts())

['Subrata Roy Sahara Stadium', 'Wankhede Stadium', 'Barabati Stadium', 'MA Chidambaram Stadium', 'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium', 'Arun Jaitley Stadium', 'Eden Gardens', 'Maharashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Punjab Cricket Association IS Bindra Stadium', 'Brabourne Stadium', 'Dr DY Patil Sports Academy', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'Narendra Modi Stadium', 'Himachal Pradesh Cricket Association Stadium', 'Newlands', "St George's Park", 'Kingsmead', 'New Wanderers Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Buffalo Park', 'OUTsurance Oval', 'Nehru Stadium', 'Sheikh Zayed Stadium', 'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium', 'Shaheed Veer Narayan Singh International Stadium', 'Saurashtra Cricket Association Stadium', 'Green Park', 'JSCA International Stadium Complex', 'Barsapara Cricket Stadium', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'De Beers Diamond Oval', 'Holkar Cricket Stadium']
venue
Wankhede Stadium                                                      2719
Eden Gardens                                                          2125
M Chinnaswamy Stadium                                                 2116
Arun Jaitley Stadium                                                  2099
MA Chidambaram Stadium                                                1991
Rajiv Gandhi International Stadium                                    1772
Sawai Mansingh Stadium                                                1347
Punjab Cricket Association IS Bindra Stadium                          1297
Narendra Modi Stadium                                                 1002
Dubai International Cricket Stadium                                    988
Sheikh Zayed Stadium                                                   788
Dr DY Patil Sports Academy                                             786
Maharashtra Cricket Association Stadium                                746
Sharjah Cricket Stadium                                                594
Brabourne Stadium                                                      567
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           501
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    374
Subrata Roy Sahara Stadium                                             336
Kingsmead                                                              317
Himachal Pradesh Cricket Association Stadium                           309
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     260
SuperSport Park                                                        249
Saurashtra Cricket Association Stadium                                 203
Holkar Cricket Stadium                                                 188
New Wanderers Stadium                                                  184
Newlands                                                               164
Barabati Stadium                                                       149
JSCA International Stadium Complex                                     148
St George's Park                                                       144
Shaheed Veer Narayan Singh International Stadium                       126
Barsapara Cricket Stadium                                              115
Nehru Stadium                                                          107
Green Park                                                              83
Vidarbha Cricket Association Stadium, Jamtha                            65
De Beers Diamond Oval                                                   62
Buffalo Park                                                            61
OUTsurance Oval                                                         43
Name: count, dtype: int64

In [16]:
from difflib import get_close_matches
mapped_venues = map_venue_name(venue)
mapped_venues

'Wankhede Stadium'

In [17]:
players_df = data[
    data['player'].isin(all_mapped)
].copy()
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
1557,335994,Ajinkya Rahane,-2.0,Dr DY Patil Sports Academy,2007/08,1,17.000000,93.818369,0.0,20.666667,19.333333,0.946751,1.0,-0.0,9.433392,1.070665,6.900000,1.0,0.000000,0,0,15.230000,294.446667,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False
1558,335997,Ajinkya Rahane,5.0,Eden Gardens,2007/08,2,35.672040,80.762144,0.0,36.318182,44.647059,1.001310,1.0,-0.0,0.000000,0.000000,0.000000,1.0,1.000000,0,0,35.672040,1592.651659,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1559,392203,Ajinkya Rahane,11.0,Buffalo Park,2009,3,35.672040,80.762144,0.0,36.318182,12.500000,0.810556,1.0,0.0,0.000000,0.000000,0.000000,1.0,0.400000,0,1,35.672040,445.900498,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1560,392208,Ajinkya Rahane,-2.0,New Wanderers Stadium,2009,4,4.666667,80.762144,0.0,47.583333,-2.000000,0.999131,1.0,-0.0,6.506407,0.000000,0.000000,1.0,0.000000,0,1,17.068816,-34.137632,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False
1561,392215,Ajinkya Rahane,14.0,Buffalo Park,2009,5,4.666667,80.762144,0.0,53.954545,12.500000,0.810556,1.0,0.0,6.271629,0.000000,0.000000,1.0,0.666667,0,1,17.068816,213.360199,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23066,1473493,Tilak Varma,7.0,Wankhede Stadium,2025,47,18.666667,143.084148,0.0,35.857143,33.947368,1.035196,1.0,0.0,25.954875,1.814688,-28.433333,5.0,0.000000,0,0,29.290000,994.318421,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False
23067,1473501,Tilak Varma,30.0,Wankhede Stadium,2025,48,10.666667,124.463458,0.0,48.857143,33.947368,1.035196,1.0,0.0,28.631956,1.477370,-31.633333,5.0,0.370370,0,0,19.510000,662.313158,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False
23068,1473506,Tilak Varma,1.0,Sawai Mansingh Stadium,2025,49,17.333333,108.705882,0.0,36.333333,43.500000,0.988582,1.0,0.0,28.054708,1.397270,-21.866667,5.0,0.000000,0,0,19.900000,865.650000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
23069,1473509,Tilak Varma,45.0,Maharaja Yadavindra Singh International Cricke...,2025,50,12.666667,89.000000,0.0,35.857143,51.500000,1.025162,1.0,0.0,30.214787,1.138515,-21.733333,5.0,0.720000,0,1,14.820000,763.230000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
23070,1473510,Tilak Varma,58.0,Narendra Modi Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.0,0.0,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.410000,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False

In [18]:
players_df = (
    players_df
    .sort_values('player_match_number')
    .groupby('player')
    .tail(1)
)
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
6141,1473509,Gerald Coetzee,2.0,Maharaja Yadavindra Singh International Cricke...,2025,14,26.333333,100.857143,0.6,23.000000,40.500000,1.025162,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
5105,1426306,Daryl Mitchell,20.0,M Chinnaswamy Stadium,2024,15,52.000000,154.983925,0.0,20.000000,20.000000,1.016059,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False
16745,1473511,Romario Shepherd,43.0,Narendra Modi Stadium,2025,17,38.666667,81.538462,0.8,27.600000,43.000000,1.079940,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
12432,1473510,Mitchell Santner,6.0,Narendra Modi Stadium,2025,31,60.333333,20.000000,1.4,33.500000,9.500000,1.079940,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
14364,1473511,Nehal Wadhera,17.0,Narendra Modi Stadium,2025,31,30.333333,128.719064,0.0,36.500000,38.250000,1.079940,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
11561,1473504,Matheesha Pathirana,41.0,Narendra Modi Stadium,2025,32,25.666667,0.000000,1.0,47.600000,48.500000,1.079940,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
22805,1473503,Tim David,1.0,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025,44,21.000000,216.000000,0.0,53.000000,36.000000,1.040207,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False
23017,1473500,Tushar Deshpande,33.0,Arun Jaitley Stadium,2025,46,24.000000,10.000000,0.6,18.333333,20.666667,1.031603,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True
23070,1473510,Tilak Varma,58.0,Narendra Modi Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
12819,1473494,Moeen Ali,29.0,Eden Gardens,2025,70,33.000000,23.717949,1.0,32.800000,40.200000,1.001310,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
17445,1473459,Ruturaj Gaikwad,1.0,Maharaja Yadavindra Singh International Cricke...,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,1.025162,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
19174,1473504,Shivam Dube,31.0,Narendra Modi Stadium,2025,76,38.666667,173.541667,0.0,31.750000,35.250000,1.079940,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
5251,1473506,Deepak Chahar,12.0,Sawai Mansingh Stadium,2025,95,30.666667,40.000000,1.0,26.454545,37.666667,0.988582,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,1117.570000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
7797,1473505,Ishan Kishan,37.0,Arun Jaitley Stadium,2025,114,70.000000,110.343137,0.0,38.181818,19.500000,1.031603,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False
8635,1473510,Jasprit Bumrah,-2.0,Narendra Modi Stadium,2025,147,57.666667,0.000000,1.8,45.666667,30.666667,1.079940,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
6876,1473510,Hardik Pandya,63.0,Narendra Modi Stadium,2025,151,19.000000,141.961353,0.2,34.705882,50.500000,1.079940,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,1142.310000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
19681,1473510,Suryakumar Yadav,62.0,Narendra Modi Stadium,2025,154,80.333333,167.090055,0.0,44.700000,59.200000,1.079940,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,4595.696000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
1739,1473505,Ajinkya Rahane,18.0,Arun Jaitley Stadium,2025,183,49.000000,139.011544,0.0,33.772727,40.100000,1.031603,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False
15604,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,32.736842,1.035196,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True
13476,1473500,MS Dhoni,18.0,Arun Jaitley Stadium,2025,241,25.000000,129.222222,0.0,34.807692,27.900000,1.031603,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False
17196,1473504,Ravindra Jadeja,78.0,Narendra Modi Stadium,2025,247,56.000000,129.261438,0.6,50.857143,43.600000,1.079940,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17757,1473510,Rohit Sharma,9.0,Narendra Modi Stadium,2025,269,48.000000,122.201587,0.0,42.666667,29.250000,1.079940,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,1398.735000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False

In [19]:
players_df['venue'] = venue
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
6141,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,40.500000,1.025162,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
5105,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,20.000000,1.016059,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False
16745,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,43.000000,1.079940,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
12432,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,9.500000,1.079940,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
14364,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,38.250000,1.079940,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
11561,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,48.500000,1.079940,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
22805,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,36.000000,1.040207,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False
23017,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,20.666667,1.031603,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True
23070,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
12819,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,40.200000,1.001310,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
17445,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,1.025162,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
19174,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,35.250000,1.079940,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
5251,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,37.666667,0.988582,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,1117.570000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
7797,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,19.500000,1.031603,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False
8635,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,30.666667,1.079940,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True
6876,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,50.500000,1.079940,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,1142.310000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
19681,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,59.200000,1.079940,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,4595.696000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False
1739,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,40.100000,1.031603,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False
15604,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,32.736842,1.035196,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True
13476,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,27.900000,1.031603,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False
17196,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,43.600000,1.079940,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17757,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,29.250000,1.079940,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,1398.735000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False

In [20]:
players_df = players_df.drop(columns = ['venue_avg_points','venue_run_factor'])
venue_data = data[data['venue'] == venue][['player','venue_avg_points','venue_run_factor']].drop_duplicates()
venue_data

                 player  venue_avg_points  venue_run_factor
1          Ashish Reddy         41.000000          1.035196
28         Ayush Badoni         42.000000          1.035196
91        Aakash Chopra          1.000000          1.035196
96     Aniket Choudhary         25.000000          1.035196
99      Akila Dananjaya          0.000000          1.035196
...                 ...               ...               ...
24628  Yuzvendra Chahal         43.333333          1.035196
24810        Yash Dayal         24.250000          1.035196
24895      Yuvraj Singh         32.300000          1.035196
25017       Zaheer Khan         33.500000          1.035196
25119    Zeeshan Ansari         12.000000          1.035196

[477 rows x 3 columns]

In [21]:
players_df = players_df.merge(venue_data,on = ['player'],how = 'left')
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,1117.570000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,1142.310000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,4595.696000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,1398.735000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196

In [22]:
pd.set_option("display.max_columns",None)

In [23]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,1117.570000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,1142.310000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,4595.696000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,1398.735000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196

In [24]:
venue_run_data = historical_data[historical_data['venue'] == venue][['player','venue_run_factor']].drop_duplicates()
venue_run_data

                 player  venue_run_factor
1          Ashish Reddy          1.035196
28         Ayush Badoni          1.035196
91        Aakash Chopra          1.035196
96     Aniket Choudhary          1.035196
99      Akila Dananjaya          1.035196
...                 ...               ...
24628  Yuzvendra Chahal          1.035196
24810        Yash Dayal          1.035196
24895      Yuvraj Singh          1.035196
25017       Zaheer Khan          1.035196
25119    Zeeshan Ansari          1.035196

[473 rows x 2 columns]

In [25]:
players_df = players_df.drop(columns = ['venue_run_factor'])
players_df = players_df.merge(venue_run_data,on = ['player'],how = 'left')
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,1091.880000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,1034.600000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,1649.910000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,510.625000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,1298.970000,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,1259.060000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,1051.560000,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,421.186667,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,1337.454000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,36.770000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,1241.152500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,1117.570000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,1201.395000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,1805.653333,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,1142.310000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,4595.696000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,1928.008000,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,1642.734737,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,639.189000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,2391.024000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,1398.735000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196

In [26]:
players_df = players_df.drop(columns = ['venue_form'])
players_df['venue_form'] = players_df['venue_avg_points'] * players_df['recent_form']
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196,931.140000
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196,809.380000
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196,1076.597143
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196,2118.954286
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953

In [27]:
players_df.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'player_role_wicketkeeper', 'team_won_toss',
       'recent_form', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler', 'venue_avg_points',
       'venue_run_factor', 'venue_form'],
      dtype='object')

In [28]:
historical_data

,match_id,player,fantasy_points,team,opponent,venue,toss_decision,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form
0,548341,Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,bat,2012,1,35.672040,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,2068.978308
1,548346,Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,field,2012,2,35.672040,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,0,0,35.672040,1462.553632
2,548348,Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,bat,2012,3,35.672040,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,820.456915
3,548352,Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,bat,2012,4,40.666667,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,0,0,38.668816,1740.096716
4,548356,Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,field,2012,5,30.666667,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,0,0,32.668816,1037.234905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,field,2025,6,3.333333,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,0,0,13.247204,89.418627
25121,1473480,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,field,2025,7,11.666667,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,0,1,14.647204,0.000000
25122,1473488,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,field,2025,8,12.333333,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,0,1,13.067204,300.545692
25123,1473492,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,field,2025,9,16.000000,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,0,1,16.647204,112.368627
25124,1473499,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,field,2025,10,9.000000,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,0,1,12.807204,-25.614408

In [29]:
historical_data['last3_battingcontri'] = historical_data.groupby(['player'])['batting_contribution_ratio'].rolling(3,min_periods = 1).mean().reset_index(level=0, drop=True)

In [30]:
historical_data

,match_id,player,fantasy_points,team,opponent,venue,toss_decision,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,last3_battingcontri
0,548341,Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,bat,2012,1,35.672040,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,2068.978308,0.000000
1,548346,Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,field,2012,2,35.672040,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,0,0,35.672040,1462.553632,0.146341
2,548348,Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,bat,2012,3,35.672040,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,820.456915,0.097561
3,548352,Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,bat,2012,4,40.666667,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,0,0,38.668816,1740.096716,0.133275
4,548356,Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,field,2012,5,30.666667,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,0,0,32.668816,1037.234905,0.035714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,field,2025,6,3.333333,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,0,0,13.247204,89.418627,0.000000
25121,1473480,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,field,2025,7,11.666667,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,0,1,14.647204,0.000000,0.000000
25122,1473488,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,field,2025,8,12.333333,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,0,1,13.067204,300.545692,0.000000
25123,1473492,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,field,2025,9,16.000000,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,0,1,16.647204,112.368627,-0.000000
25124,1473499,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,field,2025,10,9.000000,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,0,1,12.807204,-25.614408,-0.000000

In [31]:
historical_data['last3_bowlingcontri'] = historical_data.groupby(['player'])['bowling_contribution_ratio'].rolling(3,min_periods = 1).mean().reset_index(level=0, drop=True)

In [32]:
historical_data['last3_boundarypercentage'] = historical_data.groupby(['player'])['boundary_percentage'].rolling(3,min_periods = 1).mean().reset_index(level=0, drop=True)
# historical_data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/historical_data_final.csv",index = False)
# data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data_final.csv",index = False)

In [33]:
ratio_info = historical_data[['player','player_match_number','last3_battingcontri','last3_bowlingcontri','last3_boundarypercentage']]
ratio_df = (
    ratio_info
    .sort_values('player_match_number')
    .groupby('player')
    .tail(1)
)
ratio_df = ratio_df.drop(columns = ['player_match_number'])
ratio_df

,player,last3_battingcontri,last3_bowlingcontri,last3_boundarypercentage
16481,Ravi Goyal,0.000000,0.000000,0.000000
2300,Abdur Razzak,0.250000,0.750000,0.000000
16657,Sanjay Yadav,0.333333,0.666667,0.000000
2248,Abdul Basith,1.000000,0.000000,0.000000
18036,Raju Bhatkal,0.250000,0.750000,0.000000
...,...,...,...,...
9771,Dinesh Karthik,1.000000,0.000000,0.359307
13476,MS Dhoni,1.000000,0.000000,0.409314
17196,Ravindra Jadeja,0.214910,0.785090,0.404344
23544,Virat Kohli,1.000000,0.000000,0.562159
17757,Rohit Sharma,1.000000,0.000000,0.608025

In [34]:
players_df = players_df.merge(ratio_df,on = ['player'],how = 'left')
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,last3_battingcontri,last3_bowlingcontri,last3_boundarypercentage
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,-0.000000,1.000000,34.325889,1.031292,-9.066667,9.0,0.000000,0,0,26.96,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,1.000000,0.000000,35.725652,1.144836,11.100000,3.0,0.000000,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,0.465116,0.534884,32.348965,0.701723,15.966667,7.0,0.588235,0,0,38.37,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,1.000000,-0.000000,31.582168,1.111387,25.233333,8.0,0.000000,0,0,53.75,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,1.000000,0.000000,31.959002,1.045089,-3.066667,4.0,0.400000,0,1,33.96,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,0.000000,1.000000,32.434549,0.832446,-1.333333,11.0,0.000000,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,1.000000,0.000000,28.233353,1.229043,-13.700000,6.0,0.000000,0,1,29.21,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,0.000000,1.000000,28.523674,0.750254,2.600000,10.0,0.000000,0,1,20.38,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,1.000000,0.000000,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,0.000000,1.000000,28.429445,1.150216,0.300000,3.0,0.000000,0,1,33.27,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,1.000000,0.000000,47.301045,1.088771,-17.500000,1.0,0.000000,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,1.400000,-0.400000,23.249612,1.630135,0.766667,4.0,0.705882,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,0.000000,1.000000,23.542161,0.836797,10.966667,9.0,0.000000,0,0,29.67,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,1.000000,0.000000,42.744850,0.741610,38.300000,2.0,0.758621,1,1,61.61,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,-0.000000,1.000000,36.347704,1.579192,0.266667,10.0,0.000000,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,0.418605,0.581395,28.981987,0.786696,-3.800000,4.0,0.666667,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,1.000000,0.000000,22.025490,3.255319,8.633333,3.0,0.772727,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,1.000000,0.000000,22.192091,2.090835,2.600000,1.0,0.800000,0,0,48.08,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,0.000000,1.000000,28.743308,1.015889,28.466667,8.0,0.000000,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,1.000000,0.000000,23.333571,1.229987,-3.700000,5.0,0.375000,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,0.307692,0.692308,37.372598,1.300418,7.400000,6.0,0.476190,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,1.000000,0.000000,41.678665,1.223648,-3.000000,4.0,0.500000,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025

In [35]:
players_df = players_df.drop(columns = ['batting_contribution_ratio','bowling_contribution_ratio','boundary_percentage'])
players_df = players_df.rename(columns = {"last3_battingcontri":"batting_contribution_ratio","last3_bowlingcontri":"bowling_contribution_ratio",'last3_boundarypercentage':'boundary_percentage'})

In [36]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025

In [37]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'toss_decision', 'season', 'player_match_number', 'last3_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'opponent_avg_points',
       'pitch_type', 'venue_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'player_role', 'last10_std_points', 'player_consistency_index',
       'form_momentum', 'bat_pos', 'boundary_percentage',
       'player_role_wicketkeeper', 'team_won_toss', 'recent_form',
       'venue_form', 'last3_battingcontri', 'last3_bowlingcontri',
       'last3_boundarypercentage'],
      dtype='object')

In [38]:
players_df.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'player_role_wicketkeeper', 'team_won_toss', 'recent_form',
       'team_Deccan Chargers', 'team_Delhi Capitals', 'team_Gujarat Lions',
       'team_Gujarat Titans', 'team_Kochi Tuskers Kerala',
       'team_Kolkata Knight Riders', 'team_Lucknow Super Giants',
       'team_Mumbai Indians', 'team_Pune Warriors', 'team_Punjab Kings',
       'team_Rajasthan Royals', 'team_Rising Pune Supergiants',
       'team_Royal Challengers Bengaluru', 'team_Sunrisers Hyderabad',
       'opponent_Deccan Chargers', 'opponent_Delhi Capitals',
       'opponent_Gujarat Lions', 'opponent_Gujarat Titans',
       'opponent_Kochi Tuskers Kerala', 'opponent_Kolkata Knight Riders',
       'opponent_Lucknow Super Giants', 'opponent_Mumbai Indians',
       'opponent_Pune Warriors', 'opponent_Punjab Kings',
       'opponent_Rajasthan Royals', 'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler', 'venue_avg_points',
       'venue_run_factor', 'venue_form', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'boundary_percentage'],
      dtype='object')

In [39]:
team_cols = [col for col in players_df.columns if col.startswith('team_')]
opponent_cols = [col for col in players_df.columns if col.startswith('opponent_')]

In [40]:
team_cols = team_cols[1:]

In [41]:
opponent_cols = opponent_cols[1:]
opponent_cols

['opponent_Deccan Chargers',
 'opponent_Delhi Capitals',
 'opponent_Gujarat Lions',
 'opponent_Gujarat Titans',
 'opponent_Kochi Tuskers Kerala',
 'opponent_Kolkata Knight Riders',
 'opponent_Lucknow Super Giants',
 'opponent_Mumbai Indians',
 'opponent_Pune Warriors',
 'opponent_Punjab Kings',
 'opponent_Rajasthan Royals',
 'opponent_Rising Pune Supergiants',
 'opponent_Royal Challengers Bengaluru',
 'opponent_Sunrisers Hyderabad']

In [42]:
team_cols

['team_Deccan Chargers',
 'team_Delhi Capitals',
 'team_Gujarat Lions',
 'team_Gujarat Titans',
 'team_Kochi Tuskers Kerala',
 'team_Kolkata Knight Riders',
 'team_Lucknow Super Giants',
 'team_Mumbai Indians',
 'team_Pune Warriors',
 'team_Punjab Kings',
 'team_Rajasthan Royals',
 'team_Rising Pune Supergiants',
 'team_Royal Challengers Bengaluru',
 'team_Sunrisers Hyderabad']

In [43]:
players_df[team_cols] = False
players_df[opponent_cols] = False

In [44]:
if f"team_{team1}" in team_cols:
    players_df.loc[players_df['player'].isin(mapped_players_1), f"team_{team1}"] = True

if f"team_{team2}" in team_cols:
    players_df.loc[players_df['player'].isin(mapped_players_2), f"team_{team2}"] = True
if f"opponent_{team2}" in opponent_cols:
    players_df.loc[players_df['player'].isin(mapped_players_1), f"opponent_{team2}"] = True

if f"opponent_{team1}" in opponent_cols:
    players_df.loc[players_df['player'].isin(mapped_players_2), f"opponent_{team1}"] = True

In [45]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025

In [46]:
opponent_avg_dict = historical_data.groupby(['player','opponent'])['fantasy_points'].mean().to_dict()

In [47]:
player_avg_dict = (
    historical_data
    .groupby('player')['fantasy_points']
    .mean()
    .to_dict()
)

In [48]:
opponent_cols = [c for c in players_df.columns if c.startswith('opponent_')]
opponent_cols = opponent_cols[1:]
opponent_cols

['opponent_Deccan Chargers',
 'opponent_Delhi Capitals',
 'opponent_Gujarat Lions',
 'opponent_Gujarat Titans',
 'opponent_Kochi Tuskers Kerala',
 'opponent_Kolkata Knight Riders',
 'opponent_Lucknow Super Giants',
 'opponent_Mumbai Indians',
 'opponent_Pune Warriors',
 'opponent_Punjab Kings',
 'opponent_Rajasthan Royals',
 'opponent_Rising Pune Supergiants',
 'opponent_Royal Challengers Bengaluru',
 'opponent_Sunrisers Hyderabad']

In [49]:
players_df['opponent_temp'] = (
    players_df[opponent_cols]
    .idxmax(axis=1)
    .str.replace('opponent_', '')
)

In [50]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_temp
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,Deccan Chargers
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,Mumbai Indians
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,Deccan Chargers
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,Mumbai Indians
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,Deccan Chargers
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,Mumbai Indians
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,Deccan Chargers
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,Mumbai Indians
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,Deccan Chargers
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,Mumbai Indians
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,Mumbai Indians
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,Mumbai Indians
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,Mumbai Indians
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,Deccan Chargers
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,Deccan Chargers
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,Deccan Chargers
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,Deccan Chargers
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,Mumbai Indians
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,Deccan Chargers
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,Mumbai Indians
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,Mumbai Indians
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,Deccan Chargers

In [51]:
all_opponents = historical_data['opponent'].unique()
encoded_opponents = [c.replace('opponent_', '') for c in opponent_cols]

dropped_opponent = list(set(all_opponents) - set(encoded_opponents))[0]

mask = players_df[opponent_cols].sum(axis=1) == 0
players_df.loc[mask, 'opponent_temp'] = dropped_opponent

In [52]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_temp
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,23.000000,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,Chennai Super Kings
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,20.000000,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,Mumbai Indians
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,27.600000,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,Chennai Super Kings
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,33.500000,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,Mumbai Indians
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,36.500000,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,Chennai Super Kings
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,47.600000,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,Mumbai Indians
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,53.000000,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,Chennai Super Kings
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,18.333333,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,Mumbai Indians
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,36.333333,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,Chennai Super Kings
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,32.800000,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,Mumbai Indians
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,36.444444,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,Mumbai Indians
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,31.750000,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,Mumbai Indians
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,26.454545,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,Mumbai Indians
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,38.181818,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,Chennai Super Kings
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,45.666667,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,Chennai Super Kings
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,34.705882,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,Chennai Super Kings
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,44.700000,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,Chennai Super Kings
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,33.772727,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,Mumbai Indians
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,34.250000,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,Chennai Super Kings
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,34.807692,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,Mumbai Indians
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,50.857143,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,Mumbai Indians
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,42.666667,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,Chennai Super Kings

In [53]:
def get_opponent_avg(row):
    key = (row['player'], row['opponent_temp'])
    
    if key in opponent_avg_dict:
        return opponent_avg_dict[key]
    else:
        return player_avg_dict.get(row['player'], 0)
    
players_df = players_df.drop(columns = ['opponent_avg_points'])
players_df['opponent_avg_points'] = players_df.apply(get_opponent_avg, axis=1)

In [54]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_temp,opponent_avg_points
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,Chennai Super Kings,17.500000
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,Mumbai Indians,26.000000
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,Chennai Super Kings,43.000000
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,Mumbai Indians,66.000000
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,Chennai Super Kings,35.666667
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,Mumbai Indians,69.666667
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,Chennai Super Kings,16.142857
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,Mumbai Indians,47.000000
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,Chennai Super Kings,50.200000
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,Mumbai Indians,65.285714
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,Mumbai Indians,48.777778
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,Mumbai Indians,32.833333
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,Mumbai Indians,30.846154
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,Chennai Super Kings,40.727273
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,Chennai Super Kings,26.125000
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,Chennai Super Kings,34.823529
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,Chennai Super Kings,32.666667
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,Mumbai Indians,38.807692
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,Chennai Super Kings,32.454545
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,Mumbai Indians,32.921053
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,Mumbai Indians,35.228571
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,Chennai Super Kings,40.138889

In [55]:
# X_pred = players_df.drop(columns=['fantasy_points','player','venue','player_match_number','match_id','season','player_role_batsman','player_role_bowler','opponent_temp'])

# players_df['predicted_points'] = model.predict(X_pred)

In [56]:
# players_df.sort_values(by= ['predicted_points'],ascending= False).head(11)

In [57]:
players_df = players_df.drop(columns = ['opponent_temp'])

In [58]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889

In [59]:
venue

'Wankhede Stadium'

In [60]:
pitch_info = historical_data[historical_data['venue'] == venue]['pitch_type'].mode()[0]
pitch_info

'batting_friendly'

In [61]:
pitch_cols = [
    'pitch_type_batting_friendly',
    'pitch_type_pace_friendly',
    'pitch_type_spin_friendly'
]

players_df[pitch_cols] = False

In [62]:
if pitch_info == 'batting_friendly':
    players_df['pitch_type_batting_friendly'] = True
elif pitch_info == 'pace_friendly':
    players_df['pitch_type_pace_friendly'] = True
elif pitch_info == 'spin_friendly':
    players_df['pitch_type_spin_friendly'] = True

In [63]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889

In [64]:
X_pred = players_df.drop(columns=['fantasy_points','player','venue','player_match_number','match_id','season','player_role_batsman','player_role_bowler'])

players_df['predicted_points'] = model.predict(X_pred)

In [65]:
players_df.sort_values(by= ['predicted_points'],ascending= False)

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points,predicted_points
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273,24.383979
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053,17.527844
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778,5.716620
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571,4.561507
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545,4.321879
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667,4.285958
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000,3.994608
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333,3.969153
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857,3.944627
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889,3.492532
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692,3.247537
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000,2.916713
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000,2.842853
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154,2.660113
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529,2.237919
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000,2.192136
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667,1.926756
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667,1.896282
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000,1.760231
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000,1.659244
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000,1.514068
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714,1.216622

In [66]:
historical_data

,match_id,player,fantasy_points,team,opponent,venue,toss_decision,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,last3_battingcontri,last3_bowlingcontri,last3_boundarypercentage
0,548341,Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,bat,2012,1,35.672040,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,2068.978308,0.000000,1.000000,0.0
1,548346,Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,field,2012,2,35.672040,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,0,0,35.672040,1462.553632,0.146341,0.853659,0.3
2,548348,Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,bat,2012,3,35.672040,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,820.456915,0.097561,0.902439,0.2
3,548352,Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,bat,2012,4,40.666667,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,0,0,38.668816,1740.096716,0.133275,0.866725,0.2
4,548356,Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,field,2012,5,30.666667,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,0,0,32.668816,1037.234905,0.035714,0.964286,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,field,2025,6,3.333333,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,0,0,13.247204,89.418627,0.000000,1.000000,0.0
25121,1473480,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,field,2025,7,11.666667,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,0,1,14.647204,0.000000,0.000000,0.666667,0.0
25122,1473488,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,field,2025,8,12.333333,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,0,1,13.067204,300.545692,0.000000,0.666667,0.0
25123,1473492,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,field,2025,9,16.000000,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,0,1,16.647204,112.368627,-0.000000,0.666667,0.0
25124,1473499,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,field,2025,10,9.000000,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,0,1,12.807204,-25.614408,-0.000000,1.000000,0.0

In [67]:
team_map = {}

for player in mapped_players_1:
    team_map[player] = team1

for player in mapped_players_2:
    team_map[player] = team2
players_df['team'] = players_df['player'].map(team_map)

In [68]:
team_map

{'MS Dhoni': 'Chennai Super Kings',
 'Ravindra Jadeja': 'Chennai Super Kings',
 'Ruturaj Gaikwad': 'Chennai Super Kings',
 'Deepak Chahar': 'Chennai Super Kings',
 'Moeen Ali': 'Chennai Super Kings',
 'Shivam Dube': 'Chennai Super Kings',
 'Matheesha Pathirana': 'Chennai Super Kings',
 'Ajinkya Rahane': 'Chennai Super Kings',
 'Daryl Mitchell': 'Chennai Super Kings',
 'Mitchell Santner': 'Chennai Super Kings',
 'Tushar Deshpande': 'Chennai Super Kings',
 'Rohit Sharma': 'Mumbai Indians',
 'Ishan Kishan': 'Mumbai Indians',
 'Suryakumar Yadav': 'Mumbai Indians',
 'Hardik Pandya': 'Mumbai Indians',
 'Tim David': 'Mumbai Indians',
 'Jasprit Bumrah': 'Mumbai Indians',
 'Piyush Chawla': 'Mumbai Indians',
 'Tilak Varma': 'Mumbai Indians',
 'Gerald Coetzee': 'Mumbai Indians',
 'Romario Shepherd': 'Mumbai Indians',
 'Nehal Wadhera': 'Mumbai Indians'}

In [69]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points,predicted_points,team
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000,2.192136,Mumbai Indians
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000,3.994608,Chennai Super Kings
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000,2.842853,Mumbai Indians
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000,1.514068,Chennai Super Kings
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667,1.896282,Mumbai Indians
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667,1.926756,Chennai Super Kings
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857,3.944627,Mumbai Indians
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000,1.659244,Chennai Super Kings
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000,2.916713,Mumbai Indians
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714,1.216622,Chennai Super Kings
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778,5.716620,Chennai Super Kings
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333,3.969153,Chennai Super Kings
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154,2.660113,Chennai Super Kings
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273,24.383979,Mumbai Indians
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000,1.760231,Mumbai Indians
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529,2.237919,Mumbai Indians
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667,4.285958,Mumbai Indians
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692,3.247537,Chennai Super Kings
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545,4.321879,Mumbai Indians
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053,17.527844,Chennai Super Kings
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571,4.561507,Chennai Super Kings
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889,3.492532,Mumbai Indians

In [70]:
role_map = (
    historical_data
    .groupby('player')['player_role']
    .agg(lambda x: x.mode()[0])
)

In [71]:
players_df['role'] = players_df['player'].map(role_map)

In [72]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points,predicted_points,team,role
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000,2.192136,Mumbai Indians,bowler
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000,3.994608,Chennai Super Kings,batsman
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000,2.842853,Mumbai Indians,bowler
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000,1.514068,Chennai Super Kings,bowler
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667,1.896282,Mumbai Indians,batsman
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667,1.926756,Chennai Super Kings,bowler
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857,3.944627,Mumbai Indians,batsman
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000,1.659244,Chennai Super Kings,bowler
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000,2.916713,Mumbai Indians,batsman
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714,1.216622,Chennai Super Kings,batsman
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778,5.716620,Chennai Super Kings,batsman
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333,3.969153,Chennai Super Kings,batsman
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154,2.660113,Chennai Super Kings,bowler
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273,24.383979,Mumbai Indians,batsman
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000,1.760231,Mumbai Indians,bowler
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529,2.237919,Mumbai Indians,batsman
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667,4.285958,Mumbai Indians,batsman
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692,3.247537,Chennai Super Kings,batsman
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545,4.321879,Mumbai Indians,bowler
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053,17.527844,Chennai Super Kings,batsman
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571,4.561507,Chennai Super Kings,batsman
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889,3.492532,Mumbai Indians,batsman

In [73]:
player_stats = historical_data.groupby('player').agg({
    'batting_contribution_ratio': 'mean',
    'bowling_contribution_ratio': 'mean'
}).reset_index()

In [74]:
def assign_role(row):
    bat = row['batting_contribution_ratio']
    bowl = row['bowling_contribution_ratio']
    
    # All-rounder: contributes in BOTH
    if bat > 0.25 and bowl > 0.25:
        return 'AR'
    
    # Pure batsman
    elif bat >= bowl:
        return 'BAT'
    
    # Pure bowler
    else:
        return 'BOWL'

In [75]:
player_stats

               player  batting_contribution_ratio  bowling_contribution_ratio
0      AB de Villiers                    1.000000                    0.000000
1       Aakash Chopra                    1.000000                    0.000000
2         Aaron Finch                    0.985597                    0.014403
3     Aavishkar Salvi                    0.000000                    0.857143
4        Abdul Basith                    1.000000                    0.000000
..                ...                         ...                         ...
752      Yusuf Pathan                    0.849483                    0.138247
753      Yuvraj Singh                    0.829905                    0.139560
754  Yuzvendra Chahal                   -0.002716                    0.904450
755       Zaheer Khan                    0.075727                    0.782859
756    Zeeshan Ansari                    0.000000                    0.800000

[757 rows x 3 columns]

In [76]:
player_stats['role'] = player_stats.apply(assign_role, axis=1)

In [77]:
player_stats.head(50)

,player,batting_contribution_ratio,bowling_contribution_ratio,role
0,AB de Villiers,1.000000,0.000000,BAT
1,Aakash Chopra,1.000000,0.000000,BAT
2,Aaron Finch,0.985597,0.014403,BAT
3,Aavishkar Salvi,0.000000,0.857143,BOWL
4,Abdul Basith,1.000000,0.000000,BAT
5,Abdul Samad,0.972791,0.027209,BAT
6,Abdur Razzak,0.250000,0.750000,BOWL
7,Abhimanyu Mithun,0.212625,0.662375,BOWL
8,Abhinav Manohar,1.000000,0.000000,BAT
9,Abhinav Mukund,1.000000,0.000000,BAT
10,Abhishek Jhunjhunwala,0.804639,0.028695,BAT
11,Abhishek Nayar,0.824043,0.175957,BAT
12,Abhishek Raut,0.944444,0.000000,BAT
13,Abhishek Sharma,0.866969,0.094070,BAT
14,Abishek Porel,1.000000,0.000000,BAT
15,Abrar Kazi,0.000000,1.000000,BOWL
16,Abu Nechim,0.015241,0.749464,BOWL
17,Adam Gilchrist,0.990044,0.009956,BAT
18,Adam Milne,0.241643,0.658357,BOWL
19,Adam Voges,0.871094,0.128906,BAT
20,Adam Zampa,0.328824,0.534813,AR
21,Adil Rashid,0.356808,0.643192,AR
22,Aditya Dole,0.228630,0.771370,BOWL
23,Aditya Tare,1.000000,0.000000,BAT
24,Adrian Barath,1.000000,0.000000,BAT
25,Aiden Blizzard,1.000000,0.000000,BAT
26,Aiden Markram,0.951898,0.048102,BAT
27,Ajantha Mendis,0.050000,0.850000,BOWL
28,Ajinkya Rahane,0.994696,0.005304,BAT
29,Ajit Agarkar,0.401009,0.552479,AR
30,Ajit Chandila,0.035494,0.797840,BOWL
31,Akash Deep,0.212379,0.716192,BOWL
32,Akash Madhwal,0.061300,0.879876,BOWL
33,Akash Singh,0.000000,0.900000,BOWL
34,Akeal Hosein,0.500000,0.500000,AR
35,Akila Dananjaya,4.000000,-4.000000,BAT
36,Akshath Bilakhia,1.000000,0.000000,BAT
37,Akshath Reddy,1.000000,0.000000,BAT
38,Akshdeep Nath,1.000000,0.000000,BAT
39,Albie Morkel,0.382309,0.573246,AR
40,Alex Carey,1.000000,0.000000,BAT
41,Alex Hales,1.000000,0.000000,BAT
42,Alfonso Thomas,0.188199,0.745134,BOWL
43,Ali Murtaza,0.556548,0.193452,BAT
44,Alzarri Joseph,0.006185,0.902905,BOWL
45,Aman Hakim Khan,1.000000,0.000000,BAT
46,Ambati Rayudu,1.000000,0.000000,BAT
47,Amit Mishra,0.150921,0.757054,BOWL
48,Amit Paunikar,1.000000,0.000000,BAT
49,Amit Uniyal,-1.018519,2.018519,BOWL

In [78]:
players_df = players_df.drop(columns = ['role'])

In [79]:
role_map = dict(zip(player_stats['player'], player_stats['role']))
players_df['role'] = players_df['player'].map(role_map).fillna('BAT')

In [80]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points,predicted_points,team,role
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000,2.192136,Mumbai Indians,BOWL
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000,3.994608,Chennai Super Kings,BAT
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000,2.842853,Mumbai Indians,AR
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000,1.514068,Chennai Super Kings,AR
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667,1.896282,Mumbai Indians,BAT
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667,1.926756,Chennai Super Kings,BOWL
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857,3.944627,Mumbai Indians,BAT
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000,1.659244,Chennai Super Kings,BOWL
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000,2.916713,Mumbai Indians,BAT
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714,1.216622,Chennai Super Kings,AR
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778,5.716620,Chennai Super Kings,BAT
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333,3.969153,Chennai Super Kings,BAT
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154,2.660113,Chennai Super Kings,BOWL
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273,24.383979,Mumbai Indians,BAT
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000,1.760231,Mumbai Indians,BOWL
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529,2.237919,Mumbai Indians,BAT
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667,4.285958,Mumbai Indians,BAT
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692,3.247537,Chennai Super Kings,BAT
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545,4.321879,Mumbai Indians,BOWL
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053,17.527844,Chennai Super Kings,BAT
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571,4.561507,Chennai Super Kings,AR
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889,3.492532,Mumbai Indians,BAT

In [81]:
role_constraints = {
    'WK': (1, 4),
    'BAT': (3, 6),
    'AR': (1, 4),
    'BOWL': (3, 6)
}

MAX_PLAYERS = 11
MAX_PER_TEAM = 7

In [82]:
players_df = players_df.sort_values(by='predicted_points', ascending=False)

In [83]:
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points,predicted_points,team,role
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273,24.383979,Mumbai Indians,BAT
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053,17.527844,Chennai Super Kings,BAT
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778,5.716620,Chennai Super Kings,BAT
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571,4.561507,Chennai Super Kings,AR
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545,4.321879,Mumbai Indians,BOWL
16,1473510,Suryakumar Yadav,62.0,Wankhede Stadium,2025,154,80.333333,167.090055,0.0,22.025490,3.255319,8.633333,3.0,0,0,77.63,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,52.100000,1.035196,4044.523000,1.000000,0.000000,0.690324,32.666667,4.285958,Mumbai Indians,BAT
1,1426306,Daryl Mitchell,20.0,Wankhede Stadium,2024,15,52.000000,154.983925,0.0,35.725652,1.144836,11.100000,3.0,0,1,51.73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,18.000000,1.035196,931.140000,1.023810,-0.023810,0.485810,26.000000,3.994608,Chennai Super Kings,BAT
11,1473504,Shivam Dube,31.0,Wankhede Stadium,2025,76,38.666667,173.541667,0.0,23.249612,1.630135,0.766667,4.0,0,1,35.21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,33.083333,1.035196,1164.864167,1.133333,-0.133333,0.598827,32.833333,3.969153,Chennai Super Kings,BAT
6,1473503,Tim David,1.0,Wankhede Stadium,2025,44,21.000000,216.000000,0.0,28.233353,1.229043,-13.700000,6.0,0,1,29.21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,36.857143,1.035196,1076.597143,1.000000,0.000000,0.315789,16.142857,3.944627,Mumbai Indians,BAT
21,1473510,Rohit Sharma,9.0,Wankhede Stadium,2025,269,48.000000,122.201587,0.0,41.678665,1.223648,-3.000000,4.0,0,0,47.82,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,40.988372,1.035196,1960.063953,1.000000,0.000000,0.608025,40.138889,3.492532,Mumbai Indians,BAT
17,1473505,Ajinkya Rahane,18.0,Wankhede Stadium,2025,183,49.000000,139.011544,0.0,22.192091,2.090835,2.600000,1.0,0,0,48.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,44.071429,1.035196,2118.954286,1.000000,0.000000,0.638889,38.807692,3.247537,Chennai Super Kings,BAT
8,1473510,Tilak Varma,58.0,Wankhede Stadium,2025,51,25.333333,114.454545,0.0,29.533597,1.127529,-7.966667,5.0,0,0,24.41,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,33.947368,1.035196,828.655263,1.000000,0.000000,0.391515,50.200000,2.916713,Mumbai Indians,BAT
2,1473511,Romario Shepherd,43.0,Wankhede Stadium,2025,17,38.666667,81.538462,0.8,32.348965,0.701723,15.966667,7.0,0,0,38.37,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,21.000000,1.035196,805.770000,0.155039,0.844961,0.196078,43.000000,2.842853,Mumbai Indians,AR
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154,2.660113,Chennai Super Kings,BOWL
15,1473510,Hardik Pandya,63.0,Wankhede Stadium,2025,151,19.000000,141.961353,0.2,28.981987,0.786696,-3.800000,4.0,0,0,22.62,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,44.280000,1.035196,1001.613600,0.959611,0.040389,0.751360,34.823529,2.237919,Mumbai Indians,BAT
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000,2.192136,Mumbai Indians,BOWL
5,1473504,Matheesha Pathirana,41.0,Wankhede Stadium,2025,32,25.666667,0.000000,1.0,32.434549,0.832446,-1.333333,11.0,0,1,25.96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,58.000000,1.035196,1505.680000,0.000000,0.666667,0.000000,69.666667,1.926756,Chennai Super Kings,BOWL
4,1473511,Nehal Wadhera,17.0,Wankhede Stadium,2025,31,30.333333,128.719064,0.0,31.959002,1.045089,-3.066667,4.0,0,1,33.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,23.833333,1.035196,809.380000,1.000000,0.000000,0.494444,35.666667,1.896282,Mumbai Indians,BAT
14,1473510,Jasprit Bumrah,-2.0,Wankhede Stadium,2025,147,57.666667,0.000000,1.8,36.347704,1.579192,0.266667,10.0,0,0,58.88,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,43.306122,1.035196,2549.864490,-0.000000,1.000000,0.000000,26.125000,1.760231,Mumbai Indians,BOWL
7,1473500,Tushar Deshpande,33.0,Wankhede Stadium,2025,46,24.000000,10.000000,0.6,28.523674,0.750254,2.600000,10.0,0,1,20.38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,29.666667,1.035196,604.606667,-0.066667,1.066667,0.000000,47.000000,1.659244,Chennai Super Kings,BOWL
3,1473510,Mitchell Santner,6.0,Wankhede Stadium,2025,31,60.333333,20.000000,1.4,31.582168,1.111387,25.233333,8.0,0,0,53.75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,32.111111,1.035196,1725.972222,0.310196,0.689804,0.000000,66.000000,1.514068,Chennai Super Kings,AR
9,1473494,Moeen Ali,29.0,Wankhede Stadium,2025,70,33.000000,23.717949,1.0,28.429445,1.150216,0.300000,3.0,0,1,33.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,86.750000,1.035196,2886.172500,0.333333,0.666667,0.000000,65.285714,1.216622,Chennai Super Kings,AR

In [84]:
selected = []

for role, (min_req, _) in role_constraints.items():
    role_players = players_df[players_df['role'] == role].head(min_req)
    selected.append(role_players)

selected_df = pd.concat(selected)

In [85]:
selected_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,last10_std_points,player_consistency_index,form_momentum,bat_pos,player_role_wicketkeeper,team_won_toss,recent_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,venue_avg_points,venue_run_factor,venue_form,batting_contribution_ratio,bowling_contribution_ratio,boundary_percentage,opponent_avg_points,predicted_points,team,role
13,1473505,Ishan Kishan,37.0,Wankhede Stadium,2025,114,70.000000,110.343137,0.0,42.744850,0.741610,38.300000,2.0,1,1,61.61,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,38.333333,1.035196,2361.716667,1.000000,0.000000,0.687119,40.727273,24.383979,Mumbai Indians,BAT
19,1473500,MS Dhoni,18.0,Wankhede Stadium,2025,241,25.000000,129.222222,0.0,23.333571,1.229987,-3.700000,5.0,1,0,22.91,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False,26.791667,1.035196,613.797083,1.000000,0.000000,0.409314,32.921053,17.527844,Chennai Super Kings,BAT
10,1473459,Ruturaj Gaikwad,1.0,Wankhede Stadium,2025,70,34.000000,94.405594,0.0,47.301045,1.088771,-17.500000,1.0,0,0,36.77,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,39.272727,1.035196,1444.058182,1.000000,0.000000,0.446561,48.777778,5.716620,Chennai Super Kings,BAT
20,1473504,Ravindra Jadeja,78.0,Wankhede Stadium,2025,247,56.000000,129.261438,0.6,37.372598,1.300418,7.400000,6.0,0,1,54.84,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,50.043478,1.035196,2744.384348,0.214910,0.785090,0.404344,35.228571,4.561507,Chennai Super Kings,AR
18,1426305,Piyush Chawla,87.0,Wankhede Stadium,2024,194,57.666667,60.000000,1.4,28.743308,1.015889,28.466667,8.0,0,1,50.18,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,32.736842,1.035196,1642.734737,0.006536,0.993464,0.000000,32.454545,4.321879,Mumbai Indians,BOWL
12,1473506,Deepak Chahar,12.0,Wankhede Stadium,2025,95,30.666667,40.000000,1.0,23.542161,0.836797,10.966667,9.0,0,0,29.67,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,27.411765,1.035196,813.307059,0.093750,0.906250,0.166667,30.846154,2.660113,Chennai Super Kings,BOWL
0,1473509,Gerald Coetzee,2.0,Wankhede Stadium,2025,14,26.333333,100.857143,0.6,34.325889,1.031292,-9.066667,9.0,0,0,26.96,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,35.333333,1.035196,952.586667,1.113636,-0.113636,0.544444,17.500000,2.192136,Mumbai Indians,BOWL

In [86]:
# historical_data[historical_data['season'] >= 2022]

In [87]:
historical_data['season'] = historical_data['season'].str[:4].astype(int)
historical_data['season'].unique()

array([2012, 2013, 2015, 2016, 2022, 2023, 2024, 2025, 2007, 2009, 2017,
       2018, 2011, 2014, 2019, 2020, 2021])

In [88]:
# historical_data[(historical_data['season'] >= 2022) & (historical_data['team'] == 'Mumbai Indians')].tail(50)

In [89]:
# pd.set_option("display.max_rows",None)

In [90]:
# historical_data[(historical_data['season'] >= 2022) & (historical_data['team'] == 'Mumbai Indians')]
# historical_data

In [91]:
historical_data['player'].unique()

array(['Ashish Reddy', 'Ayush Badoni', 'Ajit Chandila', 'Aakash Chopra',
       'Aniket Choudhary', 'Akila Dananjaya', 'Andrew Flintoff',
       'Anshul Kamboj', 'Anil Kumble', 'Abhinav Manohar', 'Ayush Mhatre',
       'Amit Mishra', 'Abhimanyu Mithun', 'Abhinav Mukund',
       'Ashish Nehra', 'André Nel', 'Anrich Nortje',
       'Angkrish Raghuvanshi', 'Anureet Singh', 'Andrew Symonds',
       'Anshuman Tomar', 'Amit Uniyal', 'Adam Zampa', 'Akshath Bilakhia',
       'Ankeet Chavan', 'Abhishek Jhunjhunwala', 'Abrar Kazi',
       'Arshin Kulkarni', 'Ashley Noffke', 'Ajit Agarkar',
       'Adrian Barath', 'Ashoke Dinda', 'Andrew McDonald',
       'AB de Villiers', 'Aiden Blizzard', 'Adam Gilchrist',
       'Alfonso Thomas', 'Adam Voges', 'Alex Hales',
       'Dimitri Mascarenhas', 'Angelo Mathews', 'Akshdeep Nath',
       'Andre Russell', 'Adam Milne', 'Ali Murtaza', 'Amit Paunikar',
       'Aaron Finch', 'Akeal Hosein', 'Ashton Turner', 'Andrew Tye',
       'Aiden Markram', 'Ashok Menaria', 'Abhishek Nayar',
       'Ajinkya Rahane', 'Aavishkar Salvi', 'Abu Nechim', 'Arindam Ghosh',
       'Aditya Dole', 'Anustup Majumdar', 'Aditya Tare', 'Ankit Bawne',
       'Axar Patel', 'Alzarri Joseph', 'Ankit Rajpoot', 'Abhishek Raut',
       'Anukul Roy', 'Suryakumar Yadav', 'Alex Carey', 'Ambati Rayudu',
       'Adil Rashid', 'Asad Pathan', 'Abdul Basith', 'Abdul Samad',
       'Abdur Razzak', 'Abhishek Sharma', 'Abishek Porel', 'Akash Deep',
       'Akash Madhwal', 'Akash Singh', 'Aman Hakim Khan', 'Anand Rajan',
       'Aniket Verma', 'Anirudh Singh', 'Ankit Sharma', 'Ankit Soni',
       'Anmolpreet Singh', 'Anuj Rawat', 'Arjun Tendulkar', 'Arshad Khan',
       'Arshad Khan (2)', 'Arshdeep Singh', 'Ashutosh Sharma',
       'Ashwani Kumar', 'Atharva Taide', 'Avesh Khan', 'Azhar Mahmood',
       'Azmatullah Omarzai', 'Balachandra Akhil', 'Bharat Chipli',
       'Brett Geeves', 'Baba Indrajith', 'Bhuvaneshwar Kumar',
       'Ben Laughlin', 'Brett Lee', 'Sai Sudharsan', 'Billy Stanlake',
       'Bodanapu Sumanth', 'Bhargav Bhatt', 'Ben Stokes',
       'Ajantha Mendis', 'Brendon McCullum', 'Biplab Samantray',
       'Barinder Sran', 'Ben Cutting', 'Beuran Hendricks', 'Brad Haddin',
       'Brad Hodge', 'Ben Rohrer', 'Jeevan Mendis', 'Ben Dunk',
       'Barafe Sharath', 'Ben Hilfenhaus', 'Basil Thampi', 'Bipul Sharma',
       'Corbin Bosch', 'Chandrasekar Ganapathy', 'Cameron Green',
       'Chandan Madan', 'Colin Munro', 'Chetan Nanda', 'Chetan Sakariya',
       'Colin de Grandhomme', 'Colin Ingram', 'Chris Lynn',
       'Cheteshwar Pujara', 'Chris Gayle', 'Chris Morris',
       'Corey Anderson', 'Junior Dala', 'Callum Ferguson', 'Chris Green',
       'Chris Jordan', 'Clint McKay', 'Chamara Kapugedera',
       'Charl Langeveldt', 'Cameron White', 'C. M. Gautam',
       'Carlos Brathwaite', 'Chris Woakes', 'Dilhara Fernando',
       'Varun Chakravarthy', 'Dewald Brevis', 'Donovan Ferreira',
       'Duan Jansen', 'Doddapaneni Kalyankrishna', 'Devdutt Padikkal',
       'Dwaine Pretorius', 'Dinesh Salunkhe', 'David Wiese',
       'Dillon du Preez', 'David Miller', 'David Warner',
       'Doug Bracewell', 'Debabrata Das', 'Dwaraka Ravi Teja',
       'Doug Bollinger', 'Darshan Nalkande', 'Dishant Yagnik',
       'Dwayne Bravo', 'Daniel Harris', 'Deepak Hooda', 'David Hussey',
       'Davy Jacobs', 'Dawid Malan', 'Daryl Mitchell',
       'Domnic Muthuswami', 'Dominic Thornely', 'David Willey',
       'Darren Sammy', "D'Arcy Short", 'Deepak Chahar', 'Daniel Vettori',
       'Darren Bravo', 'Nuwan Zoysa', 'Devon Conway', 'Dirk Nannes',
       'Doddapaneni Vijaykumar', 'Mahela Jayawardene', 'Damien Martyn',
       'Daniel Sams', 'Dhruv Shorey', 'Dwayne Smith', 'Dhawal Kulkarni',
       'Darren Lehmann', 'Dhruv Rathi', 'Dan Christian', 'Dinesh Patil',
       'Dale Steyn', 'Dhruv Jurel', 'Evin Lewis', 'Lasith Malinga',
       'Eoin Morgan', 'Eklavya Dwivedi', 'Farhaan Behardien',
       'Faf du Plessis', 'Fabian Allen', 'Fidel Edwards', 'Faiz Fazal',
       'Fazalhaq Farooqi', 'Gerald Coetzee', 'Gautam Gambhir',
       'Brad Hogg', 'Graeme Smith', 'Hardus Viljoen', 'Glenn McGrath',
       'Glenn Phillips', 'Hanuma Vihari', 'George Garton',
       'George Bailey', 'Glenn Maxwell', 'Graham Napier',
       'Gurinder Sandhu', 'Gagandeep Singh', 'Gulbadin Naib',
       'Gurkeerat Singh', 'Gurnoor Brar', 'Halhadar Das',
       'Heinrich Klaasen', 'Himanshu Sharma', 'Harry Brook',
       'Rassie van der Dussen', 'Harry Gurney', 'Herschelle Gibbs',
       'Hardik Pandya', 'Hashim Amla', 'Hrithik Shokeen', 'Harshal Patel',
       'Harbhajan Singh', 'Harmeet Singh', 'Harpreet Brar',
       'Harpreet Singh', 'Harsh Dubey', 'Harshit Rana', 'Ishan Malhotra',
       'Ishant Sharma', 'Isuru Udana', 'Ishwar Pandey', 'Ishan Porel',
       'Irfan Pathan', 'Ishank Jaggi', 'Ish Sodhi', 'Imran Tahir',
       'Iqbal Abdulla', 'Ishan Kishan', 'Jagadeesh Arunkumar',
       'Johan Botha', 'Jake Fraser-McGurk', 'Joshua Little',
       'Jamie Overton', 'Jagadeesha Suchith', 'Jamaluddin Syed Mohammad',
       'Juan Theron', 'Jayant Yadav', 'Albie Morkel', 'Jhye Richardson',
       'Jofra Archer', 'Jos Buttler', 'Jesse Ryder', 'Jaydev Unadkat',
       'Jacob Oram', 'Jimmy Neesham', 'Joe Root', 'Jerome Taylor',
       'James Franklin', 'Jacob Bethell', 'Jacques Kallis',
       'Jasprit Bumrah', 'Jason Roy', 'Johan van der Wath', 'Joe Denly',
       'James Pattinson', 'Jonny Bairstow', 'Justin Kemp',
       'Jitesh Sharma', 'Jason Holder', 'Jason Behrendorff', 'JP Duminy',
       'James Faulkner', 'Josh Inglis', 'Javon Searles', 'Josh Hazlewood',
       'James Hopes', 'Josh Philippe', 'John Hastings', 'Jalaj S Saxena',
       'Jaskaran Singh', 'Joginder Sharma', 'Karan Goel',
       'Krishnappa Gowtham', 'Kumar Kartikeya', 'Kulwant Khejroliya',
       'Kagiso Rabada', 'Krishmar Santokie', 'Krishnakumar Upadhyay',
       'Kuldeep Yadav', 'Kyle Jamieson', 'Keshav Maharaj',
       'Kieron Pollard', 'Kemar Roach', 'Arun Karthik', 'K. C. Cariappa',
       'Kumar Sangakkara', 'Dinesh Karthik', 'Krunal Pandya',
       'Kyle Abbott', 'Khaleel Ahmed', 'Kevon Cooper', 'Karun Nair',
       'Kamlesh Nagarkoti', 'KL Rahul', 'KM Asif', 'Kedar Jadhav',
       'Keemo Paul', 'Nuwan Kulasekara', 'Kotarangada Appanna',
       'Kevin Pietersen', 'Kyle Mayers', 'Kuldeep Sen', 'Srikar Bharat',
       'Kunal Singh Rathore', 'Karn Sharma', 'Kane Williamson',
       'Kwena Maphaka', 'Kane Richardson', 'Kamran Akmal', 'Kamran Khan',
       'Karanveer Singh', 'Karim Janat', 'Kartik Tyagi', 'Kumar Kushagra',
       'Love Ablish', 'Lakshmipathy Balaji', 'Lungi Ngidi', 'Luke Ronchi',
       'Luke Wood', 'Lee Carseldine', 'Luke Pomersbach',
       'Lizaad Williams', 'Liam Plunkett', 'Lockie Ferguson',
       'Lukman Meriwala', 'Luke Wright', 'Lendl Simmons', 'Chamara Silva',
       'Laxmi Ratan Shukla', 'Ross Taylor', 'Liam Livingstone',
       'Lalit Yadav', 'Liton Das', 'Murugan Ashwin', 'Marco Jansen',
       'Mohammad Kaif', 'Murali Kartik', 'Michael Klinger',
       'Mithun Manhas', 'Mayank Markande', 'Morne Morkel',
       'Muttiah Muralitharan', 'Makhaya Ntini', 'Matheesha Pathirana',
       'Prasidh Krishna', 'Mahesh Rawat', 'Shahrukh Khan',
       'Manimaran Siddharth', 'Maheesh Theekshana', 'Manoj Tiwary',
       'Murali Vijay', 'Manan Vohra', 'Marchant de Lange',
       'Mayank Agarwal', 'Musavir Khote', 'Mitchell Starc', 'Mark Wood',
       'Mohnish Parmar', 'Moises Henriques', 'Manpreet Juneja',
       'Mohnish Mishra', 'Dasun Shanaka', 'Kusal Perera',
       'Michael Hussey', 'Farveez Maharoof', 'Michael Bracewell',
       'Mitchell Johnson', 'Michael Neser', 'Michael Clarke',
       'Martin Guptill', 'Matt Henry', 'Michael Lumb',
       'Mitchell McClenaghan', 'Mitchell Owen', 'Mitchell Santner',
       'Manav Suthar', 'Mahipal Lomror', 'Manish Pandey',
       'Matthew Hayden', 'Moeen Ali', 'Munaf Patel', 'Mohit Sharma',
       'Marlon Samuels', 'Morne van Wyk', 'Matthew Breetzke',
       'Marcus Stoinis', 'Mayank Yadav', 'Mitchell Marsh',
       'Manoj Bhandage', 'Manvinder Bisla', 'MS Dhoni', 'Manpreet Gony',
       'Matthew Wade', 'Mark Boucher', 'Matthew Short', 'Mandeep Singh',
       'Mashrafe Mortaza', 'Mayank Dagar', 'Misbah-ul-Haq',
       'Mohammad Ashraful', 'Mohammad Asif', 'Mohammad Hafeez',
       'Mohammad Nabi', 'Mohammed Shami', 'Mohammed Siraj',
       'Mohit Rathee', 'Mohsin Khan', 'Monu Kumar', 'Mujeeb Ur Rahman',
       'Mukesh Choudhary', 'Mukesh Kumar', 'Musheer Khan',
       'Mustafizur Rahman', 'Nandre Burger', 'Narayan Jagadeesan',
       'Nicholas Pooran', 'Nitish Rana', 'Navdeep Saini',
       'Nuwan Thushara', 'Nehal Wadhera', 'Nikhil Singh', 'Nayan Doshi',
       'Nic Maddinson', 'Nathan Rimmington', 'Niraj Patel',
       'Nathan McCullum', 'Thisara Perera', 'Nathan Coulter-Nile',
       'Nikhil Naik', 'Nathan Ellis', 'Naman Ojha', 'Naman Dhir',
       'Naveen-ul-Haq', 'Nithish Kumar Reddy', 'Noor Ahmad',
       'Oshane Thomas', 'Owais Shah', 'Obed McCoy', 'Odean Smith',
       'Palani Amarnath', 'Parvinder Awana', 'Prashant Chopra',
       'Paras Dogra', 'Praveen Dubey', 'Praveen Kumar', 'Pawan Negi',
       'Prasanth Parameswaran', 'Padmanabhan Prasanth',
       'Prayas Ray Barman', 'Pardeep Sahu', 'Prabhsimran Singh',
       'Pawan Suyal', 'Parthiv Patel', 'Akshath Reddy',
       'Bhanuka Rajapaksa', 'Paul Valthaty', 'Paul Collingwood',
       'Phil Salt', 'Prashant Solanki', 'Kamindu Mendis', 'Pat Cummins',
       'Pradeep Sangwan', 'Priyam Garg', 'Sarvesh Kumar', 'Prerak Mankad',
       'Piyush Chawla', 'Pragyan Ojha', 'Prithvi Shaw', 'Pinal Shah',
       'Peter Handscomb', 'Pravin Tambe', 'Dushmantha Chameera',
       'Venugopal Rao', 'Wiaan Mulder', 'Wanindu Hasaranga',
       'Pankaj Singh', 'Parvez Rasool', 'Prince Yadav', 'Priyansh Arya',
       'Quinton de Kock', 'Ravichandran Ashwin', 'Rajat Bhatia',
       'Ravi Bishnoi', 'Rishi Dhawan', 'Rahul Dravid', 'Ravi Goyal',
       'Ryan McLaren', 'Robin Minz', 'Ryan Ninan', 'Riyan Parag',
       'Rovman Powell', 'Ravi Rampaul', 'Rachin Ravindra',
       'Ravisrinivasan Sai Kishore', 'Sanjay Yadav', 'Rajagopal Sathish',
       'Rahul Sharma', 'Romario Shepherd', 'Rahul Shukla',
       'Rahul Tewatia', 'Vinay Kumar', 'Raj Bawa', 'Ravindra Jadeja',
       'Rahil Shaikh', 'Rahul Tripathi', 'Rahul Chahar',
       'Ruturaj Gaikwad', 'Ryan Rickelton', 'Richard Levi',
       'Roelof van der Merwe', 'Ronit More', 'Rohit Sharma',
       'Richard Gleeson', 'Ryan Harris', 'Robin Peterson', 'Rob Quiney',
       'Reece Topley', 'Ricky Bhui', 'Rinku Singh', 'Rajat Patidar',
       'Ryan ten Doeschate', 'Riley Meredith', 'R. P. Singh',
       'Raju Bhatkal', 'Ranadeb Bose', 'Rishabh Pant', 'Ramesh Powar',
       'Rohan Raje', 'Rilee Rossouw', 'Ramnaresh Sarwan', 'Ravi Bopara',
       'Rohan Gavaskar', 'Rajvardhan Hangargekar', 'Reetinder Sodhi',
       'Ricky Ponting', 'Raiphi Gomez', 'Ripal Patel', 'Robin Uthappa',
       'Ray Price', 'Rahmanullah Gurbaz', 'Ramandeep Singh',
       'Rashid Khan', 'Rasikh Salam', 'Anirudha Srikkanth',
       'Sreenath Aravind', 'Samuel Badree', 'Subramaniam Badrinath',
       'Shivnarine Chanderpaul', 'Shikhar Dhawan', 'Shivam Dube',
       'Shreyas Gopal', 'Shamar Joseph', 'Siddharth Kaul',
       'Shivil Kaushik', 'Sarabjit Ladda', 'Sandeep Lamichhane',
       'Sudhesan Midhun', 'Shahbaz Nadeem', 'Sumit Narwal', 'Sachin Rana',
       'Suraj Randiv', 'Sandeep Warrier', 'Sunny Sohal', 'Sreesanth',
       'Sridharan Sriram', 'Sudeep Tyagi', 'Vidyut Sivaramakrishnan',
       'Sean Abbott', 'Swapnil Asnodkar', 'Sanjay Bangar', 'Shivam Dubey',
       'Shadab Jakati', 'Sunil Joshi', 'Scott Styris', 'Shrikant Wagh',
       'Sourav Ganguly', 'Scott Kuggeleijn', 'Siddharth Chitnis',
       'Shai Hope', 'Siddhesh Lad', 'Shane Bond', 'Shaun Marsh',
       'Sherfane Rutherford', 'Spencer Johnson', 'Shalabh Srivastava',
       'Suresh Raina', 'Shaik Rasheed', 'Siddharth Trivedi',
       'Shane Warne', 'Scott Boland', 'Sam Curran', 'Shane Harwood',
       'Simon Katich', 'Shaun Pollock', 'Sachithra Senanayake',
       'Sarfaraz Khan', 'Shardul Thakur', 'Shimron Hetmyer',
       'Stephen Fleming', 'Shreevats Goswami', 'Sheldon Jackson',
       'Sunil Narine', 'Steve Smith', 'Sachin Tendulkar', 'Shane Watson',
       'Shubham Agarwal', 'Sheldon Cottrell', 'Shreyas Iyer',
       'Shrikant Mundhe', 'Suyash Prabhudessai', 'Soumya Sarkar',
       'Sufiyan Shaikh', 'Saurabh Tiwary', 'Sisanda Magala',
       'Sanath Jayasuriya', 'Stuart Binny', 'Sanju Samson',
       'Sam Billings', 'Shaun Tait', 'Shams Mulani', 'Sachin Baby',
       'Salman Butt', 'Sameer Rizvi', 'Sandeep Sharma', 'Sanvir Singh',
       'Saurav Chauhan', 'Sediqullah Atal', 'Shahbaz Ahmed',
       'Shahid Afridi', 'Shakib Al Hasan', 'Shashank Singh',
       'Shivam Mavi', 'Shivam Sharma', 'Shivam Singh', 'Shoaib Ahmed',
       'Shoaib Akhtar', 'Shoaib Malik', 'Shubman Gill', 'Sikandar Raza',
       'Simarjeet Singh', 'Sohail Tanvir', 'Sumit Kumar', 'Sunny Gupta',
       'Sunny Singh', 'Suryansh Shedge', 'Suyash Sharma', 'Swapnil Singh',
       'Tom Banton', 'Tyron Henderson', 'Tom Kohler-Cadmore',
       'Taruwar Kohli', 'T. Natarajan', 'Tabraiz Shamsi',
       'Tristan Stubbs', 'Tatenda Taibu', 'Thilan Thushara',
       'Trent Boult', 'Tim Paine', 'Tim Southee', 'Tim David',
       'Tom Curran', 'Tim Seifert', 'Tirumalasetti Suman',
       'Tillakaratne Dilshan', 'Travis Head', 'Tanmay Srivastava',
       'T. P. Sudhindra', 'Travis Birt', 'Tymal Mills',
       'Tushar Deshpande', 'Tanush Kotian', 'Tejas Baroka', 'Tilak Varma',
       'Uday Kaul', 'Udit Birla', 'Unmukt Chand', 'Usman Khawaja',
       'Umesh Yadav', 'Umar Gul', 'Umran Malik', 'Urvil Patel',
       'Vidwath Kaverappa', 'Virat Kohli', 'Vikas Nigam',
       'Vishwa Pratap Singh', 'Vyshak Vijaykumar', 'Virender Sehwag',
       'Vijay Shankar', 'Vaibhav Suryavanshi', 'Vijayakanth Viyaskanth',
       'Vaibhav Arora', 'Vijay Zol', 'Varun Aaron', 'Venkatesh Iyer',
       'V. R. V. Singh', 'Vikramjeet Malik', 'Vinayak Yeligati',
       'V. V. S. Laxman', 'V. Y. Mahesh', 'Vijaykumar Vyshak',
       'Virat Singh', 'Vishnu Vinod', 'Vivrant Sharma', 'Wasim Jaffer',
       "William O'Rourke", 'Wilkin Mota', 'Wayne Parnell', 'Will Jacks',
       'Wriddhiman Saha', 'Chaminda Vaas', 'Washington Sundar',
       'Xavier Thalaivan Sargunam', 'Xavier Bartlett',
       'Yalaka Gnaneswara Rao', 'Yogesh Nagar', 'Yarra Prithvi Raj',
       'Yalaka Venugopal Rao', 'Yusuf Abdulla', 'Yashasvi Jaiswal',
       'Yusuf Pathan', 'Yuzvendra Chahal', 'Yash Dhull',
       'Yogesh Takawale', 'Yash Dayal', 'Yash Thakur', 'Yashpal Singh',
       'Younis Khan', 'Yudhvir Singh', 'Yuvraj Singh', 'Zaheer Khan',
       'Zeeshan Ansari'], dtype=object)

In [92]:
player_mapping = {
    'A Ashish Reddy': 'Ashish Reddy',
    'A Badoni': 'Ayush Badoni',
    'A Chandila': 'Ajit Chandila',
    'A Chopra': 'Aakash Chopra',
    'A Choudhary': 'Aniket Choudhary',
    'A Dananjaya': 'Akila Dananjaya',
    'A Flintoff': 'Andrew Flintoff',
    'A Kamboj': 'Anshul Kamboj',
    'A Kumble': 'Anil Kumble',
    'A Manohar': 'Abhinav Manohar',
    'A Mhatre': 'Ayush Mhatre',
    'A Mishra': 'Amit Mishra',
    'A Mithun': 'Abhimanyu Mithun',
    'A Mukund': 'Abhinav Mukund',
    'A Nehra': 'Ashish Nehra',
    'A Nel': 'André Nel',
    'A Nortje': 'Anrich Nortje',
    'A Raghuvanshi': 'Angkrish Raghuvanshi',
    'A Singh': 'Anureet Singh',
    'A Symonds': 'Andrew Symonds',
    'A Tomar': 'Anshuman Tomar',
    'A Uniyal': 'Amit Uniyal',
    'A Zampa': 'Adam Zampa',
    'AA Bilakhia': 'Akshath Bilakhia',
    'AA Chavan': 'Ankeet Chavan',
    'AA Jhunjhunwala': 'Abhishek Jhunjhunwala',
    'AA Kazi': 'Abrar Kazi',
    'AA Kulkarni': 'Arshin Kulkarni',
    'AA Noffke': 'Ashley Noffke',
    'AB Agarkar': 'Ajit Agarkar',
    'AB Barath': 'Adrian Barath',
    'AB Dinda': 'Ashoke Dinda',
    'AB McDonald': 'Andrew McDonald',
    'AB de Villiers': 'AB de Villiers',
    'AC Blizzard': 'Aiden Blizzard',
    'AC Gilchrist': 'Adam Gilchrist',
    'AC Thomas': 'Alfonso Thomas',
    'AC Voges': 'Adam Voges',
    'AD Hales': 'Alex Hales',
    'AD Mascarenhas': 'Dimitri Mascarenhas',
    'AD Mathews': 'Angelo Mathews',
    'AD Nath': 'Akshdeep Nath',
    'AD Russell': 'Andre Russell',
    'AF Milne': 'Adam Milne',
    'AG Murtaza': 'Ali Murtaza',
    'AG Paunikar': 'Amit Paunikar',
    'AJ Finch': 'Aaron Finch',
    'AJ Hosein': 'Akeal Hosein',
    'AJ Turner': 'Ashton Turner',
    'AJ Tye': 'Andrew Tye',
    'AK Markram': 'Aiden Markram',
    'AL Menaria': 'Ashok Menaria',
    'AM Nayar': 'Abhishek Nayar',
    'AM Rahane': 'Ajinkya Rahane',
    'AM Salvi': 'Aavishkar Salvi',
    'AN Ahmed': 'Abu Nechim',
    'AN Ghosh': 'Arindam Ghosh',
    'AP Dole': 'Aditya Dole',
    'AP Majumdar': 'Anustup Majumdar',
    'AP Tare': 'Aditya Tare',
    'AR Bawne': 'Ankit Bawne',
    'AR Patel': 'Axar Patel',
    'AS Joseph': 'Alzarri Joseph',
    'AS Rajpoot': 'Ankit Rajpoot',
    'AS Raut': 'Abhishek Raut',
    'AS Roy': 'Anukul Roy',
    'AS Yadav': 'Suryakumar Yadav',
    'AT Carey': 'Alex Carey',
    'AT Rayudu': 'Ambati Rayudu',
    'AU Rashid': 'Adil Rashid',
    'AUK Pathan': 'Asad Pathan',
    'B Akhil': 'Balachandra Akhil',
    'B Chipli': 'Bharat Chipli',
    'B Geeves': 'Brett Geeves',
    'B Indrajith': 'Baba Indrajith',
    'B Kumar': 'Bhuvaneshwar Kumar',
    'B Laughlin': 'Ben Laughlin',
    'B Lee': 'Brett Lee',
    'B Sai Sudharsan': 'Sai Sudharsan',
    'B Stanlake': 'Billy Stanlake',
    'B Sumanth': 'Bodanapu Sumanth',
    'BA Bhatt': 'Bhargav Bhatt',
    'BA Stokes': 'Ben Stokes',
    'BAW Mendis': 'Ajantha Mendis',
    'BB McCullum': 'Brendon McCullum',
    'BB Samantray': 'Biplab Samantray',
    'BB Sran': 'Barinder Sran',
    'BCJ Cutting': 'Ben Cutting',
    'BE Hendricks': 'Beuran Hendricks',
    'BJ Haddin': 'Brad Haddin',
    'BJ Hodge': 'Brad Hodge',
    'BJ Rohrer': 'Ben Rohrer',
    'BKG Mendis': 'Jeevan Mendis',
    'BMAJ Mendis': 'Jeevan Mendis',
    'BR Dunk': 'Ben Dunk',
    'BR Sharath': 'Barafe Sharath',
    'BW Hilfenhaus': 'Ben Hilfenhaus',
    'C Bosch': 'Corbin Bosch',
    'C Ganapathy': 'Chandrasekar Ganapathy',
    'C Green': 'Cameron Green',
    'C Madan': 'Chandan Madan',
    'C Munro': 'Colin Munro',
    'C Nanda': 'Chetan Nanda',
    'C Sakariya': 'Chetan Sakariya',
    'C de Grandhomme': 'Colin de Grandhomme',
    'CA Ingram': 'Colin Ingram',
    'CA Lynn': 'Chris Lynn',
    'CA Pujara': 'Cheteshwar Pujara',
    'CH Gayle': 'Chris Gayle',
    'CH Morris': 'Chris Morris',
    'CJ Anderson': 'Corey Anderson',
    'CJ Dala': 'Junior Dala',
    'CJ Ferguson': 'Callum Ferguson',
    'CJ Green': 'Chris Green',
    'CJ Jordan': 'Chris Jordan',
    'CJ McKay': 'Clint McKay',
    'CK Kapugedera': 'Chamara Kapugedera',
    'CK Langeveldt': 'Charl Langeveldt',
    'CL White': 'Cameron White',
    'CM Gautam': 'C. M. Gautam',
    'CR Brathwaite': 'Carlos Brathwaite',
    'CR Woakes': 'Chris Woakes',
    'CRD Fernando': 'Dilhara Fernando',
    'CV Varun': 'Varun Chakravarthy',
    'D Brevis': 'Dewald Brevis',
    'D Ferreira': 'Donovan Ferreira',
    'D Jansen': 'Duan Jansen',
    'D Kalyankrishna': 'Doddapaneni Kalyankrishna',
    'D Padikkal': 'Devdutt Padikkal',
    'D Pretorius': 'Dwaine Pretorius',
    'D Salunkhe': 'Dinesh Salunkhe',
    'D Wiese': 'David Wiese',
    'D du Preez': 'Dillon du Preez',
    'DA Miller': 'David Miller',
    'DA Warner': 'David Warner',
    'DAJ Bracewell': 'Doug Bracewell',
    'DB Das': 'Debabrata Das',
    'DB Ravi Teja': 'Dwaraka Ravi Teja',
    'DE Bollinger': 'Doug Bollinger',
    'DG Nalkande': 'Darshan Nalkande',
    'DH Yagnik': 'Dishant Yagnik',
    'DJ Bravo': 'Dwayne Bravo',
    'DJ Harris': 'Daniel Harris',
    'DJ Hooda': 'Deepak Hooda',
    'DJ Hussey': 'David Hussey',
    'DJ Jacobs': 'Davy Jacobs',
    'DJ Malan': 'Dawid Malan',
    'DJ Mitchell': 'Daryl Mitchell',
    'DJ Muthuswami': 'Domnic Muthuswami',
    'DJ Thornely': 'Dominic Thornely',
    'DJ Willey': 'David Willey',
    'DJG Sammy': 'Darren Sammy',
    'DJM Short': "D'Arcy Short",
    'DL Chahar': 'Deepak Chahar',
    'DL Vettori': 'Daniel Vettori',
    'DM Bravo': 'Darren Bravo',
    'DNT Zoysa': 'Nuwan Zoysa',
    'DP Conway': 'Devon Conway',
    'DP Nannes': 'Dirk Nannes',
    'DP Vijaykumar': 'Doddapaneni Vijaykumar',
    'DPMD Jayawardene': 'Mahela Jayawardene',
    'DR Martyn': 'Damien Martyn',
    'DR Sams': 'Daniel Sams',
    'DR Shorey': 'Dhruv Shorey',
    'DR Smith': 'Dwayne Smith',
    'DS Kulkarni': 'Dhawal Kulkarni',
    'DS Lehmann': 'Darren Lehmann',
    'DS Rathi': 'Dhruv Rathi',
    'DT Christian': 'Dan Christian',
    'DT Patil': 'Dinesh Patil',
    'DW Steyn': 'Dale Steyn',
    'E Lewis': 'Evin Lewis',
    'E Malinga': 'Lasith Malinga',
    'EJG Morgan': 'Eoin Morgan',
    'ER Dwivedi': 'Eklavya Dwivedi',
    'F Behardien': 'Farhaan Behardien',
    'F du Plessis': 'Faf du Plessis',
    'FA Allen': 'Fabian Allen',
    'FH Edwards': 'Fidel Edwards',
    'FY Fazal': 'Faiz Fazal',
    'G Coetzee': 'Gerald Coetzee',
    'G Gambhir': 'Gautam Gambhir',
    'GB Hogg': 'Brad Hogg',
    'GC Smith': 'Graeme Smith',
    'GC Viljoen': 'Hardus Viljoen',
    'GD McGrath': 'Glenn McGrath',
    'GD Phillips': 'Glenn Phillips',
    'GH Vihari': 'Hanuma Vihari',
    'GHS Garton': 'George Garton',
    'GJ Bailey': 'George Bailey',
    'GJ Maxwell': 'Glenn Maxwell',
    'GR Napier': 'Graham Napier',
    'GS Sandhu': 'Gurinder Sandhu',
    'H Das': 'Halhadar Das',
    'H Klaasen': 'Heinrich Klaasen',
    'H Sharma': 'Himanshu Sharma',
    'HC Brook': 'Harry Brook',
    'HE van der Dussen': 'Rassie van der Dussen',
    'HF Gurney': 'Harry Gurney',
    'HH Gibbs': 'Herschelle Gibbs',
    'HH Pandya': 'Hardik Pandya',
    'HM Amla': 'Hashim Amla',
    'HR Shokeen': 'Hrithik Shokeen',
    'HV Patel': 'Harshal Patel',
    'I Malhotra': 'Ishan Malhotra',
    'I Sharma': 'Ishant Sharma',
    'I Udana': 'Isuru Udana',
    'IC Pandey': 'Ishwar Pandey',
    'IC Porel': 'Ishan Porel',
    'IK Pathan': 'Irfan Pathan',
    'IR Jaggi': 'Ishank Jaggi',
    'IS Sodhi': 'Ish Sodhi',
    'J Arunkumar': 'Jagadeesh Arunkumar',
    'J Botha': 'Johan Botha',
    'J Fraser-McGurk': 'Jake Fraser-McGurk',
    'J Little': 'Joshua Little',
    'J Overton': 'Jamie Overton',
    'J Suchith': 'Jagadeesha Suchith',
    'J Syed Mohammad': 'Jamaluddin Syed Mohammad',
    'J Theron': 'Juan Theron',
    'J Yadav': 'Jayant Yadav',
    'JA Morkel': 'Albie Morkel',
    'JA Richardson': 'Jhye Richardson',
    'JC Archer': 'Jofra Archer',
    'JC Buttler': 'Jos Buttler',
    'JD Ryder': 'Jesse Ryder',
    'JD Unadkat': 'Jaydev Unadkat',
    'JDP Oram': 'Jacob Oram',
    'JDS Neesham': 'Jimmy Neesham',
    'JE Root': 'Joe Root',
    'JE Taylor': 'Jerome Taylor',
    'JEC Franklin': 'James Franklin',
    'JG Bethell': 'Jacob Bethell',
    'JH Kallis': 'Jacques Kallis',
    'JJ Bumrah': 'Jasprit Bumrah',
    'JJ Roy': 'Jason Roy',
    'JJ van der Wath': 'Johan van der Wath',
    'JL Denly': 'Joe Denly',
    'JL Pattinson': 'James Pattinson',
    'JM Bairstow': 'Jonny Bairstow',
    'JM Kemp': 'Justin Kemp',
    'JM Sharma': 'Jitesh Sharma',
    'JO Holder': 'Jason Holder',
    'JP Behrendorff': 'Jason Behrendorff',
    'JP Duminy': 'JP Duminy',
    'JP Faulkner': 'James Faulkner',
    'JP Inglis': 'Josh Inglis',
    'JPR Scantlebury-Searles': 'Javon Searles',
    'JR Hazlewood': 'Josh Hazlewood',
    'JR Hopes': 'James Hopes',
    'JR Philippe': 'Josh Philippe',
    'JW Hastings': 'John Hastings',
    'K Goel': 'Karan Goel',
    'K Gowtham': 'Krishnappa Gowtham',
    'K Kartikeya': 'Kumar Kartikeya',
    'K Khejroliya': 'Kulwant Khejroliya',
    'K Rabada': 'Kagiso Rabada',
    'K Santokie': 'Krishmar Santokie',
    'K Upadhyay': 'Krishnakumar Upadhyay',
    'K Yadav': 'Kuldeep Yadav',
    'KA Jamieson': 'Kyle Jamieson',
    'KA Maharaj': 'Keshav Maharaj',
    'KA Pollard': 'Kieron Pollard',
    'KAJ Roach': 'Kemar Roach',
    'KB Arun Karthik': 'Arun Karthik',
    'KC Cariappa': 'K. C. Cariappa',
    'KC Sangakkara': 'Kumar Sangakkara',
    'KD Karthik': 'Dinesh Karthik',
    'KH Pandya': 'Krunal Pandya',
    'KJ Abbott': 'Kyle Abbott',
    'KK Ahmed': 'Khaleel Ahmed',
    'KK Cooper': 'Kevon Cooper',
    'KK Nair': 'Karun Nair',
    'KL Nagarkoti': 'Kamlesh Nagarkoti',
    'KL Rahul': 'KL Rahul',
    'KM Asif': 'KM Asif',
    'KM Jadhav': 'Kedar Jadhav',
    'KMA Paul': 'Keemo Paul',
    'KMDN Kulasekara': 'Nuwan Kulasekara',
    'KP Appanna': 'Kotarangada Appanna',
    'KP Pietersen': 'Kevin Pietersen',
    'KR Mayers': 'Kyle Mayers',
    'KR Sen': 'Kuldeep Sen',
    'KS Bharat': 'Srikar Bharat',
    'KS Rathore': 'Kunal Singh Rathore',
    'KS Sharma': 'Karn Sharma',
    'KS Williamson': 'Kane Williamson',
    'KT Maphaka': 'Kwena Maphaka',
    'KV Sharma': 'Karn Sharma',
    'KW Richardson': 'Kane Richardson',
    'L Ablish': 'Love Ablish',
    'L Balaji': 'Lakshmipathy Balaji',
    'L Ngidi': 'Lungi Ngidi',
    'L Ronchi': 'Luke Ronchi',
    'L Wood': 'Luke Wood',
    'LA Carseldine': 'Lee Carseldine',
    'LA Pomersbach': 'Luke Pomersbach',
    'LB Williams': 'Lizaad Williams',
    'LE Plunkett': 'Liam Plunkett',
    'LH Ferguson': 'Lockie Ferguson',
    'LI Meriwala': 'Lukman Meriwala',
    'LJ Wright': 'Luke Wright',
    'LMP Simmons': 'Lendl Simmons',
    'LPC Silva': 'Chamara Silva',
    'LR Shukla': 'Laxmi Ratan Shukla',
    'LRPL Taylor': 'Ross Taylor',
    'LS Livingstone': 'Liam Livingstone',
    'M Ashwin': 'Murugan Ashwin',
    'M Jansen': 'Marco Jansen',
    'M Kaif': 'Mohammad Kaif',
    'M Kartik': 'Murali Kartik',
    'M Klinger': 'Michael Klinger',
    'M Manhas': 'Mithun Manhas',
    'M Markande': 'Mayank Markande',
    'M Morkel': 'Morne Morkel',
    'M Muralitharan': 'Muttiah Muralitharan',
    'M Ntini': 'Makhaya Ntini',
    'M Pathirana': 'Matheesha Pathirana',
    'M Prasidh Krishna': 'Prasidh Krishna',
    'M Rawat': 'Mahesh Rawat',
    'M Shahrukh Khan': 'Shahrukh Khan',
    'M Siddharth': 'Manimaran Siddharth',
    'M Theekshana': 'Maheesh Theekshana',
    'M Tiwari': 'Manoj Tiwary',
    'M Vijay': 'Murali Vijay',
    'M Vohra': 'Manan Vohra',
    'M de Lange': 'Marchant de Lange',
    'MA Agarwal': 'Mayank Agarwal',
    'MA Khote': 'Musavir Khote',
    'MA Starc': 'Mitchell Starc',
    'MA Wood': 'Mark Wood',
    'MB Parmar': 'Mohnish Parmar',
    'MC Henriques': 'Moises Henriques',
    'MC Juneja': 'Manpreet Juneja',
    'MD Mishra': 'Mohnish Mishra',
    'MD Shanaka': 'Dasun Shanaka',
    'MDKJ Perera': 'Kusal Perera',
    'MEK Hussey': 'Michael Hussey',
    'MF Maharoof': 'Farveez Maharoof',
    'MG Bracewell': 'Michael Bracewell',
    'MG Johnson': 'Mitchell Johnson',
    'MG Neser': 'Michael Neser',
    'MJ Clarke': 'Michael Clarke',
    'MJ Guptill': 'Martin Guptill',
    'MJ Henry': 'Matt Henry',
    'MJ Lumb': 'Michael Lumb',
    'MJ McClenaghan': 'Mitchell McClenaghan',
    'MJ Owen': 'Mitchell Owen',
    'MJ Santner': 'Mitchell Santner',
    'MJ Suthar': 'Manav Suthar',
    'MK Lomror': 'Mahipal Lomror',
    'MK Pandey': 'Manish Pandey',
    'MK Tiwary': 'Manoj Tiwary',
    'ML Hayden': 'Matthew Hayden',
    'MM Ali': 'Moeen Ali',
    'MM Patel': 'Munaf Patel',
    'MM Sharma': 'Mohit Sharma',
    'MN Samuels': 'Marlon Samuels',
    'MN van Wyk': 'Morne van Wyk',
    'MP Breetzke': 'Matthew Breetzke',
    'MP Stoinis': 'Marcus Stoinis',
    'MP Yadav': 'Mayank Yadav',
    'MR Marsh': 'Mitchell Marsh',
    'MS Bhandage': 'Manoj Bhandage',
    'MS Bisla': 'Manvinder Bisla',
    'MS Dhoni': 'MS Dhoni',
    'MS Gony': 'Manpreet Gony',
    'MS Wade': 'Matthew Wade',
    'MV Boucher': 'Mark Boucher',
    'MW Short': 'Matthew Short',
    'N Burger': 'Nandre Burger',
    'N Jagadeesan': 'Narayan Jagadeesan',
    'N Pooran': 'Nicholas Pooran',
    'N Rana': 'Nitish Rana',
    'N Saini': 'Navdeep Saini',
    'N Thushara': 'Nuwan Thushara',
    'N Wadhera': 'Nehal Wadhera',
    'NA Saini': 'Navdeep Saini',
    'NB Singh': 'Nikhil Singh',
    'ND Doshi': 'Nayan Doshi',
    'NJ Maddinson': 'Nic Maddinson',
    'NJ Rimmington': 'Nathan Rimmington',
    'NK Patel': 'Niraj Patel',
    'NL McCullum': 'Nathan McCullum',
    'NLTC Perera': 'Thisara Perera',
    'NM Coulter-Nile': 'Nathan Coulter-Nile',
    'NS Naik': 'Nikhil Naik',
    'NT Ellis': 'Nathan Ellis',
    'NV Ojha': 'Naman Ojha',
    'O Thomas': 'Oshane Thomas',
    'OA Shah': 'Owais Shah',
    'OC McCoy': 'Obed McCoy',
    'OF Smith': 'Odean Smith',
    'P Amarnath': 'Palani Amarnath',
    'P Awana': 'Parvinder Awana',
    'P Chopra': 'Prashant Chopra',
    'P Dogra': 'Paras Dogra',
    'P Dubey': 'Praveen Dubey',
    'P Kumar': 'Praveen Kumar',
    'P Negi': 'Pawan Negi',
    'P Parameswaran': 'Prasanth Parameswaran',
    'P Prasanth': 'Padmanabhan Prasanth',
    'P Ray Barman': 'Prayas Ray Barman',
    'P Sahu': 'Pardeep Sahu',
    'P Simran Singh': 'Prabhsimran Singh',
    'P Suyal': 'Pawan Suyal',
    'PA Patel': 'Parthiv Patel',
    'PA Reddy': 'Akshath Reddy',
    'PBB Rajapaksa': 'Bhanuka Rajapaksa',
    'PC Valthaty': 'Paul Valthaty',
    'PD Collingwood': 'Paul Collingwood',
    'PD Salt': 'Phil Salt',
    'PH Solanki': 'Prashant Solanki',
    'PHKD Mendis': 'Kamindu Mendis',
    'PJ Cummins': 'Pat Cummins',
    'PJ Sangwan': 'Pradeep Sangwan',
    'PK Garg': 'Priyam Garg',
    'PM Sarvesh Kumar': 'Sarvesh Kumar',
    'PN Mankad': 'Prerak Mankad',
    'PP Chawla': 'Piyush Chawla',
    'PP Ojha': 'Pragyan Ojha',
    'PP Shaw': 'Prithvi Shaw',
    'PR Shah': 'Pinal Shah',
    'PSP Handscomb': 'Peter Handscomb',
    'PV Tambe': 'Pravin Tambe',
    'PVD Chameera': 'Dushmantha Chameera',
    'PVSN Raju': 'Venugopal Rao',
    'PWA Mulder': 'Wiaan Mulder',
    'PWH de Silva': 'Wanindu Hasaranga',
    'Q de Kock': 'Quinton de Kock',
    'R Ashwin': 'Ravichandran Ashwin',
    'R Bhatia': 'Rajat Bhatia',
    'R Bishnoi': 'Ravi Bishnoi',
    'R Dhawan': 'Rishi Dhawan',
    'R Dravid': 'Rahul Dravid',
    'R Goyal': 'Ravi Goyal',
    'R McLaren': 'Ryan McLaren',
    'R Minz': 'Robin Minz',
    'R Ninan': 'Ryan Ninan',
    'R Parag': 'Riyan Parag',
    'R Powell': 'Rovman Powell',
    'R Rampaul': 'Ravi Rampaul',
    'R Ravindra': 'Rachin Ravindra',
    'R Sai Kishore': 'Ravisrinivasan Sai Kishore',
    'R Sanjay Yadav': 'Sanjay Yadav',
    'R Sathish': 'Rajagopal Sathish',
    'R Sharma': 'Rahul Sharma',
    'R Shepherd': 'Romario Shepherd',
    'R Shukla': 'Rahul Shukla',
    'R Tewatia': 'Rahul Tewatia',
    'R Vinay Kumar': 'Vinay Kumar',
    'RA Bawa': 'Raj Bawa',
    'RA Jadeja': 'Ravindra Jadeja',
    'RA Shaikh': 'Rahil Shaikh',
    'RA Tripathi': 'Rahul Tripathi',
    'RD Chahar': 'Rahul Chahar',
    'RD Gaikwad': 'Ruturaj Gaikwad',
    'RD Rickelton': 'Ryan Rickelton',
    'RE Levi': 'Richard Levi',
    'RE van der Merwe': 'Roelof van der Merwe',
    'RG More': 'Ronit More',
    'RG Sharma': 'Rohit Sharma',
    'RJ Gleeson': 'Richard Gleeson',
    'RJ Harris': 'Ryan Harris',
    'RJ Peterson': 'Robin Peterson',
    'RJ Quiney': 'Rob Quiney',
    'RJW Topley': 'Reece Topley',
    'RK Bhui': 'Ricky Bhui',
    'RK Singh': 'Rinku Singh',
    'RM Patidar': 'Rajat Patidar',
    'RN ten Doeschate': 'Ryan ten Doeschate',
    'RP Meredith': 'Riley Meredith',
    'RP Singh': 'R. P. Singh',
    'RR Bhatkal': 'Raju Bhatkal',
    'RR Bose': 'Ranadeb Bose',
    'RR Pant': 'Rishabh Pant',
    'RR Powar': 'Ramesh Powar',
    'RR Raje': 'Rohan Raje',
    'RR Rossouw': 'Rilee Rossouw',
    'RR Sarwan': 'Ramnaresh Sarwan',
    'RS Bopara': 'Ravi Bopara',
    'RS Gavaskar': 'Rohan Gavaskar',
    'RS Hangargekar': 'Rajvardhan Hangargekar',
    'RS Sodhi': 'Reetinder Sodhi',
    'RT Ponting': 'Ricky Ponting',
    'RV Gomez': 'Raiphi Gomez',
    'RV Patel': 'Ripal Patel',
    'RV Uthappa': 'Robin Uthappa',
    'RW Price': 'Ray Price',
    'S Anirudha': 'Anirudha Srikkanth',
    'S Aravind': 'Sreenath Aravind',
    'S Badree': 'Samuel Badree',
    'S Badrinath': 'Subramaniam Badrinath',
    'S Chanderpaul': 'Shivnarine Chanderpaul',
    'S Dhawan': 'Shikhar Dhawan',
    'S Dube': 'Shivam Dube',
    'S Gopal': 'Shreyas Gopal',
    'S Joseph': 'Shamar Joseph',
    'S Kaul': 'Siddharth Kaul',
    'S Kaushik': 'Shivil Kaushik',
    'S Ladda': 'Sarabjit Ladda',
    'S Lamichhane': 'Sandeep Lamichhane',
    'S Midhun': 'Sudhesan Midhun',
    'S Nadeem': 'Shahbaz Nadeem',
    'S Narwal': 'Sumit Narwal',
    'S Rana': 'Sachin Rana',
    'S Randiv': 'Suraj Randiv',
    'S Sandeep Warrier': 'Sandeep Warrier',
    'S Sohal': 'Sunny Sohal',
    'S Sreesanth': 'Sreesanth',
    'S Sriram': 'Sridharan Sriram',
    'S Tyagi': 'Sudeep Tyagi',
    'S Vidyut': 'Vidyut Sivaramakrishnan',
    'SA Abbott': 'Sean Abbott',
    'SA Asnodkar': 'Swapnil Asnodkar',
    'SA Yadav': 'Suryakumar Yadav',
    'SB Bangar': 'Sanjay Bangar',
    'SB Dubey': 'Shivam Dubey',
    'SB Jakati': 'Shadab Jakati',
    'SB Joshi': 'Sunil Joshi',
    'SB Styris': 'Scott Styris',
    'SB Wagh': 'Shrikant Wagh',
    'SC Ganguly': 'Sourav Ganguly',
    'SC Kuggeleijn': 'Scott Kuggeleijn',
    'SD Chitnis': 'Siddharth Chitnis',
    'SD Hope': 'Shai Hope',
    'SD Lad': 'Siddhesh Lad',
    'SE Bond': 'Shane Bond',
    'SE Marsh': 'Shaun Marsh',
    'SE Rutherford': 'Sherfane Rutherford',
    'SH Johnson': 'Spencer Johnson',
    'SJ Srivastava': 'Shalabh Srivastava',
    'SK Raina': 'Suresh Raina',
    'SK Rasheed': 'Shaik Rasheed',
    'SK Trivedi': 'Siddharth Trivedi',
    'SK Warne': 'Shane Warne',
    'SL Malinga': 'Lasith Malinga',
    'SM Boland': 'Scott Boland',
    'SM Curran': 'Sam Curran',
    'SM Harwood': 'Shane Harwood',
    'SM Katich': 'Simon Katich',
    'SM Pollock': 'Shaun Pollock',
    'SMSM Senanayake': 'Sachithra Senanayake',
    'SN Khan': 'Sarfaraz Khan',
    'SN Thakur': 'Shardul Thakur',
    'SO Hetmyer': 'Shimron Hetmyer',
    'SP Fleming': 'Stephen Fleming',
    'SP Goswami': 'Shreevats Goswami',
    'SP Jackson': 'Sheldon Jackson',
    'SP Narine': 'Sunil Narine',
    'SPD Smith': 'Steve Smith',
    'SR Tendulkar': 'Sachin Tendulkar',
    'SR Watson': 'Shane Watson',
    'SS Agarwal': 'Shubham Agarwal',
    'SS Cottrell': 'Sheldon Cottrell',
    'SS Iyer': 'Shreyas Iyer',
    'SS Mundhe': 'Shrikant Mundhe',
    'SS Prabhudessai': 'Suyash Prabhudessai',
    'SS Sarkar': 'Soumya Sarkar',
    'SS Shaikh': 'Sufiyan Shaikh',
    'SS Tiwary': 'Saurabh Tiwary',
    'SSB Magala': 'Sisanda Magala',
    'ST Jayasuriya': 'Sanath Jayasuriya',
    'STR Binny': 'Stuart Binny',
    'SV Samson': 'Sanju Samson',
    'SW Billings': 'Sam Billings',
    'SW Tait': 'Shaun Tait',
    'SZ Mulani': 'Shams Mulani',
    'T Banton': 'Tom Banton',
    'T Henderson': 'Tyron Henderson',
    'T Kohler-Cadmore': 'Tom Kohler-Cadmore',
    'T Kohli': 'Taruwar Kohli',
    'T Natarajan': 'T. Natarajan',
    'T Shamsi': 'Tabraiz Shamsi',
    'T Stubbs': 'Tristan Stubbs',
    'T Taibu': 'Tatenda Taibu',
    'T Thushara': 'Thilan Thushara',
    'TA Boult': 'Trent Boult',
    'TD Paine': 'Tim Paine',
    'TG Southee': 'Tim Southee',
    'TH David': 'Tim David',
    'TK Curran': 'Tom Curran',
    'TL Seifert': 'Tim Seifert',
    'TL Suman': 'Tirumalasetti Suman',
    'TM Dilshan': 'Tillakaratne Dilshan',
    'TM Head': 'Travis Head',
    'TM Srivastava': 'Tanmay Srivastava',
    'TP Sudhindra': 'T. P. Sudhindra',
    'TR Birt': 'Travis Birt',
    'TS Mills': 'Tymal Mills',
    'TU Deshpande': 'Tushar Deshpande',
    'U Kaul': 'Uday Kaul',
    'UA Birla': 'Udit Birla',
    'UBT Chand': 'Unmukt Chand',
    'UT Khawaja': 'Usman Khawaja',
    'UT Yadav': 'Umesh Yadav',
    'V Kaverappa': 'Vidwath Kaverappa',
    'V Kohli': 'Virat Kohli',
    'V Nigam': 'Vikas Nigam',
    'V Pratap Singh': 'Vishwa Pratap Singh',
    'V Puthur': 'Vyshak Vijaykumar',
    'V Sehwag': 'Virender Sehwag',
    'V Shankar': 'Vijay Shankar',
    'V Suryavanshi': 'Vaibhav Suryavanshi',
    'V Viyaskanth': 'Vijayakanth Viyaskanth',
    'VG Arora': 'Vaibhav Arora',
    'VH Zol': 'Vijay Zol',
    'VR Aaron': 'Varun Aaron',
    'VR Iyer': 'Venkatesh Iyer',
    'VRV Singh': 'V. R. V. Singh',
    'VS Malik': 'Vikramjeet Malik',
    'VS Yeligati': 'Vinayak Yeligati',
    'VVS Laxman': 'V. V. S. Laxman',
    'VY Mahesh': 'V. Y. Mahesh',
    'W Jaffer': 'Wasim Jaffer',
    "W O'Rourke": "William O'Rourke",
    'WA Mota': 'Wilkin Mota',
    'WD Parnell': 'Wayne Parnell',
    'WG Jacks': 'Will Jacks',
    'WP Saha': 'Wriddhiman Saha',
    'WPUJC Vaas': 'Chaminda Vaas',
    'X Thalaivan Sargunam': 'Xavier Thalaivan Sargunam',
    'XC Bartlett': 'Xavier Bartlett',
    'Y Gnaneswara Rao': 'Yalaka Gnaneswara Rao',
    'Y Nagar': 'Yogesh Nagar',
    'Y Prithvi Raj': 'Yarra Prithvi Raj',
    'Y Venugopal Rao': 'Yalaka Venugopal Rao',
    'YA Abdulla': 'Yusuf Abdulla',
    'YBK Jaiswal': 'Yashasvi Jaiswal',
    'YK Pathan': 'Yusuf Pathan',
    'YS Chahal': 'Yuzvendra Chahal',
    'YV Dhull': 'Yash Dhull',
    'YV Takawale': 'Yogesh Takawale',
    'Z Khan': 'Zaheer Khan'
}

In [105]:
# def build_dream11_team(players_df):
#     team = []
    
#     role_count = {'wk': 0, 'BAT': 0, 'BOWL': 0, 'AR': 0}
#     team_count = {}

#     for _, row in players_df.iterrows():
#         player = row['player']
#         role = row['role']
#         team_name = row['team']
#         is_wk = row['player_role_wicketkeeper']
        
#         # Determine role
#         if is_wk:
#             player_role = 'wk'
#         else:
#             player_role = role
        
#         # Check team limit (max 7 players from a team)
#         if team_name not in team_count:
#             team_count[team_name] = 0
#         if team_count[team_name] >= 7:
#             continue
        
#         # Check role limits
#         if player_role == 'wk' and role_count['wk'] >= 4:
#             continue
#         if player_role == 'BAT' and role_count['BAT'] >= 6:
#             continue
#         if player_role == 'BOWL' and role_count['BOWL'] >= 6:
#             continue
#         if player_role == 'AR' and role_count['AR'] >= 4:
#             continue
        
#         # Add player
#         team.append(player)
#         role_count[player_role] += 1
#         team_count[team_name] += 1
        
#         # Stop if 11 players selected
#         if len(team) == 11:
#             break

#     return team, role_count, team_count

In [106]:
# def validate_and_fix(team, players_df):
#     # Convert to df
#     selected = players_df[players_df['player'].isin(team)]
    
#     def count_roles(df):
#         wk = df['player_role_wicketkeeper'].sum()
#         bat = len(df[(df['role'] == 'BAT') & (~df['player_role_wicketkeeper'])])
#         bowl = len(df[df['role'] == 'BOWL'])
#         ar = len(df[df['role'] == 'AR'])
#         return wk, bat, bowl, ar

#     wk, bat, bowl, ar = count_roles(selected)
    
#     # Add missing WK if needed
#     if wk == 0:
#         wk_candidates = players_df[
#             (players_df['player_role_wicketkeeper']) &
#             (~players_df['player'].isin(team))
#         ]
#         if not wk_candidates.empty:
#             team[-1] = wk_candidates.iloc[0]['player']
    
#     return team

In [107]:
# def choose_captains(team, players_df):
#     selected = players_df[players_df['player'].isin(team)]
#     selected = selected.sort_values(by='predicted_points', ascending=False)
    
#     captain = selected.iloc[0]['player']
#     vice_captain = selected.iloc[1]['player']
    
#     return captain, vice_captain

In [123]:
players_df = players_df.sort_values(by='predicted_points', ascending=False).reset_index(drop=True)

In [109]:
# team, role_count, team_count = build_dream11_team(players_df)

In [110]:
# team

['Ishan Kishan',
 'MS Dhoni',
 'Ruturaj Gaikwad',
 'Ravindra Jadeja',
 'Piyush Chawla',
 'Suryakumar Yadav',
 'Daryl Mitchell',
 'Shivam Dube',
 'Tim David',
 'Rohit Sharma',
 'Romario Shepherd']

In [111]:
# role_count

{'wk': 2, 'BAT': 6, 'BOWL': 1, 'AR': 2}

In [112]:
# team_count

{'Mumbai Indians': 6, 'Chennai Super Kings': 5}

In [113]:
# team = validate_and_fix(team, players_df)

In [114]:
# team

['Ishan Kishan',
 'MS Dhoni',
 'Ruturaj Gaikwad',
 'Ravindra Jadeja',
 'Piyush Chawla',
 'Suryakumar Yadav',
 'Daryl Mitchell',
 'Shivam Dube',
 'Tim David',
 'Rohit Sharma',
 'Romario Shepherd']

In [115]:
# captain, vice_captain = choose_captains(team, players_df)

In [116]:
# print("🏏 Final Team:")
# print(team)

# print("\n📊 Role Distribution:")
# print(role_count)

# print("\n🏢 Team Distribution:")
# print(team_count)

# print("\n👑 Captain:", captain)
# print("🤝 Vice-Captain:", vice_captain)

🏏 Final Team:
['Ishan Kishan', 'MS Dhoni', 'Ruturaj Gaikwad', 'Ravindra Jadeja', 'Piyush Chawla', 'Suryakumar Yadav', 'Daryl Mitchell', 'Shivam Dube', 'Tim David', 'Rohit Sharma', 'Romario Shepherd']

📊 Role Distribution:
{'wk': 2, 'BAT': 6, 'BOWL': 1, 'AR': 2}

🏢 Team Distribution:
{'Mumbai Indians': 6, 'Chennai Super Kings': 5}

👑 Captain: Ishan Kishan
🤝 Vice-Captain: MS Dhoni

In [124]:
def get_role(row):
    if row['player_role_wicketkeeper']:
        return 'WK'
    return row['role'].upper()

players_df['final_role'] = players_df.apply(get_role, axis=1)

In [125]:
def build_valid_team(players_df):
    team = []
    team_count = {}
    
    role_constraints = {
        'WK': (1, 4),
        'BAT': (3, 6),
        'AR': (1, 4),
        'BOWL': (3, 6)
    }

    role_count = {r: 0 for r in role_constraints}

    # ✅ Step 1: Fill minimum requirements
    for role, (min_req, max_req) in role_constraints.items():
        candidates = players_df[
            (players_df['final_role'] == role) &
            (~players_df['player'].isin(team))
        ]
        
        for _, row in candidates.iterrows():
            if role_count[role] >= min_req:
                break
                
            team_name = row['team']
            
            if team_count.get(team_name, 0) >= 7:
                continue
            
            team.append(row['player'])
            role_count[role] += 1
            team_count[team_name] = team_count.get(team_name, 0) + 1

    # ✅ Step 2: Fill remaining slots (best players)
    for _, row in players_df.iterrows():
        if len(team) >= 11:
            break
            
        player = row['player']
        role = row['final_role']
        team_name = row['team']
        
        if player in team:
            continue
        
        # Team constraint
        if team_count.get(team_name, 0) >= 7:
            continue
        
        # Role max constraint
        if role_count[role] >= role_constraints[role][1]:
            continue
        
        team.append(player)
        role_count[role] += 1
        team_count[team_name] = team_count.get(team_name, 0) + 1

    return team, role_count, team_count

In [126]:

team, role_count, team_count = build_valid_team(players_df)
captain, vice_captain = choose_captains(team, players_df)

In [127]:
print("Team size:", len(team))
print("Role count:", role_count)
print("Team count:", team_count)

Team size: 11
Role count: {'WK': 2, 'BAT': 5, 'AR': 1, 'BOWL': 3}
Team count: {'Mumbai Indians': 5, 'Chennai Super Kings': 6}

In [128]:
print("🏏 Final Team:")
print(team)

print("\n📊 Role Distribution:")
print(role_count)

print("\n🏢 Team Distribution:")
print(team_count)

print("\n👑 Captain:", captain)
print("🤝 Vice-Captain:", vice_captain)

🏏 Final Team:
['Ishan Kishan', 'Ruturaj Gaikwad', 'Suryakumar Yadav', 'Daryl Mitchell', 'Ravindra Jadeja', 'Piyush Chawla', 'Deepak Chahar', 'Gerald Coetzee', 'MS Dhoni', 'Shivam Dube', 'Tim David']

📊 Role Distribution:
{'WK': 2, 'BAT': 5, 'AR': 1, 'BOWL': 3}

🏢 Team Distribution:
{'Mumbai Indians': 5, 'Chennai Super Kings': 6}

👑 Captain: Ishan Kishan
🤝 Vice-Captain: MS Dhoni