In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/half_processed/half_prepared_data.csv")
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points              1461
last5_avg_points              2701
last10_avg_points             5300
rolling_strike_rate           2711
rolling_wickets               2701
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1461
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
boundary_percentage              0
bat_pos_per_match              289
dtype: int64

In [3]:
avg_fantasy_points=data['fantasy_points'].mean()
avg_fantasy_points

np.float64(35.67203980099502)

In [4]:
data['toss_winner'].unique()

array(['Deccan Chargers', 'Mumbai Indians', 'Chennai Super Kings',
       'Royal Challengers Bangalore', 'Rajasthan Royals', 'Pune Warriors',
       'Sunrisers Hyderabad', 'Delhi Daredevils', 'Kolkata Knight Riders',
       'Kings XI Punjab', 'Gujarat Titans', 'Lucknow Super Giants',
       'Punjab Kings', 'Delhi Capitals', 'Royal Challengers Bengaluru',
       'Gujarat Lions', 'Kochi Tuskers Kerala', 'Rising Pune Supergiants',
       'Rising Pune Supergiant'], dtype=object)

In [5]:
team_map = {
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru",
    "Kings XI Punjab": "Punjab Kings",
    "Delhi Daredevils": "Delhi Capitals",
    "Rising Pune Supergiant": "Rising Pune Supergiants"
}
data['team'] = data['team'].replace(team_map)
data['opponent'] = data['opponent'].replace(team_map)
data['toss_winner'] = data['toss_winner'].replace(team_map)

In [6]:
data['team'].unique()

array(['Deccan Chargers', 'Sunrisers Hyderabad', 'Lucknow Super Giants',
       'Rajasthan Royals', 'Kolkata Knight Riders',
       'Royal Challengers Bengaluru', 'Mumbai Indians',
       'Chennai Super Kings', 'Gujarat Titans', 'Delhi Capitals',
       'Pune Warriors', 'Rising Pune Supergiants', 'Punjab Kings',
       'Gujarat Lions', 'Kochi Tuskers Kerala'], dtype=object)

In [7]:
data[['last3_avg_points','last5_avg_points','last10_avg_points']] = data[['last3_avg_points','last5_avg_points','last10_avg_points']].fillna(avg_fantasy_points)
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points                 0
last5_avg_points                 0
last10_avg_points                0
rolling_strike_rate           2711
rolling_wickets               2701
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1461
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
boundary_percentage              0
bat_pos_per_match              289
dtype: int64

In [8]:
data['team'].unique()

array(['Deccan Chargers', 'Sunrisers Hyderabad', 'Lucknow Super Giants',
       'Rajasthan Royals', 'Kolkata Knight Riders',
       'Royal Challengers Bengaluru', 'Mumbai Indians',
       'Chennai Super Kings', 'Gujarat Titans', 'Delhi Capitals',
       'Pune Warriors', 'Rising Pune Supergiants', 'Punjab Kings',
       'Gujarat Lions', 'Kochi Tuskers Kerala'], dtype=object)

In [9]:
data['strike_rate'] = data['strike_rate'].replace([np.inf, -np.inf], 0)

In [10]:
avg_strike_rate = data['strike_rate'].mean()
avg_strike_rate

np.float64(80.7621438072104)

In [11]:
data['rolling_strike_rate'] = data['rolling_strike_rate'].fillna(avg_strike_rate)

In [12]:
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points                 0
last5_avg_points                 0
last10_avg_points                0
rolling_strike_rate              0
rolling_wickets               2701
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1461
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
boundary_percentage              0
bat_pos_per_match              289
dtype: int64

In [13]:
data['rolling_wickets'] = data['rolling_wickets'].fillna(0)

In [14]:
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points                 0
last5_avg_points                 0
last10_avg_points                0
rolling_strike_rate              0
rolling_wickets                  0
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points             1461
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
boundary_percentage              0
bat_pos_per_match              289
dtype: int64

In [15]:
data['last10_std_points'] = data['last10_std_points'].fillna(0)
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points                 0
last5_avg_points                 0
last10_avg_points                0
rolling_strike_rate              0
rolling_wickets                  0
venue_avg_points                 0
opponent_avg_points              0
pitch_type                       0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points                0
player_consistency_index         0
form_momentum                 5300
bat_pos                        289
boundary_percentage              0
bat_pos_per_match              289
dtype: int64

In [16]:
data['form_momentum'] = data['form_momentum'].fillna(0)
data.isnull().sum()

match_id                        0
player                          0
runs                            0
balls                           0
fours                           0
sixes                           0
strike_rate                     0
runs_conceded                   0
balls_bowled                    0
wickets                         0
overs                           0
economy                         0
fielding_points                 0
batting_points                  0
batting_bonus                   0
sr_bonus                        0
wicket_bonus                    0
eco_bonus                       0
lbw_bowled_bonus                0
bowling_points                  0
maiden_points                   0
fantasy_points                  0
team                            0
opponent                        0
venue                           0
city                            0
toss_winner                     0
toss_decision                   0
stage                           0
season                          0
date                            0
player_match_number             0
last3_avg_points                0
last5_avg_points                0
last10_avg_points               0
rolling_strike_rate             0
rolling_wickets                 0
venue_avg_points                0
opponent_avg_points             0
pitch_type                      0
venue_run_factor                0
batting_contribution_ratio      0
bowling_contribution_ratio      0
player_role                     0
last10_std_points               0
player_consistency_index        0
form_momentum                   0
bat_pos                       289
boundary_percentage             0
bat_pos_per_match             289
dtype: int64

In [17]:
data['bat_pos'] = data['bat_pos'].fillna(11)
data['bat_pos_per_match'] = data['bat_pos_per_match'].fillna(11)

In [18]:
data.isnull().sum()

match_id                      0
player                        0
runs                          0
balls                         0
fours                         0
sixes                         0
strike_rate                   0
runs_conceded                 0
balls_bowled                  0
wickets                       0
overs                         0
economy                       0
fielding_points               0
batting_points                0
batting_bonus                 0
sr_bonus                      0
wicket_bonus                  0
eco_bonus                     0
lbw_bowled_bonus              0
bowling_points                0
maiden_points                 0
fantasy_points                0
team                          0
opponent                      0
venue                         0
city                          0
toss_winner                   0
toss_decision                 0
stage                         0
season                        0
date                          0
player_match_number           0
last3_avg_points              0
last5_avg_points              0
last10_avg_points             0
rolling_strike_rate           0
rolling_wickets               0
venue_avg_points              0
opponent_avg_points           0
pitch_type                    0
venue_run_factor              0
batting_contribution_ratio    0
bowling_contribution_ratio    0
player_role                   0
last10_std_points             0
player_consistency_index      0
form_momentum                 0
bat_pos                       0
boundary_percentage           0
bat_pos_per_match             0
dtype: int64

In [19]:
cols_to_drop = [
'runs','balls','fours','sixes','strike_rate',
'runs_conceded','balls_bowled','wickets','overs','economy',
'batting_points','bowling_points','fielding_points',
'batting_bonus','sr_bonus','wicket_bonus','eco_bonus',
'lbw_bowled_bonus','maiden_points'
]
data = data.drop(columns = cols_to_drop)

In [20]:
data.head()

,match_id,player,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,...,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match
0,548341,A Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,...,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0
1,548346,A Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,...,1.010270,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0
2,548348,A Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,...,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0
3,548352,A Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,...,0.988070,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0
4,548356,A Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,...,0.964953,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0

In [21]:
pd.set_option('display.max_columns', None)

In [22]:
data.head()

,match_id,player,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match
0,548341,A Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0
1,548346,A Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0
2,548348,A Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0
3,548352,A Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0
4,548356,A Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0

In [23]:
data['date'] = pd.to_datetime(data['date'])

data['match_month'] = data['date'].dt.month
data = data.drop(columns=['date'])

In [24]:
data

,match_id,player,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,match_month
0,548341,A Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,4
1,548346,A Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,4
2,548348,A Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,5
3,548352,A Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,5
4,548356,A Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,6,3.333333,25.60000,35.67204,0.000000,0.8,6.75,18.500000,balanced,1.134422,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,4
25121,1473480,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,7,11.666667,13.60000,35.67204,0.000000,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,4
25122,1473488,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,8,12.333333,7.00000,35.67204,0.000000,0.2,23.00,11.500000,balanced,1.116228,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,5
25123,1473492,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,9,16.000000,11.60000,35.67204,0.000000,0.4,6.75,44.500000,balanced,1.134422,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,5
25124,1473499,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,5

In [25]:
data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'city', 'toss_winner', 'toss_decision', 'stage', 'season',
       'player_match_number', 'last3_avg_points', 'last5_avg_points',
       'last10_avg_points', 'rolling_strike_rate', 'rolling_wickets',
       'venue_avg_points', 'opponent_avg_points', 'pitch_type',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'player_role', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'bat_pos_per_match', 'match_month'],
      dtype='object')

In [26]:
data = data.drop(columns=['match_id'])

In [27]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/data_processed.csv",index = False)

In [28]:
data.head()

,player,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,match_month
0,A Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,4
1,A Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,4
2,A Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,5
3,A Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,5
4,A Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,5

In [29]:
data['team_won_toss'] = (
    data['team'] == data['toss_winner']
).astype(int)

In [30]:
data

,player,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,match_month,team_won_toss
0,A Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,4,1
1,A Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,4,0
2,A Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,5,1
3,A Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Unknown,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,5,0
4,A Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Mumbai Indians,field,Unknown,2025,6,3.333333,25.60000,35.67204,0.000000,0.8,6.75,18.500000,balanced,1.134422,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,4,0
25121,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,field,Unknown,2025,7,11.666667,13.60000,35.67204,0.000000,0.4,0.00,0.000000,spin_friendly,1.003589,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,4,1
25122,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,8,12.333333,7.00000,35.67204,0.000000,0.2,23.00,11.500000,balanced,1.116228,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,5,1
25123,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,9,16.000000,11.60000,35.67204,0.000000,0.4,6.75,44.500000,balanced,1.134422,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,5,1
25124,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.00,-2.000000,spin_friendly,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,5,1

In [31]:
data = data.drop(columns=['toss_winner'])

In [32]:
data = data.drop(columns=['city'])

In [33]:
from sklearn.preprocessing import LabelEncoder

le_player = LabelEncoder()
data['player'] = le_player.fit_transform(data['player'])

le_venue = LabelEncoder()
data['venue'] = le_venue.fit_transform(data['venue'])
data.head()

,player,fantasy_points,team,opponent,venue,toss_decision,stage,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,pitch_type,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,match_month,team_won_toss
0,0,58.0,Deccan Chargers,Pune Warriors,53,bat,Unknown,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,balanced,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,4,1
1,0,41.0,Deccan Chargers,Mumbai Indians,56,field,Unknown,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,batting_friendly,1.010270,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,4,0
2,0,23.0,Deccan Chargers,Pune Warriors,2,bat,Unknown,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,balanced,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,5,1
3,0,28.0,Deccan Chargers,Chennai Super Kings,27,bat,Unknown,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,spin_friendly,0.988070,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,5,0
4,0,33.0,Deccan Chargers,Royal Challengers Bengaluru,23,field,Unknown,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,batting_friendly,0.964953,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,5,0

In [34]:
cat_cols = [
    'team',
    'opponent',
    'toss_decision',
    'stage',
    'pitch_type',
    'player_role'
]

data = pd.get_dummies(
    data,
    columns=cat_cols,
    drop_first=True
)

In [35]:
data

,player,fantasy_points,venue,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,match_month,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,stage_Elimination Final,stage_Eliminator,stage_Final,stage_Qualifier 1,stage_Qualifier 2,stage_Semi Final,stage_Unknown,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
0,0,58.0,53,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,7.0,4,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True
1,0,41.0,56,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,1.010270,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,8.0,4,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False
2,0,23.0,2,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,7.0,5,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True
3,0,28.0,27,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,0.988070,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,6.0,5,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True
4,0,33.0,23,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,0.964953,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,7.0,5,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,766,25.0,44,2025,6,3.333333,25.60000,35.67204,0.000000,0.8,6.75,18.500000,1.134422,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,11.0,4,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
25121,766,0.0,28,2025,7,11.666667,13.60000,35.67204,0.000000,0.4,0.00,0.000000,1.003589,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,11.0,4,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False
25122,766,23.0,33,2025,8,12.333333,7.00000,35.67204,0.000000,0.2,23.00,11.500000,1.116228,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,11.0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
25123,766,4.0,44,2025,9,16.000000,11.60000,35.67204,0.000000,0.4,6.75,44.500000,1.134422,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,11.0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
25124,766,-2.0,4,2025,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.00,-2.000000,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,11.0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,True

In [36]:
data.columns

Index(['player', 'fantasy_points', 'venue', 'season', 'player_match_number',
       'last3_avg_points', 'last5_avg_points', 'last10_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'venue_avg_points',
       'opponent_avg_points', 'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'bat_pos_per_match', 'match_month',
       'team_won_toss', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'stage_Elimination Final', 'stage_Eliminator',
       'stage_Final', 'stage_Qualifier 1', 'stage_Qualifier 2',
       'stage_Semi Final', 'stage_Unknown', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler'],
      dtype='object')

In [37]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/ready_for_training.csv",index = False)