In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/ready_for_training.csv")

In [2]:
pd.set_option("display.max_columns",None)
data['recent_form'] = (data['last3_avg_points']*0.6 + data['last5_avg_points']*0.3 + data['last10_avg_points']*0.1)
data['venue_form'] = data['venue_avg_points'] * data['recent_form']

In [3]:
colsToDrop = ['player_match_number',
              'last5_avg_points',
              'last10_avg_points',
              'bat_pos_per_match',
              'match_month',
              'stage_Elimination Final',
              'stage_Eliminator',
              'stage_Final',
              'stage_Qualifier 1',
              'stage_Qualifier 2',
              'stage_Semi Final',
              'stage_Unknown']
data = data.drop(columns = colsToDrop)
data['season'] = data['season'].str[:4].astype(int)
data['season'].unique()

array([2012, 2013, 2015, 2016, 2022, 2023, 2024, 2025, 2007, 2009, 2017,
       2018, 2011, 2014, 2019, 2020, 2021])

In [4]:
train = data[data['season'] <= 2022]
test  = data[data['season'] > 2022]
X_train = train.drop(columns=['fantasy_points','player','venue','season','player_role_batsman','player_role_bowler'])
y_train = train['fantasy_points']

X_test = test.drop(columns=['fantasy_points','player','venue','season','player_role_batsman','player_role_bowler'])
y_test = test['fantasy_points']
print(X_test.shape)
print(X_train.shape)

(4995, 49)
(20130, 49)

In [5]:
X_train

,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,recent_form,venue_form
0,35.672040,80.762144,0.0,58.00,39.250000,0.879923,0.000000,1.000000,0.000000,0.000000,0.000000,7.0,0.0,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,35.672040,2068.978308
1,35.672040,80.762144,0.0,41.00,30.000000,1.010270,0.292683,0.707317,0.000000,0.000000,0.000000,7.0,0.6,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,35.672040,1462.553632
2,35.672040,80.762144,0.0,23.00,39.250000,1.027630,0.000000,1.000000,0.000000,0.000000,0.000000,7.0,0.0,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,35.672040,820.456915
3,40.666667,80.762144,0.0,45.00,47.333333,0.988070,0.107143,0.892857,17.502381,0.000000,0.000000,7.0,0.0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,38.668816,1740.096716
4,30.666667,80.762144,0.0,31.75,38.714286,0.964953,0.000000,1.000000,15.631165,0.000000,0.000000,7.0,0.0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,32.668816,1037.234905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25110,19.333333,0.000000,1.0,11.00,39.000000,0.955192,0.000000,0.000000,28.920581,0.892098,-6.466667,9.0,0.0,0,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,23.000000,253.000000
25111,0.000000,0.000000,0.4,38.00,26.600000,0.970209,1.000000,-0.000000,29.944578,0.758067,-22.700000,9.0,0.0,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,6.230000,236.740000
25112,-1.333333,3.636364,0.4,8.00,13.000000,1.012649,0.000000,0.000000,30.461086,0.725516,-23.433333,9.0,0.0,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,4.650000,37.200000
25113,1.333333,3.636364,0.0,38.00,70.500000,0.970209,0.000000,1.000000,30.077862,0.754708,-21.366667,9.0,0.0,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,3.310000,125.780000
25114,21.333333,3.636364,0.4,38.00,33.000000,0.970209,0.038462,0.961538,32.327491,0.810456,-4.866667,9.0,0.0,0,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,19.260000,731.880000

In [6]:
num_attributes = ['last3_avg_points',
                  'rolling_strike_rate',
                  'rolling_wickets',
                  'venue_avg_points',
                  'opponent_avg_points',
                  'venue_run_factor',
                  'batting_contribution_ratio',
                  'bowling_contribution_ratio',
                  'last10_std_points',
                  'player_consistency_index',
                  'form_momentum',
                  'boundary_percentage',
                  'recent_form',
                  'venue_form']
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()
X_train[num_attributes] = scaler.fit_transform(X_train[num_attributes])
X_test[num_attributes] = scaler.fit_transform(X_test[num_attributes])

In [8]:
X_train

,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,recent_form,venue_form
0,-0.022106,-0.006803,-0.783634,1.140195,0.227753,-1.843340,-1.031422,1.136854,-2.199164,-1.607630,0.025211,7.0,-0.895793,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,-0.035839,0.605056
1,-0.022106,-0.006803,-0.783634,0.279162,-0.346013,0.648967,-0.516493,0.616795,-2.199164,-1.607630,0.025211,7.0,0.895683,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,-0.035839,0.080491
2,-0.022106,-0.006803,-0.783634,-0.632521,0.227753,0.980915,-1.031422,1.136854,-2.199164,-1.607630,0.025211,7.0,-0.895793,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,-0.035839,-0.474932
3,0.229925,-0.006803,-0.783634,0.481758,0.729153,0.224498,-0.842921,0.946475,-0.856952,-1.607630,0.025211,7.0,-0.895793,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0.143775,0.320569
4,-0.274679,-0.006803,-0.783634,-0.189342,0.194524,-0.217508,-1.031422,1.136854,-1.000451,-1.607630,0.025211,7.0,-0.895793,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,-0.215840,-0.287416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25110,-0.846563,-1.663806,0.958448,-1.240309,0.212246,-0.404154,-1.031422,-0.640016,0.018679,-0.106226,-0.439689,9.0,-0.895793,0,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,-0.795347,-0.965789
25111,-1.822130,-1.663806,-0.086801,0.127215,-0.556911,-0.117008,0.727917,-0.640016,0.097207,-0.331801,-1.606731,9.0,-0.895793,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,-1.800469,-0.979854
25112,-1.889410,-1.589198,-0.086801,-1.392256,-1.400502,0.694461,-1.031422,-0.640016,0.136817,-0.386585,-1.659452,9.0,-0.895793,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,-1.895168,-1.152459
25113,-1.754849,-1.589198,-0.783634,0.127215,2.166153,-0.117008,-1.031422,1.136854,0.107428,-0.337455,-1.510876,9.0,-0.895793,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,-1.975481,-1.075836
25114,-0.745642,-1.589198,-0.086801,0.127215,-0.159926,-0.117008,-0.963755,1.068513,0.279946,-0.243631,-0.324662,9.0,-0.895793,0,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,-1.019507,-0.551552

In [9]:
from xgboost import XGBRegressor

xg = XGBRegressor(
    n_estimators=900,
    learning_rate=0.01,
    max_depth=4,
    subsample=0.85,
    colsample_bytree=0.8,
    min_child_weight=3,
    gamma=0.1,
    random_state=42
)

xg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=0.1, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=4, max_leaves=None,
             min_child_weight=3, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=900, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [10]:
y_pred = xg.predict(X_test)

In [11]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test, y_pred))

15.68368999834366

In [12]:
importance = pd.Series(
    xg.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

print(importance.head(20))

venue_avg_points                    0.280127
bowling_contribution_ratio          0.122025
opponent_avg_points                 0.104779
boundary_percentage                 0.073538
batting_contribution_ratio          0.047494
venue_form                          0.031204
rolling_wickets                     0.030879
bat_pos                             0.024378
team_Lucknow Super Giants           0.012644
team_Royal Challengers Bengaluru    0.012609
recent_form                         0.012605
last3_avg_points                    0.012384
last10_std_points                   0.012296
rolling_strike_rate                 0.011859
pitch_type_batting_friendly         0.011232
opponent_Sunrisers Hyderabad        0.010674
team_Punjab Kings                   0.010438
pitch_type_pace_friendly            0.009452
player_consistency_index            0.009138
form_momentum                       0.008795
dtype: float32

In [13]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
xgb = XGBRegressor(
    objective='reg:squarederror',
    random_state=42
)
param_grid = {
    'n_estimators': [300, 500, 700],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.01, 0.03, 0.05],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8],
    'min_child_weight': [1, 3, 5]
}
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='neg_mean_absolute_error',
    cv=5,
    verbose=2,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 486 candidates, totalling 2430 fits
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.9; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.7; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=500, subsample=0.7; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=700, subsample=0.7; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=700, subsample=0.9; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.9; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   2.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=500, subsample=0.7; total time=   1.8s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   1.8s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=700, subsample=0.7; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=700, subsample=0.9; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=500, subsample=0.7; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=500, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=700, subsample=0.7; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=700, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=300, subsample=0.9; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   3.8s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   3.8s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   5.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   5.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=500, subsample=0.7; total time=   3.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   3.5s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=700, subsample=0.7; total time=   4.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=700, subsample=0.9; total time=   4.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=300, subsample=0.9; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=500, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=700, subsample=0.7; total time=   4.5s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=700, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.9; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.7; total time=   1.4s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   1.0s[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.7; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.7; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.9; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=500, subsample=0.7; total time=   0.9s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=500, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=700, subsample=0.7; total time=   1.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=700, subsample=0.7; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   2.5s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   1.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=500, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=700, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=300, subsample=0.7; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=300, subsample=0.7; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=300, subsample=0.9; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=500, subsample=0.7; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=500, subsample=0.9; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=700, subsample=0.7; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=5, n_estimators=700, subsample=0.9; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=300, subsample=0.9; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   3.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   3.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=700, subsample=0.7; total time=   4.8s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   5.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=500, subsample=0.7; total time=   3.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=500, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=700, subsample=0.7; total time=   4.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=3, n_estimators=700, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=300, subsample=0.7; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=300, subsample=0.9; total time=   2.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=500, subsample=0.7; total time=   3.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=500, subsample=0.9; total time=   3.4s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=700, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=700, subsample=0.9; total time=   4.2s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.7; total time=   1.4s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   0.9s
[CV] END colsample_bytree=0.7, learning_rate=0.03, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.7; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.7; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=300, subsample=0.9; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.7; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=500, subsample=0.9; total time=   0.9s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.7; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=3, n_estimators=700, subsample=0.9; total time=   1.2s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=300, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=300, subsample=0.9; total time=   0.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=500, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=500, subsample=0.9; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=700, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.7; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=300, subsample=0.9; total time=   1.1s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=500, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=500, subsample=0.9; total time=   1.7s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=700, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=700, subsample=0.9; total time=   2.3s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=6, min_child_weight=3, n_estimators=300, subsample=0.8; total time=   1.2s

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=42, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.7, 0.8],
                         'learning_rate': [0.01, 0.03, 0.05],
                         'max_depth': [4, 6, 8], 'min_child_weight': [1, 3, 5],
                         'n_estimators': [300, 500, 700],
                         'subsample': [0.7, 0.8, 0.9]},
             scoring='neg_mean_absolute_error', verbose=2)

In [14]:
best_model = grid_search.best_estimator_

In [15]:
best_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=8, max_leaves=None,
             min_child_weight=5, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=700, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [16]:
from sklearn.metrics import mean_absolute_error

preds = best_model.predict(X_test)

mae = mean_absolute_error(y_test, preds)

print("MAE:", mae)

MAE: 17.23902228356668