In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data_final_final.csv")

In [3]:
pd.set_option("display.max_columns",None)

In [4]:
data = data.drop(columns = ['stage_3rd Place Play-Off'])

KeyError: "['stage_3rd Place Play-Off'] not found in axis"

In [5]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
0,548341,Ashish Reddy,58.0,Subrata Roy Sahara Stadium,2012,1,35.672040,80.762144,0.0,39.250000,58.00,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,2068.978308,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
1,548346,Ashish Reddy,41.0,Wankhede Stadium,2012,2,35.672040,80.762144,0.0,30.000000,41.00,1.035196,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,35.672040,1462.553632,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
2,548348,Ashish Reddy,23.0,Barabati Stadium,2012,3,35.672040,80.762144,0.0,39.250000,23.00,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,820.456915,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,548352,Ashish Reddy,28.0,MA Chidambaram Stadium,2012,4,40.666667,80.762144,0.0,47.333333,45.00,0.984847,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,38.668816,1740.096716,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
4,548356,Ashish Reddy,33.0,M Chinnaswamy Stadium,2012,5,30.666667,80.762144,0.0,38.714286,31.75,1.016059,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,32.668816,1037.234905,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Rajiv Gandhi International Stadium,2025,6,3.333333,0.000000,0.8,18.500000,6.75,0.994802,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,13.247204,89.418627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True
25121,1473480,Zeeshan Ansari,0.0,MA Chidambaram Stadium,2025,7,11.666667,0.000000,0.4,0.000000,0.00,0.984847,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,14.647204,0.000000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
25122,1473488,Zeeshan Ansari,23.0,Narendra Modi Stadium,2025,8,12.333333,0.000000,0.2,11.500000,23.00,1.079940,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,13.067204,300.545692,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25123,1473492,Zeeshan Ansari,4.0,Rajiv Gandhi International Stadium,2025,9,16.000000,0.000000,0.4,44.500000,6.75,0.994802,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,16.647204,112.368627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25124,1473499,Zeeshan Ansari,-2.0,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025,10,9.000000,0.000000,0.4,-2.000000,-2.00,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,12.807204,-25.614408,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

In [6]:
# data['recent_form'] = (data['last3_avg_points']*0.6 + data['last5_avg_points']*0.3 + data['last10_avg_points']*0.1)

In [7]:
# data['venue_form'] = data['venue_avg_points'] * data['recent_form']

In [8]:
data.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'venue_avg_points',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'player_role_wicketkeeper', 'recent_form',
       'venue_form', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'pitch_type_batting_friendly', 'pitch_type_pace_friendly',
       'pitch_type_spin_friendly', 'player_role_batsman',
       'player_role_bowler'],
      dtype='object')

In [9]:
# colsToDrop =  ['last5_avg_points',
#               'last10_avg_points',
#               'bat_pos_per_match',
#               'match_month',
#               'stage_Elimination Final',
#               'stage_Eliminator',
#               'stage_Final',
#               'stage_Qualifier 1',
#               'stage_Qualifier 2',
#               'stage_Semi Final',
#               'stage_Unknown']
# data = data.drop(columns = colsToDrop)

In [10]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
0,548341,Ashish Reddy,58.0,Subrata Roy Sahara Stadium,2012,1,35.672040,80.762144,0.0,39.250000,58.00,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,2068.978308,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
1,548346,Ashish Reddy,41.0,Wankhede Stadium,2012,2,35.672040,80.762144,0.0,30.000000,41.00,1.035196,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,35.672040,1462.553632,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
2,548348,Ashish Reddy,23.0,Barabati Stadium,2012,3,35.672040,80.762144,0.0,39.250000,23.00,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,820.456915,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,548352,Ashish Reddy,28.0,MA Chidambaram Stadium,2012,4,40.666667,80.762144,0.0,47.333333,45.00,0.984847,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,38.668816,1740.096716,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
4,548356,Ashish Reddy,33.0,M Chinnaswamy Stadium,2012,5,30.666667,80.762144,0.0,38.714286,31.75,1.016059,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,32.668816,1037.234905,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Rajiv Gandhi International Stadium,2025,6,3.333333,0.000000,0.8,18.500000,6.75,0.994802,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,13.247204,89.418627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True
25121,1473480,Zeeshan Ansari,0.0,MA Chidambaram Stadium,2025,7,11.666667,0.000000,0.4,0.000000,0.00,0.984847,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,14.647204,0.000000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
25122,1473488,Zeeshan Ansari,23.0,Narendra Modi Stadium,2025,8,12.333333,0.000000,0.2,11.500000,23.00,1.079940,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,13.067204,300.545692,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25123,1473492,Zeeshan Ansari,4.0,Rajiv Gandhi International Stadium,2025,9,16.000000,0.000000,0.4,44.500000,6.75,0.994802,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,16.647204,112.368627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25124,1473499,Zeeshan Ansari,-2.0,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025,10,9.000000,0.000000,0.4,-2.000000,-2.00,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,12.807204,-25.614408,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

In [11]:
data['season'] = data['season'].str[:4].astype(int)
data['season'].unique()

array([2012, 2013, 2015, 2016, 2022, 2023, 2024, 2025, 2007, 2009, 2017,
       2018, 2011, 2014, 2019, 2020, 2021])

In [12]:
train = data[data['season'] <= 2022].copy()
test  = data[data['season'] > 2022].copy()
X_train = train.drop(columns=['fantasy_points','player','venue','season','player_role_batsman','player_role_bowler','match_id','player_match_number'])
y_train = train['fantasy_points']

X_test = test.drop(columns=['fantasy_points','player','venue','season','player_role_batsman','player_role_bowler','match_id','player_match_number'])
y_test = test['fantasy_points']

print(X_test.shape)
print(X_train.shape)
print(test.shape)
print(train.shape)

(4995, 47)
(20130, 47)
(4995, 55)
(20130, 55)

In [13]:
# from lightgbm import LGBMRegressor
# from sklearn.model_selection import GridSearchCV

# lgbm = LGBMRegressor(
#     objective="regression",
#     n_estimators=800,
#     random_state=42,
#     reg_alpha=0.1,
#     reg_lambda=1
# )

# param_grid = {

#     "num_leaves": [100,140],

#     "max_depth": [7,9],

#     "learning_rate": [0.018,0.022],

#     "subsample": [0.85, 0.9],

#     "colsample_bytree": [0.55, 0.6],

#     "min_child_samples": [5, 8]
# }

# grid = GridSearchCV(
#     estimator=lgbm,
#     param_grid=param_grid,
#     scoring="neg_mean_absolute_error",
#     cv=2,
#     verbose=2,
#     n_jobs=-1
# )

# grid.fit(X_train, y_train)

# print("Best Params:", grid.best_params_)
# print("Best MAE:", -grid.best_score_)

In [65]:
from lightgbm import LGBMRegressor
best_params = {'subsample': 1, 'num_leaves': 120, 'min_child_samples': 5, 'max_depth': 8, 'learning_rate': 0.02, 'colsample_bytree': 0.6}
# best_params = {'subsample': 0.9, 'num_leaves': 135, 'min_child_samples': 5, 'max_depth': 10, 'learning_rate': 0.02, 'colsample_bytree': 0.6}
final_model = LGBMRegressor(
    n_estimators=600,
    random_state=42,
    reg_alpha = 0.1,
    reg_lambda = 1,
    **best_params
)

final_model.fit(
    X_train,
    y_train,
)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001006 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3129
[LightGBM] [Info] Number of data points in the train set: 20130, number of used features: 47
[LightGBM] [Info] Start training from score 35.483756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(colsample_bytree=0.6, learning_rate=0.02, max_depth=8,
              min_child_samples=5, n_estimators=600, num_leaves=120,
              random_state=42, reg_alpha=0.1, reg_lambda=1, subsample=1)

In [66]:
y_pred = final_model.predict(X_test)

In [67]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test, y_pred))

14.308433729616489

In [68]:
test['predictions'] = y_pred

In [69]:
# import joblib
# le_player = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/encoders/player_encoder.pkl")
# le_venue = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/encoders/venue_encoder.pkl")
# test['player'] = le_player.inverse_transform(test['player'])
# test['venue'] = le_venue.inverse_transform(test['venue'])
# test

In [70]:
test.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'venue_avg_points',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'player_role_wicketkeeper', 'recent_form',
       'venue_form', 'team_Deccan Chargers', 'team_Delhi Capitals',
       'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'pitch_type_batting_friendly', 'pitch_type_pace_friendly',
       'pitch_type_spin_friendly', 'player_role_batsman', 'player_role_bowler',
       'predictions'],
      dtype='object')

In [71]:
best_team_actual = (
    test.sort_values(['match_id','fantasy_points'], ascending=[True, False])
        .groupby('match_id')
        .head(11)
)
best_team_actual

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,predictions
17412,1359475,Ruturaj Gaikwad,136.0,Narendra Modi Stadium,2023,37,25.666667,101.605479,0.0,70.857143,59.000000,1.079940,1.0,0.0,44.810713,1.071172,-22.333333,1.0,0.760870,0,31.300000,1846.700000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,77.480103
22337,1359475,Shubman Gill,97.0,Narendra Modi Stadium,2023,71,35.000000,106.154322,0.0,40.250000,64.280000,1.079940,1.0,0.0,27.011109,1.392020,-2.600000,2.0,0.666667,0,37.000000,2378.360000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,51.736618
18253,1359475,Rajvardhan Hangargekar,79.0,Narendra Modi Stadium,2023,1,35.672040,80.762144,0.0,79.000000,79.000000,1.079940,0.0,1.0,0.000000,0.000000,0.000000,11.0,0.000000,0,35.672040,2818.091144,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,91.405971
18614,1359475,Rashid Khan,73.0,Narendra Modi Stadium,2023,93,37.000000,63.333333,1.6,43.944444,37.521739,1.079940,0.2,0.8,39.242975,1.291951,-13.700000,8.0,1.000000,0,43.470000,1631.070000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,36.361741
13812,1359475,Mohammed Shami,58.0,Narendra Modi Stadium,2023,94,22.000000,0.000000,1.0,30.000000,43.642857,1.079940,0.0,1.0,29.628065,1.296068,-16.400000,9.0,0.000000,0,27.420000,1196.687143,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,37.743731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22576,1485779,Tristan Stubbs,60.0,Sawai Mansingh Stadium,2025,31,27.333333,119.222222,0.0,32.500000,65.000000,0.988582,1.0,0.0,22.232109,1.547312,-7.066667,6.0,0.444444,1,27.880000,1812.200000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,48.941314
23558,1485779,Vikas Nigam,58.0,Sawai Mansingh Stadium,2025,14,20.666667,141.176471,0.4,58.000000,58.000000,0.988582,0.0,1.0,41.108123,0.805194,-12.433333,7.0,0.000000,0,27.590000,1600.220000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,61.279633
10239,1485779,KL Rahul,51.0,Sawai Mansingh Stadium,2025,135,60.000000,134.439560,0.0,38.800000,70.600000,0.988582,1.0,0.0,54.970699,1.073299,1.000000,1.0,0.857143,1,56.060000,3957.836000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,50.391420
10753,1485779,Kuldeep Yadav,50.0,Sawai Mansingh Stadium,2025,98,10.000000,37.500000,0.2,31.363636,29.500000,0.988582,0.0,1.0,25.299319,0.810298,-10.500000,9.0,0.000000,0,9.910000,292.345000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,35.464878
8984,1485779,Josh Inglis,49.0,Sawai Mansingh Stadium,2025,7,28.333333,150.112045,0.0,49.000000,79.500000,0.988582,1.0,0.0,14.746751,0.000000,0.000000,3.0,0.750000,1,29.927204,2379.212716,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,87.336675

In [72]:
best_team_predicted = (
    test.sort_values(['match_id','predictions'], ascending=[True, False])
        .groupby('match_id')
        .head(11)
)

In [73]:
best_team_predicted

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,predictions
18253,1359475,Rajvardhan Hangargekar,79.0,Narendra Modi Stadium,2023,1,35.672040,80.762144,0.0,79.000000,79.000000,1.079940,0.000000,1.000000,0.000000,0.000000,0.000000,11.0,0.000000,0,35.672040,2818.091144,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,91.405971
3100,1359475,Sai Sudharsan,27.0,Narendra Modi Stadium,2023,6,41.000000,128.334364,0.0,80.000000,70.210526,1.079940,1.000000,0.000000,26.975915,0.000000,0.000000,3.0,0.545455,0,39.507204,2773.821585,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,81.821091
17412,1359475,Ruturaj Gaikwad,136.0,Narendra Modi Stadium,2023,37,25.666667,101.605479,0.0,70.857143,59.000000,1.079940,1.000000,0.000000,44.810713,1.071172,-22.333333,1.0,0.760870,0,31.300000,1846.700000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,77.480103
17153,1359475,Ravindra Jadeja,34.0,Narendra Modi Stadium,2023,204,18.000000,102.416667,0.2,50.857143,43.600000,1.079940,0.029412,0.970588,26.597619,1.282070,-16.100000,6.0,0.000000,0,21.530000,938.708000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,57.381253
22337,1359475,Shubman Gill,97.0,Narendra Modi Stadium,2023,71,35.000000,106.154322,0.0,40.250000,64.280000,1.079940,1.000000,0.000000,27.011109,1.392020,-2.600000,2.0,0.666667,0,37.000000,2378.360000,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,51.736618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6092,1485779,Faf du Plessis,39.0,Sawai Mansingh Stadium,2025,147,3.666667,80.424675,0.0,64.444444,43.000000,0.988582,1.000000,0.000000,37.196923,1.008148,-33.833333,2.0,0.608696,0,13.030000,560.290000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,57.283048
10239,1485779,KL Rahul,51.0,Sawai Mansingh Stadium,2025,135,60.000000,134.439560,0.0,38.800000,70.600000,0.988582,1.000000,0.000000,54.970699,1.073299,1.000000,1.0,0.857143,1,56.060000,3957.836000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,50.391420
14100,1485779,Mustafizur Rahman,79.0,Sawai Mansingh Stadium,2025,60,13.000000,0.000000,0.8,34.428571,52.000000,0.988582,0.000000,1.000000,17.771700,1.603673,-15.500000,11.0,0.000000,0,17.250000,897.000000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,49.639978
22576,1485779,Tristan Stubbs,60.0,Sawai Mansingh Stadium,2025,31,27.333333,119.222222,0.0,32.500000,65.000000,0.988582,1.000000,0.000000,22.232109,1.547312,-7.066667,6.0,0.444444,1,27.880000,1812.200000,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,48.941314
15030,1485779,Prabhsimran Singh,38.0,Sawai Mansingh Stadium,2025,48,78.666667,181.537037,0.0,54.833333,31.333333,0.988582,1.000000,0.000000,37.735336,1.621822,17.466667,2.0,0.785714,1,79.000000,2475.333333,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,46.205362

In [74]:
print("Actual:")
print(best_team_actual[best_team_actual['match_id'] == 1359475]['player'])
print("Predicted-:")
print(best_team_predicted[best_team_predicted['match_id'] == 1359475]['player'])

Actual:
17412           Ruturaj Gaikwad
22337              Shubman Gill
18253    Rajvardhan Hangargekar
18614               Rashid Khan
13812            Mohammed Shami
24187           Wriddhiman Saha
1976             Alzarri Joseph
23725             Vijay Shankar
17153           Ravindra Jadeja
7850              Joshua Little
12795                 Moeen Ali
Name: player, dtype: object
Predicted-:
18253    Rajvardhan Hangargekar
3100              Sai Sudharsan
17412           Ruturaj Gaikwad
17153           Ravindra Jadeja
22337              Shubman Gill
23725             Vijay Shankar
13812            Mohammed Shami
18614               Rashid Khan
22979          Tushar Deshpande
13441                  MS Dhoni
1976             Alzarri Joseph
Name: player, dtype: object

In [75]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 14.308433729616489
RMSE: 21.105994096872717
R2: 0.619056088055026

In [76]:
from scipy.stats import spearmanr

corr, _ = spearmanr(y_test, y_pred)
print("Spearman Rank Correlation:", corr)

Spearman Rank Correlation: 0.8224615853566056

In [77]:
results = X_test.copy()

results['actual_points'] = y_test
results['predicted_points'] = y_pred
results['player'] = test['player']
results['match_id'] = test['match_id']

In [78]:
results

,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,actual_points,predicted_points,player,match_id
39,25.666667,76.666667,0.4,31.333333,28.277778,1.040207,1.0,0.0,10.926014,2.159983,2.066667,6.0,0.888889,0,26.040000,736.353333,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,23.0,28.683637,Ayush Badoni,1359477
40,21.000000,102.640693,0.2,39.500000,16.000000,0.984847,1.0,0.0,10.926014,2.159983,-2.600000,6.0,0.000000,0,22.160000,354.560000,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,23.0,8.227318,Ayush Badoni,1359480
41,23.000000,108.196248,0.2,11.400000,18.000000,1.016059,1.0,0.0,10.298328,2.184821,0.500000,6.0,0.533333,0,23.430000,421.740000,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,38.0,18.503897,Ayush Badoni,1359489
42,28.000000,116.529582,0.2,43.000000,28.277778,1.040207,1.0,0.0,11.370527,2.128309,3.800000,6.0,0.000000,0,26.660000,753.885556,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,5.0,10.353528,Ayush Badoni,1359495
43,22.000000,118.650794,0.2,21.000000,23.000000,0.988582,1.0,0.0,11.370527,2.128309,-2.200000,6.0,0.000000,0,22.340000,513.820000,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,1.0,8.943602,Ayush Badoni,1359500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,3.333333,0.000000,0.8,18.500000,6.750000,0.994802,0.0,1.0,36.004166,0.000000,0.000000,11.0,0.000000,0,13.247204,89.418627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,25.0,8.762191,Zeeshan Ansari,1473478
25121,11.666667,0.000000,0.4,0.000000,0.000000,0.984847,0.0,0.0,32.204037,0.000000,0.000000,11.0,0.000000,0,14.647204,0.000000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0.0,-0.095852,Zeeshan Ansari,1473480
25122,12.333333,0.000000,0.2,11.500000,23.000000,1.079940,0.0,1.0,30.937725,0.000000,0.000000,11.0,0.000000,0,13.067204,300.545692,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,23.0,19.665140,Zeeshan Ansari,1473488
25123,16.000000,0.000000,0.4,44.500000,6.750000,0.994802,-0.0,1.0,28.645618,0.000000,0.000000,11.0,0.000000,0,16.647204,112.368627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,4.0,12.905198,Zeeshan Ansari,1473492
25124,9.000000,0.000000,0.4,-2.000000,-2.000000,1.040207,-0.0,1.0,27.459060,0.000000,0.000000,11.0,0.000000,0,12.807204,-25.614408,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,-2.0,-3.668508,Zeeshan Ansari,1473499

In [79]:
correct_counts = []

for match in results['match_id'].unique():

    match_df = results[results['match_id'] == match]

    predicted_top11 = match_df.sort_values(
        'predicted_points', ascending=False
    ).head(11)['player']

    actual_top11 = match_df.sort_values(
        'actual_points', ascending=False
    ).head(11)['player']

    overlap = len(set(predicted_top11) & set(actual_top11))

    correct_counts.append(overlap)

print("Average correct players in top 11:", sum(correct_counts)/len(correct_counts))

Average correct players in top 11: 8.986301369863014

In [80]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
0,548341,Ashish Reddy,58.0,Subrata Roy Sahara Stadium,2012,1,35.672040,80.762144,0.0,39.250000,58.00,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,2068.978308,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
1,548346,Ashish Reddy,41.0,Wankhede Stadium,2012,2,35.672040,80.762144,0.0,30.000000,41.00,1.035196,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,35.672040,1462.553632,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
2,548348,Ashish Reddy,23.0,Barabati Stadium,2012,3,35.672040,80.762144,0.0,39.250000,23.00,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,820.456915,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,548352,Ashish Reddy,28.0,MA Chidambaram Stadium,2012,4,40.666667,80.762144,0.0,47.333333,45.00,0.984847,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,38.668816,1740.096716,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
4,548356,Ashish Reddy,33.0,M Chinnaswamy Stadium,2012,5,30.666667,80.762144,0.0,38.714286,31.75,1.016059,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,32.668816,1037.234905,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Rajiv Gandhi International Stadium,2025,6,3.333333,0.000000,0.8,18.500000,6.75,0.994802,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,13.247204,89.418627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True
25121,1473480,Zeeshan Ansari,0.0,MA Chidambaram Stadium,2025,7,11.666667,0.000000,0.4,0.000000,0.00,0.984847,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,14.647204,0.000000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
25122,1473488,Zeeshan Ansari,23.0,Narendra Modi Stadium,2025,8,12.333333,0.000000,0.2,11.500000,23.00,1.079940,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,13.067204,300.545692,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25123,1473492,Zeeshan Ansari,4.0,Rajiv Gandhi International Stadium,2025,9,16.000000,0.000000,0.4,44.500000,6.75,0.994802,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,16.647204,112.368627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25124,1473499,Zeeshan Ansari,-2.0,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025,10,9.000000,0.000000,0.4,-2.000000,-2.00,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,12.807204,-25.614408,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

In [418]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv",index = False)