In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/half_processed/half_prepared_data.csv")

In [3]:
pd.set_option("display.max_columns",None)

In [4]:
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,0.0,7.0
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,NaN,0.0,NaN,7.0,0.6,8.0
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,0.0,7.0
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,NaN,7.0,0.0,6.0
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,NaN,7.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,NaN,NaN,0.0,NaN
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,NaN,NaN,0.0,NaN
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,11.500000,NaN,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,NaN,NaN,0.0,NaN
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,NaN,NaN,0.0,NaN
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.000000,NaN,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,NaN,NaN,0.0,NaN

In [5]:
player_mapping = {
    'A Ashish Reddy': 'Ashish Reddy',
    'A Badoni': 'Ayush Badoni',
    'A Chandila': 'Ajit Chandila',
    'A Chopra': 'Aakash Chopra',
    'A Choudhary': 'Aniket Choudhary',
    'A Dananjaya': 'Akila Dananjaya',
    'A Flintoff': 'Andrew Flintoff',
    'A Kamboj': 'Anshul Kamboj',
    'A Kumble': 'Anil Kumble',
    'A Manohar': 'Abhinav Manohar',
    'A Mhatre': 'Ayush Mhatre',
    'A Mishra': 'Amit Mishra',
    'A Mithun': 'Abhimanyu Mithun',
    'A Mukund': 'Abhinav Mukund',
    'A Nehra': 'Ashish Nehra',
    'A Nel': 'André Nel',
    'A Nortje': 'Anrich Nortje',
    'A Raghuvanshi': 'Angkrish Raghuvanshi',
    'A Singh': 'Anureet Singh',
    'A Symonds': 'Andrew Symonds',
    'A Tomar': 'Anshuman Tomar',
    'A Uniyal': 'Amit Uniyal',
    'A Zampa': 'Adam Zampa',
    'AA Bilakhia': 'Akshath Bilakhia',
    'AA Chavan': 'Ankeet Chavan',
    'AA Jhunjhunwala': 'Abhishek Jhunjhunwala',
    'AA Kazi': 'Abrar Kazi',
    'AA Kulkarni': 'Arshin Kulkarni',
    'AA Noffke': 'Ashley Noffke',
    'AB Agarkar': 'Ajit Agarkar',
    'AB Barath': 'Adrian Barath',
    'AB Dinda': 'Ashoke Dinda',
    'AB McDonald': 'Andrew McDonald',
    'AB de Villiers': 'AB de Villiers',
    'AC Blizzard': 'Aiden Blizzard',
    'AC Gilchrist': 'Adam Gilchrist',
    'AC Thomas': 'Alfonso Thomas',
    'AC Voges': 'Adam Voges',
    'AD Hales': 'Alex Hales',
    'AD Mascarenhas': 'Dimitri Mascarenhas',
    'AD Mathews': 'Angelo Mathews',
    'AD Nath': 'Akshdeep Nath',
    'AD Russell': 'Andre Russell',
    'AF Milne': 'Adam Milne',
    'AG Murtaza': 'Ali Murtaza',
    'AG Paunikar': 'Amit Paunikar',
    'AJ Finch': 'Aaron Finch',
    'AJ Hosein': 'Akeal Hosein',
    'AJ Turner': 'Ashton Turner',
    'AJ Tye': 'Andrew Tye',
    'AK Markram': 'Aiden Markram',
    'AL Menaria': 'Ashok Menaria',
    'AM Nayar': 'Abhishek Nayar',
    'AM Rahane': 'Ajinkya Rahane',
    'AM Salvi': 'Aavishkar Salvi',
    'AN Ahmed': 'Abu Nechim',
    'AN Ghosh': 'Arindam Ghosh',
    'AP Dole': 'Aditya Dole',
    'AP Majumdar': 'Anustup Majumdar',
    'AP Tare': 'Aditya Tare',
    'AR Bawne': 'Ankit Bawne',
    'AR Patel': 'Axar Patel',
    'AS Joseph': 'Alzarri Joseph',
    'AS Rajpoot': 'Ankit Rajpoot',
    'AS Raut': 'Abhishek Raut',
    'AS Roy': 'Anukul Roy',
    'AS Yadav': 'Suryakumar Yadav',
    'AT Carey': 'Alex Carey',
    'AT Rayudu': 'Ambati Rayudu',
    'AU Rashid': 'Adil Rashid',
    'AUK Pathan': 'Asad Pathan',
    'B Akhil': 'Balachandra Akhil',
    'B Chipli': 'Bharat Chipli',
    'B Geeves': 'Brett Geeves',
    'B Indrajith': 'Baba Indrajith',
    'B Kumar': 'Bhuvaneshwar Kumar',
    'B Laughlin': 'Ben Laughlin',
    'B Lee': 'Brett Lee',
    'B Sai Sudharsan': 'Sai Sudharsan',
    'B Stanlake': 'Billy Stanlake',
    'B Sumanth': 'Bodanapu Sumanth',
    'BA Bhatt': 'Bhargav Bhatt',
    'BA Stokes': 'Ben Stokes',
    'BAW Mendis': 'Ajantha Mendis',
    'BB McCullum': 'Brendon McCullum',
    'BB Samantray': 'Biplab Samantray',
    'BB Sran': 'Barinder Sran',
    'BCJ Cutting': 'Ben Cutting',
    'BE Hendricks': 'Beuran Hendricks',
    'BJ Haddin': 'Brad Haddin',
    'BJ Hodge': 'Brad Hodge',
    'BJ Rohrer': 'Ben Rohrer',
    'BKG Mendis': 'Jeevan Mendis',
    'BMAJ Mendis': 'Jeevan Mendis',
    'BR Dunk': 'Ben Dunk',
    'BR Sharath': 'Barafe Sharath',
    'BW Hilfenhaus': 'Ben Hilfenhaus',
    'C Bosch': 'Corbin Bosch',
    'C Ganapathy': 'Chandrasekar Ganapathy',
    'C Green': 'Cameron Green',
    'C Madan': 'Chandan Madan',
    'C Munro': 'Colin Munro',
    'C Nanda': 'Chetan Nanda',
    'C Sakariya': 'Chetan Sakariya',
    'C de Grandhomme': 'Colin de Grandhomme',
    'CA Ingram': 'Colin Ingram',
    'CA Lynn': 'Chris Lynn',
    'CA Pujara': 'Cheteshwar Pujara',
    'CH Gayle': 'Chris Gayle',
    'CH Morris': 'Chris Morris',
    'CJ Anderson': 'Corey Anderson',
    'CJ Dala': 'Junior Dala',
    'CJ Ferguson': 'Callum Ferguson',
    'CJ Green': 'Chris Green',
    'CJ Jordan': 'Chris Jordan',
    'CJ McKay': 'Clint McKay',
    'CK Kapugedera': 'Chamara Kapugedera',
    'CK Langeveldt': 'Charl Langeveldt',
    'CL White': 'Cameron White',
    'CM Gautam': 'C. M. Gautam',
    'CR Brathwaite': 'Carlos Brathwaite',
    'CR Woakes': 'Chris Woakes',
    'CRD Fernando': 'Dilhara Fernando',
    'CV Varun': 'Varun Chakravarthy',
    'D Brevis': 'Dewald Brevis',
    'D Ferreira': 'Donovan Ferreira',
    'D Jansen': 'Duan Jansen',
    'D Kalyankrishna': 'Doddapaneni Kalyankrishna',
    'D Padikkal': 'Devdutt Padikkal',
    'D Pretorius': 'Dwaine Pretorius',
    'D Salunkhe': 'Dinesh Salunkhe',
    'D Wiese': 'David Wiese',
    'D du Preez': 'Dillon du Preez',
    'DA Miller': 'David Miller',
    'DA Warner': 'David Warner',
    'DAJ Bracewell': 'Doug Bracewell',
    'DB Das': 'Debabrata Das',
    'DB Ravi Teja': 'Dwaraka Ravi Teja',
    'DE Bollinger': 'Doug Bollinger',
    'DG Nalkande': 'Darshan Nalkande',
    'DH Yagnik': 'Dishant Yagnik',
    'DJ Bravo': 'Dwayne Bravo',
    'DJ Harris': 'Daniel Harris',
    'DJ Hooda': 'Deepak Hooda',
    'DJ Hussey': 'David Hussey',
    'DJ Jacobs': 'Davy Jacobs',
    'DJ Malan': 'Dawid Malan',
    'DJ Mitchell': 'Daryl Mitchell',
    'DJ Muthuswami': 'Domnic Muthuswami',
    'DJ Thornely': 'Dominic Thornely',
    'DJ Willey': 'David Willey',
    'DJG Sammy': 'Darren Sammy',
    'DJM Short': "D'Arcy Short",
    'DL Chahar': 'Deepak Chahar',
    'DL Vettori': 'Daniel Vettori',
    'DM Bravo': 'Darren Bravo',
    'DNT Zoysa': 'Nuwan Zoysa',
    'DP Conway': 'Devon Conway',
    'DP Nannes': 'Dirk Nannes',
    'DP Vijaykumar': 'Doddapaneni Vijaykumar',
    'DPMD Jayawardene': 'Mahela Jayawardene',
    'DR Martyn': 'Damien Martyn',
    'DR Sams': 'Daniel Sams',
    'DR Shorey': 'Dhruv Shorey',
    'DR Smith': 'Dwayne Smith',
    'DS Kulkarni': 'Dhawal Kulkarni',
    'DS Lehmann': 'Darren Lehmann',
    'DS Rathi': 'Dhruv Rathi',
    'DT Christian': 'Dan Christian',
    'DT Patil': 'Dinesh Patil',
    'DW Steyn': 'Dale Steyn',
    'E Lewis': 'Evin Lewis',
    'E Malinga': 'Lasith Malinga',
    'EJG Morgan': 'Eoin Morgan',
    'ER Dwivedi': 'Eklavya Dwivedi',
    'F Behardien': 'Farhaan Behardien',
    'F du Plessis': 'Faf du Plessis',
    'FA Allen': 'Fabian Allen',
    'FH Edwards': 'Fidel Edwards',
    'FY Fazal': 'Faiz Fazal',
    'G Coetzee': 'Gerald Coetzee',
    'G Gambhir': 'Gautam Gambhir',
    'GB Hogg': 'Brad Hogg',
    'GC Smith': 'Graeme Smith',
    'GC Viljoen': 'Hardus Viljoen',
    'GD McGrath': 'Glenn McGrath',
    'GD Phillips': 'Glenn Phillips',
    'GH Vihari': 'Hanuma Vihari',
    'GHS Garton': 'George Garton',
    'GJ Bailey': 'George Bailey',
    'GJ Maxwell': 'Glenn Maxwell',
    'GR Napier': 'Graham Napier',
    'GS Sandhu': 'Gurinder Sandhu',
    'H Das': 'Halhadar Das',
    'H Klaasen': 'Heinrich Klaasen',
    'H Sharma': 'Himanshu Sharma',
    'HC Brook': 'Harry Brook',
    'HE van der Dussen': 'Rassie van der Dussen',
    'HF Gurney': 'Harry Gurney',
    'HH Gibbs': 'Herschelle Gibbs',
    'HH Pandya': 'Hardik Pandya',
    'HM Amla': 'Hashim Amla',
    'HR Shokeen': 'Hrithik Shokeen',
    'HV Patel': 'Harshal Patel',
    'I Malhotra': 'Ishan Malhotra',
    'I Sharma': 'Ishant Sharma',
    'I Udana': 'Isuru Udana',
    'IC Pandey': 'Ishwar Pandey',
    'IC Porel': 'Ishan Porel',
    'IK Pathan': 'Irfan Pathan',
    'IR Jaggi': 'Ishank Jaggi',
    'IS Sodhi': 'Ish Sodhi',
    'J Arunkumar': 'Jagadeesh Arunkumar',
    'J Botha': 'Johan Botha',
    'J Fraser-McGurk': 'Jake Fraser-McGurk',
    'J Little': 'Joshua Little',
    'J Overton': 'Jamie Overton',
    'J Suchith': 'Jagadeesha Suchith',
    'J Syed Mohammad': 'Jamaluddin Syed Mohammad',
    'J Theron': 'Juan Theron',
    'J Yadav': 'Jayant Yadav',
    'JA Morkel': 'Albie Morkel',
    'JA Richardson': 'Jhye Richardson',
    'JC Archer': 'Jofra Archer',
    'JC Buttler': 'Jos Buttler',
    'JD Ryder': 'Jesse Ryder',
    'JD Unadkat': 'Jaydev Unadkat',
    'JDP Oram': 'Jacob Oram',
    'JDS Neesham': 'Jimmy Neesham',
    'JE Root': 'Joe Root',
    'JE Taylor': 'Jerome Taylor',
    'JEC Franklin': 'James Franklin',
    'JG Bethell': 'Jacob Bethell',
    'JH Kallis': 'Jacques Kallis',
    'JJ Bumrah': 'Jasprit Bumrah',
    'JJ Roy': 'Jason Roy',
    'JJ van der Wath': 'Johan van der Wath',
    'JL Denly': 'Joe Denly',
    'JL Pattinson': 'James Pattinson',
    'JM Bairstow': 'Jonny Bairstow',
    'JM Kemp': 'Justin Kemp',
    'JM Sharma': 'Jitesh Sharma',
    'JO Holder': 'Jason Holder',
    'JP Behrendorff': 'Jason Behrendorff',
    'JP Duminy': 'JP Duminy',
    'JP Faulkner': 'James Faulkner',
    'JP Inglis': 'Josh Inglis',
    'JPR Scantlebury-Searles': 'Javon Searles',
    'JR Hazlewood': 'Josh Hazlewood',
    'JR Hopes': 'James Hopes',
    'JR Philippe': 'Josh Philippe',
    'JW Hastings': 'John Hastings',
    'K Goel': 'Karan Goel',
    'K Gowtham': 'Krishnappa Gowtham',
    'K Kartikeya': 'Kumar Kartikeya',
    'K Khejroliya': 'Kulwant Khejroliya',
    'K Rabada': 'Kagiso Rabada',
    'K Santokie': 'Krishmar Santokie',
    'K Upadhyay': 'Krishnakumar Upadhyay',
    'K Yadav': 'Kuldeep Yadav',
    'KA Jamieson': 'Kyle Jamieson',
    'KA Maharaj': 'Keshav Maharaj',
    'KA Pollard': 'Kieron Pollard',
    'KAJ Roach': 'Kemar Roach',
    'KB Arun Karthik': 'Arun Karthik',
    'KC Cariappa': 'K. C. Cariappa',
    'KC Sangakkara': 'Kumar Sangakkara',
    'KD Karthik': 'Dinesh Karthik',
    'KH Pandya': 'Krunal Pandya',
    'KJ Abbott': 'Kyle Abbott',
    'KK Ahmed': 'Khaleel Ahmed',
    'KK Cooper': 'Kevon Cooper',
    'KK Nair': 'Karun Nair',
    'KL Nagarkoti': 'Kamlesh Nagarkoti',
    'KL Rahul': 'KL Rahul',
    'KM Asif': 'KM Asif',
    'KM Jadhav': 'Kedar Jadhav',
    'KMA Paul': 'Keemo Paul',
    'KMDN Kulasekara': 'Nuwan Kulasekara',
    'KP Appanna': 'Kotarangada Appanna',
    'KP Pietersen': 'Kevin Pietersen',
    'KR Mayers': 'Kyle Mayers',
    'KR Sen': 'Kuldeep Sen',
    'KS Bharat': 'Srikar Bharat',
    'KS Rathore': 'Kunal Singh Rathore',
    'KS Sharma': 'Karn Sharma',
    'KS Williamson': 'Kane Williamson',
    'KT Maphaka': 'Kwena Maphaka',
    'KV Sharma': 'Karn Sharma',
    'KW Richardson': 'Kane Richardson',
    'L Ablish': 'Love Ablish',
    'L Balaji': 'Lakshmipathy Balaji',
    'L Ngidi': 'Lungi Ngidi',
    'L Ronchi': 'Luke Ronchi',
    'L Wood': 'Luke Wood',
    'LA Carseldine': 'Lee Carseldine',
    'LA Pomersbach': 'Luke Pomersbach',
    'LB Williams': 'Lizaad Williams',
    'LE Plunkett': 'Liam Plunkett',
    'LH Ferguson': 'Lockie Ferguson',
    'LI Meriwala': 'Lukman Meriwala',
    'LJ Wright': 'Luke Wright',
    'LMP Simmons': 'Lendl Simmons',
    'LPC Silva': 'Chamara Silva',
    'LR Shukla': 'Laxmi Ratan Shukla',
    'LRPL Taylor': 'Ross Taylor',
    'LS Livingstone': 'Liam Livingstone',
    'M Ashwin': 'Murugan Ashwin',
    'M Jansen': 'Marco Jansen',
    'M Kaif': 'Mohammad Kaif',
    'M Kartik': 'Murali Kartik',
    'M Klinger': 'Michael Klinger',
    'M Manhas': 'Mithun Manhas',
    'M Markande': 'Mayank Markande',
    'M Morkel': 'Morne Morkel',
    'M Muralitharan': 'Muttiah Muralitharan',
    'M Ntini': 'Makhaya Ntini',
    'M Pathirana': 'Matheesha Pathirana',
    'M Prasidh Krishna': 'Prasidh Krishna',
    'M Rawat': 'Mahesh Rawat',
    'M Shahrukh Khan': 'Shahrukh Khan',
    'M Siddharth': 'Manimaran Siddharth',
    'M Theekshana': 'Maheesh Theekshana',
    'M Tiwari': 'Manoj Tiwary',
    'M Vijay': 'Murali Vijay',
    'M Vohra': 'Manan Vohra',
    'M de Lange': 'Marchant de Lange',
    'MA Agarwal': 'Mayank Agarwal',
    'MA Khote': 'Musavir Khote',
    'MA Starc': 'Mitchell Starc',
    'MA Wood': 'Mark Wood',
    'MB Parmar': 'Mohnish Parmar',
    'MC Henriques': 'Moises Henriques',
    'MC Juneja': 'Manpreet Juneja',
    'MD Mishra': 'Mohnish Mishra',
    'MD Shanaka': 'Dasun Shanaka',
    'MDKJ Perera': 'Kusal Perera',
    'MEK Hussey': 'Michael Hussey',
    'MF Maharoof': 'Farveez Maharoof',
    'MG Bracewell': 'Michael Bracewell',
    'MG Johnson': 'Mitchell Johnson',
    'MG Neser': 'Michael Neser',
    'MJ Clarke': 'Michael Clarke',
    'MJ Guptill': 'Martin Guptill',
    'MJ Henry': 'Matt Henry',
    'MJ Lumb': 'Michael Lumb',
    'MJ McClenaghan': 'Mitchell McClenaghan',
    'MJ Owen': 'Mitchell Owen',
    'MJ Santner': 'Mitchell Santner',
    'MJ Suthar': 'Manav Suthar',
    'MK Lomror': 'Mahipal Lomror',
    'MK Pandey': 'Manish Pandey',
    'MK Tiwary': 'Manoj Tiwary',
    'ML Hayden': 'Matthew Hayden',
    'MM Ali': 'Moeen Ali',
    'MM Patel': 'Munaf Patel',
    'MM Sharma': 'Mohit Sharma',
    'MN Samuels': 'Marlon Samuels',
    'MN van Wyk': 'Morne van Wyk',
    'MP Breetzke': 'Matthew Breetzke',
    'MP Stoinis': 'Marcus Stoinis',
    'MP Yadav': 'Mayank Yadav',
    'MR Marsh': 'Mitchell Marsh',
    'MS Bhandage': 'Manoj Bhandage',
    'MS Bisla': 'Manvinder Bisla',
    'MS Dhoni': 'MS Dhoni',
    'MS Gony': 'Manpreet Gony',
    'MS Wade': 'Matthew Wade',
    'MV Boucher': 'Mark Boucher',
    'MW Short': 'Matthew Short',
    'N Burger': 'Nandre Burger',
    'N Jagadeesan': 'Narayan Jagadeesan',
    'N Pooran': 'Nicholas Pooran',
    'N Rana': 'Nitish Rana',
    'N Saini': 'Navdeep Saini',
    'N Thushara': 'Nuwan Thushara',
    'N Wadhera': 'Nehal Wadhera',
    'NA Saini': 'Navdeep Saini',
    'NB Singh': 'Nikhil Singh',
    'ND Doshi': 'Nayan Doshi',
    'NJ Maddinson': 'Nic Maddinson',
    'NJ Rimmington': 'Nathan Rimmington',
    'NK Patel': 'Niraj Patel',
    'NL McCullum': 'Nathan McCullum',
    'NLTC Perera': 'Thisara Perera',
    'NM Coulter-Nile': 'Nathan Coulter-Nile',
    'NS Naik': 'Nikhil Naik',
    'NT Ellis': 'Nathan Ellis',
    'NV Ojha': 'Naman Ojha',
    'O Thomas': 'Oshane Thomas',
    'OA Shah': 'Owais Shah',
    'OC McCoy': 'Obed McCoy',
    'OF Smith': 'Odean Smith',
    'P Amarnath': 'Palani Amarnath',
    'P Awana': 'Parvinder Awana',
    'P Chopra': 'Prashant Chopra',
    'P Dogra': 'Paras Dogra',
    'P Dubey': 'Praveen Dubey',
    'P Kumar': 'Praveen Kumar',
    'P Negi': 'Pawan Negi',
    'P Parameswaran': 'Prasanth Parameswaran',
    'P Prasanth': 'Padmanabhan Prasanth',
    'P Ray Barman': 'Prayas Ray Barman',
    'P Sahu': 'Pardeep Sahu',
    'P Simran Singh': 'Prabhsimran Singh',
    'P Suyal': 'Pawan Suyal',
    'PA Patel': 'Parthiv Patel',
    'PA Reddy': 'Akshath Reddy',
    'PBB Rajapaksa': 'Bhanuka Rajapaksa',
    'PC Valthaty': 'Paul Valthaty',
    'PD Collingwood': 'Paul Collingwood',
    'PD Salt': 'Phil Salt',
    'PH Solanki': 'Prashant Solanki',
    'PHKD Mendis': 'Kamindu Mendis',
    'PJ Cummins': 'Pat Cummins',
    'PJ Sangwan': 'Pradeep Sangwan',
    'PK Garg': 'Priyam Garg',
    'PM Sarvesh Kumar': 'Sarvesh Kumar',
    'PN Mankad': 'Prerak Mankad',
    'PP Chawla': 'Piyush Chawla',
    'PP Ojha': 'Pragyan Ojha',
    'PP Shaw': 'Prithvi Shaw',
    'PR Shah': 'Pinal Shah',
    'PSP Handscomb': 'Peter Handscomb',
    'PV Tambe': 'Pravin Tambe',
    'PVD Chameera': 'Dushmantha Chameera',
    'PVSN Raju': 'Venugopal Rao',
    'PWA Mulder': 'Wiaan Mulder',
    'PWH de Silva': 'Wanindu Hasaranga',
    'Q de Kock': 'Quinton de Kock',
    'R Ashwin': 'Ravichandran Ashwin',
    'R Bhatia': 'Rajat Bhatia',
    'R Bishnoi': 'Ravi Bishnoi',
    'R Dhawan': 'Rishi Dhawan',
    'R Dravid': 'Rahul Dravid',
    'R Goyal': 'Ravi Goyal',
    'R McLaren': 'Ryan McLaren',
    'R Minz': 'Robin Minz',
    'R Ninan': 'Ryan Ninan',
    'R Parag': 'Riyan Parag',
    'R Powell': 'Rovman Powell',
    'R Rampaul': 'Ravi Rampaul',
    'R Ravindra': 'Rachin Ravindra',
    'R Sai Kishore': 'Ravisrinivasan Sai Kishore',
    'R Sanjay Yadav': 'Sanjay Yadav',
    'R Sathish': 'Rajagopal Sathish',
    'R Sharma': 'Rahul Sharma',
    'R Shepherd': 'Romario Shepherd',
    'R Shukla': 'Rahul Shukla',
    'R Tewatia': 'Rahul Tewatia',
    'R Vinay Kumar': 'Vinay Kumar',
    'RA Bawa': 'Raj Bawa',
    'RA Jadeja': 'Ravindra Jadeja',
    'RA Shaikh': 'Rahil Shaikh',
    'RA Tripathi': 'Rahul Tripathi',
    'RD Chahar': 'Rahul Chahar',
    'RD Gaikwad': 'Ruturaj Gaikwad',
    'RD Rickelton': 'Ryan Rickelton',
    'RE Levi': 'Richard Levi',
    'RE van der Merwe': 'Roelof van der Merwe',
    'RG More': 'Ronit More',
    'RG Sharma': 'Rohit Sharma',
    'RJ Gleeson': 'Richard Gleeson',
    'RJ Harris': 'Ryan Harris',
    'RJ Peterson': 'Robin Peterson',
    'RJ Quiney': 'Rob Quiney',
    'RJW Topley': 'Reece Topley',
    'RK Bhui': 'Ricky Bhui',
    'RK Singh': 'Rinku Singh',
    'RM Patidar': 'Rajat Patidar',
    'RN ten Doeschate': 'Ryan ten Doeschate',
    'RP Meredith': 'Riley Meredith',
    'RP Singh': 'R. P. Singh',
    'RR Bhatkal': 'Raju Bhatkal',
    'RR Bose': 'Ranadeb Bose',
    'RR Pant': 'Rishabh Pant',
    'RR Powar': 'Ramesh Powar',
    'RR Raje': 'Rohan Raje',
    'RR Rossouw': 'Rilee Rossouw',
    'RR Sarwan': 'Ramnaresh Sarwan',
    'RS Bopara': 'Ravi Bopara',
    'RS Gavaskar': 'Rohan Gavaskar',
    'RS Hangargekar': 'Rajvardhan Hangargekar',
    'RS Sodhi': 'Reetinder Sodhi',
    'RT Ponting': 'Ricky Ponting',
    'RV Gomez': 'Raiphi Gomez',
    'RV Patel': 'Ripal Patel',
    'RV Uthappa': 'Robin Uthappa',
    'RW Price': 'Ray Price',
    'S Anirudha': 'Anirudha Srikkanth',
    'S Aravind': 'Sreenath Aravind',
    'S Badree': 'Samuel Badree',
    'S Badrinath': 'Subramaniam Badrinath',
    'S Chanderpaul': 'Shivnarine Chanderpaul',
    'S Dhawan': 'Shikhar Dhawan',
    'S Dube': 'Shivam Dube',
    'S Gopal': 'Shreyas Gopal',
    'S Joseph': 'Shamar Joseph',
    'S Kaul': 'Siddharth Kaul',
    'S Kaushik': 'Shivil Kaushik',
    'S Ladda': 'Sarabjit Ladda',
    'S Lamichhane': 'Sandeep Lamichhane',
    'S Midhun': 'Sudhesan Midhun',
    'S Nadeem': 'Shahbaz Nadeem',
    'S Narwal': 'Sumit Narwal',
    'S Rana': 'Sachin Rana',
    'S Randiv': 'Suraj Randiv',
    'S Sandeep Warrier': 'Sandeep Warrier',
    'S Sohal': 'Sunny Sohal',
    'S Sreesanth': 'Sreesanth',
    'S Sriram': 'Sridharan Sriram',
    'S Tyagi': 'Sudeep Tyagi',
    'S Vidyut': 'Vidyut Sivaramakrishnan',
    'SA Abbott': 'Sean Abbott',
    'SA Asnodkar': 'Swapnil Asnodkar',
    'SA Yadav': 'Suryakumar Yadav',
    'SB Bangar': 'Sanjay Bangar',
    'SB Dubey': 'Shivam Dubey',
    'SB Jakati': 'Shadab Jakati',
    'SB Joshi': 'Sunil Joshi',
    'SB Styris': 'Scott Styris',
    'SB Wagh': 'Shrikant Wagh',
    'SC Ganguly': 'Sourav Ganguly',
    'SC Kuggeleijn': 'Scott Kuggeleijn',
    'SD Chitnis': 'Siddharth Chitnis',
    'SD Hope': 'Shai Hope',
    'SD Lad': 'Siddhesh Lad',
    'SE Bond': 'Shane Bond',
    'SE Marsh': 'Shaun Marsh',
    'SE Rutherford': 'Sherfane Rutherford',
    'SH Johnson': 'Spencer Johnson',
    'SJ Srivastava': 'Shalabh Srivastava',
    'SK Raina': 'Suresh Raina',
    'SK Rasheed': 'Shaik Rasheed',
    'SK Trivedi': 'Siddharth Trivedi',
    'SK Warne': 'Shane Warne',
    'SL Malinga': 'Lasith Malinga',
    'SM Boland': 'Scott Boland',
    'SM Curran': 'Sam Curran',
    'SM Harwood': 'Shane Harwood',
    'SM Katich': 'Simon Katich',
    'SM Pollock': 'Shaun Pollock',
    'SMSM Senanayake': 'Sachithra Senanayake',
    'SN Khan': 'Sarfaraz Khan',
    'SN Thakur': 'Shardul Thakur',
    'SO Hetmyer': 'Shimron Hetmyer',
    'SP Fleming': 'Stephen Fleming',
    'SP Goswami': 'Shreevats Goswami',
    'SP Jackson': 'Sheldon Jackson',
    'SP Narine': 'Sunil Narine',
    'SPD Smith': 'Steve Smith',
    'SR Tendulkar': 'Sachin Tendulkar',
    'SR Watson': 'Shane Watson',
    'SS Agarwal': 'Shubham Agarwal',
    'SS Cottrell': 'Sheldon Cottrell',
    'SS Iyer': 'Shreyas Iyer',
    'SS Mundhe': 'Shrikant Mundhe',
    'SS Prabhudessai': 'Suyash Prabhudessai',
    'SS Sarkar': 'Soumya Sarkar',
    'SS Shaikh': 'Sufiyan Shaikh',
    'SS Tiwary': 'Saurabh Tiwary',
    'SSB Magala': 'Sisanda Magala',
    'ST Jayasuriya': 'Sanath Jayasuriya',
    'STR Binny': 'Stuart Binny',
    'SV Samson': 'Sanju Samson',
    'SW Billings': 'Sam Billings',
    'SW Tait': 'Shaun Tait',
    'SZ Mulani': 'Shams Mulani',
    'T Banton': 'Tom Banton',
    'T Henderson': 'Tyron Henderson',
    'T Kohler-Cadmore': 'Tom Kohler-Cadmore',
    'T Kohli': 'Taruwar Kohli',
    'T Natarajan': 'T. Natarajan',
    'T Shamsi': 'Tabraiz Shamsi',
    'T Stubbs': 'Tristan Stubbs',
    'T Taibu': 'Tatenda Taibu',
    'T Thushara': 'Thilan Thushara',
    'TA Boult': 'Trent Boult',
    'TD Paine': 'Tim Paine',
    'TG Southee': 'Tim Southee',
    'TH David': 'Tim David',
    'TK Curran': 'Tom Curran',
    'TL Seifert': 'Tim Seifert',
    'TL Suman': 'Tirumalasetti Suman',
    'TM Dilshan': 'Tillakaratne Dilshan',
    'TM Head': 'Travis Head',
    'TM Srivastava': 'Tanmay Srivastava',
    'TP Sudhindra': 'T. P. Sudhindra',
    'TR Birt': 'Travis Birt',
    'TS Mills': 'Tymal Mills',
    'TU Deshpande': 'Tushar Deshpande',
    'U Kaul': 'Uday Kaul',
    'UA Birla': 'Udit Birla',
    'UBT Chand': 'Unmukt Chand',
    'UT Khawaja': 'Usman Khawaja',
    'UT Yadav': 'Umesh Yadav',
    'V Kaverappa': 'Vidwath Kaverappa',
    'V Kohli': 'Virat Kohli',
    'V Nigam': 'Vikas Nigam',
    'V Pratap Singh': 'Vishwa Pratap Singh',
    'V Puthur': 'Vyshak Vijaykumar',
    'V Sehwag': 'Virender Sehwag',
    'V Shankar': 'Vijay Shankar',
    'V Suryavanshi': 'Vaibhav Suryavanshi',
    'V Viyaskanth': 'Vijayakanth Viyaskanth',
    'VG Arora': 'Vaibhav Arora',
    'VH Zol': 'Vijay Zol',
    'VR Aaron': 'Varun Aaron',
    'VR Iyer': 'Venkatesh Iyer',
    'VRV Singh': 'V. R. V. Singh',
    'VS Malik': 'Vikramjeet Malik',
    'VS Yeligati': 'Vinayak Yeligati',
    'VVS Laxman': 'V. V. S. Laxman',
    'VY Mahesh': 'V. Y. Mahesh',
    'W Jaffer': 'Wasim Jaffer',
    "W O'Rourke": "William O'Rourke",
    'WA Mota': 'Wilkin Mota',
    'WD Parnell': 'Wayne Parnell',
    'WG Jacks': 'Will Jacks',
    'WP Saha': 'Wriddhiman Saha',
    'WPUJC Vaas': 'Chaminda Vaas',
    'X Thalaivan Sargunam': 'Xavier Thalaivan Sargunam',
    'XC Bartlett': 'Xavier Bartlett',
    'Y Gnaneswara Rao': 'Yalaka Gnaneswara Rao',
    'Y Nagar': 'Yogesh Nagar',
    'Y Prithvi Raj': 'Yarra Prithvi Raj',
    'Y Venugopal Rao': 'Yalaka Venugopal Rao',
    'YA Abdulla': 'Yusuf Abdulla',
    'YBK Jaiswal': 'Yashasvi Jaiswal',
    'YK Pathan': 'Yusuf Pathan',
    'YS Chahal': 'Yuzvendra Chahal',
    'YV Dhull': 'Yash Dhull',
    'YV Takawale': 'Yogesh Takawale',
    'Z Khan': 'Zaheer Khan'
}

In [6]:
data['player'] = data['player'].replace(player_mapping)

In [7]:
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match
0,548341,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,0.0,7.0
1,548346,Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,NaN,0.0,NaN,7.0,0.6,8.0
2,548348,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,0.0,7.0
3,548352,Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,NaN,7.0,0.0,6.0
4,548356,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,NaN,7.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,NaN,NaN,0.0,NaN
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,NaN,NaN,0.0,NaN
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,11.500000,NaN,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,NaN,NaN,0.0,NaN
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,NaN,NaN,0.0,NaN
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.000000,NaN,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,NaN,NaN,0.0,NaN

In [12]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/half_processed/half_prepared_data.csv",index = False)

In [13]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/database_csv.csv")

In [15]:
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper
0,548341,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
1,548346,Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,35.672040,35.67204,35.67204,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,0
2,548348,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
3,548352,Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,35.67204,35.67204,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,0
4,548356,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,35.67204,35.67204,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.60000,35.67204,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,0
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.60000,35.67204,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,0
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.00000,35.67204,0.000000,0.2,11.500000,NaN,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,0
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.60000,35.67204,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,0
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.000000,NaN,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,0

In [16]:
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points                 0
last5_avg_points                 0
last10_avg_points                0
rolling_strike_rate              0
rolling_wickets                  0
opponent_avg_points              0
pitch_type                    1618
venue_avg_points                 0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points                0
player_consistency_index         0
form_momentum                    0
bat_pos                          0
boundary_percentage              0
bat_pos_per_match                0
player_role_wicketkeeper         0
dtype: int64

In [19]:
data['pitch_type'] = data['pitch_type'].fillna("balanced")

In [20]:
data.isnull().sum()

match_id                      0
player                        0
runs                          0
balls                         0
fours                         0
sixes                         0
strike_rate                   0
runs_conceded                 0
balls_bowled                  0
wickets                       0
overs                         0
economy                       0
fielding_points               0
batting_points                0
batting_bonus                 0
sr_bonus                      0
wicket_bonus                  0
eco_bonus                     0
lbw_bowled_bonus              0
bowling_points                0
maiden_points                 0
fantasy_points                0
team                          0
opponent                      0
venue                         0
city                          0
toss_winner                   0
toss_decision                 0
stage                         0
season                        0
date                          0
player_match_number           0
last3_avg_points              0
last5_avg_points              0
last10_avg_points             0
rolling_strike_rate           0
rolling_wickets               0
opponent_avg_points           0
pitch_type                    0
venue_avg_points              0
venue_run_factor              0
batting_contribution_ratio    0
bowling_contribution_ratio    0
player_role                   0
last10_std_points             0
player_consistency_index      0
form_momentum                 0
bat_pos                       0
boundary_percentage           0
bat_pos_per_match             0
player_role_wicketkeeper      0
dtype: int64

In [21]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/database_csv.csv",index = False)

In [22]:
data.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points', 'batting_points', 'batting_bonus', 'sr_bonus',
       'wicket_bonus', 'eco_bonus', 'lbw_bowled_bonus', 'bowling_points',
       'maiden_points', 'fantasy_points', 'team', 'opponent', 'venue', 'city',
       'toss_winner', 'toss_decision', 'stage', 'season', 'date',
       'player_match_number', 'last3_avg_points', 'last5_avg_points',
       'last10_avg_points', 'rolling_strike_rate', 'rolling_wickets',
       'opponent_avg_points', 'pitch_type', 'venue_avg_points',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'player_role', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'bat_pos_per_match', 'player_role_wicketkeeper'],
      dtype='object')

In [23]:
data['venue'].value_counts()

venue
Wankhede Stadium                                                      2719
Eden Gardens                                                          2125
M Chinnaswamy Stadium                                                 2116
Arun Jaitley Stadium                                                  2099
MA Chidambaram Stadium                                                1991
Rajiv Gandhi International Stadium                                    1772
Sawai Mansingh Stadium                                                1347
Punjab Cricket Association IS Bindra Stadium                          1297
Narendra Modi Stadium                                                 1002
Dubai International Cricket Stadium                                    988
Sheikh Zayed Stadium                                                   788
Dr DY Patil Sports Academy                                             786
Maharashtra Cricket Association Stadium                                746
Sharjah Cricket Stadium                                                594
Brabourne Stadium                                                      567
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           501
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    374
Subrata Roy Sahara Stadium                                             336
Kingsmead                                                              317
Himachal Pradesh Cricket Association Stadium                           309
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     260
SuperSport Park                                                        249
Saurashtra Cricket Association Stadium                                 203
Holkar Cricket Stadium                                                 188
New Wanderers Stadium                                                  184
Newlands                                                               164
Barabati Stadium                                                       149
JSCA International Stadium Complex                                     148
St George's Park                                                       144
Shaheed Veer Narayan Singh International Stadium                       126
Barsapara Cricket Stadium                                              115
Nehru Stadium                                                          107
Green Park                                                              83
Vidarbha Cricket Association Stadium, Jamtha                            65
De Beers Diamond Oval                                                   62
Buffalo Park                                                            61
OUTsurance Oval                                                         43
Name: count, dtype: int64

In [30]:
data[data['venue'] == "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium"]['pitch_type'].value_counts()

pitch_type
balanced    501
Name: count, dtype: int64

In [37]:
data[['match_id','player']].value_counts()

match_id  player
392229    Ryan Harris             2
          Simon Katich            2
          Rohit Sharma            2
          Ramesh Powar            2
          R. P. Singh             2
                                 ..
729287    AB de Villiers          1
729285    Yalaka Venugopal Rao    1
          Stuart Binny            1
          Shikhar Dhawan          1
1485779   Vikas Nigam             1
Name: count, Length: 25018, dtype: int64

In [34]:
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper
0,548341,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
1,548346,Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,35.672040,35.67204,35.67204,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,0
2,548348,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
3,548352,Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,35.67204,35.67204,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,0
4,548356,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,35.67204,35.67204,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.60000,35.67204,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,0
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.60000,35.67204,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,0
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.00000,35.67204,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,0
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.60000,35.67204,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,0
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,0

In [39]:
data2 = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data_final_final.csv")

In [43]:
data.columns

Index(['match_id', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate',
       'runs_conceded', 'balls_bowled', 'wickets', 'overs', 'economy',
       'fielding_points', 'batting_points', 'batting_bonus', 'sr_bonus',
       'wicket_bonus', 'eco_bonus', 'lbw_bowled_bonus', 'bowling_points',
       'maiden_points', 'fantasy_points', 'team', 'opponent', 'venue', 'city',
       'toss_winner', 'toss_decision', 'stage', 'season', 'date',
       'player_match_number', 'last3_avg_points', 'last5_avg_points',
       'last10_avg_points', 'rolling_strike_rate', 'rolling_wickets',
       'opponent_avg_points', 'pitch_type', 'venue_avg_points',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'player_role', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'bat_pos_per_match', 'player_role_wicketkeeper'],
      dtype='object')

In [ ]:
data3 = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/historical_data_final_final.csv")